### ISSUE TITLE
您好..按照这个配置完 启动后 查看后台报错....

### ISSUE THREAD

**Issue by blankhang** [breakwa11/shadowsocks-rss#10]
2015-07-21 10:08:44 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 149, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 85, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 242, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 407, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on 'XXXX' (111)")

**Comment by cfcboy** [comment]
mysql配置没有问题？

服务端配置

shadowsocks目录内，文件Config.py：
MYSQL_HOST = 'mdss.mengsky.net' #前端mysql域名/IP
MYSQL_PORT = 3306 #mysql端口
MYSQL_USER = 'ss' #mysql用户名(建议不要用Root账户)
MYSQL_PASS = 'ss' #mysql密码
MYSQL_DB = 'shadowsocks' #数据库名

文件config.json：
"method":"aes-256-cfb", #修改成您要的加密方式的名称

**Comment by blankhang** [comment]
我随便改了下 mysql配置 问题是 我完全不知道配置这个MYSQL是干什么的....说明没说明.

**Comment by cfcboy** [comment]
这个是MYSQL是多用户的，单用户可以看教程里面。可以用单用户的。不用配置MYSQL

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks-rss/issues/9

**Comment by hzjixiang** [comment]
我也是同样的问题，有人解决了吗？  
搜到这个 http://stackoverflow.com/questions/22164248/pymysql-2003-cant-connect-to-mysql-server-on-r-s-self-host-e

**Comment by soulrenger** [comment]
这个问题就是你mysql没有配置好导致的，一个是配置文件可能写错，另一个是使用了ip地址指定mysql链接而没有打开对应的mysql默认连接权限;mysql由于不同版本，安装后的初始密码也不同，比如centos6自带的5.1默认版本默认密码为空，5.6以上数据库版本密码在初次安装之后会以以隐藏文件形式放在/root/.mysql_secret文件内，以此密码登陆后需要设置修改默认密码，创建新的对应ss数据库，导入相应建库脚本，之后更新账户访问策略，可以设置为%允许所有ip登陆，但是基于安全性原因不推荐;5.1等低版本在建库脚本导入时由于utf8mfb格式该版本不支持还会导致几个数据库表建立失败，进而多用户分支前端页面出错;mysql默认允许localhost登陆，其它ip设置需要自己手动更改，如何修改，请放狗搜索”mysql
远程登录”关键字，不会超过两秒钟

hzjixiang <notifications@github.com>于2016年9月17日周六 02:07写道：

**Comment by hzjixiang** [comment]
直接设置为%允许所有ip登陆我试了好久都不行，创建新账号才解决。
我在数据库 user里面添加 % (新用户） （新密码），然后就成功连上了   。 
 按照你的思路可以解决所有问题了，还是谢谢你。

**Comment by jeanim** [comment]
虽然是老问题了，不过我最后是在以上的基础之上，然后还需要/etc/mysql/mysql.conf.d中bind-address=127.0.0.1 修改为 bind-address=0.0.0.0,或删除该行才连接上的。ubuntu系统
