### ISSUE TITLE
hi everyone! 关于使用shadowbox作为加密传输协议在国内集中转发流量到国外的想法

### ISSUE THREAD

**Issue by tardis2012** [breakwa11/shadowsocks-rss#100]
我自己在国外租用服务器配置ipsec pptp l2tp 动不动就是丢包连不上，苹果手机端没有合适的shadowsocks翻墙版本，想自己编译，无奈编程技术还不到家，编译出的shadowsocks非常不稳定，手机不能上twitter好难受，突然冒出一个想法，大家帮我参谋一下，防火墙防外不防内，我何不在国内租一台服务器建立pptp服务，然后再把服务器和国外服务器用shadowsocks-rss互联，用breakwall姐姐的新协议，再调整一下路由让流量全部从shadowsocks转发，大家说可行不？

**Comment by falseen** [comment]
当然可行。

**Comment by tardis2012** [comment]
哇哇哇，好激动，开搞，准备租个阿里云

**Comment by tardis2012** [comment]
@falseen thanks 搞好了 分你个账号

**Comment by falseen** [comment]
我有vps。我记得IOS越狱之后是可以用shadowsocks的，现在不能用了吗 ？

**Comment by tardis2012** [comment]
对越狱后的手机不放心，没敢越狱

**Comment by v2ray** [comment]
可惜云主机上没有图形界面。

**Comment by falseen** [comment]
用python版的客户端就行了，不过目前python版的客户端对混淆插件的支持还不是很完整，但这应该不是问题，以后会慢慢完善的。

**Comment by Aivier** [comment]
一般国内服务器要求实名购买，支付渠道也是实名，而且...其实机房是有更严格的过滤系统，只是不一定会去立刻干扰你的操作
前两天某家就是类似的玩法，然后又喝茶去了

**Comment by changreich** [comment]
服务器有单独的公网地址，更好封杀了，明明nat最安全的；
它对流量小的都是不怎么管，没有很严格的限制，就看你这个服务器往外走的流量这么大就呵呵了；
不过如果是做成集群，负载均衡的话，也就不那么明显；
再者，既然都做成集群了，就有更多的其它成熟的替代方案了；

**Comment by bsfmig-a** [comment]
个人使用应该问题不太大吧~？比如，我现在有控制着一台教育网的服务器，就可以配合IPv6的转发这么用。

**Comment by changreich** [comment]
怎么快怎么来，当然是经过的路由越少越好，能直连就没必要再走服务器，何况是多平台支持都比较良好的ss，不过ipv6性能比较好的话还是可以的
