### ISSUE TITLE
再来报告一个关于前置代理的bug

### ISSUE THREAD

**Issue by redfrog999** [breakwa11/shadowsocks-rss#101]
直接描述就是，新的TCP协议搭建的server无法作为前置代理服务器来跑了。不管后端的服务器是新的TCP协议还是原版的TCP协议，只要是采用新协议的server当前置Proxy，都会出现安全连接失败的问题。Breakwa11是不是能排查一下客户端，解决掉这个bug？THX。

**Comment by breakwa11** [comment]
问题是我自己就是用新协议的server当前置用的啊，一直正常，你是不是配置有问题？

**Comment by redfrog999** [comment]
抱歉，折腾了几个小时，才发现原来是我的前置服务器挂了，奇怪的是没有重启之前，设定为原版TCP协议还是能连通的，设定为新协议就安全连接失效。重启就好了。这个Issue可以Shut down了。
