### ISSUE TITLE
[建议，不是报错]Privoxy监听端口是否随机，能否设置为一个选项

### ISSUE THREAD

**Issue by unc0** [breakwa11/shadowsocks-rss#109]
比如 mychrome、aria2c 之类只支持 http 代理的，SSR 已经自带 privoxy 了，固定端口感觉用起来更方便一些。

**Comment by falseen** [comment]
本来就是固定的，难道你没测试过？

**Comment by unc0** [comment]
@falseen 你不看 changelog 的？还是没更新过……

```
版本3.5.2 2015-09-30
1.软件更新提示方式调整，点击气泡不弹窗
2.注册表键值更名，避免与原版冲突
3.Privoxy监听端口随机，不再默认为8123，避免与原版冲突
```

**Comment by falseen** [comment]
这个监听端口是不用管的，它目前没起任何作用（ssr调用的时候做了一些更改）。ssr的固定代理端口是1080，不管是http或socks，你还是先测试一下行不行再说吧。

**Comment by unc0** [comment]
@falseen `listen-address 127.0.0.1:47838` 每次都会变啊，没测试我发到这里干什么……

你自己每次开完机去看看 ssr 的 temp 里 privoxy.conf 好不……

**Comment by falseen** [comment]
都说了Privoxy的监听端口是不用管的，不管它监听什么端口ssr的代理端口都是固定的。

如果说你的软件无法通过ssr的默认端口1080进行http代理，而使用privoxy的那个随机端口却可以的话，那就是另外一回事了。

**Comment by falseen** [comment]
如果你确定你的软件无法通过ssr的端口进行http代理的话，那就有可能是ssr调用的时候出了问题。我一直想跟你确认的就是这个，而你却总在说privoxy的随机端口……

**Comment by unc0** [comment]
@falseen 我说的就是 SSR 自带 privoxy 随机端口的问题啊，你到底要干嘛……

**Comment by falseen** [comment]
跟你无法沟通，到此为止吧。

**Comment by unc0** [comment]
@falseen 我本来就不是找你沟通，你什么毛病……

**Comment by falseen** [comment]
https://github.com/breakwa11/shadowsocks-rss/issues/70

**Comment by breakwa11** [comment]
ssr中的本地端口你设置是哪个就用哪个

**Comment by falseen** [comment]
@breakwa11 如果他那里确实不能通过ssr的端口进行代理，而通过那个随机端口却可以的话，那就要查一下是什么问题了，可是他又不肯说。我上面发的那个链接中也有人提到了无法进行http代理，所以我感觉这个问题可能真的存在。我晚上测试一下吧。

**Comment by breakwa11** [comment]
我只想知道他用pac方式能不能用，除非他用不了pac方式。而且另外那边他也没说清楚

**Comment by unc0** [comment]
@breakwa11 PAC 可以用的，那看来我是说的很不清楚，我是说能不能允许让用户配置SSR内置的 privoxy 端口，因为有用一些程序只支持 http 代理的，不想再自己开一个固定端口的 privoxy 。

**Comment by unc0** [comment]
3.5.2 之前的 SSR 内置 privoxy 是固定 8123 端口对吧？然后突然改成随机的了，这样别的程序用到 HTTP 代理的，就要每次开启 SSR 都调整一次，要不就必须自己开一个固定端口的 privoxy 去转 SSR 的固定本地端口（SOCKS5 那个）。

**Comment by breakwa11** [comment]
我已经说过了，请用你在ssr里设置的本地端口，不管是不是http，不要用privoxy配置里的端口

**Comment by falseen** [comment]
@breakwa11  我似乎明白他的意思了，他可能是想说他那里的ssr可以正常使用，通过ssr的端口也可以进行http/https/socks代理。但是，他想修改ssr自带的privoxy的配置，也就是不通过ssr的端口进行http代理。

不知道我猜的对不对。

**Comment by unc0** [comment]
@falseen 我是觉得 SSR 自带的 privoxy 到底是不是随机端口可以让用户自行决定，这样省得某些用户再自己单独去配置一个 privoxy （固定端口）的来给某些需要 HTTP 代理的工具使用。

**Comment by breakwa11** [comment]
是不是重要的事情我要重复说三次才显得重要呢，那个端口支持http，那个端口支持http代理，那个端口不但支持http，也可以socks5/socks4
