### ISSUE TITLE
gitclone过来的不能直接用chacha20

### ISSUE THREAD

**Issue by changreich** [breakwa11/shadowsocks-rss#110]
centos/redhat还好，能yum install libsodium / apt-get
是些冷门（ArchLinux）的就不好了，建议能在gitclone里面的顺带上libsodium的源码包；

**Comment by changreich** [comment]
或者直接在里面带上so也可以，做个软连接照样能用，还比较省事儿

**Comment by Aivier** [comment]
自己编译下也没什么难度，这东西不算大，编译时间也不长

**Comment by changreich** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup
或许在这里把 libsodium 添进基本库列表吧；
对我来说是没什么问题，但以后用的人多了，难免是会出现这种问题
难道还一个个指导不成？

**Comment by falseen** [comment]
Wiki每个人都可以编辑，你添加一下呗。添加的时候最好说明一下这个是可选的，对应的是chacha。

**Comment by changreich** [comment]
额，还真可以，那就可以close了
