### ISSUE TITLE
能否对每个ss端口提供单独的加密方法

### ISSUE THREAD

**Issue by troyliu0105** [breakwa11/shadowsocks-rss#112]
比如在有的android手机上，chacha20很不错，但是电脑上rc4-md5又要快一点。。。。

**Comment by cfcboy** [comment]
已经有人提过类似问题。。也有解决办法，官方WIKI里面也有。细心的你应该可以找到。

**Comment by falseen** [comment]
rc4-md5在速度和安全性方面已经没有什么优势了，现在的vps几乎已经感觉不到rc4-md5和aes-256-cfb在速度上的差异了。所以，推荐你用aes-256-cfb或chacha20。至于每个端口设置不同的加密方式，这个没太大的必要，因为现在常用的加密方式也就aes-256-cfb和chacha20两种。（楼上说的应该是每个端口设置不同的混淆插件）
