### ISSUE TITLE
3.5.9无法运行时切换服务器

### ISSUE THREAD

**Issue by choueis** [breakwa11/shadowsocks-rss#114]
代理启动状态下，切换服务器是无效的，还是在使用之前正在使用的服务器配置，只有退出然后重启shadowsocks，再启动代理后，才会使用新的服务器配置

**Comment by yfdyh000** [comment]
有效的，只是已有连接不会断开，避免某些重要连接中断（非断点续传下载；git；SSH；等等）。
切换后用“断开当前所有连接”的菜单。

**Comment by wenliyang** [comment]
https://github.com/breakwa11/shadowsocks-rss/issues/37
