### ISSUE TITLE
更新本地PAC为绕过局域网ip/绕过中国ip/gfwlist三者的功能分别是什么？

### ISSUE THREAD

**Issue by a2232189** [breakwa11/shadowsocks-rss#117]
不是很理解作者的这三个功能的意思

**Comment by breakwa11** [comment]
绕过局域网ip -> 局域网IP直连，其它都代理
绕过中国ip -> 局域网IP和中国IP直连，其它代理
gfwlist -> 局域网IP直连，gfwlist匹配的代理，其它的直连

**Comment by a2232189** [comment]
@breakwa11 谢谢

**Comment by a2232189** [comment]
绕过中国ip具体如何实现？也是通过一份名单吗？

**Comment by mikelei8291** [comment]
@a2232189 https://github.com/breakwa11/gfw_whitelist

**Comment by momobile** [comment]
@a2232189 IP分布是有规律的，每个国家和地区的IP段都不一样，此外内网和外网IP也都不一样
