### ISSUE TITLE
咨询一个负载均衡的问题

### ISSUE THREAD

**Issue by xwj1003** [breakwa11/shadowsocks-rss#118]
版本3.6
看到一个负载均衡的选项, 然后我使用低延迟优先. 如果我有200个节点, 其中有20个ping 小于100, 程序会使用多少个节点? 能否自己设置连接数, 比如3个. 还有可以设置延迟阀值, 只使用小于阀值的节点.

而且我发现, 并不是延迟优先, 因为有些延迟300多, 为何还走流量?

**Comment by breakwa11** [comment]
优先只是代表被选中的概率更高，而不是较高延迟的就没有被选中的机会。会用多少个节点是看你建立了多少个连接，然后随机分配的

**Comment by xwj1003** [comment]
我觉得有必要改进. 因为我有200个节点, PING<100估计有20个.
1优先使用延迟, 应该是发现小于某个阀值的(自己设置), 应立即使用, 然后停用PING高的节点
2可以自定连接数, 如果不能设置,建议最多5个. 连接太多了会影响机器性能.

**Comment by dNEryno** [comment]
ping全部,选个最低的.然后按顺序排列..不行还可以手动选择下一个速度快的节点.方便.
而不是现在这样,看个网页也要走好几个节点..

**Comment by breakwa11** [comment]
你可以通过手工关闭延迟大的节点来达到目的，毕竟墙对流量集中比较敏感，负载均衡主要的目的还是为了“均衡”，高速只是次要的考虑点，优先考虑的是节点的出错率和当前连接数，当前连接数比其它节点高的时候被选中的概率是较低的

**Comment by BROBIRD** [comment]
负载均衡好像会导致谷歌账号登录失败

**Comment by mikelei8291** [comment]
那我也说一下。。就是负载均衡的时候Linode登录后不能保持，点击页面上的链接到新的面板会要求再次登录，似乎是因为Linode的安全策略是换了IP访问就要重新登录

**Comment by breakwa11** [comment]
对于会检查IP的敏感操作请关掉负载均衡再操作，包括登陆，登陆银行账号或VPS后台操作等等，如果仅登陆时会检查，那么使用定时切换的负载均衡也可

**Comment by mikelei8291** [comment]
其实没什么问题，如果硬要自动化反而繁琐了，所以以前遇到这个问题也没发issue，还是先把重点放在主要代码上

**Comment by xwj1003** [comment]
改起来不难. 否则负载均衡和手动选择没啥区别了.

**Comment by mikelei8291** [comment]
建议把负载均衡直接放到右键菜单里方便开关，现在每次都要点好几下才能切换

**Comment by wenliyang** [comment]
@mikelei8291 https://github.com/breakwa11/shadowsocks-rss/issues/84

**Comment by mikelei8291** [comment]
还是没有习惯新的打开方式。。不过中键打开统计窗口还算好用
