### ISSUE TITLE
PAC不起作用

### ISSUE THREAD

**Issue by Balanky** [breakwa11/shadowsocks-rss#122]
在墙内的IP地址查询网站上在线查自己的IP地址，显示的都是VPS的IP，几个PAC都一样。用Netmon查看流量显示墙内的走的都是ShadowsocksR，试了一下原版的也是一样。以前用GoAgent不是这样的。

**Comment by breakwa11** [comment]
起不起作用要看你浏览器是配置的使用PAC还是直接用端口，直接用端口那当然相当于全局了

**Comment by breakwa11** [comment]
问题到底有没有解决？如果解决了请关闭issue，如果没有，请继续反馈现在的情况

**Comment by lpnueg4** [comment]
Hi @breakwa11， 求教，你的意思是，如果使用端口，PAC就不会起作用了吗？那Firefox怎么才能使用PAC？用另外的插件吗？
