### ISSUE TITLE
每次开机后，某些 PAC 规则都会失效！

### ISSUE THREAD

**Issue by L-Meteor** [breakwa11/shadowsocks-rss#123]
每次开机，某些网站都回显示"连接被重置"而无法连接，必须重新更新 PAC 后，才又能但开这些网页。搞得现在每次开机都得更新一次 PAC，很是麻烦！记得以前没遇到过这种情况，请问这是怎么回事呢？谢谢！

**Comment by falseen** [comment]
猜测是pac文件被删除了

**Comment by L-Meteor** [comment]
并不是所有的网页都不能打开,Google等都能打开,YouTube 也能正常观看.只是个别一,两个网站显示"连接被重置"而已.

**Comment by mikelei8291** [comment]
你用的PAC文件是哪个？
GFW List还是Bypass China IP?

**Comment by L-Meteor** [comment]
我用的是绕过中国的IP.

**Comment by breakwa11** [comment]
你打开exe路径下的pac.txt看看内容
