### ISSUE TITLE
更新完3.6.2之后，连不上网了

### ISSUE THREAD

**Issue by zhoufenfens** [breakwa11/shadowsocks-rss#125]
刚刚更新了，完全上不了，换回3.6.1.3，又好了

**Comment by zhoufenfens** [comment]
win10系统，错误日志
>[2015-11-02 18:14:18] System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 Shadowsocks.Obfs.ObfsFactory.GetObfs(String method)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)

**Comment by fengcen** [comment]
我的也是，更新到 3.6.2 就不能用，换回 3.6.1 就正常使用，是不是新版要修改什么设置？

**Comment by zhoufenfens** [comment]
@fengcen 更新到3.6.2.1好了
