### ISSUE TITLE
现阶段作者的重心是不是应该在修复BUG上

### ISSUE THREAD

**Issue by MCOAB152** [breakwa11/shadowsocks-rss#128]
在支持OTA one-time-auth 上我感觉到R目前为止最新版本都还存在问题，
表现为网页图片加载随机红叉，css一定几率无法载入（几率很小）
日志里无任何提示。

该现象跟原版原作者最后一个版本一样，
因为那时候shadowsocks-libev还没有加入OTA验证，
在使用原版（最后一版客户端+最新版服务端）时首次加载一个新页面必定会css图片加载随机失败，刷新正常，
只是现在R版本现象变少，
但今天上午3个小时使用中发现了2次。

建议，现作者不用疯狂加入新功能而且几乎全是实验性质的，
维护一下现有代码，扫除一下BUG，
我并不是专业coder，
所以测试并确定OTA问题花费了我几乎半天。

并且，似乎R版本在并发\性能上存在问题，
大概就是某些时候需要一段时间R版本才能提升到最大速度，而原版几乎是瞬时，
没有使用任何R版本附加功能。
具体我无法描述，
但可以自行和原本进行交叉测试。

**Comment by mikelei8291** [comment]
你原版开TCP-FastOpen了吗？

**Comment by breakwa11** [comment]
R版的auth和libev的OTA并不一样
你这些测试所使用的服务端版本是哪个？都使用相同服务端吗
相应地，客户端和服务端如何配置？

**Comment by MCOAB152** [comment]
@mikelei8291 没有 配置文件里没有TFO和worker
@breakwa11 S-L 2.4.1 测试环境为同一台服务器、相同的配置 客户端为原版最后一版和R版3.6.2.1
不知道作者的意思是想逐渐脱离shadowsocks自己写一个协议？

**Comment by breakwa11** [comment]
服务端用的是哪个版本的程序？
SSR现在是完全基于原协议做的，不打算自己另写协议，我觉得使用原协议来制作协议插件很方便也很容易

**Comment by lilbgae** [comment]
并且，似乎R版本在并发\性能上存在问题，
大概就是某些时候需要一段时间R版本才能提升到最大速度，而原版几乎是瞬时
我也有这样的感觉，下载东西都是慢慢提速的

**Comment by redfrog999** [comment]
最近的bug确实有点多。3.2.6.1和3.6.3都会造成某些网页的元素丢失和排版错乱。我现在用的是3.5.9和3.6.1.3这两个版本，个人认为是最快最稳定的两个版本。希望开发者先除虫再引入新功能。

**Comment by breakwa11** [comment]
@redfrog999 最近版本号的第4位的变动都是修BUG用的，第3位的变动相比已经减慢了
另外有没有具体点的描述？那个页面是不是总是出错？是不是3613是好的，3621就有问题？
我对比了一下代码，网络逻辑并没有改过，变的地方一个是结束后socket对象置null，一个没有置空；另一地方是把obfs替换为protocol

**Comment by redfrog999** [comment]
@breakwa11 看了下记录，有彭博商业，BBC英文，Youtube，Rfa这几个站在使用3.6.2.1和3.6.3时出现元素丢失情况，Youtube是把某些头像和国旗给丢了，Rfa是出现排版混乱。换回3.5.9/3.5.8/3.6.1.3就OK。

再来我是同时使用自建VPS和免费节点，然后发现各家搭建的服务器使用的Server端有很大不同，用了新版TCP协议，加持http_simple的出错几率明显小；如果是没有开启这个的，出错几率较大，所以我猜测可能是服务端和客户端的兼容问题导致。这个恐怕靠侠女无力解决。因此我是保持多个版本的客户端同时使用，方便切换。另，测试了3.6.3.1，貌似没出现了。我再多跑几天看看。

最后通报一个bug，如果你同时开启RSS版客户端和Clowwindy版本的客户端作为前置，你再开启GOA，用作前置的RSS版客户端就会崩溃，出现502错误，100%在win8.1重现，当然像我这个奇葩用法的应该很少，如果侠女有空就修理下，没空就算了。☻

**Comment by breakwa11** [comment]
@redfrog999 排版那个问题不像是兼容问题，客户端log是不是有些什么错误，3631修了一些情况下会访问空对象的问题。关于那个BUG，Clowwindy版和SSR版哪个先打开？GOA是哪个版本哪个分支客户端？

@MCOAB152 关于并发性能，我在本地局域网测试了一下，瞬间10M/s的速度，感觉不像是性能问题。有空测测新版

**Comment by redfrog999** [comment]
@breakwa11  测试到现在，3631没有出现那些错误了。log里也是一片和谐。速度方面我倒是没觉得慢过，反而是RSS版比原版的来得快和稳定。

那个BUG，我详细描述下：
使用环境：win8.1；   FF40.3；  RSS所有版本都会重现；   clowwindy是最后修正2.5.8；  GOA最后那个3.2.3版，phus.lu没有给出尾数版本号，我自己命名为Final版

使用场景：因为工作需要，我会先启动3个RSS（启动一个也是同样错误），对应不同的端口；然后启动GOA，利用Autorange大数据下载；到这一步全部OK。如果现在再次启动一个Clowwindy版客户端，对应一个特殊端口，GOA就立刻出现502错误。这个时候你停止使用GOA，转为使用RSS仍然崩溃，下边是刚刚重现bug后的log：

System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:33659
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2015-11-11 23:13:43]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void ConnectCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

我换了启动顺序，先启动Clowwindy版，再启动RSS，最后启动GOA，那就没有问题了。但是我都是把需要启动的软件丢到启动组，就不知道系统的启动顺序，所以出现502的概率蛮高的。这个问题，女侠看看有没有解决的可能。thx

**Comment by breakwa11** [comment]
@redfrog999 这个是已知问题，原版会杀光所有的privoxy进程，导致SSR的http转发失败，而SSR做了检查，只杀自己目录运行的privoxy，所以可以和其它版本共存。这问题提交给原版让他们去修

**Comment by redfrog999** [comment]
@breakwa11 玩了一段时间了，还不知道这个bug。恩，现在还看不到原版的修正，我自己想法搞定吧。
