### ISSUE TITLE
mac上使用shadowsocksR

### ISSUE THREAD

**Issue by afdnlw** [breakwa11/shadowsocks-rss#129]
3.协议插件 这块 ，Mac上应该是用不了的吧？我在mac上使用原shadowsocks for mac 客户端，其它的混淆协议能正常使用，如果有mac版 的R客户端就更好了。

**Comment by breakwa11** [comment]
你肯定搞错了什么，其它的混淆协议不可能正常使用

**Comment by breakwa11** [comment]
mac上应该能跑python版的ssr

**Comment by afdnlw** [comment]
说一下我的情况，我是mac，然后客户端使用的是最后一版的shadowsocksX2.6.3,服务端使用shadowsocksR最新版本，然后config.json 里，obfs值为：random_head_compatible，的确可以正常使用，

**Comment by afdnlw** [comment]
我又亲自把混淆插件的六个选项挨个试了一遍，发现http_simple_compatible／tls_simple_compatible／random_head_compatible这三个都能用，而不兼容原协议的的http_simple／tls_simple／random_head则都不能用。 另外，python版的ssr能给个链接吗？没有找到。谢谢

**Comment by afdnlw** [comment]
在你github主页上找到了ssr—python版本的，我研究下，谢谢！

**Comment by mikelei8291** [comment]
原版客户端肯定不支持新协议啊。。。加了compatible是兼容原协议所以才能用的。。。
