### ISSUE TITLE
查看连接详细信息

### ISSUE THREAD

**Issue by Auston** [breakwa11/shadowsocks-rss#13]
哪里可以查看当前连接详细信息？
比如查看连接了哪些网址，某段时间，持续很长时间速度超过5000K，但是完全不知道在下载什么东西，没开视频，没下载，也没什么软件更新。

**Comment by cfcboy** [comment]
这种软件，电脑上太多了吧。。。什么管家类的。

**Comment by breakwa11** [comment]
软件本身不提供这个功能，只能用其它的连接查看软件如TCPView
