### ISSUE TITLE
间歇性用不了

### ISSUE THREAD

**Issue by a2232189** [breakwa11/shadowsocks-rss#132]
间歇性用不了，服务器记录也不显示连错，但下载速度为0或几乎为0，使用“断开所有连接”功能后立刻可以正常使用，求解

**Comment by mikelei8291** [comment]
有同样的问题，版本 `3.6.2.1` ，连接完全正常，但是没有速度，看服务器端的log没有发现异常

**Comment by breakwa11** [comment]
有没有测试过之前最近哪个版本是正常的？另外配置是使用PAC还是http方式还是socks5方式代理？刚才做了一下代码对比，暂没有找到原因

**Comment by breakwa11** [comment]
@mikelei8291 另外要确认一下不是3.6.2，3.6.2有bug，在3.6.2.1修好

**Comment by a2232189** [comment]
我安卓端也有同样的问题。我觉得可能是服务器方面的问题。比如服务器跟要连接的网站之间的通讯故障

**Comment by a2232189** [comment]
我安卓端和pc端都有同样的问题。我觉得可能是服务器方面的问题。比如服务器跟要连接的网站之间的通讯故障

**Comment by breakwa11** [comment]
@a2232189 服务端是SSR-python？有没有在同一服务器上同时使用其它版本对比测试？

**Comment by a2232189** [comment]
服务端是manyuser 。因为不只有自己使用所以不方便做控制变量测试

**Comment by a2232189** [comment]
服务端是mengskysama的manyuser 。因为不只有自己使用所以不方便做控制变量测试

**Comment by mikelei8291** [comment]
似乎是我的服务器有问题，这个问题已经没有了

**Comment by breakwa11** [comment]
@a2232189 mengskysama的manyuser版本略有点老，如果你有服务端log你可以反馈给mengskysama看看。如果你对服务器有管理权，你完全可以多开一个单用户来测，看看是mengskysama的锅还是和SSR两个版本都有问题

**Comment by a2232189** [comment]
@breakwa11 “多开一个单用户”是指在mengskysama的manyuser里多开一个端口（用户）来测，还是指在同一台服务器里同时装mengskysama的manyuser和SSR的manyuser进行测试？

**Comment by breakwa11** [comment]
安装一个SSR的manyuser，但不启用数据库，而是运行单用户（用配置文件方式）

**Comment by a2232189** [comment]
为何不能用命令行模式启动呢？会有冲突？

**Comment by breakwa11** [comment]
可以用命令行启动

**Comment by a2232189** [comment]
测试了一天，用了SSR的manyuser后问题依旧

**Comment by a2232189** [comment]
我仍然觉得是服务器的问题，因为这是我新近搬迁的服务器，以前那个服务器没有问题。可否提供测试是否服务器问题的具体方法？

**Comment by breakwa11** [comment]
你有不少于3个服务器吗？有的话看看是不是只有你那个有这个问题

**Comment by a2232189** [comment]
问题详细描述：
服务端：mengskysama的manyuser及SSR的manyuser
客户端：shadowsocks-android 及shadowsocks-R
问题：正常使用某一端口数分钟后，便用不了。shadowsocks-R显示下载速度为0或几乎为0，连错为0。同一端口在不同客户端要么同时可用，要么同时不能用。此时切换到另一个端口的话，能正常使用。问题端口在一定时间后自动恢复成可用

**Comment by a2232189** [comment]
我用别的服务器试试。

**Comment by breakwa11** [comment]
@a2232189 按你的描述，根本不是客户端或服务端的问题，是你的端口被GFW短时间封锁

**Comment by breakwa11** [comment]
但你所说的
`使用“断开所有连接”功能后立刻可以正常使用`
你确认存在吗？

**Comment by a2232189** [comment]
不好意思。
使用“断开所有连接”功能后立刻可以正常使用 是错误的
是某一次碰巧可以恢复，而已。

**Comment by a2232189** [comment]
为什么会短暂封我端口呢？如果是我，我会选择长期封ip，这样不是更干脆吗

**Comment by breakwa11** [comment]
因为GFW并不肯定这一定是用来翻的，并且封锁太多会导致运行缓慢，也许因为这采用试探式的临时封锁，最好备3个以上服务器，开启负载均衡，如果条件允许，开启http_simple混淆，最好是protocol使用auth_simple彻底灭掉GFW重放攻击
