### ISSUE TITLE
能麻烦看下这是什么问题吗?谢谢

### ISSUE THREAD

**Issue by TygerKu** [breakwa11/shadowsocks-rss#133]
作者你好,我用最新的3.6.2.1连接游戏的时候会每次在5-6分钟的时候断线,看了下日志,内容是一样的,能麻烦你看下是什么问题吗?谢谢!

日志:
[2015-11-10 15:28:43] ShadowsocksR started
[2015-11-10 15:33:56] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-11-10 15:33:56]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void PipeConnectionReceiveCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by TygerKu** [comment]
另外我看了下服务器连接统计,出错比例是0%

**Comment by breakwa11** [comment]
有点像是服务端的超时断线，服务端这个默认值正是300秒

**Comment by breakwa11** [comment]
试试新版本

**Comment by TygerKu** [comment]
试了下3.6.3 beta 一连接就会出现上面的日志,但是游戏正常,但还是过了5分20秒左右再次出现上面的日志,然后掉线.

日志:
[2015-11-10 17:32:22] ShadowsocksR started
[2015-11-10 17:32:33] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-11-10 17:32:33] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-11-10 17:32:33]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void PipeConnectionReceiveCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

[2015-11-10 17:32:33]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void PipeConnectionReceiveCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

[2015-11-10 17:37:43] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-11-10 17:37:43]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void PipeConnectionReceiveCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by TygerKu** [comment]
我SS账号是买的,所以服务器那边我无法查看什么,卖家说支持UDP转发,我游戏也确实连接的上也能玩,防火墙的进程里也显示数据都是通过ShadowsocksR的,UDP TCP都有,就是5分多钟就掉了,麻烦你了啊!

**Comment by breakwa11** [comment]
明天会给你一个修好的版本

**Comment by TygerKu** [comment]
谢谢!

**Comment by TygerKu** [comment]
试了下 3.6.3.1 beta还是跟之前一样.

日志:
[2015-11-11 10:50:42] ShadowsocksR started
[2015-11-11 10:56:12] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-11-11 10:56:12]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void PipeConnectionReceiveCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by TygerKu** [comment]
昨天做了下测试
1.换官方客户端情况一样,只是掉线,日志不会记录
2.更换另一家SS账号,情况一样
3.全局软件我原先使用的是SocksCap64更换成ProxyCap也是一样情况,换成Proxifier后不掉线,但是去防火墙看了下,Proxifier只是把TCP通过了客户端,UDP还是由游戏自身连接.....
不知道是不是无解了 =.=

**Comment by TygerKu** [comment]
可能确实跟服务器有关,今天又测试了几次原版客户端,掉线的时候会出现下面的日志

[2015-11-12 12:27:21] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)

**Comment by breakwa11** [comment]
原因不详，那个错误其实只表示连接断开了

**Comment by TygerKu** [comment]
嗯 不管怎样谢谢你!
