### ISSUE TITLE
客户端人数连接多的时候经常爆出超出最大连接数

### ISSUE THREAD

**Issue by sukui** [breakwa11/shadowsocks-rss#134]
浏览器中错误提示:
~~~
maximum number of open connections reached
~~~
不知道是C#的并发限制还是浏览器的限制或者是windows 2008的 限制！

不知道有什么建议的调整方案

**Comment by breakwa11** [comment]
客户端默认只开了1024连接，更多会报错。另外系统本身也会有最大连接数限制
你是怎么使用客户端的？你在局域网里开客户端同时并局域网共享，然后让大家都指向你的机器？

**Comment by sukui** [comment]
对的. 大概有 50多人在使用！ 指向同一个局域网共享！ 不知道有没有办法解决？

**Comment by mikelei8291** [comment]
所以干嘛不直接每个人的设备上开自己的客户端？

**Comment by sukui** [comment]
这样每台机器都要安装 .net frame  。 很多人太小白了！

**Comment by sukui** [comment]
程序给他们都不会用

**Comment by sukui** [comment]
暂时的处理方法是多开几个client , 把人都分流到各个client . 效果还可以

**Comment by xbb123** [comment]
Try using Nginx as a front, then make your SS servers as upstreams. Remember to set the weight equally to balance the traffic.

**Comment by xbb123** [comment]
Maybe I didn't make myself clear. You may use Nginx to distribute your PAC files from different servers.

**Comment by sukui** [comment]
It seems good to work . but It also need  more server to be client server . if there have linux client also have pac rules?

**Comment by sukui** [comment]
It seems good to work. But now I just add another client server and devided the users into three group . Because the number of users will not change a lot ! Also thank you for your suggestion. Sometime I will try It !

**Comment by xbb123** [comment]
It's not necessarily true. You can have a Nginx installed on a existing SS server. However, I don't recommend doing this.

**Comment by xbb123** [comment]
Editing PAC settings manually works, but it's almost impossible to redirect/balance traffic when a server fails. For better availability, Nginx method maybe better.
