### ISSUE TITLE
About one bug.

### ISSUE THREAD

**Issue by ilikecola** [breakwa11/shadowsocks-rss#135]
Recently I found a bug that everything filled is correct but log shows "ClientPostDecrypt ERROR"
What's wrong with it?

Hubei ChinaTelecom

Version: 3.6.3.1 Beta

**Comment by breakwa11** [comment]
What's your protocol & obfs settings?

**Comment by breakwa11** [comment]
maybe already fixed. try new version

**Comment by ilikecola** [comment]
I am sorry for late reply.I change protocol&obfs to the recommendation and now it works well.Anyway,I use this tools for some games based on TCP which may hold long time connections, however sometimes connections will close by foreign host.I don't know what causes this consequence but I will try to "debug".

Thank for your attention and hard working!


port            HTTPS
Encryption chacha20
Protocol     auth_sha1
Obfs           tls1.0_session_auth
