### ISSUE TITLE
SSR页面响应速度慢于原版SS

### ISSUE THREAD

**Issue by GEM7** [breakwa11/shadowsocks-rss#136]
问题1
我在同一台机器（CENTOS 6）上同时安装并运行了ss和ssR，分别指定.conf 文件来运行。都是基于python同样的优化策略，锐速。以及加密方式。不同的端口：SSR仅仅开启了http_simple；我在切换二者进行加载网页的速度比对。发现对于一些非视频的页面，两者的区别并不大。但是一到看视频的时候SSR的速度几乎提不起来只能看480P。而SS可以流畅看4K。请问这是混淆算法的问题吗？请问该如何解决
问题2
我尝试用supervisor来守护ssr但是在运行时SSR 出现了错误。请问这个问题该如何解决。

小小建议：在wiki里运行ssr的相关指令前面都加上路径：比如执行的指令变成 python shadowsocks/shadowsocks/server.py -c /etc/shadowsocks.json 或者定义变量比如说： qidong=" python shadowsocks/shadowsocks/server.py -c /etc/shadowsocks.json" 这样 只用输入$qidong 就行了。

就您的习惯：开机启动的话您倾向于使用supervisord 还是 直接把命令写入rc.local?

谢谢

**Comment by KagayamaKaede** [comment]
问题二：
我记得supervisor/systemd好像需要可执行文件的完整路径/path/to/python /path/to/ssserver.py -c /path/to/xx.json。

最好贴上错误方便定位问题。

**Comment by breakwa11** [comment]
有没有测试过SSR不开启http_simple？

**Comment by GEM7** [comment]
谢谢你的回复。我刚刚测试了，现在暂时都好了。重启了一下服务器先开的原版再用命令开SSR成功了。我想应该是ISP的问题导致的网速不好吧。另外。怎样将默认输出的的shadowsocks.log 改成shadowsocksr.log我感觉不改的话好像和原来的有点串了

**Comment by breakwa11** [comment]
输出的log文件是什么名字什么路径是由你的启动方式决定的

**Comment by falseen** [comment]
-d参数启动的默认log是shadowsocks.log ，可以通过参数指定log路径，输入-h可以查看所有参数的说明。

**Comment by GEM7** [comment]
我明白了。多谢二位的指点！

**Comment by breakwa11** [comment]
新版本的3.6.3.4应该会好一些，之前有一段调试用的代码，略微占CPU，现在去掉了应该和以前一样

**Comment by GEM7** [comment]
原来是这样啊。我傍晚试了一下，已经都能跑起来了。Thank You！！ ；）
