### ISSUE TITLE
很好用，但有几点问题需要反馈一下

### ISSUE THREAD

**Issue by polong** [breakwa11/shadowsocks-rss#14]
1、希望能根据连接质量暂停某一个线路，而不是删除，这点仿佛很需要。
2、有时如果网络不太顺畅时，看youtube会断掉，等半天都没有重要连上，需要刷新一下才解决问题。
3、我是选随机选择线路，随机方式是按延迟，但是在服务器连接统计中点到某个服务端时，明显感觉流量都连接这条线路中了，按理说应该不是这样吧？
4、我觉得连接不应该按延迟，因为延迟低不一定表示速度快，是不是应该更智能一点，比如按统计某个时间段的连接质量和连接速度为参考依据，而主要流量最终集中在其中在质量好的有限几条线路中。
5、应该按时间段统计每条线路的质量并保存，现在的统计对线路的选择参考上没什么帮助。
6、在win8中拖动服务器连接统计窗口会卡哦。
7、有时一个服务商有多条线路，但是端口、密码和加密方式都是一样的，我如果要添加这多条线路是十分麻烦，是不是可以一个配置里可以对应多个服务器？或者有什么方式可以解决这个问题？

**Comment by breakwa11** [comment]
关于1，请点击统计列表“开”的一列来临时开关
关于2，这不能在socks5下解决，可建立一个http代理来设置，如privoxy
关于3，你是不是设置了“选中优先”
关于4和5，这个问题我也想过，但不好实现，并且有比较重要的功能在做，目前就搁置了
关于6，窗口不要拉太大就行，彻底的解决方法我早就想过了，但需要写大量代码，以后再优化
关于7，配置窗口有二维码显示，用扫码功能扫进去（扫了并编辑后在还没保存的情况下再扫会有bug，先连续扫几次再一起编辑吧）
