### ISSUE TITLE
[已解决]3.6.3.3无法使用；（问题原因：在调整功能的时候有一个情况下会留下空指针，仅在3.6.3.3中出现）

### ISSUE THREAD

**Issue by GEM7** [breakwa11/shadowsocks-rss#140]
3.6.3.3 无法使用
3.6.3.3-win-dotnet4.0,无法使用。打开网页时
Chrome显示无法显示此网ERR_CONNECTION_RESET；
Firefox:显示安全连接失败载入页面时到服务器的连接被重置；
3.6.3.2和原版SS正常。
一下是3.6.3.3是日志内容：
[2015-11-16 19:57:41] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.SetObfsPlugin()
   在 Shadowsocks.Controller.Handler.StartPipe()
[2015-11-16 19:57:41] Void LogUsefulException(System.Exception)
Void StartPipe()
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

谢谢

**Comment by breakwa11** [comment]
你的节点配置是什么样的？

**Comment by GEM7** [comment]
我是直接从上一版本的文件夹中复制粘贴过来的

**Comment by breakwa11** [comment]
我是想知道具体的协议和混淆等配置信息

**Comment by GEM7** [comment]
SSR：加密协议：aes-256-cfb ;TCP协议：origin；obfs:http_simple(未填写插件参数) 
SS:     加密协议：aes-256-cfb;TCP协议：origin；obfs:plain(未填写插件参数)

**Comment by breakwa11** [comment]
知道原因了，稍等

**Comment by GEM7** [comment]
多谢你的回应，等你消息!

**Comment by breakwa11** [comment]
已修好，测试一下看看

**Comment by GEM7** [comment]
问题已在3.6.3.4版本中解决。谢谢你了。请问具体是什么问题呢，我想改一下标题让其他人都好找到。；）

**Comment by breakwa11** [comment]
就是一个BUG，在调整功能的时候有一个情况下会留下空指针，仅仅在那个版本中出现

**Comment by GEM7** [comment]
哦！那我酌情修改一下下标题~ ；）

**Comment by breakwa11** [comment]
不用写“已解决”，解决的问题会close的

**Comment by GEM7** [comment]
啊哈~我以后会注意的。第一次用github给发issue；） Thank you anyway
