### ISSUE TITLE
麻烦能提供不要自动修改IE的PAC的功能

### ISSUE THREAD

**Issue by ColorValue** [breakwa11/shadowsocks-rss#141]

**Comment by breakwa11** [comment]
关闭“启用系统代理”即可

**Comment by mikelei8291** [comment]
不改pac设置怎么走代理。。。
全局？ <s>当我没说</s>

**Comment by ertcds** [comment]
@breakwa11  关闭“启用系统代理” 默认的代理端口是多少？8123怎么不行。。

**Comment by breakwa11** [comment]
你在软件里设置的端口是多少就用哪个

**Comment by breakwa11** [comment]
默认是1080

**Comment by ColorValue** [comment]
@breakwa11  我一般使用Chrome的SwitchyOmega 里的PAC模式 ，IE要使用另外代理的PAC上。SSR开启又自动修改PAC，对我作用不大。

**Comment by breakwa11** [comment]
那你直接关闭“启用系统代理”不就好了吗？这个功能一直都有啊
