### ISSUE TITLE
提一个想法，SSR数据包中转功能

### ISSUE THREAD

**Issue by MrSong0607** [breakwa11/shadowsocks-rss#145]
简单的说就是利用国内的云服务器，新浪云或者百度云。客户端先把数据包发送到云服务器，例如新浪云，然后在新浪云上用python实现将数据包转发到VPS的指定端口上，这样一来，对于部分对外出口流量封锁严重的地区，就可以实现比较快速的访问了，不知道这个想法有没有可行度，大家讨论下

**Comment by falseen** [comment]
当然是可行的，简单的设置下iptables就行了，不用那么麻烦。

**Comment by mikelei8291** [comment]
@MrSong0607 #100 已经有提到过

**Comment by MrSong0607** [comment]
有实现的办法吗

**Comment by KagayamaKaede** [comment]
falseen已经说过用iptables了，稍微去了解下相关命令就好。
还有令另外一种方法就是https://github.com/zhenpingfeng/shadowsocks-wiki/blob/master/Setup-a-Shadowsocks-relay.md
不过这个方法代价稍大。

**Comment by MrSong0607** [comment]
国内的那些云主机，除了阿里的，其他的都算不上VPS，没有iptables的，有没有python的办法来实现这个功能呢？
