### ISSUE TITLE
3.6.4的udp over tcp无法使用

### ISSUE THREAD

**Issue by Corzcode** [breakwa11/shadowsocks-rss#146]
pip install --upgrade shadowsocks
更新过shadowsock也还是不能使用

使用dnsproxy测的

**Comment by breakwa11** [comment]
这样安装的是原版，不是SSR版，非SSR是不支持的

**Comment by Corzcode** [comment]
那https://github.com/breakwa11/shadowsocks的manyuser分支是SSR版么？

**Comment by breakwa11** [comment]
是的
