### ISSUE TITLE
使用"obfs":"http_simple_compatible",客户端使用http_simple使会有Bad response. The server or forwarder response doesn't look like HTTP.

### ISSUE THREAD

**Issue by aaasss112** [breakwa11/shadowsocks-rss#148]
服务端配置是：
{
    "server":"0.0.0.0",
    "server_ipv6": "::",
    "server_port":8080,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"aaasssWR",
    "timeout":300,
    "method":"aes-256-cfb",
    "protocol":"origin",
    "obfs":"http_simple_compatible",
    "fast_open": true,
    "workers": 1
}

客户端选择aes-256-cfb加密
TCP协议origin
混淆插件选择http_simple，访问网站会有
Bad response. The server or forwarder response doesn't look like HTTP.
报错。
选择plain则很正常。服务端和客户端版本都是当前最新的。

**Comment by mikelei8291** [comment]
这是最新版吗？

**Comment by aaasss112** [comment]
刚刚从github这边下载下来的，应该是最新版了吧。
