### ISSUE TITLE
帮忙看看这个错误，多谢。 Q:在一个非套接字上尝试了一个操作

### ISSUE THREAD

**Issue by usc** [breakwa11/shadowsocks-rss#149]
操作系统：win10
版本：3.6.4.1
偶尔会出现整个ss都没反应了，网页打不开，只有重启ssr才可以，查看日志如下

[2015-11-23 17:08:51] System.Net.Sockets.SocketException (0x80004005): 在一个非套接字上尝试了一个操作。
   在 System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Listener.timer_Elapsed(Object sender, ElapsedEventArgs eventArgs, Socket socket)
[2015-11-23 17:08:51] Void LogUsefulException(System.Exception)
Void timer_Elapsed(System.Object, System.Timers.ElapsedEventArgs, System.Net.Sockets.Socket)
Void <ResetTimeout>b__1(System.Object, System.Timers.ElapsedEventArgs)
Void MyTimerCallback(System.Object)
Void CallCallbackInContext(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void CallCallback()
Void Fire()
Void FireNextTimers()
Void AppDomainTimerCallback()

**Comment by breakwa11** [comment]
目前在我这边很难重现了，你那出现的频率高吗？是用.net4.0版本吗

**Comment by usc** [comment]
不好意思，现在才回复，是.net4.0，奇怪的是目前有两台机器，家里一台，办公一台，环境几乎一样，家里的就没有问题，也不知道是不是办公网络的问题

**Comment by breakwa11** [comment]
试试新版本有没有问题

**Comment by usc** [comment]
好，我试试，tks

**Comment by usc** [comment]
试了两天了，到目前为止没出现过了，多谢
