### ISSUE TITLE
Shadowsocks+Tor

### ISSUE THREAD

**Issue by worksofcox** [breakwa11/shadowsocks-rss#151]
我想问一下可不可以在服务端安装Tor然后客户端通过Shadowsocks链接，然后在服务端通过某种方式将Shadowsocks的流量全部通过Tor走，这样就能解决Tor网桥的限制也能轻松跨平台使用匿名网络了，如果能那有什么办法实现呢？

**Comment by lersh** [comment]
我研究过，可以用obfs4的网桥混淆

**Comment by worksofcox** [comment]
我指的不是在原有ss上再增加一个混淆，是将就原有ssr连接方式，在服务端做个中转，把ssr的流量全部走tor实现ssr直接使用tor的匿名网络@lersh

**Comment by falseen** [comment]
这个是可行的 ，操作起来也不难。

**Comment by worksofcox** [comment]
请问该如何做？@falseen

**Comment by falseen** [comment]
在服务端开启ss和tor ，然后用iptables或者其他代理工具（比如proxychains）把ss的流量重定向到tor就行了。

**Comment by worksofcox** [comment]
谢谢，我下来试试@falseen

**Comment by worksofcox** [comment]
我用proxychains成功实现了，但是还有个问题，proxychains好像不能指定某端口转发，只能指定某个进程，如果我只想某个端口转发怎么做？我尝试多开一个ssr服务进程（用不同的配置文件），但好像不行@falseen

**Comment by falseen** [comment]
用iptables 或者 haproxy 可以指定某个端口转发。

**Comment by worksofcox** [comment]
好的，我试试

**Comment by falseen** [comment]
等等，你说的某个端口转发是指ss服务端监听的端口还是客户端请求的目标服务器端口 ？

**Comment by falseen** [comment]
最简单的办法就是用不同的用户组多开ss服务端，一个用户组对应一个端口（如果要每个端口都分别设置的话），然后在iptables中设置不同用户的过滤规则。

**Comment by worksofcox** [comment]
但是怎样才能多开服务端呢？我先用root运行了一个服务端，python server.py -c root.json -d start，之后想用用户test运行另一个，在同一目录下执行python server.py -c tset.json --user tset -d start，得到错误提示2015-11-26 14:45:38 ERROR    already started at pid 20770，请问该如何解决？@falseen

**Comment by worksofcox** [comment]
已解决，后面加个&就ok了@falseen

**Comment by qqzg** [comment]
你用的什么命令 将SS转发到tor的，
