### ISSUE TITLE
不知道有没有openwrt下的客户端

### ISSUE THREAD

**Issue by lersh** [breakwa11/shadowsocks-rss#152]
原来openwrt下有原版ss协议的客户端，这样在路由器上配置完全家的设备都能科学上网了，现在这个ssr似乎没有openwrt版，只能开着电脑当代理了

**Comment by mikelei8291** [comment]
安装Python用Python版就行

**Comment by breakwa11** [comment]
快有了，等等吧

**Comment by breakwa11** [comment]
有了，不过目前还只支持http_simple混淆，同时需要自己编译。。。

**Comment by yech1990** [comment]
自己编译啊....

有人编译好WNDR4300的么
