### ISSUE TITLE
关于新的shadowsocks-libev

### ISSUE THREAD

**Issue by djj200504001** [breakwa11/shadowsocks-rss#153]
首先求详细指导一下Usage怎么用，直接输入命令会这样：
root@localhost:/# ss-m<aes-256-cfb>
-bash: syntax error near unexpected token `newline'
然后是Security Tips中，输入命令后发现不支持-m命令
PS：我用的Debian 8.0 x86_64  
顺便问句我看到的源列表里都是jessie的，加进去wheezy的会不会有啥奇怪的问题（虽然我已经加了

**Comment by djj200504001** [comment]
root@localhost:/# ss-m《aes-256-cfb》
-bash: syntax error near unexpected token `newline'
晕，貌似加了两边的<会显示不出来？

**Comment by breakwa11** [comment]
要git clone下来编译，还不支持直接用源安装，主页的readme等很多都还没改

**Comment by djj200504001** [comment]
此刻我的内心是崩溃的……默认的协议是啥？混淆呢？直接装的能用么？

**Comment by breakwa11** [comment]
不要着急，明天会把其它协议和功能进行完善，之后就会写使用文档

**Comment by breakwa11** [comment]
功能基本完善，在编写文档。另外你用的命令都错了，看一下别人写的使用教程吧
