### ISSUE TITLE
关于版本的问题，之前提过的问题又出现了。

### ISSUE THREAD

**Issue by cfcboy** [breakwa11/shadowsocks-rss#155]
一直喜欢用最新的服务端版本，经常性的git pull。
同一台服务器，同一时间。不同git服务端版本，速度不同。
目前测试的版本，速度最快的是：git reset --hard 79260ff
这个是我自己git reflog出来的，不知道源上面是不是一样。
目前最新版的服务端，经常性的出现https错误。网页访问不了。
而且访问google邮箱。git网站。tumblr网站。非常的慢。是不是服务端代码有问题。
帮忙检查看看。

**Comment by breakwa11** [comment]
测试一下新版本
