### ISSUE TITLE
今天干扰掉包好严重！

### ISSUE THREAD

**Issue by sukui** [breakwa11/shadowsocks-rss#156]
妈蛋，方校长还不如直接物理断网算了！

**Comment by sukui** [comment]
vps被盯上了，ping都掉包，同一机房小流量的vps没这个问题

**Comment by watsonweng** [comment]
我昨天开启UDP Over TCP后下完一个大文件，发现我VPS整个机房的IPv6地址都ping不通。。。不知道是什么原因

**Comment by sukui** [comment]
线路问题. 需要用国内 vps中转流量
