### ISSUE TITLE
关于『允许来自局域网的连接』安全性的问题

### ISSUE THREAD

**Issue by chengr28** [breakwa11/shadowsocks-rss#157]
RT 最近开着程序，之前测试时把这个选项打开了，然后有次也是非常特殊地没有经过路由器连上了拥有公网地址的网络，接着才过一阵就被扫描端口爆破掉了……
各种肉鸡连接通过代理发垃圾邮件和暴力破解网站密码 =_/=

程序这个功能如果启用监听的似乎是 any 地址并且没有任何过滤，允许所有来源地址连接，和我想象中的并不一样，于是……虽然看到了 https://github.com/breakwa11/shadowsocks-rss/issues/77 但还是希望先增加一下过滤掉非局域网地址的能力，算是应急w

**Comment by breakwa11** [comment]
添加一个允许的地址列表？怎么过滤掉公网地址是个问题。。。。有什么思路么？

**Comment by breakwa11** [comment]
一个临时实现做好了，不过不知道全不全面，就是检查连接方是不是如下地址：
10.0.0.0/8
127.0.0.0/24
172.16.0.0/12
192.168.0.0/16

**Comment by chengr28** [comment]
https://en.wikipedia.org/wiki/Reserved_IP_addresses 这里有详细的介绍，基本就是那4个：
10.0.0.0/8
127.0.0.0/8
172.16.0.0/12
192.168.0.0/16

我那边的话 IPv6 过滤了3个：
FC00::/7
FE80::/10
::1

**Comment by chengr28** [comment]
嘛考虑到有可能拿来做公共服务器什么的……建议是弄一个『允许连接』的选项菜单让用户自己选，里面有只有自己可以用、局域网可用、所有来源可用之类的

**Comment by breakwa11** [comment]
366版做了个临时的

**Comment by BROBIRD** [comment]
100.64.0.0/10  呢……

**Comment by akw28888** [comment]
@BROBIRD 
民用的內網並不會用100.64啊

**Comment by chengr28** [comment]
@BROBIRD 这个是给 ISP 用的，私人内网一般不会用

**Comment by BROBIRD** [comment]
@chengr28 @akw28888 知道了，感谢赐教

**Comment by breakwa11** [comment]
增加了用户名密码验证支持
