### ISSUE TITLE
全局模式无法正常工作

### ISSUE THREAD

**Issue by antikan** [breakwa11/shadowsocks-rss#158]
google drive等连不上无法同步文件，前面的版本是正常的，最新版不能；使用libev版本可以。

**Comment by breakwa11** [comment]
有log吗

**Comment by antikan** [comment]
[2015-12-02 19:27:23] Void LogUsefulException(System.Exception)
Void StartPipe()
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)

[2015-12-03 18:14:53] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.StartPipe()
[2015-12-03 18:14:53] Void LogUsefulException(System.Exception)
Void StartPipe()
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)



[2015-12-03 18:26:32] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.StartPipe()
[2015-12-03 18:26:32] Void LogUsefulException(System.Exception)
Void StartPipe()
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)

[2015-12-03 18:28:32] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.StartPipe()
[2015-12-03 18:28:32] Void LogUsefulException(System.Exception)
Void StartPipe()
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)

[2015-12-03 18:28:42] [Warn]Proxy server [(2402:9e80:0:1000::1:9d26)]
connection timeout
[2015-12-03 18:30:42] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.StartPipe()
[2015-12-03 18:30:42] Void LogUsefulException(System.Exception)
Void StartPipe()
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)

[2015-12-03 18:33:13] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.StartPipe()
[2015-12-03 18:33:13] Void LogUsefulException(System.Exception)
Void StartPipe()
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32,
System.Threading.NativeOverlapped*)

[2015-12-03 18:34:52] ShadowsocksR started
[2015-12-03 18:40:54] ShadowsocksR started
[2015-12-03 18:47:13] System.InvalidOperationException: 进程已退出，因此无法处理请求。
   在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean
throwIfExited)
   在 System.Diagnostics.Process.Kill()
   在 Shadowsocks.Controller.HttpProxyRunner.Stop()




2015-12-06 22:10 GMT+08:00 BreakWa11 <notifications@github.com>:

**Comment by breakwa11** [comment]
google drive貌似没有设置代理的地方？

**Comment by antikan** [comment]
没有的

2015-12-14 4:25 GMT+08:00 BreakWa11 <notifications@github.com>:

**Comment by breakwa11** [comment]
那你是怎么让它走代理的？

**Comment by antikan** [comment]
ssr开系统全局代理，ssr之前几个版本是没问题的

**Comment by breakwa11** [comment]
你肯定搞错了，SSR开全局也不能让它走代理，请配合使用proxifier
