### ISSUE TITLE
PAC 模式会干扰 Internet Explorer 中 JavaScript 的工作

### ISSUE THREAD

**Issue by aenerv7** [breakwa11/shadowsocks-rss#160]
OS：Windows 10

最近在 steam 和杉果上买游戏的时候偶然发现的，因为银行网银控件的关系只有用 IE 在这些网站上买东西，但是如果开着 ShadowsocksR 并设置系统代理模式为 PAC 模式的话会导致页面错乱，steam 登录什么的也不行，杉果则在游戏详情页会提示该页面需要 JavaScript 支持。看起来似乎是 PAC 模式下 ShadowsocksR 干扰了浏览器本身 JavaScript 功能的运作的样子，因为如果关掉 ShadowsocksR 或者设置成全局模式则页面一切正常。

今天又反复尝试了一下，确实只有在 PAC 模式下才会出现类似状况，切换到全局模式或者关掉之后都正常，从结果来看的确干扰了 Internet Explorer 中 JavaScript 的工作，所以修改了一下标题。

**Comment by breakwa11** [comment]
PAC模式下任何PAC设置都这样？

**Comment by aenerv7** [comment]
今天到家试了一下，4 种 PAC 设置中：
“绕过局域网 IP ”和“绕过大陆常见域名列表”是可以正常工作的
“绕过大陆 IP ”和“GFWList”两种设置下会出现问题

**Comment by breakwa11** [comment]
有具体网页地址么

**Comment by aenerv7** [comment]
在上述情况下进入 steam 商店页面（http://store.steampowered.com/）能够发现和正常情况下是不一样的（当然就像问题所说只限于 IE 浏览器，我的是 Windows 10 上的 IE11），在点击页面右上角登陆之后同样会无法登陆，尤其是换电脑登陆 steam 会给账户发一封确认邮件，登陆页面会弹出来输入确认邮件中安全码的框，框里的按钮在点击之后完全无反应。

如果 steam 不够直观的话可以进到杉果游戏商城任意一款产品的详情页面，例如我随手点开一个：http://www.sonkwo.com/products/1943#，进去之后页面上的视频播放功能失效，显示：“播放视频需要javascript支持”，这也正是我怀疑 PAC 模式是干扰了 IE 中 JS 工作的原因。

**Comment by breakwa11** [comment]
我测试了一下，没有复现你的问题，你确认一下你的IE的IE选项，里面的安全页，看看是不是启用了保护模式

**Comment by aenerv7** [comment]
我这两天专门试了一下，关闭了保护模式之后还是会有相同的问题，还有没有可能是别的原因导致的？

**Comment by aenerv7** [comment]
我刚才开了控制台看了一样，IE 里 steam 页面会返回不少 304（尤其是有一些类似于 js 的连接），但是在 Chrome 里基本都是 200 或者少数几个 302（由于对这块不是特别熟所以只能提供一些参考了，看能不能帮上忙）

**Comment by breakwa11** [comment]
我测试的时候，开启了保护模式时能复现，关了后就不能复现，你试试关了后立即重启浏览器再试试看

**Comment by aenerv7** [comment]
我试了一下，无论是开启还是关闭保护模式，问题都是存在的，关了之后立即重启问题也仍然存在...

**Comment by wl1244hotmai** [comment]
我也复现了lz的问题。。。

**Comment by aenerv7** [comment]
考虑到有些 PAC 能够生效，我怀疑可能是 PAC 本身的问题，今天下班回家我对比了一下绕过常见域名和绕过大陆的 IP 这两个类似的 PAC，经过一番修改实验之后，发现问题出在最后一个 function 里这一块

```
if (check_ipv4(dnsIps[0]) === true) {
	return getProxyFromIP(dnsIps[0]);
} else if (check_ipv6_dns(dnsIps[0]) === true) {
	return ipv6_proxy();
}
```

可以看到 if 里检查 ipv4 地址的判断如果为真，会去调用一个叫

```
getProxyFromIP
```

的方法，而如果我去掉这个方法，那么页面就正常了。所以我觉得从这个现象可以看出是 PAC 本身的问题导致了 IE 的 JS 失效，因为 PAC 作为一段 JS 代码在执行的时候很可能在 IE 上抛错了...不过我看了下控制台也没看到什么输出或者提示，尝试着跟进 PAC 里的 JS 代码看能不能改一改但最后也还是没摸到头绪。

**Comment by breakwa11** [comment]
明天我看看

**Comment by breakwa11** [comment]
测试了一下，PAC本身没有问题，所连接的IP为106.3.36.22，是国内的，判断为直连并没有错误。

但是，根源是那个网站本身，它首先判断了浏览器，如果是IE7或更老的版本，则使用那个IP的脚本，但同时那个IP判断了主站连接IP和脚本用的IP，不一致时会断开。

又另外，IE通常会开启“在兼容性视图中显示 Intranet 站点”，开启了的话默认使用IE7。关闭方法：在兼容性视图设置里，找到这个选项，去掉打钩，以上问题即可解决

另一个临时解决办法是按F12，切换兼容模式所用的版本。我用的是IE11，在仿真那页里面，有个文档模式，在那里可设置，改为IE9或以上就搞定了。

**Comment by aenerv7** [comment]
确实是这个问题，我试了一下，关掉了“在兼容性视图中显示 Intranet 站点”这个选项就正常了，感谢！
