### ISSUE TITLE
SSR的系统PAC模式在IE11上会失效

### ISSUE THREAD

**Issue by mahaoying** [breakwa11/shadowsocks-rss#161]
发现新做的系统装了IE11开SSR的系统PAC模式是正常的，可以正常代理跨到脸谱站、油管等，但是从昨天开始突然就失效了，PAC模式IE提示的就是无法显示此页，全局就正常的，IE重置也不行。网上搜过教程也试过了，皆无效，求作者大神给个能解决的办法。不想开全局，而且我也有用chrome+SwitchyMega,但是对IE还是有部分需求的，希望能解决PAC突然不能用这个问题。
之前用IE8一切正常哈。IE11也正常了很长一段时间。

**Comment by breakwa11** [comment]
突然失效的话请回想你那天安装了什么软件

**Comment by mahaoying** [comment]
用了netsh修复了下socks目录就正常了，当天只更新了下ADsafe，怀疑是导致socks损坏的原因。

**Comment by breakwa11** [comment]
迅雷呢？迅雷是已知的会产生明显影响的软件
