### ISSUE TITLE
3.6.6经常出现ssl error

### ISSUE THREAD

**Issue by hpfs0** [breakwa11/shadowsocks-rss#163]
使用的时候会有这样的错误，求大神解惑。用的是http_simple
[2015-12-07 11:26:04] failed to recv data in RspHttpHandshakeAuthRecv

**Comment by breakwa11** [comment]
具体你是如何配置的？

**Comment by hpfs0** [comment]
我用的别人的服务端，obfs用的是http_simple，其他的配置和原版一样

**Comment by mikelei8291** [comment]
应该是 `auth_sha1` 的问题吧，我打开 `auth_sha1` 以后首次连接会出现SSL错误，但是之后就好了

**Comment by hpfs0** [comment]
我没用<code>auth_sha1</code>这玩意儿，我也有时回出现SSL错误和privoxy错误

**Comment by breakwa11** [comment]
换新版如还有问题，再开issue
