### ISSUE TITLE
windows 2003 上怎么部署服务端？

### ISSUE THREAD

**Issue by c21xdx** [breakwa11/shadowsocks-rss#164]
怎么搭建环境啊？需要装些什么多？ 下载了python的WIN版本，安装了，不认识git。貌似一些开发套件会包括python git什么的。
windows 2003 上怎么部署服务端？谢谢

**Comment by mikelei8291** [comment]
https://github.com/shadowsocks/shadowsocks/wiki/Install-Shadowsocks-Server-on-Windows

**Comment by c21xdx** [comment]
有详细点的么？ 装了Python for Windows之后使用git clone -b manyuser https://github.com/breakwa11/shadowsocks.git, git命令识别不出来啊

**Comment by falseen** [comment]
安装git或手动下载ss源码。

**Comment by c21xdx** [comment]
![qq 20151208164532](https://cloud.githubusercontent.com/assets/5766149/11651554/92fee212-9dcc-11e5-8096-5f8d19b9afba.png)
不行啊，装了python27 for windows,装了Win32 OpenSSL，装了Visual C++ 2008（网上教程说OpenSSL需要装这个支持）,下载SSR源码https://github.com/breakwa11/shadowsocks/archive/master.zip，解压出来放置，目录C:/python27/shadowsocks/shadowsocks/，CMD下CD到python27目录，执行 python C:/python27/shadowsocks/shadowsocks/server.py -p 3389 -k loudi123 -m rc4-md5，结果一对错误，如截图所示。还是不行啊怎么破？

**Comment by breakwa11** [comment]
主分支的代码是旧的，要用manyuser分支

**Comment by c21xdx** [comment]
@breakwa11
出现以下截图算是成功运行了吧，但还是连不上
![qq 20151208190338](https://cloud.githubusercontent.com/assets/5766149/11654396/42005b3e-9de0-11e5-8139-3b6c8b0f8a64.png)
我以为是防火墙问题，点开防火墙，出现以下提示，貌似防火墙都没有启动啊。怎么破？
![qq 20151208190603](https://cloud.githubusercontent.com/assets/5766149/11654409/547dc8be-9de0-11e5-9822-34ebeb815552.png)

**Comment by breakwa11** [comment]
客户端连接的时候如果没有出现任何log，那就是在连接的时候有异常。不过防火墙不一定在你的系统里，有的VPS有外部管理的防火墙

**Comment by c21xdx** [comment]
@breakwa11 
换了个常用的端口就可以了，应该是你说的外部防火墙问题。不过加上 -d start 后台运行失败，应该是WIN不支持。 如果写 shadowsocks.json 配置文件的话，放在哪里呢？

**Comment by mikelei8291** [comment]
<s>所以为什么非要拿Windows Server折腾自己→_→</s>
