### ISSUE TITLE
不能跟net_speeder配合使用？

### ISSUE THREAD

**Issue by cfcboy** [breakwa11/shadowsocks-rss#166]
不能跟net_speeder配合使用？

**Comment by mikelei8291** [comment]
可以，但是这个net-speeder本质上损人不利己，不建议使用

**Comment by cfcboy** [comment]
@mikelei8291 我装上之后。不能用。。是不是我用的协议有问题。你用的是哪个协议和混淆？

**Comment by mikelei8291** [comment]
我并没有用过net-speeder，但有成功的例子

**Comment by cfcboy** [comment]
@mikelei8291 那个是SS，不是SSR。

**Comment by superfls** [comment]
可以配合使用，net－speeder和ss应该没多大依赖关系，至少我配着么多没发现问题，注意点的是一般的net都是只支持centos 5，6，centos7的话有点特殊，比较难找，还有就是openvz的应该是没效果的，最后是注意启动参数就行了。
