### ISSUE TITLE
服务器在US,代理要怎么设置才连得上?

### ISSUE THREAD

**Issue by yu-yang2** [breakwa11/shadowsocks-rss#167]
用的公司的linux server,但是要连代理才能上外网,shadowsocks有这样的参数设置么?

**Comment by cfcboy** [comment]
设置里面不是有个前置代理吗？

**Comment by yu-yang2** [comment]
可以讲讲怎么弄么?貌似是我服务器在美国的IP被墙...我找了好久也没找到SS的前置代理怎么用

**Comment by yu-yang2** [comment]
@cfcboy 谢谢

**Comment by yu-yang2** [comment]
美国的Linux是需要export proxy才能访问外网的:(

**Comment by wyxls** [comment]
前置代理貌似只支持socks5和http

**Comment by breakwa11** [comment]
建议修改你的表述，我不清楚你到底遇到什么问题
