### ISSUE TITLE
3.6.6 电脑死机

### ISSUE THREAD

**Issue by Thisdk** [breakwa11/shadowsocks-rss#168]
是这样的.可能问题是我太极端了
我连接到5个服务器
开启负载均衡
然后同时看油管3部720P的电影.
然后过了几分钟..死机了

**Comment by cfcboy** [comment]
你电脑配置低的问题吧。

**Comment by Thisdk** [comment]
@cfcboy CPU是I3的..内存8G.不过占用了5G多.可能还真是配置太低

**Comment by cfcboy** [comment]
@Thisdk 应该是吧。我的是i7 4770 32G...没碰过卡的问题。

**Comment by antikan** [comment]
网卡驱动也可能，我的蓝屏重启过
