### ISSUE TITLE
3.3.0版UDP over UDP无法使用

### ISSUE THREAD

**Issue by kirafreedom** [breakwa11/shadowsocks-rss#17]
打不开网页，勾上UDP over TCP正常，服务端是libev和python版
[2015-08-06 08:49:45] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.BeginConnect(IPAddress ipAddress, Int32 serverPort)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)
[2015-08-06 08:49:45] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.BeginConnect(IPAddress ipAddress, Int32 serverPort)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)
[2015-08-06 08:49:45] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.BeginConnect(IPAddress ipAddress, Int32 serverPort)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)
[2015-08-06 08:49:46] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Handler.BeginConnect(IPAddress ipAddress, Int32 serverPort)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)

**Comment by breakwa11** [comment]
3.3.0版已丢弃，直接用3.3.1版吧
