### ISSUE TITLE
import db_transfer     import cymysql

### ISSUE THREAD

**Issue by aesean** [breakwa11/shadowsocks-rss#171]
ubuntu@ip-172-31-27-55:~/src/shadowsocksr/shadowsocks$ sudo python ./server.py -p 81 -k mima -m aes-256-cfb -o http_simple -d start
IPv6 not support
Traceback (most recent call last):
  File "./server.py", line 28, in <module>
    import db_transfer
  File "/home/ubuntu/src/shadowsocksr/shadowsocks/db_transfer.py", line 5, in <module>
    import cymysql
ImportError: No module named cymysql

**Comment by findix** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup(manyuser)

> 安装cymysql
> pip install cymysql
