### ISSUE TITLE
服务器端如何卸载干净重装？

### ISSUE THREAD

**Issue by ganganray** [breakwa11/shadowsocks-rss#174]
我可能在服务器端做了些错误的操作，譬如在manyuser目录做了些操作，现在用不了了。能否干净卸载，重新安装？不知道该怎么操作？

**Comment by nicedayever** [comment]
直接删除 /root/shadowsocks 这个文件夹就行了，ssr python 本来就不用安装。

要是你还觉得不够干净，直接新装系统。

**Comment by ganganray** [comment]
谢谢。确定是这个目录吗？/root 我进不去，里面似乎也没shadowsocks这个文件夹。另外，怎么看manyusr版本的shadowsocks是否处于运行状态，以及如何关闭？

**Comment by nicedayever** [comment]
根据wiki上的安装描述，ssr默认都被放置在/root/shadowsocks这个目录的，你进不去可能因为你没有root权限

查看是否在运行状态，输入 ps aux 可以看看有没有python /xxx/shadowsocks/shadowsocks/server.py 这个进程。

**Comment by breakwa11** [comment]
如果你用非root用户在默认目录git clone，那么通常路径是~/shadowsocks

**Comment by ganganray** [comment]
谢谢。我直接把~/shadowsocks 删了。重新安装后就好了。
