### ISSUE TITLE
[Suggestion] http-simple 中伪造一个完整的http header

### ISSUE THREAD

**Issue by nicedayever** [breakwa11/shadowsocks-rss#175]
现有的http-simple 混淆插件仅仅支持定义域名这一个参数，推荐开放给用户一个定义完整http header的功能，例如这样的

User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
Content-Type: text/plain; charset=utf-8 
Accept: */*
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4,zh-TW;q=0.2
Cookie: blar blar blar

**Comment by breakwa11** [comment]
好主意，不过我要研究一下怎么加到参数里面。。。

**Comment by nicedayever** [comment]
@breakwa11 hi, 刚刚下载了3.6.9，可是发现选择了http-simple插件后，混淆参数仍然只能输入一行字符，这种情况下怎么定义完整header呀？

**Comment by breakwa11** [comment]
见文档
