### ISSUE TITLE
希望能广播一下ss与迅雷冲突的最好解决办法

### ISSUE THREAD

**Issue by iamsurfing** [breakwa11/shadowsocks-rss#176]
一，在安装迅雷的时候不要选择多浏览器支持。
二，已经安装迅雷上的把“设置--监视设置--监视浏览器”的勾取消。
（我认为应该是迅雷更改了有关于浏览器方面的注册表，但是不知道是哪里）

 @breakwa11  
就是希望如果日志中再出现“failed to recv data in handshakeReceive2Callback”并且检测到迅雷的进程运行时，可以出现一个警告，列出上面的解决办法

**Comment by Mirr0ch1** [comment]
之前看到过有说。咔嚓掉迅雷的XLPlatformService就好了。

**Comment by iamsurfing** [comment]
我用的是迅雷纯净版
第一，我也试过喀嚓掉XLPlatformService，然并卵。
第二，我说的这个方法亲测可行。
第三，重启后迅雷又会打开服务。
毕竟迅雷还是有很多人用的，这样子一劳永逸不是很好吗？

**Comment by mikelei8291** [comment]
“咔嚓”说的是删除那个服务，不是禁用

**Comment by Mirr0ch1** [comment]
重启讯雷迅雷管UAC要权限的时候直接拒绝就好了🌚…

**Comment by wenliyang** [comment]
迅雷绿色版，没这服务

**Comment by breakwa11** [comment]
其实我也不知道哪个是最好的解决办法，不过最近看到居然有人把这个问题丢到迅雷论坛上了。。。。

**Comment by iamsurfing** [comment]
好吧我又重新安装了一下迅雷，实验如下：
在安装时如果不选择多浏览器支持，那么ss可以照常使用。
在安装时如果选择多浏览器支持，那么ss就在部分连接用不了（比如可以用谷歌系，不能用flickr），日志报错，在去掉监视浏览器的勾后还是用不了。重启，迅速打开浏览器和ss，依然用不了，过了一会儿出现了一个用户账户的提示（thunderplatform.exe -s）点是后浏览器马上就有了反应，打开了flickr，其他网站也没有问题。
得出结论：
安装时的多浏览器支持与安装后迅雷设置里的监视浏览器是一个意思。不选就可以了。
日志报错后，只要在去掉监视浏览器的勾后重启出现用户账户提示，选是，就能正常使用ss。出现用户账户提示之前包括重启前都不能正常用。
（果然应该是注册表的问题。）

**Comment by Rithard** [comment]
有更好的解决方法吗？好像速度有影响，这迅雷我也是服了，到底干了什么！

**Comment by breakwa11** [comment]
最好的解决办法是升级到迅雷最新版，问题已解决
