### ISSUE TITLE
一个网页一次打不开之后以后再也打不开

### ISSUE THREAD

**Issue by qijiangh** [breakwa11/shadowsocks-rss#177]
昨天刚部署的Debian服务器。TCP协议是auth_simple，obfs是random_head。打开苹果日报网页后，因为Facebook插件没加载上，就再加载网页了一次，结果这个网页始终就打不开，换浏览器也没用。后来不知怎么，整个台湾苹果日报都打不开了。网络测速最高可达500KB/s，所以网络没问题。就算到另一个地点，换了电脑，换了网络还是一样，所以肯定是服务器的问题。与此对比，打开所有其他网站都是正常的，包括香港的苹果日报。问题在重启服务器的shadowsocks服务后解决。

**Comment by breakwa11** [comment]
像是DNS缓冲的问题

**Comment by qijiangh** [comment]
怎么解决？

**Comment by wyxls** [comment]
服务端清除一下dns缓存就行了

**Comment by breakwa11** [comment]
请问现在最新版本还会重现这个问题吗？
