### ISSUE TITLE
ssr不监听TCP端口，而监听了TCP6端口

### ISSUE THREAD

**Issue by kid740246048** [breakwa11/shadowsocks-rss#178]
按wiki的步骤配置的，配置文件如下

```json
{
	"server":"0.0.0.0",
	"server_ipv6":"::",
	"local_address":"127.0.0.1",
	"local_port":1080,
	"port_password":{
		"8000":{"protocol":"auth_simple", "password":"test", "obfs":"http_simple", "obfs_param":""},
		"8002":{"protocol":"origin", "password":"test"}
	},
	"timeout":300,
	"method":"aes-256-cfb",
	"fast_open": false,
	"workers": 1
}
```

运行后netstat -apn查看，只有TCP6和UDP6的监听
> tcp6       0      0 :::8000                 :::*                    LISTEN      5567/python
> tcp6       0      0 :::8002                 :::*                    LISTEN      5567/python
> udp6       0      0 :::8000                 :::*                                5567/python
> udp6       0      0 :::8002                 :::*                                5567/python

请问如何切换到TCP监听？

**Comment by mikelei8291** [comment]
你这不是最新版的 `config.json` 吧，最新版有个 `"dns_ipv6": ` 的字段
`git pull` 一下吧

**Comment by kid740246048** [comment]
代码都是最新的，这个`config.json`是按照[服务端配置教程](https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup)里面的参考配置写的，不知道具体应该改哪里，烦请指点，谢谢了

**Comment by kid740246048** [comment]
我在`~/shadowsocks/`目录下找到了新版的`config.json`文件，然后把我原来的配置文件改成了如下  
```json
{
	"server":"0.0.0.0",
	"server_ipv6":"::",
	"local_address":"127.0.0.1",
	"local_port":1080,
	"port_password":{
		"8000":{"protocol":"auth_simple", "password":"test", "obfs":"http_simple", "obfs_param":""},
		"8002":{"protocol":"origin", "password":"test"}
	},
	"method":"aes-256-cfb",
	"dns_ipv6": false,
	"fast_open": false,
	"workers": 1
}
```
但是尝试连接还是失败

**Comment by breakwa11** [comment]
监听了tcp6后，tcp也可以用的，你连不上应该是防火墙的问题

**Comment by kid740246048** [comment]
问题解决了，的确是我防火墙的问题，系统启用的firewalld，我却在iptables下放行端口，难怪总是无法连通，麻烦各位了
