### ISSUE TITLE
客户端服务器比较多，服务器连接统计数据更新的时候拖动窗口会出现卡顿

### ISSUE THREAD

**Issue by RuioWolf** [breakwa11/shadowsocks-rss#179]
就是服务器比较多，然后通过SS下东西的时候，只要统计的数据一更新整个窗口都会卡一下，虽然不是什么大问题但是强迫症比较难受。。。

**Comment by breakwa11** [comment]
暂时还是把统计窗口弄小一点吧。。。。

**Comment by mikelei8291** [comment]
这是电脑性能问题吧？

**Comment by RuioWolf** [comment]
@breakwa11 @mikelei8291 应该是因为我的服务器列表里面服务器比较多，所以更新数据的时候才会卡住窗口吧。。。不会是电脑问题感觉

**Comment by breakwa11** [comment]
DONE
