### ISSUE TITLE
Python的客户端还没有支持auth_sha1

### ISSUE THREAD

**Issue by kid424** [breakwa11/shadowsocks-rss#182]
四川电信最近干扰丧心病狂，开始转用ssr。因为是用Mac，只能用Python客户端，也就是shadowsocks/shadowsocks/local.py。使用的时候发现目前还不支持推荐的auth_sha1插件，服务端日志显示Protocol ERROR, TCP ogn data xxxx…… 暂时使用auth_simple中，希望作者有时间更新一下，造福一下非Windows用户

**Comment by breakwa11** [comment]
应该修好了，试试

**Comment by kid424** [comment]
确实是修好了，非常感谢。顺便请教下，首页写的：

建议配置方式：

重连次数设置为5 超时秒数设置为60 开启负载均衡

这个重连次数5是在哪里设置？

**Comment by breakwa11** [comment]
只有c#有，在右键->选项设置
