### ISSUE TITLE
关于局域网HTTP代理->ss代理的二级或多级代理

### ISSUE THREAD

**Issue by wyxls** [breakwa11/shadowsocks-rss#183]
一些使用环境需要设置局域网HTTP代理，流量路线是：PC→局域网HTTP代理→ss→服务端→服务器，还是PC→ss→局域网HTTP代理→服务端→目标服务器？

具体要怎么实现，二级代理？尝试过客户端里的前置代理(Http隧道)，不奏效。

**Comment by breakwa11** [comment]
ss本身不要设置二级代理，然后http代理程序设置它的二级代理是ss客户端的地址和端口

**Comment by vcnovember** [comment]
[Gost](https://github.com/ginuerzh/gost)应该可以满足你的需求

**Comment by wyxls** [comment]
我指的是类似于公共http代理服务器一样，只有ip和端口。

不具备对http代理端的操作权。具体来说就是在ie里设置lan为192.168.0.39:808代理http,https,ftp，但不能在局域网代理的服务端上挂载二级代理

**Comment by wyxls** [comment]
再仔细想了一下，这样说是没法进行单方面二级代理了

**Comment by breakwa11** [comment]
@wyxls 我说的方案可以解决啊
流量路线是：PC→局域网HTTP代理→ss客户端→ss服务端→目标服务器

**Comment by wyxls** [comment]
@breakwa11 呃，我用的是windows，所以我对代理理解只停留在:ie里设置系统级代理。

但windows还能在哪里设置二级代理呢？浏览器和其他软件基本也只能设置一级代理

难道通过转发软件(proxifier)之类的？

**Comment by breakwa11** [comment]
当然只能设置一级，你得在【代理软件】里设置二级代理
ss本身不要设置二级代理，然后http代理程序设置它的二级代理是ss客户端的地址和端口，浏览器设置http代理是http代理程序的地址和端口

**Comment by wyxls** [comment]
哦，了解了解，看来还是要靠第三个软件实现

**Comment by gowk** [comment]
@vcnovember 谢谢你推荐的 gost，解决了我的大问题

**Comment by jerryshao4u** [comment]
@gowk 我也想知道你这么用的gost  我这公司代理走的http是需要验证用户的..没明白怎么用..

**Comment by gowk** [comment]
@jerryshao4u 不知道你是不是遇到了跟我相同的情况。我所在公司也是必须设置 HTTP 代理才能上外网。但是不需要用户和密码。

你可以建一个配置文件，比如 ss.conf，内容：

```json
{
  "ServeNodes": [
    ":8080"
  ],
  "ChainNodes": [
    "http://用户名:密码@公司代理地址:代理端口",
    "ss://加密协议:密码@ss代理服务器地址:ss代理端口"
  ]
}
```

之后运行 gost -C=ss.conf，然后再设置你的浏览器使用本地 8080 端口就行了。如果你用 Chrome 推荐使用 Proxy SwitchyOmege 插件，很方便。

**Comment by xunxuntj** [comment]
楼上的方法解决了我的问题

**Comment by guoxf2016** [comment]
使用gost，配置如下：
{
	"ServeNodes": [
		":8080"
	],
	"ChainNodes": [
		"http://127.0.0.1:3128", //这个是cntlm代理
		"ss://加密协议:密码@ss代理服务器地址:ss代理端口"
	]
}

但是打开网页，gost报了一个错误：
502 Proxy Error ( The specified Secure Sockets Layer (SSL) port
 is not allowed. Forefront TMG is not configured to allow SSL requests from this port. Most Web browsers use port 443 for SSL requests.  )

@gowk 请问是哪里配置的不对吗？谢谢！

**Comment by gowk** [comment]
@guoxf2016 检查一下你的 cntlm 配置吧，或者看看是不是防火墙的问题，直接用 http://127.0.0.1:3128 可以上网吗

**Comment by guoxf2016** [comment]
@gowk 不加下面的一行ss代理，可以正常访问墙内网站，
不开gost，直接用 http://127.0.0.1:3128 可以上网。
下面的ss代理是直接用服务器端的ip和端口对吧，不用在本地开ss客户端对吗？
看错误信息似乎是端口必须是443，难道是ss服务端必须打开443端口？

**Comment by gowk** [comment]
@guoxf2016 不用本地开 ss 客户端，gost 就是客户端了，避免歧义，我修改为："ss://加密协议:密码@ss服务器地址:端口"

**Comment by guoxf2016** [comment]
@gowk  在服务端搞了个端口转发，解决了。谢谢！
