### ISSUE TITLE
更新有点过频啊

### ISSUE THREAD

**Issue by 1608637229** [breakwa11/shadowsocks-rss#185]
不知道优化了什么，我用的那个还是2.58版本，是不是和这个不一样啊

**Comment by qijiangh** [comment]
我还好。跟着版本更新就好了。就怕代理不给力。这年头找个给力的代理真不容易，花多少钱都没保障。

**Comment by WLZLCX** [comment]
所以，我用的也是原来的SS 2.5.8版

**Comment by hypogaea** [comment]
这种软件还是跟着更新的好，免得旧版登不上去了哭瞎

**Comment by breakwa11** [comment]
话说你既然用的是2.5.8，那你怎么知道更新有点过频？不是应该和你那个版本没有关系么？

**Comment by hanzexu990323** [comment]
這種問題能不能不要再提了，毫無意義啊。
@breakwa11 不關閉麽
