### ISSUE TITLE
现在iOS端是没有人接手了吗……

### ISSUE THREAD

**Issue by BROBIRD** [breakwa11/shadowsocks-rss#188]
希望有大神可以继续维护

**Comment by Cloverr0** [comment]
ios有surge不过被下架了

**Comment by breakwa11** [comment]
我认为那个并不是“被下架”

**Comment by BROBIRD** [comment]
@breakwa11 貌似在作者的博客里有人问了他为什么下架，他发了一个“茶”的表情

**Comment by breakwa11** [comment]
但现在貌似又准备上架1.1.2版，已经提交审核了

**Comment by BROBIRD** [comment]
@breakwa11 他在博客里说会标高价，供老用户更新……

**Comment by breakwa11** [comment]
如果真是茶的原因，那这一回足够来第二杯，还打半价

**Comment by BROBIRD** [comment]
@breakwa11 半价是什么梗……

**Comment by mayuelei66** [comment]
99.9美金 还是一堆人购买。当时9.9的时候犹豫了半天的，没买的人后来都后悔了

**Comment by zkzipoo** [comment]
是啊，为了能用只能维持手机ios 8

**Comment by leungzw** [comment]
淘宝上有卖surge账号的，把他的apple id给你安装。
风险提示：apple id可远程锁机。安装完尽早退出。

**Comment by zkzipoo** [comment]
@leungzw 感觉有点害怕。。。

**Comment by bsfmig-a** [comment]
@leungzw 更好的方法是，用Xcode自己签一个开发者版本出来。现在这样的自签名ipa已经不需要Apple Developer Program了，分发才需要。

**Comment by zkzipoo** [comment]
@bsfmig-a 没有源码也可以签吗？

**Comment by tardis2012** [comment]
@zkzipoo github上的iOS客户端没有能直接编译的了，少了几个关键部分的代码， 我下载了好多版本的shadowsocks 编译到最后都缺少一些源文件

**Comment by tardis2012** [comment]
我现在在尝试逆向工程surge

**Comment by zkzipoo** [comment]
@tardis2012 哥，如果搞定了请叫上我，我帮你免费测试

**Comment by bsfmig-a** [comment]
@zkzipoo 可以。签名的过程是给IPA包加个数字签名，使得这个二进制Bundle能够被iOS的应用软件安装安全检查机制接受。

**Comment by zkzipoo** [comment]
@bsfmig-a 那有surge的ipa吗？哪里可以下载到~

**Comment by guijianchou** [comment]
热乎的surge ipa文件，需要的自取。有更新的话请直接at我。https://onedrive.live.com/redir?resid=2441FDA4712B8FFB!964&authkey=!AE5ckSDRl0xG2CU&ithint=file%2cipa

**Comment by yclddv** [comment]
@breakwa11 68被喝茶 680就不被喝茶了 这个逻辑说不通啊

**Comment by Naville** [comment]
@guijianchou 
git:(master) ✗ otool -l /Users/Naville/Downloads/Surge\ 1.2.2/Payload/Surge-iOS.app/Surge-iOS |grep cryptid
      cryptid 1
      cryptid 1




ROFL

**Comment by lersh** [comment]
不是有shadowrocket了吗，6元，我用了很正常

**Comment by rconex** [comment]
@guijianchou 链接失效了

**Comment by hanxi** [comment]
@zkzipoo 新鲜出炉的重签ipa教程

**Comment by guijianchou** [comment]
@rconex    surge 1.2.4   https://onedrive.live.com/redir?resid=2441FDA4712B8FFB!969&authkey=!AJkikxE18t552HQ&ithint=file%2cipa

**Comment by zning1994** [comment]
@guijianchou 话说重签IPA的，能用surge for mac beta吗？

**Comment by guijianchou** [comment]
@zning1994 理论上可以，因为surge for mac并没有通过账户之类的认证，这样几乎不存在强制绑定（虽然最终也是要ios 客户端通过蓝牙认证）。不过我上面发的是直接我账户在itunes上下载的，没有重签IPA

**Comment by zning1994** [comment]
@guijianchou soga，回头实践下

**Comment by captain-zhu** [comment]
@guijianchou 
有最新版的吗,1.24版本闪退
