### ISSUE TITLE
FIREFOX+AUTOPROXY用过这个后，其它代理不能正常使用。

### ISSUE THREAD

**Issue by leoxxx** [breakwa11/shadowsocks-rss#19]
我有在用SS,GOAGENT和SSH，最近发现用了这个以后其它两个无法正常使用。如果想要其它代理能正常使用必须要SS进行一次有效的连接后才能正常使用其它的代理。看了一下goagent托盘区的提示，原来是“GOAGENT已启动”，现在是”http ://127.0.0.1:1080/pac?t=201508070947536751“。这东西每次启动客户端都会自动生成，后面的数字好像日期有关。IE里是找到了相关设置，注册表也找个只有IE的项。不知道FIREFOX这东西在哪里可以改。

**Comment by breakwa11** [comment]
因为你启用了系统代理，想独立使用就不启用系统代理，自己设置浏览器设置

**Comment by leoxxx** [comment]
@breakwa11 那么我现在怎么改回来？我一直以为客户端上的那个是启动连接。IE那边到是搞定了，不会再自动生成。但是GOAGENT打开还是显示那个地址。这个系统代理在哪里可以删除？

**Comment by breakwa11** [comment]
对的，禁用GoAgent使用IE代理设置，或者客户端不启用系统代理都可以

**Comment by leoxxx** [comment]
刚试了，正常了。
