### ISSUE TITLE
多用户版本运行几个小时小时无法使用

### ISSUE THREAD

**Issue by op2009** [breakwa11/shadowsocks-rss#190]
log

:04:59 INFO     starting server at 0.0.0.0:5102015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [516] pass [46689]2015-12-27 13:04:59 INFO     starting server at [::]:5162015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5162015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [520] pass [49113]2015-12-27 13:04:59 INFO     starting server at [::]:5202015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5202015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [525] pass [54179]2015-12-27 13:04:59 INFO     starting server at [::]:5252015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5252015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [532] pass [96339]2015-12-27 13:04:59 INFO     starting server at [::]:5322015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5322015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [539] pass [25356]2015-12-27 13:04:59 INFO     starting server at [::]:5392015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5392015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [544] pass [81722]2015-12-27 13:04:59 INFO     starting server at [::]:5442015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5442015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [550] pass [49648]2015-12-27 13:04:59 INFO     starting server at [::]:5502015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5502015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [561] pass [30394]2015-12-27 13:04:59 INFO     starting server at [::]:5612015-12-27 13:04:59 WARNING  IPV6 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     starting server at 0.0.0.0:5612015-12-27 13:04:59 WARNING  IPV4 [Errno 98] Address already in use 2015-12-27 13:04:59 INFO     db start server at port [568] pass [27777]2015-12-27 13:04:59 INFO     starting server at [::]:5682015-12-272015-12-27 13:0

**Comment by breakwa11** [comment]
你开了两个，前一个未完全关掉

**Comment by breakwa11** [comment]
更新一下服务端代码，把前一进程杀掉，然后关了ssh会话，重新登陆应该就好了

**Comment by op2009** [comment]
我昨晚尝试一下 我把系统重新安装了 在弄一次  还是一样，我确实只启动一个，但是10个小时突然多出来一个但是实际我只是启动一个 结果自己跑出来两个，不知道原因在哪里

**Comment by breakwa11** [comment]
你得检查你的守护进程配置，另外我2小时前说让你更新，是因为2小时前我有修改

**Comment by op2009** [comment]
好的我已经更新了 ，现在测试一晚看还有断线没有

**Comment by op2009** [comment]
还是一样问题，这次没有出现重复 python server.py  但是 PS 有进程就是连不上，必须手动关闭 python 再次启动才能连上 ，服务器 linode 难道我用数据库导致

**Comment by breakwa11** [comment]
你再更新一下新版，运行后再查查log看看
另外，你服务器内存多大？有没有swap

**Comment by op2009** [comment]
linode 2g 512 MB, swap)  内存 找到原因了，服务端配合自带./run.sh脚本启动，就可以了， 没有发生问题了，我之前使用 cd /root/shadowsocks
nohup python server.py &  自己手动开机加载会有问题 ，现在./run.sh脚本启动服务端已经没有发生了

**Comment by breakwa11** [comment]
那就好

**Comment by sunnoy** [comment]
服务端配合自带./run.sh脚本启动，就可以了， 没有发生问题了，我之前使用 cd /root/shadowsocks
nohup python server.py & 自己手动开机加载会有问题 ，现在./run.sh脚本启动服务端已经没有发生了
请问这是怎么操作的呢

**Comment by andy817** [comment]
我也没有解决这个问题，，，而且是经常宕机，重启好频繁。。。

**Comment by guliujian** [comment]
你没有把这个程序开机启动当然不能开机自动加载，还有你得看你的run.sh到底执行了啥，不贴上来看看谁也不知道他干了啥。

**Comment by andy817** [comment]
我已经把run.sh加到rc.local里面了，关于这个“ run.sh到底执行了啥”   我也不懂，不知道怎么看，自学linux入门中。
还望大神指教。
万分感谢！
