### ISSUE TITLE
一个关于GFWList的小问题

### ISSUE THREAD

**Issue by BROBIRD** [breakwa11/shadowsocks-rss#192]
只是问一下客户端使用的是哪一个GFWLIST源？如果要向在线列表中添加新的被Q地址，在哪里添加？

**Comment by breakwa11** [comment]
向gfwlist项目提交issue
https://github.com/gfwlist/gfwlist/issues
这里是github，没有自我审查的必要

**Comment by BROBIRD** [comment]
@breakwa11 好的，了解！
