### ISSUE TITLE
Python版与libev版相性不好？

### ISSUE THREAD

**Issue by wyxls** [breakwa11/shadowsocks-rss#194]
服务器挂的Python多用户版，毕竟方便管理

openwrt挂的libev版，检测能用，只是tcp连接一多就处理不过来，连接闲置较多，导致路由解析失败

执行的netstat -ltnap | grep -c TIME_WAIT，很多情况下都超50

只能在服务器挂libev端了？可是libev又不支持多用户参数

也许只是路由太多设备(快20台)导致的?

**Comment by breakwa11** [comment]
连接数较多的时候你需要优化一下系统参数，但TIME_WAIT数量并没有什么关系

**Comment by wyxls** [comment]
Python版的服务端兼容libev版客户端连接(ss-redir和ss-tunnel)么？

**Comment by breakwa11** [comment]
ss-local/redir只是处理本地地址方式的区别，外部协议都一样的，所以是能用的

**Comment by debiansid** [comment]
打开混淆就不能连接

**Comment by debiansid** [comment]
兼容性：目前ssr-libev客户端仅支持verify_simple, auth_simple, auth_sha1协议，及http_simple混淆。其余的ssr-python及ssr-c#支持全部的协议和混淆。

什么时候可以支持全部协议及混淆？
