### ISSUE TITLE
[建议] 关于固定 HTTP(S) 代理端口

### ISSUE THREAD

**Issue by chenyiping1995** [breakwa11/shadowsocks-rss#196]
因为 YouTube-DL 不兼容 SOCKS 代理，所以必须走 HTTP 代理。
虽然ShadowsocksR的介绍称“全能代理，同一端口支持socks4/socks4a/socks5/http”，但是实际使用时 YouTube-DL 会卡在 [youtube] Downloading login page 上。
![image](https://cloud.githubusercontent.com/assets/16564295/12125362/ebe80268-b425-11e5-90d9-cd03d13180da.png)

ShadowsocksR 会生成一个 temp 文件夹，里面用了 privoxy，每次打开 privoxy.conf 都能看到第一行listen-address 127.0.0.1:(此处为SOCKS2HTTP代理端口) 会变化。

能否在 ShadowsocksR 的选项设置里提供选项，让用户选择自己的 HTTP(S) 代理端口（若用户不指定则使用全能代理），或者能否帮忙检查，是什么样的原因造成 Youtube-DL 不能正确识别 ShadowsocksR 设置的“全能代理”？感激不尽。

Youtube-DL项目地址 https://github.com/rg3/youtube-dl

**Comment by mikelei8291** [comment]
端口应该是固定的啊，在“选项设置”里

**Comment by falseen** [comment]
又来一个说端口问题的，我真是不知道说什么好了。。。
建议你翻翻以前的issues ，已经有好几个人这样问过了。
我还是补充一下吧，那个随机端口是为了不跟原来的privoxy端口冲突（假如用户在开了privoxy的情况下启动ssr，两个privoxy的端口就会冲突）。
在实际使用过程中，这个随机端口是不起作用的，不信你自己测试一下就知道了。

**Comment by falseen** [comment]
不过这个下载工具确实挺好用的，我试了一下没有出现你说的问题。
我是用pip 安装的。

**Comment by chenyiping1995** [comment]
@falseen
但是我实际用的时候，给YouTube-DL指定为使用Privoxy的随机的端口(手动到conf下查看)就不会出现问题，能正常工作，而使用SSR默认1080端口就不行，这是什么原因呢。。

**Comment by falseen** [comment]
那就有可能是ssr调用Privoxy的过程中出了问题，有没有用其他软件测试过ssr的http代理（默认端口）？

**Comment by chenyiping1995** [comment]
@falseen 
看起来是Youtube-DL的问题。设置Chrome的代理为HTTP可以正常使用。

可以问一下你用Youtube-DL的参数么？我在怀疑我Youtube-DL参数设置的问题了。
我使用的参数是：(所有变量在我自己写的Bat开头进行定义。)
youtube-dl --proxy %proxy% --write-description --write-thumbnail --write-sub -u %gAccount% -p %gPassword% --embed-subs --add-metadata -f %formatCode% %vid%

**Comment by falseen** [comment]
我只用了 --proxy -u -p 参数，其他参数没用。你把其他参数去掉试试。

**Comment by chenyiping1995** [comment]
![image](https://cloud.githubusercontent.com/assets/16564295/12135573/80613c3c-b478-11e5-894c-7d43b78b1c6f.png)
使用 Privoxy 的情况。

**Comment by breakwa11** [comment]
这个速度差别是统计方式的不同，它是统计从开始到现在的平均，软件中仅仅是最近5秒

**Comment by chenyiping1995** [comment]
@breakwa11 重点并不是速度差的问题，而是Privoxy的端口问题。

**Comment by chenyiping1995** [comment]
@breakwa11 见上面的记录。

**Comment by breakwa11** [comment]
原因貌似找到了，下版本修好

**Comment by breakwa11** [comment]
已发布 https://github.com/breakwa11/shadowsocks-csharp/releases/tag/3.7.2
清测试一下

**Comment by chenyiping1995** [comment]
@breakwa11 
有进展，不过这次卡在新地方，而且有个新错误。
![image](https://cloud.githubusercontent.com/assets/16564295/12215217/7c1648de-b6ee-11e5-9ee4-28905f1e0cfc.png)

Y outube-DL版本2016.1.9。

**Comment by breakwa11** [comment]
找到问题了，再试试 https://github.com/breakwa11/shadowsocks-csharp/releases/tag/3.7.2.1

**Comment by chenyiping1995** [comment]
@breakwa11
已换3.7.2.1版本，依然跟3.7.2一样的结果。（顺提这版本号可真……）

**Comment by breakwa11** [comment]
你有BTsync吗，上面同步一个beta2版本试试呢

**Comment by breakwa11** [comment]
BTsync上的beta3已测试可以下载，你试试看

**Comment by chenyiping1995** [comment]
@breakwa11 
beta 3没有出现任何Error信息，卡在第二行
![image](https://cloud.githubusercontent.com/assets/16564295/12229144/597a040e-b87f-11e5-9ccc-27e798d9cb2e.png)

**Comment by fovecifer** [comment]
用proxychains 配合youtube-dl
我一直用这个方法

**Comment by chenyiping1995** [comment]
@fovecifer 
然而按理说ShadowsocksR提供的端口是可以HTTP代理的，何劳再用第三方工具呢?
其实每次开启ShadowsocksR的时候，temp下的Privoxy提供了一个随机端口可以用，然而每次都会变。

**Comment by breakwa11** [comment]
3.7.3已修正，实测正常

**Comment by chenyiping1995** [comment]
@breakwa11 
3.7.3 工作正常，感谢修复。
