### ISSUE TITLE
怎么设置前置HTTP代理啊，就是怎么把socks5转成HTTP？

### ISSUE THREAD

**Issue by nonozone** [breakwa11/shadowsocks-rss#197]
在选项设置里折腾了半天，发现没成功啊。

**Comment by breakwa11** [comment]
到底设置什么，你说的两个东西根本没有一点关系，你肯定搞错了

**Comment by nonozone** [comment]
```
多重代理，通过设置前置socks5/http代理，可达到任意重代理
```

还是我理解错了？现在SS不是socks代理么，我想本地把socks转成https代理。就是直接用ssR代替Privoxy的工作。

**Comment by breakwa11** [comment]
你根本就理解错了，你用不上多重代理

**Comment by nonozone** [comment]
@breakwa11 那如果我需要把socks转成本地http代理，还是一样需要用privoxy才可以，对吧？

**Comment by breakwa11** [comment]
根本不需要，直接用你设置的端口就得了，请看主页使用说明
