### ISSUE TITLE
为什么使用服务器版本搭建完后用PS4测试是NAT3？

### ISSUE THREAD

**Issue by superfls** [breakwa11/shadowsocks-rss#198]
centos7.0系统，mariadb数据库，没有安装ss-panel，其余都是按照wiki上设置的，服务启动没有问题，也能正常使用，但是使用PS4进行网络测试显示NAT3，求解！！！！

**Comment by breakwa11** [comment]
我也不知道。。。设计的时候是按NAT2做的，有人说用了后是NAT2，像你是NAT3，具体为什么我暂时不清楚

**Comment by wyxls** [comment]
也许只是因为你的网是网中网_(:з」∠)_

**Comment by superfls** [comment]
好吧，这个确实属于运气问题，有时会出现NAT3的情况，现在已经正常了。
