### ISSUE TITLE
可否添加一个开关，是否调用ss_polipo.exe

### ISSUE THREAD

**Issue by wholeworm** [breakwa11/shadowsocks-rss#20]
原因如下：

第一，对于chrome和firefox用户来说，根本不需要这个程序来转换为HTTP代理，白白浪费系统资源。

第二，对于IE用户来说，PolipoRunner.Start()方法里面，会先查找名为ss_polipo.exe的进程，然后全部kill掉。这在开启了多个客户端的时候，会把其他客户端的子进程一起kill掉，导致出错。原版程序由于只能启动一个，所以不存在这个问题。然而这个修改版改了polipo的路径，可以启动多个，但是Start()方法里面的逻辑并没有修改，会导致问题。

所以我建议，能否加入一个设置项，让用户可以选择是否要转换成HTTP代理。

感谢！

**Comment by breakwa11** [comment]
不会的啊，是不是启动原版导致把polipo杀了？

**Comment by wholeworm** [comment]
谢谢回复，确实是启动原版导致的。
不过我还是想要有这样一个开关，因为多两个进程看着很不爽啊。。。

**Comment by breakwa11** [comment]
目前还不能去掉
