### ISSUE TITLE
局域网连接对UDP协议的支持

### ISSUE THREAD

**Issue by wyxls** [breakwa11/shadowsocks-rss#201]
设备设置局域网IP通过另一台允许局域网连接的客户端进行代理，是否包含UDP协议转发？

如果支持的话，UDP协议的数据和请求的转发与否是不是取决于该设备代理是否支持UDP转发？

**Comment by breakwa11** [comment]
具体看客户端是否支持，目前最新版本都是支持的
但是UDP转发有两种理解，如果是Socks5代理的UDP，那么是年f客户端，如果是重定向转发，那么需要路由器或一台linux机来做
