### ISSUE TITLE
为啥用SS，开了全局代理，也不能给BlueStacks代理啊！

### ISSUE THREAD

**Issue by doio** [breakwa11/shadowsocks-rss#202]
如题，模式都试过了，就是没有流量经过，要是SS能模拟VPN功能就好了？

**Comment by wyxls** [comment]
因为bluestack并没有理睬IE的系统代理

**Comment by doio** [comment]
吼吼吼~~~那有其它办法吗？就是让SS真正的全局？

**Comment by hanzexu990323** [comment]
乃可以使用 Proxifier 來把Socks5/HTTP轉為真正的全局代理
