### ISSUE TITLE
3.7.3似乎无法更新PAC了，强行断开连接后出现如下错误

### ISSUE THREAD

**Issue by BROBIRD** [breakwa11/shadowsocks-rss#204]
[2016-01-11 18:49:01] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-01-11 18:49:01] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

**Comment by breakwa11** [comment]
3.7.3.1已修好
