### ISSUE TITLE
Win10下关了系统代理之后Edge无法工作

### ISSUE THREAD

**Issue by tsstss123** [breakwa11/shadowsocks-rss#206]
RT
关掉程序/重启也无法解决问题...然后系统里一些程序(包括那个语音搜索栏)也用不了网了...
谢谢

**Comment by breakwa11** [comment]
关掉后检查一下IE里面的internet连接选项，局域网代理部分，看一下是什么设置

**Comment by tsstss123** [comment]
这部分是全空着的...

**Comment by tsstss123** [comment]
在IE->高级里重置了整个IE之后重启可以用了...谢谢

**Comment by breakwa11** [comment]
类似问题我也曾经遇到过，原因不明，但肯定是IE哪里的配置有问题。。。
