### ISSUE TITLE
3.7.3.1版的前置代理有问题

### ISSUE THREAD

**Issue by redfrog999** [breakwa11/shadowsocks-rss#207]
同样的配置文档，相同的前置节点设置，最新版卡卡卡，卡得很。换回3.6.9一切正常。侠女测试看看，估计还要再修一修。

**Comment by breakwa11** [comment]
具体配置是啥？用什么配置？

**Comment by redfrog999** [comment]
昨晚N多case忙晕了，：（。经过今天白天的测试，原来是小区的线路Boom了，抱歉。现在一切正常了。
