### ISSUE TITLE
关于config.json和user-config.json

### ISSUE THREAD

**Issue by superfls** [breakwa11/shadowsocks-rss#208]
我同时配置的了两个文件，加密方式和端口设置的都不一样， 发现最后是user-config.json文件生效的，但是看日志的话这两个文件都加载了，这两个文件有什么关系吗？

**Comment by breakwa11** [comment]
在存在user-config.json的时候就用这个文件，避免更新的时候配置文件冲突

**Comment by superfls** [comment]
哦，谢谢!
