### ISSUE TITLE
能否出一个libev服务器端的安装配置教程

### ISSUE THREAD

**Issue by iamdamaha** [breakwa11/shadowsocks-rss#209]
一直都是用的原版的libev服务器端，新版不知道在安装配置方式上有些什么改动，能否出一个新的教程。原版现在受干扰严重，用起来已经断断续续了

**Comment by breakwa11** [comment]
ssr服务端现只有python版

**Comment by debiansid** [comment]
@breakwa11 什么时候ssr移植到libev

**Comment by breakwa11** [comment]
客户端有libev,c#,python

**Comment by antikan** [comment]
python客户端拥有c#的全部功能就好了
