### ISSUE TITLE
新版的manyuser，用户更改了节点密码之后不用重启服务器了么？

### ISSUE THREAD

**Issue by kozora** [breakwa11/shadowsocks-rss#21]
RT

**Comment by niuniu123** [comment]
刚更新测试了下，依旧需要重启服务器，这是个大问题，如果别有用心的用户知道了这个bug，你就准备整天重启服务器吧，如果你不只一个加速节点，有你忙的。。。关键是影响用户体验

**Comment by kozora** [comment]
我不知道这个是manyuser的锅还是sspanel的

**Comment by breakwa11** [comment]
并不需要重启服务器，但生效需要半分钟到一分钟的时间

**Comment by kozora** [comment]
等会就去更新！

**Comment by breakwa11** [comment]
更新后如果没有发现问题，告诉我一声

**Comment by kozora** [comment]
更改密码之后，过了好几分钟了，还是和没更新新版manyuser一样，无法生效，http://ww4.sinaimg.cn/large/891f6d5ajw1euyzzqvd4ej20h10160t0.jpg

**Comment by kozora** [comment]
生效了，但是不是几分钟后，起码一小时吧。。

**Comment by breakwa11** [comment]
修好了

**Comment by kozora** [comment]
服务端更新一下代码？

**Comment by kozora** [comment]
过了半天了。。还是和刚才一样。。

**Comment by kozora** [comment]
不需要重启服务器倒是可以了。只需要运行一下 ./stop.sh  再运行 ./run.sh   不过还是有点麻烦

**Comment by breakwa11** [comment]
问题解决了，更新一下吧
