### ISSUE TITLE
关于redirect参数的使用

### ISSUE THREAD

**Issue by superfls** [breakwa11/shadowsocks-rss#211]
我的理解是当请求的数据有问题时，服务器会把请求重定向到设置的这个网址返回给用户。
配置为："redirect":"www.baidu.com",
然后在浏览器中输入一个不存在的网址，返回的时浏览器的错误提示，而不是百度网页，不明白是我理解有问题还是操作问题。

**Comment by debiansid** [comment]
我理解是给墙用的redirect

**Comment by mikelei8291** [comment]
使用错误的密码或加密方式连接才会被重定向。。。

**Comment by mikelei8291** [comment]
而且建议你把该值设置为国外的网站，原因我就不细说了。。

**Comment by breakwa11** [comment]
这是是防GFW主动探测，让其重定向，伪装响应用的，和楼主的理解不同
