### ISSUE TITLE
关于清空Log

### ISSUE THREAD

**Issue by hpfs0** [breakwa11/shadowsocks-rss#212]
由于使用时间长了，Log文件很大，想对Log做清理操作。由于Log文件一直在被客户端使用中，只能先关闭客户端然后在手动清理Log，感觉这样比较麻烦。建议在客户端里加入清理Log的功能谢谢。

**Comment by ruan11223344** [comment]
赞同~  或者可以设定时隔多久清理~？

**Comment by mikelei8291** [comment]
自己做个crontab就行啊

**Comment by breakwa11** [comment]
我的想法是log按年月命名，这样每个log限制于一个月，同时旧的可以直接删除掉

**Comment by ruan11223344** [comment]
这样也好分清log 文件 ，赞同。🎁

**Comment by hpfs0** [comment]
@breakwa11 这个想法可以接受

**Comment by breakwa11** [comment]
已实现
