### ISSUE TITLE
DNS解析请求是在本地机器吗？

### ISSUE THREAD

**Issue by xie3507** [breakwa11/shadowsocks-rss#219]
我发现把本机DNS服务器设为一个无效地址后，通过代理不能再上网。这是不是意味着域名解析是在本地进行的，而不是通过代理服务器呢？
但是在代码中ss客户端与浏览器握手完之后，并没有把IP和Port传递给ss服务端。那ss服务端是怎么代替浏览器发起请求的呢？

**Comment by breakwa11** [comment]
这样的话除非你的服务器节点设置是ip，不然还是连不上

**Comment by xie3507** [comment]
@breakwa11  您的意思是域名解析还是在本机？

**Comment by breakwa11** [comment]
节点如果你填写的域名，那么会使用本地解析获取节点IP，其它情况不会用到本地解析，除非你用了绕过大陆IP的PAC

**Comment by xie3507** [comment]
@breakwa11 我通过公司的局域网访问互联网，公司的公网IP可能只有一个。我现在通过ss代理后，每次访问网站总是只能返回响应头部，响应体为空。但是我在家直接访问互联网却没有这个问题。请问这是什么原因呢？

**Comment by breakwa11** [comment]
换个混淆试试
