### ISSUE TITLE
log文件导致同步频繁

### ISSUE THREAD

**Issue by ityan2008** [breakwa11/shadowsocks-rss#221]
我是把软件放在同步的文件夹的，但是temp文件夹里面的文件频繁变动，导致不停同步，可否不让他生成那些文件？这些信息都保存在缓存里面，需要查看的时候从软件调用查看。

**Comment by wenliyang** [comment]
同步软件应该有排除功能，你排除temp文件夹，不让它同步就行了吧

**Comment by ityan2008** [comment]
我用的Onedrive，它是可以排除，但是排除之后会在同步的图标上面显示个叉叉，文件夹上面也会有个大叉叉。以前clowwindy的版本就不存在这个问题。

**Comment by ityan2008** [comment]
我觉得可以在软件中设置一个开关，这样需要查看日志的时候才让它生成log文件。
