### ISSUE TITLE
最新版本3.7.4出错率明显上升

### ISSUE THREAD

**Issue by KyonCN** [breakwa11/shadowsocks-rss#224]
本地日志一直显示failed to recv data in HandshakeReceive2Callback
一直有26%的出错率 大多数是超时 一两个空连 
在上一个版本上面没有出现这个问题
一开始我以为是迅雷服务的问题 后来我确认了几遍 关闭了迅雷的服务 还是报错

**Comment by road0001** [comment]
同，我的也是……

**Comment by breakwa11** [comment]
是不是因为btsync，我关了它就没事，开了就偶然出现，你看看你的是不是这样

**Comment by breakwa11** [comment]
更新到最新版本
