### ISSUE TITLE
pac更新失败

### ISSUE THREAD

**Issue by mengyyy** [breakwa11/shadowsocks-rss#226]
想问问怎样手动更新（已放弃用自带的更新）
[2016-01-29 15:09:25] System.Reflection.TargetInvocationException: 鎿嶄綔杩囩▼涓嚭鐜板紓甯革紝缁撴灉鏃犳晥銆傛湁鍏冲紓甯哥殑璇︾粏淇℃伅锛岃鏌ョ湅 InnerException銆?---> System.Net.WebException: 鍩虹杩炴帴宸茬粡鍏抽棴: 鏈兘涓?SSL/TLS 瀹夊叏閫氶亾寤虹珛淇′换鍏崇郴銆?---> System.Security.Authentication.AuthenticationException: 鏍规嵁楠岃瘉杩囩▼锛岃繙绋嬭瘉涔︽棤鏁堛€?
   鍦?System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   鍦?System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   鍦?System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 鍐呴儴寮傚父鍫嗘爤璺熻釜鐨勭粨灏?---
   鍦?System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   鍦?System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   鍦?System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 鍐呴儴寮傚父鍫嗘爤璺熻釜鐨勭粨灏?---
   鍦?System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   鍦?System.Net.DownloadStringCompletedEventArgs.get_Result()
   鍦?Shadowsocks.Controller.GFWListUpdater.http_DownloadPACCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-01-29 15:09:25] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadPACCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object _InvokeMethodFast(System.Object, System.Object[], System.SignatureStruct ByRef, System.Reflection.MethodAttributes, System.RuntimeTypeHandle)
System.Object InvokeMethodFast(System.Object, System.Object[], System.Signature, System.Reflection.MethodAttributes, System.RuntimeTypeHandle)
System.Object Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, Boolean)
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void runTryCode(System.Object)
Void ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

**Comment by breakwa11** [comment]
可能是老版本客户端的问题，尝试新版本并确认节点信息正确
