### ISSUE TITLE
求mac客户端

### ISSUE THREAD

**Issue by chncwang** [breakwa11/shadowsocks-rss#230]
求mac客户端~因为命令行版并不好装，安装m2crypto时会提示找不到openssl，当我想把openssl链接到/etc/include时，mac系统又不允许你动/etc目录，sudo都不行

**Comment by ChaoCheung** [comment]
@chncwang https://github.com/shadowsocks/shadowsocks-iOS/releases/download/2.6.3/ShadowsocksX-2.6.3.dmg

**Comment by chncwang** [comment]
这个是不是只能兼容模式？和shadowsocks是一样的？

**Comment by setsunawang** [comment]
@chncwang 
[Stackoverflow](http://stackoverflow.com/questions/33005354/trouble-installing-m2crypto-with-pip-on-el-capitan)
按照第三个方法，用port安装,之前先去macport网站下pkg安装port。
我是这么安装成功的，希望对你有用。

**Comment by breakwa11** [comment]
https://plus.google.com/u/0/112409360242027408521/posts/VtZ1zaEiaJz
