### ISSUE TITLE
不知道是否只是3.7.4的问题，在访问动漫花园的时候发现的

### ISSUE THREAD

**Issue by BROBIRD** [breakwa11/shadowsocks-rss#232]
当使用PAC模式时，访问动漫花园的时候似乎只是在“读取PAC”后首次访问会走代理，之后的访问都是直接访问源站，导致除了首次访问之外都返回403 Forbidden，开全局则没有问题
补充：其他网站好像也有相同问题

**Comment by xx199qq530** [comment]
PS,SS-gui在电信下也不能幸免。重启路由后IP地址发生变化

**Comment by BROBIRD** [comment]
===============更新=================
貌似是负载均衡的锅 关掉或者换成“定时切换”好像就好了

**Comment by breakwa11** [comment]
那是网站本身的IP校验，和软件无关

**Comment by BROBIRD** [comment]
不是 我是说它不是每次都走代理
