### ISSUE TITLE
使用时被断网

### ISSUE THREAD

**Issue by xx199qq530** [breakwa11/shadowsocks-rss#233]
你好，最近在在浙江电信下  3.7.4.1版下，一旦链接打开外网几分钟后就会断网，重启路由器后恢复。
现在只能暂用SS-gui2.5.8版本，出现此问题j间隔较长约一小时。还有，RSS在浙江移动下没有异常。

**Comment by Gonesave** [comment]
同浙江的路过

**Comment by breakwa11** [comment]
你应提供具体的配置，如果因为配置有问题导致被封锁，那要改配置。如果因为你机器上安装了什么软件可能产生这个结果，你也应该说明
