### ISSUE TITLE
【投诉 / 建议】可否加入服务器发生故障自动“报警”功能

### ISSUE THREAD

**Issue by ARwMq9b6** [breakwa11/shadowsocks-rss#237]
请求添加功能让 ssr 在发现有服务器“罢工”（比如下载流量一直为零）后在某一时间向主人报告。

“某一时间”可以是“即刻”、“下次启动时”、“第二天”等；

提醒方式可以是“在桌面冒气泡”、“拉警报”、“给主人发邮件”、“向主人的 Telegram 发消息”等。

**Comment by sukui** [comment]
..............................

**Comment by sukui** [comment]
这个看作者心情，或者你给钱她雇佣她强制开发！

**Comment by leungzw** [comment]
这太扯了。
续费或服务器的问题让软件来监测…
自己找第三方的实现好过

**Comment by qijiangh** [comment]
我也觉得没必要为实现这个功能耗费精力。

**Comment by ARwMq9b6** [comment]
用批处理配合 [ss-local]( http://dl.lazyzhu.com/file/Toolchain/ss-libev/ ) 测试节点可用性 +1。

**Comment by ChaoCheung** [comment]
我的天，服务器挂了可以用阿里云的云监控SSR的端口，可以发短信，发邮件及时通知你！！！
