### ISSUE TITLE
【投诉 / 建议】求加入通过远程服务器获取及更新节点信息的功能

### ISSUE THREAD

**Issue by ARwMq9b6** [breakwa11/shadowsocks-rss#238]
**缘由 / 困扰**：给男朋友的电脑用了 ShadowsocksR, 由于经常不在他身边，更换服务器密码、加密方式、协议、混淆方式后只能用远程协助帮他更改设置，这样做很多次后就希望换个男朋友

**请求**： 客户端每次启动后（或节点信息失效后）自动向远程服务器拉取最新的配置信息

**Comment by leungzw** [comment]
#中国好女友

膜拜⊙▽⊙

**Comment by qijiangh** [comment]
朝圣

**Comment by leungzw** [comment]
用批处理来启动ss。
先把远程服务器上的配置下载回来，然后再启动ss。

#中国好女友

膜拜⊙▽⊙

**Comment by ARwMq9b6** [comment]
@leungzw +1.

**Comment by Gonesave** [comment]
@leungzw 表示不知道怎么做批处理有教程吗/(ㄒoㄒ)/~~

**Comment by ChaoCheung** [comment]
@ARwMq9b6 分手吧！没有必要

**Comment by czmecho** [comment]
这需求。。。。

弄一个稳定的SS服务，至少也可以用三五个月吧。何必呢。

**Comment by Lolisky** [comment]
要是我就把config.json直接扔到同步盘里23333

**Comment by BROBIRD** [comment]
@Lolisky 好主意，不过我让我先吃完这碗狗粮再赞你
