### ISSUE TITLE
[安装问题]：安装不上

### ISSUE THREAD

**Issue by usami-mizugi** [breakwa11/shadowsocks-rss#239]
整个安装流程都做了一边，数据库段还是没有表，整个SS-R还是无法使用。能出一个详细一点的教程么？我接触linux不到一年。

**Comment by leungzw** [comment]
数据库可以在phpmyadmin里面手工导入

**Comment by usami-mizugi** [comment]
你好，非常感谢您的回复。现在我前端后端都部署好了，出现了以下问题，1.前端找回密码功能的那个邮箱不支持ismtp吗？1.前端注册的帐号，给的SS端口和密码连接不上。(少许帐号能正常使用)，请问问题出在哪儿？

2016年2月25日星期四，leungzw <notifications@github.com> 写道：

> 数据库可以在phpmyadmin里面手工导入
> On Feb 25, 2016 16:11, "usami-mizugi" <notifications@github.com
