### ISSUE TITLE
用ChnIPList 能否添加自定义网址？

### ISSUE THREAD

**Issue by haoever** [breakwa11/shadowsocks-rss#24]
在Firefox 上用ChnIPList 绝大多数时候都没问题，可这两天不知为何字幕组 http://www.zimuzu.tv/ 打不开了，停用ss便可以打开（原来好像启用时也是能打开的）。

请问能不能对chniplist 自定义白名单呢？谢谢！

**Comment by breakwa11** [comment]
这应该是DNS污染的问题（如果用全局方式能打得开的话），这个list害怕DNS污染的，目前还不支持白名单，以后会加上

**Comment by haoever** [comment]
刚试了试，全局模式也是一样的状况打不开。

**Comment by breakwa11** [comment]
不对呀，我全局能正常打开。。。

**Comment by haoever** [comment]
我在全局和pac下一样打不开，不用ss打开速度倒是很快。目前为止只发现这么一个网站是这种情况，不过这是个香港ip，其它香港ip的网站好像也没试过。下面是网站打不开时所显示内容。

“403 Forbidden

You don't have permission to access the URL on this server. Sorry for the inconvenience. 
Please report this message and include the following information to us. 
Thank you very much! 

URL: 	http://www.zimuzu.tv/user/login 
Server: 	b0601 
Date: 	2015/08/13 15:44:29 

Powered by Tengine/2.0.0”

**Comment by breakwa11** [comment]
这就是打开了，只是服务器那边可能屏蔽了你的HK IP

**Comment by haoever** [comment]
试了其它的HK IP，可以打开，看来是专门针对某个网站做了屏蔽啊。谢啦。。期待chnlplist 能够支持自定义规则。

**Comment by breakwa11** [comment]
不再添加功能支持
