### ISSUE TITLE
没有openwrt路由器上能用的客户端吗

### ISSUE THREAD

**Issue by hdstar2009** [breakwa11/shadowsocks-rss#240]
路由器对所有设备有效，更方便的说。

**Comment by ChaoCheung** [comment]
只是没有SSR的客户端，SS的客户端一样的可以用 @hdstar2009

**Comment by hdstar2009** [comment]
ss的客户端不能支持混淆等特性吧

2016-02-26 16:57 GMT+08:00 ChaoCheung <notifications@github.com>:

**Comment by nvono** [comment]
这里不是有个shadowsocks-libev支持openwrt，自己编译下看看能用不

**Comment by lersh** [comment]
@nvono  我编译了你shadowsocksR的分支的代码，但是安装时提示
[root@PandoraBox_0DFD:/tmp]#opkg install shadowsocksR-libev-spec_2.4.5-1_ramips_1004kc.ipk 
Unknown package 'shadowsocksR-libev-spec'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksR-libev-spec found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package shadowsocksR-libev-spec.

这是为什么啊?

**Comment by fsaimon** [comment]
op源里有现成的包啊，同时也有luci的包

发自我的 iPhone

**Comment by lersh** [comment]
@fsaimon op源里有shadowsocksR的包？？？？？？！！！！！

**Comment by fsaimon** [comment]
呃 只是ss的包 没有ssr的

**Comment by lersh** [comment]
解决了，说下怎么解决的
一是，在/etc/opkg.conf里加了以下几行
arch all 100
arch noarch 200
arch ralink 300
arch ramips_24kec 400


二是换了mt7620的SDK编译，就能装上了
之前因为我的路由器是newifi2，用的是mt7621的SDK编译，所以装不上

**Comment by bettermanbao** [comment]
你们libev版编译好，混淆和协议定义都能用吗？

**Comment by lersh** [comment]
@bettermanbao 可以用，我的json是这样的
{
    "server": "",
    "server_port": ,
    "local_address": "0.0.0.0",
    "local_port": 1080,
    "password": "",
    "timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "auth_simple",
    "obfs": "http_simple"
}

**Comment by bettermanbao** [comment]
你是在openwrt下运行的吗？我现在的情况是auth_开头的都不可以，只有verify_simple可以用。

**Comment by lersh** [comment]
@bettermanbao 我就是在openwrt下工作的啊
你是不是编译的不是shadowsocksR分支？或者用错了SDK？你的路由器的型号是什么？openwrt版本是什么？是不是缺少支持库？

**Comment by bettermanbao** [comment]
@lersh 我是ar71xx的平台，你有没有试过polarssl的版本？我现在怀疑是polarssl不兼容造成的。

**Comment by lersh** [comment]
@bettermanbao 没试过ar71xx的代码，主要是我没有这个架构的路由器，我只ramips的
我可以帮你试试看polarssl的

**Comment by lersh** [comment]
@bettermanbao polarssl的不行，装上了提示我can't load library 'libmbedtls.so.9'

**Comment by bettermanbao** [comment]
@lersh 联系到破娃酱了，确认是bug了。你的mt7620是little endian和x86相同，我的ar71xx是big endian的，所以出问题了。

**Comment by lersh** [comment]
原来是这样啊。。。。真是艰辛啊

**Comment by lersh** [comment]
@bettermanbao 那这是客户端的BUG咯？你要自己去修复 @nvono 的代码？

**Comment by bettermanbao** [comment]
@lersh 和 @nvono 的代码没关系，牛b加高效的破娃酱就刚刚已经修好了。

**Comment by lersh** [comment]
@bettermanbao  嗯嗯，我刚才看到了，原来 @nvono fork的@harveyhu2012 ，@harveyhu2012结果还是再fork 了 @breakwa11 的代码…………好长一串

**Comment by bettermanbao** [comment]
需要openwrt客户端的，可以看看我的repo，有惊喜哦。
https://github.com/bettermanbao/openwrt-shadowsocksR-libev-full

**Comment by lersh** [comment]
@hdstar2009 close掉这个issues吧
