### ISSUE TITLE
msss,mengsky.net是个什么鬼

### ISSUE THREAD

**Issue by loveyanbei** [breakwa11/shadowsocks-rss#247]
{
    "ipv6": "[::]",
    "local_address":"127.0.0.1",
    "local_port":1080,                                                                                                "port_password":{                                                                                             {                                                                                                                     "ipv6": "[::]",                                                                                                   "local_address":"127.0.0.1",                                                                                      "local_port":1080,                                                                                                "port_password":{                                                                                                     "21":"password1",                                                                                                 "301":"ssrtest"                                                                                               },                                                                                                                "timeout":300,                                                                                                    "method":"aes-256-cfb",                                                                                           "protocol": "auth_sha1",                                                                                          "protocol_param": "",                                                                                             "obfs":"http_simple",                                                                                             "obfs_param": "",                                                                                                 "redirect": "",                                                                                                   "dns_ipv6": false,                                                                                                "fast_open": true,                                                                                                "workers": 1                                                                                                  }                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 "ssr.json" 19L, 392C written                                                                                      root@vultr:~/shadowsocks# ls
asyncmgr.py  Config.py        debian       README.md   server_pool.py  shadowsocks      stop.sh        tests
CHANGES      CONTRIBUTING.md  LICENSE      README.rst  server.py       shadowsocks.sql  switchrule.py  utils
config.json  db_transfer.py   MANIFEST.in  run.sh      setup.py        ssr.json         tail.sh
root@vultr:~/shadowsocks# python setup.py install
running install
running bdist_egg
running egg_info
creating shadowsocks.egg-info
writing shadowsocks.egg-info/PKG-INFO
writing top-level names to shadowsocks.egg-info/top_level.txt
writing dependency_links to shadowsocks.egg-info/dependency_links.txt
writing entry points to shadowsocks.egg-info/entry_points.txt
writing manifest file 'shadowsocks.egg-info/SOURCES.txt'
reading manifest file 'shadowsocks.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'shadowsocks.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/local.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/tcprelay.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/encrypt.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/asyncdns.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/server.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/eventloop.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/shell.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/common.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/obfs.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/manager.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/encrypt_test.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/udprelay.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/daemon.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/__init__.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/lru_cache.py -> build/lib.linux-x86_64-2.7/shadowsocks
copying shadowsocks/ordereddict.py -> build/lib.linux-x86_64-2.7/shadowsocks
creating build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/ctypes_openssl.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/table.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/ctypes_libsodium.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/sodium.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/openssl.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/rc4_md5.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/__init__.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
copying shadowsocks/crypto/util.py -> build/lib.linux-x86_64-2.7/shadowsocks/crypto
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/local.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/tcprelay.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/encrypt.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/asyncdns.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/server.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/eventloop.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/shell.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/common.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/obfs.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/manager.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/encrypt_test.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/udprelay.py -> build/bdist.linux-x86_64/egg/shadowsocks
creating build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/crypto/ctypes_openssl.py -> build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/crypto/table.py -> build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/crypto/ctypes_libsodium.py -> build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/crypto/sodium.py -> build/bdist.linux-x86_64/egg/shadowsocks/cryptocopying build/lib.linux-x86_64-2.7/shadowsocks/crypto/openssl.py -> build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/crypto/rc4_md5.py -> build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/crypto/__init__.py -> build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/crypto/util.py -> build/bdist.linux-x86_64/egg/shadowsocks/crypto
copying build/lib.linux-x86_64-2.7/shadowsocks/daemon.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/__init__.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/lru_cache.py -> build/bdist.linux-x86_64/egg/shadowsocks
copying build/lib.linux-x86_64-2.7/shadowsocks/ordereddict.py -> build/bdist.linux-x86_64/egg/shadowsocks
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/local.py to local.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/tcprelay.py to tcprelay.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/encrypt.py to encrypt.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/asyncdns.py to asyncdns.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/server.py to server.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/eventloop.py to eventloop.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/shell.py to shell.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/common.py to common.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/obfs.py to obfs.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/manager.py to manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/encrypt_test.py to encrypt_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/udprelay.py to udprelay.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/crypto/ctypes_openssl.py to ctypes_openssl.pyc
byte-compiling build/bdist.linux-x86_64/egg/shadowsocks/crypto/table.py to table.pyc
{
"server":"108.61.162.17",
"server_port":"443",
"local_port":1080,
"local_address":"127.0.0.1",
"password":"lytfight!",
" ============================================================================
" Netrw Directory Listing                                        (netrw v153)
"   /root/shadowsocks/shadowsocks
"   Sorted by      name
"   Sort sequence: [\/]$,\<core\%(\.\d\+\)\=\>,\.h$,\.c$,\.cpp$,\~\=\*$,*,\.o$,\.obj$,\.info$,\.swp$,\.bak$,\~$
"   Quick Help: <F1>:help  -:go up dir  D:delete  R:rename  s:sort-by  x:special                                  " ==============================================================================                                  ../                                                                                                               ./                                                                                                                crypto/                                                                                                           obfsplugin/                                                                                                       local.py*                                                                                                         server.py*                                                                                                        __init__.py                                                                                                       asyncdns.py                                                                                                       common.py                                                                                                         daemon.py                                                                                                         encrypt.py                                                                                                        encrypt_test.py                                                                                                   eventloop.py                                                                                                      lru_cache.py                                                                                                      manager.py                                                                                                        obfs.py                                                                                                           ordereddict.py                                                                                                    run.sh                                                                                                            shell.py                                                                                                          stop.sh                                                                                                           tail.sh                                                                                                           tcprelay.py                                                                                                       udprelay.py                                                                                                       ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                                                 ~                                                                                       root@vultr:~/shadowsocks# python server.py -c ssr.json
loaded collections.OrderedDict
IPv6 support
Traceback (most recent call last):
  File "server.py", line 28, in <module>
    import db_transfer
  File "/root/shadowsocks/db_transfer.py", line 5, in <module>
    import cymysql
ImportError: No module named cymysql
root@vultr:~/shadowsocks# pip install cymysql
Downloading/unpacking cymysql
  Downloading cymysql-0.8.5.tar.gz (384kB): 384kB downloaded
  Running setup.py (path:/tmp/pip-build-3QNUey/cymysql/setup.py) egg_info for package cymysql

Installing collected packages: cymysql
  Running setup.py install for cymysql

Successfully installed cymysql
Cleaning up...
root@vultr:~/shadowsocks# python server.py -c ssr.json
loaded collections.OrderedDict
IPv6 support
INFO: loading config from ssr.json
2016-03-12 04:21:39 INFO     loading libcrypto from libcrypto.so.1.0.0
Shadowsocks 2.6.12
2016-03-12 04:23:46 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 175, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 94, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on 'mdss.mengsky.net' (110)")

2016-03-12 04:26:08 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 175, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 94, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on 'mdss.mengsky.net' (110)")

2016-03-12 04:28:30 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 175, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 94, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on 'mdss.mengsky.net' (110)")

**Comment by python12450** [comment]
你用了数据库版。。。。请把这个域名改成你的数据库服务器地址

**Comment by python12450** [comment]
还有你没有安装cymysql
