### ISSUE TITLE
ss manyuser 多用户自动暂停，是什么原因？256M内存 

### ISSUE THREAD

**Issue by leehost** [breakwa11/shadowsocks-rss#250]
screen -ls 
提示 screen is terminating
kill 后重新运行
screen -S ss	
python server.py
节点恢复正常
这是什么问题导致的？

**Comment by breakwa11** [comment]
我也不知道

**Comment by leehost** [comment]
谢谢回复，有些正常有些容易断，现在换sh后台正常
