### ISSUE TITLE
恕我愚钝小白...多用户的话我没看懂诶，有没有哪个大神解释下

### ISSUE THREAD

**Issue by SSLDY** [breakwa11/shadowsocks-rss#254]
原文：
---------------------------------------------------------------------------------
文件config.json复制一份到user-config.json，然后编辑：

"method":"aes-256-cfb",                   //修改成您要的加密方式的名称
"protocol": "auth_sha1_compatible",       //修改成您要的协议插件名称
"obfs": "tls1.0_session_auth_compatible", //修改成您要的混淆插件名称
------------------------------------------------------------------

config.json是复制到user目录？没找到这个目录...
还是..新建一个文件user-config.json？跟config.json放同一个目录？

**Comment by breakwa11** [comment]
同一目录，直接用cp命令不就好了吗
