### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by newgates** [breakwa11/shadowsocks-rss#255]
在访问某些网站的时候会出现这样的错误 比如[http://www.adidas.com/](url)

> Privoxy encountered an error while processing your request:

> Could not load template file no-server-data or one of its included components.

> Please contact your proxy administrator.

> If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

请问这是什么原因呢

**Comment by wenliyang** [comment]
设置成socks5代理，而不是http的，就没这种错误了

**Comment by breakwa11** [comment]
这个是遇到没有返回任何数据的情况，原因不确定，如果访问同一站总是出现相同的问题，即使刷新也一样，那有可能是BUG

**Comment by xbb123** [comment]
原因很多 首先尝试排除VPS到该网站的访问 其次尝试更换浏览器 最后尝试改成Privoxy 3.0.24

**Comment by breakwa11** [comment]
尝试更新到新版本试试看

**Comment by ycdm** [comment]
目前基本处于无法使用的状态，任何网络都会这样。我用回ss 了~

**Comment by Abclite** [comment]
我也是这个问题，感觉最新版很多BUG...

**Comment by breakwa11** [comment]
@Abclite 最新版本根本就不会500，除非没配置正确

**Comment by moqiguzhu** [comment]
ss version:3.4

Same error message printed when I visit websites which does not exist.
