### ISSUE TITLE
shadowsocks-libev 或者 shadowsocks-libev-spec 是否支持负载均衡?

### ISSUE THREAD

**Issue by GreatFireWall** [breakwa11/shadowsocks-rss#257]
另外 
https://github.com/breakwa11/shadowsocks-libev 
fork from
https://github.com/shadowsocks/shadowsocks-libev
跟原来的有什么不同?

**Comment by breakwa11** [comment]
不支持
区别就是SSR与原版

**Comment by GreatFireWall** [comment]
我想问一下, openwrt-shadowsocks 有 R 版么.

**Comment by breakwa11** [comment]
有，有人编译了，去G+社区找

**Comment by GreatFireWall** [comment]
谢谢
