### ISSUE TITLE
如果使用GFWlist，FireFox就无法加载PAC

### ISSUE THREAD

**Issue by BROBIRD** [breakwa11/shadowsocks-rss#260]
错误信息：
```
PAC Execution Error: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create []
PAC Execution Error: uncaught exception: out of memory []
PAC file failed to install from http://127.0.0.1:1080/pac?t=201604061314295770
```

**Comment by yfdyh000** [comment]
https://github.com/gfwlist/gfwlist/issues/141
https://bugzilla.mozilla.org/show_bug.cgi?id=1250776

**Comment by BROBIRD** [comment]
@breakwa11

**Comment by breakwa11** [comment]
不是SSR的锅，建议可用国内域名白名单代替

**Comment by BROBIRD** [comment]
@breakwa11 何以见得不是SSR的锅？如果不是，那么是firefox的锅吗？

**Comment by BROBIRD** [comment]
@yfdyh000 Bug页面已经一个多月没有动静了

**Comment by yfdyh000** [comment]
我当时测试过，确实始终重现了，但后来没找到原因所在。

**Comment by BROBIRD** [comment]
现在想想当时我提的动漫花园的issue #232 应该是这个原因，就是因为读不出来PAC，我说我的谷歌为什么开了SS却不走……

**Comment by breakwa11** [comment]
你的FF有安装管理代理的插件吗

**Comment by yfdyh000** [comment]
原生的Firefox就会这样。Ctrl+Shift+J打开浏览器控制台，选项-高级-网络-设置中可点“重新载入”按钮触发。是生成的PAC的问题（与传输方式无关），原因不明。

**Comment by BROBIRD** [comment]
@breakwa11 有一个Foxyproxy，但是禁用了

**Comment by breakwa11** [comment]
那你用那个插件来配置试试看，我用插件配置的方式一直没有遇到你说的问题

**Comment by BROBIRD** [comment]
@breakwa11 用插件确实是没问题了……要不暂时就这样吧……搞不清楚是哪一环出了问题

**Comment by breakwa11** [comment]
我测试了一下，裸的FF使用PAC功能时，基本就是个残废，其它模式倒是都好用，建议要么用插件，要么不要用PAC，即使使用系统代理配置，而系统代理配置是PAC时，都比直接配置使用PAC正常

**Comment by yfdyh000** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/439
