### ISSUE TITLE
ss-tunnel在使用混淆之后udp通讯经常被墙阻断

### ISSUE THREAD

**Issue by semglassie** [breakwa11/shadowsocks-rss#264]
在openwrt上使用bettermanbao编译的openwrt-shadowsocksR-libev-full，开启ss-tunnel使用混淆后不定时的udp通讯就被墙阻断，此时无法访问所有的境外dns服务器地址，也不能使用udp访问自己的vps，而不使用混淆协议反而不会被阻断，望能增加libev版支持的混淆形式，目前的两种貌似都容易被墙探测和阻断

**Comment by lersh** [comment]
我在我公司里也遇到了类似的问题，udp不定期被阻断，但是在家里电信线路是没问题，可能不是墙的问题。解决方案是用pdnsd或者dnscrypt-proxy，通过tcp解析dns，然后再把tcp的dns加入ss的白名单走混淆，就没有这问题了

**Comment by semglassie** [comment]
UDP包伪装成http或者TLS的应用是不是很古怪，一般正常情况下没有这样的应用，所以才容易被墙探测到吧，相反原协议的udp包特征就不明显

**Comment by breakwa11** [comment]
楼上你搞错了，不是伪装，是完全使用TCP来发送UDP包，这样根本不知道实质上走的是UDP，原协议的UDP人家才不管你什么特征，发现经常发送不是DNS的UDP并且是发向国外的包，很容易直接全给你拦了，现在UDP的拦截简单且暴力。唯一的解决方案是让libev支持UDP over TCP

之所以开启混淆同时还开UDP容易被阻断UDP，你想想哪个网站服务器会同时提供UDP连接的？这不是很少见吗。

另外还有一种较简单的方案，就是TCP与UDP不使用同一个SS服务器

**Comment by semglassie** [comment]
明白了，所以使用http混淆最好还是不要再使用ss-tunnel，但是libev版并没有udp over tcp功能，目前只能用pdnsd让dns解析采用tcp协议完成，希望作者有空更新下libev版的ssr，谢谢

**Comment by lersh** [comment]
@semglassie 我现在看下来用dnscrypt-proxy走opendns的tcp解析还是挺稳定的，所以libev上不是udp over TCP我已经不care了
opendns天生支持tcp解析，再把opendns的ip加入翻墙列表，那就更稳定了

**Comment by breakwa11** [comment]
dup #252
