### ISSUE TITLE
android 可以连接，mac连接不上  ERROR [Errno 111] Connection refused

### ISSUE THREAD

**Issue by KarlXing** [breakwa11/shadowsocks-rss#265]
请问android连接正常，mac就连接不上 查看一下日志发现问题是 ERROR    [Errno 111] Connection refused。该怎么解决？系统是Ubuntu14.04

**Comment by breakwa11** [comment]
检查防火墙和客户端配置

**Comment by yohn89** [comment]
遇到了同样的问题，手机上正常连接，Mac上提示ERROR [Errno 111] Connection refused
iptables里没有设置过规则
