### ISSUE TITLE
可以添加一个比特币捐赠链接吗？

### ISSUE THREAD

**Issue by testcpphello** [breakwa11/shadowsocks-rss#266]
十分感谢作者的贡献

**Comment by breakwa11** [comment]
不接受捐助

**Comment by BROBIRD** [comment]
然而……ZeroNet里面这是什么……@breakwa11 
![20160420191856](https://cloud.githubusercontent.com/assets/7692707/14672854/0842d5aa-072d-11e6-8c59-c4dac33953e7.png)

**Comment by breakwa11** [comment]
那个是ZeroNet的捐助

**Comment by BROBIRD** [comment]
@breakwa11 这个字符串代表的是是你的页面……

**Comment by breakwa11** [comment]
@BROBIRD  每个页面都有这个东西，不信你去看看

**Comment by BROBIRD** [comment]
@breakwa11 是啊，但是这是每个页面唯一的标识……

**Comment by emptyset12** [comment]
@BROBIRD 有意思吗

**Comment by BROBIRD** [comment]
@emptyset12 你想说什么
