### ISSUE TITLE
感觉SSR的路由规则是不是有点问题？

### ISSUE THREAD

**Issue by nonozone** [breakwa11/shadowsocks-rss#267]
我这个问题可能描述的不太恰当。

表现：最近发现我很多网站不手动输入https，就没法打开，比如translate.google.com,facebook.com,还有其他的一些非Google网站，只有手动添加了https之后，才可以打开。以前我一直以为是自己的Chrome浏览器升级了，有bug的原因。但是今天我访问自己公司网站（服务器JP节点），因为要测试一个东西，我直接开全局，发现连公司网站也无法打开了。

后来我关掉SSR，直接用SS，上述问题都没有了。实在不知道这个是什么原因。

**Comment by breakwa11** [comment]
你用的客户端版本以及版本号？

**Comment by nonozone** [comment]
W10, 64bit, SSR3.7.4

**Comment by hot36952** [comment]
对于服务器iptables的设置，我也有一些问题。
服务器安装好ssr后，客户端无法连接网络。
此时iptables -F 清除后，客户端可以连接网络。
然后给iptables开放ssr设置的端口，再把INPUT/OUTPUT修改为DROP，此时端口可以ping通
，但客户端无法连接网络。

**Comment by breakwa11** [comment]
新版本中还有这个问题吗？

**Comment by breakwa11** [comment]
No response
