### ISSUE TITLE
在 GitHub 上同步更新。

### ISSUE THREAD

**Issue by XhstormR** [breakwa11/shadowsocks-rss#268]
v3.8.0.1 在 BitTorrent Sync 更新了，但是 GitHub 上没有同步更新。

[仓库](https://github.com/breakwa11/shadowsocks-csharp/releases)里还是 2 月份的 v3.7.4.1，是打算以后都不发布在 GitHub 上了吗？

**Comment by laincat** [comment]
嗯？没有同步到 3.8 啊，我只同步到 3.7.6.2

**Comment by emacsenli** [comment]
install zeronet  from github and go to this link

http://127.0.0.1:43110/1GUwoyRUxHWkUik5o4BBKgjrpbeCMXFj9z/

2016-04-20 8:32 GMT+08:00 laincat <notifications@github.com>:

**Comment by yjd** [comment]
以后我就到zd去下了。

**Comment by XhstormR** [comment]
@yjd 不是第一渠道，不安全。

**Comment by xm4854** [comment]
这都更新到3.8.*了 仓库还是老的
