### ISSUE TITLE
有个不是很重要的小问题

### ISSUE THREAD

**Issue by yjd** [breakwa11/shadowsocks-rss#269]
环境：
Win2008R2 x64 
Python 2.7.11 x86 (x64装不上老出错)
git 最新便携版。

代码git便携版从https://github.com/breakwa11/shadowsocks.git取的。

Git\shadowsocks\shadowsocks 单用户版
![qq 20160420095030](https://cloud.githubusercontent.com/assets/6856740/14661080/67c9e478-06dd-11e6-95cd-c9ac4ac9ca65.png)

为了目录整洁，拷到其他地方运行正常。但是主目录的文件夹名字不能修改。
否则客户端连接老提示协议不对。测了好久才发现是这个问题。

今天用了最新3.8.0.1服务器统计更好了，不用每次都要拉窗体。
希望再优化个小地方--服务器列，每次显示前自动计算下最长的自动调整下列宽。
不然每次要看完整信息都要双击下（虽然关闭之前不用再调-_-!!）。
而且调整后，下次重新打开程序又要调整。
我这种几个服务器地址应该加这个代码不会影响效率。
如果有人非常多怕影响效率，可以设计成软件打开调整一次，关闭保持位置。
下次软件启动直接读配置。

纯建议希望考虑。

**Comment by breakwa11** [comment]
早期实现就是自适应列宽，但是会非常坑，同时更新效率低下，所以去掉了，另外就是考虑到默认服务器列比较窄减少截图意外（暴露地址什么的）

**Comment by yjd** [comment]
好吧，那就忽略第二个问题。

**Comment by breakwa11** [comment]
你前一个我没看太懂，但如果是python下的目录，那是真的不能改，目录名影响类的引用

**Comment by yjd** [comment]
就是把shadowsocks\shadowsocks 剪切到任意地方。运行python server.py 正常。
改名就出错不改名正常。

**Comment by breakwa11** [comment]
第二级的shadowsocks目录名是不能改的，名字被引用在源代码里了

**Comment by yjd** [comment]
@breakwa11 
不能程序启动读下目录名赋值到一个全局变量？python不会，不清楚。
如果代码量小下次更新可考虑改下。改动大就免了^_^。纯建议
