### ISSUE TITLE
ShadowsocksR C# 版本提示代理异常

### ISSUE THREAD

**Issue by xuefliang** [breakwa11/shadowsocks-rss#270]
代理异常截图如下：
![qq 20160420143931](https://cloud.githubusercontent.com/assets/3095597/14665551/8b3dbff0-0706-11e6-893f-21ac743ad10b.jpg)
该怎么解决？

**Comment by breakwa11** [comment]
偶然出现是正常现象，刷新就行了，具体原因已经在页面上写好了，除非是一直都这样

**Comment by xuefliang** [comment]
从中午开始一直是这样，刷新没用！

**Comment by breakwa11** [comment]
你把http改https再试试呢？

**Comment by breakwa11** [comment]
以及你用的版本是哪个

**Comment by xuefliang** [comment]
![qq 20160420162943](https://cloud.githubusercontent.com/assets/3095597/14668127/2c2b69f4-0715-11e6-97e6-07c7c59e2b96.jpg)这是使用htts的截图，我用的是3.8.0.1版本

**Comment by breakwa11** [comment]
检查你的节点配置及网络，以及使用多个版本对比

**Comment by xuefliang** [comment]
已经解决，是配置obfs混淆协议tls1.2错误导致的，多谢！
