### ISSUE TITLE
请问PC端的shadowsocksR是不是无法转发udp数据包？

### ISSUE THREAD

**Issue by ghost0627** [breakwa11/shadowsocks-rss#271]
我指的不是那个udp ove tcp。我发现在PC上的客户端似乎没法转发udp包

**Comment by breakwa11** [comment]
和你所在地区以及你用的服务器地址有关，有的地方出境UDP流量全部丢掉

**Comment by ghost0627** [comment]
您的意思是客户端本身是支持的？需要做什么特别设置么？还是填写完服务器信息后默认就支持？

**Comment by breakwa11** [comment]
我觉得你问得不清不楚，首先PC上并没有多少真需要代理UDP的程序，你到底是用的什么东西需要这功能？另外PC版本不是路由器版本，和路由的转发是两码事

**Comment by ghost0627** [comment]
我觉得我们把问题复杂化了，我的问题其实就1个：PC端的ShadowsocksR 3.7.4是否支持udp转发?

**Comment by breakwa11** [comment]
拜托我要搞明白你要的是哪一种转发，我还是不知道你要的是代理还是路由重定向转发，而帮助文档我写得**非常清楚**是支持UDP**代理**

**Comment by ghost0627** [comment]
了解了，谢谢

**Comment by breakwa11** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by bloodxia** [comment]
UDP代理不可用。服务器端是shadowsocks-libev版。客户端，我用sockscap做测试，无法使用。是不是UDP转发需要使用你的server端？

**Comment by bullying520** [comment]
楼主应该是想玩游戏的吧 用PC共享给主机 需要的是UDP转发 这点PC上是不支持的 所以可以装个虚拟机 系统装LEDE x64软路由 然后在软路由里面设置你的SS 然后在主机上设置网关为你的虚拟机ip就行了
参见https://www.psnine.com/topic/31184
