### ISSUE TITLE
3.7.4.1更新PAC文件出错，是不是该升级了？

### ISSUE THREAD

**Issue by hypogaea** [breakwa11/shadowsocks-rss#273]
我用的Windows 10，今天更新PAC文件弹了个错：
[![751a32402cb09e69.png](http://imgchr.com/images/751a32402cb09e69.png)](http://imgchr.com/image/ABQ)

本地SSR版本是3.7.4.1，刚看到有人说有新版本了，该怎么更新呢？ #268

**Comment by hypogaea** [comment]
另外我头一次学怎么用Markdown，能推荐个好的图床吗？[Pinterest](https://www.pinterest.com)做图床怎么样？

**Comment by BROBIRD** [comment]
用zeronet更新
