### ISSUE TITLE
SSR未来架构建议

### ISSUE THREAD

**Issue by oxyqdz2h** [breakwa11/shadowsocks-rss#274]
SSR未来架构建议

【服务端】
1、服务端集成SQLite，多用户验证不再需要另外安装MySQL。
2、字段大概为：ID、用户名、密码、ss端口、ss加密方式、ss密码、ss协议、ss协议参数、ss混淆、ss混淆参数、上行流量、下行流量、剩余流量、计费时间、余额、程序标题、程序界面、运营商广告等。

【传输】
客户端增加超级混淆功能：客户端在随机时间间隔，使用随机协议，随机端口，向随机IP，发送随机大小的，随机数据包。用于抗时序和增加包分析成本。
（一个客户端看不出效果，如果多了，效果非常好）

【客户端】
1、客户端由一个exe主程序和一个加密的配置文件组成。
2、exe主程序，由作者负责分发；加密的配置文件由SSR运营商负责分发。
3、加密的配置文件，是由服务器，使用用户密码加密，自动生成的。里面包含服务器IP，端口，协议，混淆，ss密码等内容。
4、用户不输入正确的密码，是无法解密配置文件的，从而极大的保护了服务器信息。
5、加密的配置文件，可以是二维码的形式，贴在网页上。
6、客户端界面混淆功能。客户端可以选择加载在线皮肤，使得看起来像个游戏界面或者其他软件，以防止某些安全软件的截图或者光学识别。
7、用户登录以后，使用解密出来的程序标题，并显示解密出来的程序界面和运营商广告，一方面加强运营效果，一方面可混淆界面。

【总结】
对于最终用户来说，根本不需要知道什么IP，端口，协议，混淆什么的，最终用户只需要：
1、双击exe
2、输入用户名
3、输入密码
即可。极大的保护了服务器安全。

良好的商业运作，能极大的提高产品的生命周期。期待将来能出现全套整合的系统，从SSR客户端，到前端用户系统网页，后端管理系统网页，到数据库，再到SSR服务端，一条龙。

**Comment by oxyqdz2h** [comment]
随机时间间隔，发送随机大小的，随机数据，用于抗时序。

**Comment by IK1010** [comment]
你知道为什么SS穿墙能力比VPN强吗？

**Comment by wyxls** [comment]
然而作者如果这么作死，迟早会出事的_(:з」∠)_

**Comment by BROBIRD** [comment]
这种软件还想着商业化，作死么……你太天真了

**Comment by antikan** [comment]
奸商想这么搞就自己动手嘛，反正开源的。

**Comment by python12450** [comment]
你自己慢慢研究去，这种东西不是作者负责的，而且你的随机端口啥的用V2RAY就可以实现了

**Comment by breakwa11** [comment]
@python12450 他说的随机端口和你说的并不一样，你说的SS一样可以做，他说的只是为了发垃圾数据

**Comment by oxyqdz2h** [comment]
开源不一定只在代码上，更应该体现在设计模式上。

1、提取SSR客户端的内核，做成控制台应用程序，与客户端界面独立。谁都可以做GUI，然后调用ShadowSocksR_Core.exe -各种参数。这样可是界面更加安全，也可分担作者的工作量。作者只需要保证ShadowSocksR_Core.exe的哈希签名即可，ShadowSocksR_GUI.exe由运营商负责。

2、更加开放的自定义混淆功能。虽然是开源的，但是混淆和协议自己写还是有点复杂，更何况，没必要重复开发别人已经做过的东西。希望可以自己指定一个xml文件，定义混淆协议，而不是重新写代码。比如：
<Byte5>
    HelloWorld
    <Byte10>
        <TrueData />
    </Byte10>
</Byte5>

**Comment by yfdyh000** [comment]
@oxyqdz2h 然后作者就需要保证所有参数和功能的开发设计，安全性、稳定性和性能，变成设计一个内部专用的通信协议了。

**Comment by oxyqdz2h** [comment]
比如：
【Byte1】
HelloWorld
【RandomNumber /】
【Byte10】
【TrueData /】
【/Byte10】
【/Byte1】

**Comment by impig33** [comment]
酱妹已经放出源码了，不难的话自己撸吧

**Comment by Hansoncoder** [comment]
你们有iOS客户端的源码么，我想找一份看看。
