### ISSUE TITLE
最近一个星期的问题

### ISSUE THREAD

**Issue by nemo5175747** [breakwa11/shadowsocks-rss#275]
我用这个已经一年多快2年了，一直很好。突然这几天win的3.7.4.1不工作了。chrome+SwitchyOmega。配置没变过一只用的好好的。在公司不行，拿回家接进家里的网络也不行。这里不能贴图我就描述下，server statistic表现为从avg speed开始后面的项目里面除了upload，和empty response有数值，其他都是0.
奇怪的事情1，同样网络里面我家我的mac上运行的这个，同样配置，就运行的很好。
奇怪的事情2，同样的配置，我找了2个朋友（不同的网络环境）试，完全相同的配置直接放过去运行，一个一切正常，一个跟我一样。
我尝试过改server port，也尝试过改加密方法。都无效。(ps: 我自己有vps)
就是最近1个多星期的事，请问有其他人碰到么？
谢谢！

**Comment by breakwa11** [comment]
检查log

**Comment by nemo5175747** [comment]
相关时段的log就是这个：

[2016-04-25 11:06:48] ShadowsocksR started
[2016-04-25 11:07:04] [Error]connect to update server error
[2016-04-25 12:11:11] ShadowsocksR started
[2016-04-25 12:11:27] [Error]connect to update server error
[2016-04-25 12:14:18] ShadowsocksR started
[2016-04-25 12:14:31] [Error]connect to update server error
[2016-04-25 12:17:59] ShadowsocksR started
[2016-04-25 12:20:27] ShadowsocksR started
[2016-04-25 12:20:33] ShadowsocksR started
[2016-04-25 12:20:45] [Error]connect to update server error
[2016-04-25 18:12:58] ShadowsocksR started
[2016-04-25 18:13:07] [Error]connect to update server error
[2016-04-25 18:13:44] ShadowsocksR started
[2016-04-25 19:29:32] ShadowsocksR started
[2016-04-25 19:29:42] [Error]connect to update server error
[2016-04-25 19:33:22] ShadowsocksR started
[2016-04-25 19:33:33] [Error]connect to update server error

**Comment by oxyqdz2h** [comment]
是SwitchyOmega的问题，清空SwitchyOmega的设置，重新建，尤其要注意SwitchyOmega里面的PAC和rule list是否设置不当。当SwitchyOmega条目过多的时候，就会卡住，或者出错。

**Comment by nemo5175747** [comment]
谢谢楼上。
我还做过相关尝试：1，关闭chrome，然后enable system proxy，然后放到global模式，然后检查IE 的connection已经被成功的改成需要的设置了。然后用IE访问，盯着ss 的statistic。一样的结果。
2，我还有另外一个app，是直接在app里面设置代理的，直接代理到127.0.0.1和我设置的端口。这个app也是这样用ss代理出去多年了。尝试让他run，也是一样的结果。
所以我判断问题还是在我的电脑本身上，网络环境上。我还能做什么么？

**Comment by nemo5175747** [comment]
![capture](https://cloud.githubusercontent.com/assets/18659424/14805632/306b3578-0ba0-11e6-8366-be490c12e3ee.JPG)

**Comment by wenliyang** [comment]
服务端是部署的ssR的么，不是话换ssR的，并且启用ssR的混淆插件，而不只是修改ss的加密协议

**Comment by nemo5175747** [comment]
谢谢楼上。服务器确实部署的是SS，不是SSR。我找下SSR试试。但是在我试之前我想说，我client也用ss 3.0试过了。仍然是只有发没有收。
![capture](https://cloud.githubusercontent.com/assets/18659424/14808018/6339690c-0bb4-11e6-91bb-d75aaab7602c.JPG)

**Comment by nemo5175747** [comment]
@wenliyang 服务器重新部署SSR 加混淆协议。现在一切都ok了，看到了熟悉的绿色。谢谢！
![capture](https://cloud.githubusercontent.com/assets/18659424/14808616/600f2262-0bb9-11e6-917e-1ef174481536.JPG)

**Comment by nemo5175747** [comment]
@breakwa11 @wenliyang 若若的问一句，SSR客户端有for mac版本的么？我现在在公司windows是好了，很担心回到家，家里的mac用不了了。

**Comment by breakwa11** [comment]
有SSR for GoAgentX on Mac

**Comment by breakwa11** [comment]
看了一下你提供的信息，貌似是典型的被定点拦截，你可以提供你公司所在地址及网络服务商吗？（可以的话用twitter私信，或加密邮件，或bitmessage）

**Comment by antikan** [comment]
有的网管软件已经能拦截SS了（ssr还没试)。

**Comment by nemo5175747** [comment]
所以更新不能停呀不能停

**Comment by daniuer** [comment]
我可能发现这个问题的解决方法了，因为我的电脑上安装有Firefox和chrome。我用YouTube的4K视频测试节点速度的时候发现用同样的SSR客户端同样的节点和SSR配置，SSR系统代理为PAC模式，选择的PAC是绕过大陆常见IP。用Firefox可以流畅播放4K视频，Firefox安装的代理软件是FoxyProxy。用chrome播放任何视频都会卡不说，连访问普通的Google搜索和Twitter都常常断流打不开。我就怀疑可能是SwitchyOmega软件导致的不兼容，SwitchyOmega代理规则里设置为Shadowsocks自动切换，规则列表是gfwlist和我添加的一些网站。我发现只要启用了SwitchyOmega插件，不管是走直连模式还是Shadowsocks自动切换模式都会导致需要翻墙的软件断流，禁用掉SwitchyOmega后再播放4K视频就非常流畅了。不知道是从SSR的那个版本开始跟SwitchyOmega出现这个兼容问题的，chrome是我的主力浏览器，我是奇怪为什么SSR越更新越慢，大概是这个原因引起的，错怪了SSR。

**Comment by breakwa11** [comment]
@daniuer 你这个问题值得单独发一个issue来跟踪，最好多提供点那个插件的信息，和操作系统信息

**Comment by daniuer** [comment]
@breakwa11 我的系统是WIN7 X64，chrome版本是55.0.2883.87，Proxy SwitchyOmega插件版本是最新的2.3.21，这是Proxy SwitchyOmega项目地址https://github.com/FelisCatus/SwitchyOmega。发现用路由器版SSR翻墙如果开启了Proxy SwitchyOmega的代理模式会导致所有需要翻墙的网站无法打开，非墙网站不受影响。开启Proxy SwitchyOmega的直连模式被墙网站会加载不全。停用Proxy SwitchyOmega后不管SSR PC客户端或者开启路由器SSR翻墙全部正常了。SSR PC端已经集成了Proxy SwitchyOmega类似功能，停用不受影响。

**Comment by breakwa11** [comment]
@daniuer 我测试一下，有可能是路由的版本被混淆欺骗了

**Comment by daniuer** [comment]
@breakwa11 谢谢破娃大神，停用这个插件后一切正常，等于问题解决了。

**Comment by nemo5175747** [comment]
我现在就用chrome和switchyomega，mac上用ShadowsocksX-NG。都用白名单。SSR用auth_sha1和tls1.2_ticket_auth。各种网络环境都顺滑如丝。
SSR还是很靠谱的，至少对于我。

**Comment by daniuer** [comment]
看这个链接反馈的问题，不过我是WIN7http://hktkdy.com/2016/05/30/201605/shadowsocksr-switchomega/

**Comment by daniuer** [comment]
@breakwa11 抱歉我最近没上来这里回答，我发现把混淆关闭并且把服务器负载均衡均全部关闭再打开后，这个故障神奇的消失了，用的最新的4.1.0客户端。系统设置是全局，代理规则是绕过局域网和大陆，PAC是GFWlist.
