### ISSUE TITLE
升级提示错误,升级成功了吗?

### ISSUE THREAD

**Issue by 340681** [breakwa11/shadowsocks-rss#277]
-bash-4.1# cd shadowsocks
-bash-4.1# git pull
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 15 (delta 10), reused 10 (delta 10), pack-reused 2
Unpacking objects: 100% (15/15), done.
From https://github.com/breakwa11/shadowsocks
   962a05f..9f4f42e  manyuser   -> origin/manyuser
Updating 962a05f..9f4f42e
error: Your local changes to 'config.json' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.
-bash-4.1#

**Comment by breakwa11** [comment]
把config.json改为user-config.json，再pull，以后要改配置就直接改user-config.json即可

**Comment by Abclite** [comment]
我也是这个问题，就是重装都不行......
把config.json改为user-config.json，再pull  是不行的。。。

**Comment by breakwa11** [comment]
@ Abclite 你直接编辑config.json才会导致这个问题

**Comment by Abclite** [comment]
我直接编辑config.json就显示正常了。。。诡异，如果不编辑config.json，连SSR都失效

**Comment by breakwa11** [comment]
@Abclite 如果有user-config.json，就读user-config.json，如果没有就读config.json，除非你直接指定了文件，用user-config.json就是避免你更新的时候文件冲突，但你非要这样写那我就没办法了

**Comment by Abclite** [comment]
@breakwa11 我是经过测试了才反馈的，今天想把SSR服务端升级，然后试着git pull就出现上面提示...
如果我不执行cp config.json user-config.json的话，那么以后git pull后，是否config.json就清空了？

**Comment by breakwa11** [comment]
不是cp，要mv，如果已经cp那直接把config.json删了
