### ISSUE TITLE
win10用ssr之后每次重启电脑都要执行netsh winsock reset之后才能正常用

### ISSUE THREAD

**Issue by magiczst** [breakwa11/shadowsocks-rss#279]
运行完shadowsocksSSR关机重启电脑下面的无线图标会消失，谷歌内核的浏览器也打不开必须管理员运行cmd之后执行netsh winsock reset这个之后重启电脑之后才可以正常使用，有什么办法解决么。

**Comment by antikan** [comment]
我是win10 X64，一直没问题。

**Comment by breakwa11** [comment]
你安装了迅雷？迅雷服务开机启动？我不确定还有没有别的服务会修改

**Comment by breakwa11** [comment]
软件本身除了会修改IE的代理设置，以及如果你开启软件自启动时，会修改相应项的注册表外，没有其它地方对系统有修改

**Comment by magiczst** [comment]
安装了迅雷但是没有选择开启开机启动

**Comment by breakwa11** [comment]
我说的是迅雷服务，默认一定是开机启动，不管你迅雷本身是不是开机启动，这玩意会有干扰

**Comment by yjd** [comment]
推荐迅雷kanx绿化版
