### ISSUE TITLE
对GPL协议的违反

### ISSUE THREAD

**Issue by starrify** [breakwa11/shadowsocks-rss#28]
### 问题描述

本软件(指这一repo中的`ShadowsocksR`, 下同)目前并不开源, 作者对此的说明为:
> 本版本因部分使用与原版不兼容的协议，以及很多的实验性功能，为避免使用的人太多导致将来修改协议时需要考虑兼容性问题，暂以非开源形式以限制使用广度。

据信, 本软件是在[`shadowsocks-windows`](https://github.com/shadowsocks/shadowsocks-windows)的基础上修改得到. 而[`shadowsocks-windows`本身是在GPLv3协议下发布的](https://github.com/shadowsocks/shadowsocks-windows/blob/master/LICENSE.txt)

如果本软件的确使用了`shadowsocks-windows`的源代码, 那么尽管作者已做出相应的说明, 并给出"今后将会开源"的承诺(由作者"**暂**以非开源形式"一句猜测得到), 本软件仍然已经形成了对GPL协议的违反.

### 可能的解决方案

- 作者可以通过声明或证明本软件并未使用`shadowsocks-windows`或其他可能造成协议问题的自由软件的源代码来解决这个问题
- 作者可以通过修改本软件(譬如使用相应的自由软件协议进行发布)来避免**今后**对自由软件协议的继续违反(若**之前**已经有过对自由软件协议的违反, 建议咨询相应的专业人士并联系相关软件作者)

-- 

以上是客观部分, 这里加一点主观的意见. 私以为"作者的本意是好的", "这一份闭源工具给很多人提供了帮助", 与"这一份闭源工具可能是违反了自由软件协议的"是几件不同的事情. 这里的issue是针对其中"这一份闭源工具可能是违反了自由软件协议的"这件事情而提出的.

**Comment by librehat** [comment]
以这种理由不开放源代码是不充分的，作者要么**立即**按照GPLv3协议放出源代码，要么必须**立即**停止发布该软件。

**Comment by polong** [comment]
我才知道，原来这个的作者这么没品，算了，不用了，回归原作者的东西。

**Comment by xlz** [comment]
https://help.github.com/articles/dmca-takedown-policy/

**Comment by yfdyh000** [comment]
根据 https://github.com/breakwa11/shadowsocks-rss ，作者更新了说明，并且在 https://github.com/breakwa11/shadowsocks-csharp 开源了（并合方式），不过也声明停止更新了……

**Comment by heeroyuyj** [comment]
真是可惜了, 我其实理解作者的大概意思, 也确实作者自己对于功能的实现都在加加减减, 来回反复改, 我觉得确实过早开源, 会出现很混乱的局面, 当然, 楼上诸位说的 GPL 协议也在理

怎么说呢, 停更了, 一种美玉蒙尘的感觉... 看到作者写的最后的说明, 的确, 最早和 Shadowsocks 作者提出希望在电脑上实现 UDP, 对方的确也说没意义, 要了干嘛, 以及实现困难, 种种... 要怪只能怪自己, 没有编程的本事, 好不容易盼到了 ShadowsocksR, 实现了, 现在, 哎...

**Comment by dangelization** [comment]
说两句吧。

我觉得就像SSR作者所说，他是学经济的，对于问题的思考理解方式也凭依于此。

但是有一个重要的问题是作者可能忽视的：
像SS，GOAgent这类开源免费软件，他们的发展是依托于“众筹”，而非“市场竞争”
你想要增加SS的功能，可以pull request，作者不同意，可以自己fork。
同理而言，别人也可以对你的project做相同的事。
说到底，这是一个开发者社区的事，开发者们愿意做贡献，才能促成类似开源免费软件的发展。
如果没有SS的开源，那SSR又从何而来？在吐槽SS作者不接受自己意见的同时，是否想过这个问题？

市场竞争的游戏规则适用于收费，闭源的软件，因为他是消费者主导的，而非开发者理想、兴趣主导的。
然而对于用户而言，一个开放，免费的SS，更加符合需求。毕竟对于FQ而言，开放意味着能够很快的变化，意味着可以有各种变异版本，意味着更难以关进笼子。shadowvpn不就是从别的vpn的基础上变异出来的么

理想可以竞争，免费的发展却需要分享。

**Comment by LinusSong** [comment]
GPLv3本身就是合同，使用其代码就必须同意，这就是规则，不管你怎么样，竞争还是如何，都必须先同意，否则就不允许使用

**Comment by cfcboy** [comment]
我不管上面那些大神出于什么目的要求作者开源。最起码我们这些小白用着作者的软件很舒服。功能也够实用。不管作者开不开源，最起码有作者来维护这个项目。而且还是免费的。如果作者以后不再更新，我就不知道还有谁以后会来维持这个项目，来方便我们这些使用者。我不懂代码。不管啥隐私，这个是我的事情。如果不相信作者，你可以不用。。你们以这种方式来叫作者开源。。我们这些使用应该咋办？？？

**Comment by breakwa11** [comment]
@cfcboy 这是合理要求，我只是一直在奇怪作者为什么不直接邮件我，而宁愿帖子直接发牢骚。停更还有一个原因是发现SS协议上的漏洞，但我感觉我的蹩脚修改没啥用，他还是会有他的修改方式解决的，所以考虑后来的版本一不使用ss协议，二不使用他的客户端一行代码，全部自己写（如果我还是不死心要写的话），但至少年内应该不会有版本了

**Comment by PINK-FL0YD** [comment]
请仔细阅读GPL协议后再表达你的意见，如果还能理直气壮的说你的做法正确，真是无药可救！墙又高了一层！

**Comment by zodiacg** [comment]
大致看了下，SSR的作者大概不懂“开源”到底是什么意思，也不懂“开源”的运作方式。
SS闭源，SSR作为竞争产品出现，互相用功能对抗，互相促进，这是市场竞争。但是开源不是市场竞争。

>我只是一直在奇怪作者为什么不直接邮件我，而宁愿帖子直接发牢骚。
这句话是非常可笑的。SS开源（而且是GPL协议明确指出使用源代码需要保持GPL协议开放源代码），就等于明确表示你如果对功能不满意可以自己添加，发PR如果作者不接受可以fork，即使fork了依然公开源代码，以后可以在别的新功能上互通有无。这是一个开源的良性健康的发展。而SS的代码向SSR单向流动，反过来却没有任何贡献。同样是SS客户端，go实现就是健康的，qt也是健康的，SSR就是不健康的。

io.js就是因为不满node.js在版本更新上的保守而产生的fork。数不胜数的开源项目都是user因为这样的原因逐渐变成contributor的。clowwindy也很明确的指出希望能看到contributor。而作者你呢？

**Comment by zhangchunlin** [comment]
你怪作者
"我只是一直在奇怪作者为什么不直接邮件我，而宁愿帖子直接发牢骚"
但
"停更还有一个原因是发现SS协议上的漏洞，但我感觉我的蹩脚修改没啥用，他还是会有他的修改方式解决的"
但你为什么不把你的"蹩脚修改"提pr给作者做参考和建议呢?
这个在开源世界,特别在github不是很自然的做法吗?

**Comment by aflyhorse** [comment]
@cfcboy GPL协议讲究的是一种分享精神，你可以用我的代码，但必须标注来源，感谢，并同样把这代码公开给别人看。你想想你花了一个月卸了篇长文，结果被人抄袭走，作者名字改掉，再被加一句“本文版权属XX所有，未经允许不得转载”的感受吧。

**Comment by redfrog999** [comment]
唉，虽然作者不再更新了，不过作为普通用户，你增加的前置代理功能对我非常非常有用，解决了我一个大难题，在此感谢你的努力和付出。非常希望看到作者能另起炉灶，把对原程序的不满意变成改进甚至破坏性创新的驱动力，创制出更好的作品。Thanks,again。

**Comment by ruleroller** [comment]
其实要竞争，可以啊，大家都开源，你搞了个功能，我“抄抄”并改进，你看我的功能挺好，你也“抄抄”并再进行了改进，如此循环，达到开源的大和谐。当然，主线不理分支不合并功能，最后被分支干掉的事情也有发生的。可SSR只单向从SS那里“抄”，而不回馈代码回SS，这能叫竞争？又说希望市场逼迫SS作者加上某些功能，可他还是得重复造轮子了啊。至于说将来会开源，但这期间逼原作者添加功能，都不算时间的吗？

SSR的作者请三思，不可本末倒置，毕竟，有了开源的Shadowsocks，才有ShadowsocksR，遵守协议是大前提。

**Comment by soulrenger** [comment]
是单纯的抄？在我看来增加了很多主线不具有的功能，到头来还被人扣帽子，想起了psp破解事件，伸手党成功劣币驱逐良币 发自网易邮箱大师 在2015年08月19日 17:51 ，ruleroller写道： 其实要竞争，可以啊，大家都开源，你搞了个功能，我“抄抄”并改进，你看我的功能挺好，你也“抄抄”并再进行了改进，如此循环，达到开源的大和谐。当然，主线不理分支不合并功能，最后被分支干掉的事情也有发生的。可SSR只单向从SS那里“抄”，而不回馈代码回SS，这能叫竞争？又说希望市场逼迫SS作者加上某些功能，可他还是得重复造轮子了啊。至于说将来会开源，但这期间逼原作者添加功能，都不算时间的吗？ SSR的作者请三思，不可本末倒置，毕竟，有了开源的Shadowsocks，才有ShadowsocksR，遵守协议是大前提。 — Reply to this email directly or view it on GitHub.

**Comment by ruleroller** [comment]
@soulrenger 真没看懂你的回复，到底是支持SSR作者还是SS的作者，又是在说谁是“伸手党”。

“是单纯的抄？在我看来增加了很多主线不具有的功能，到头来还被人扣帽子”，好像是支持SSR的作者的做法，是啊，增加了主线不具有的功能，但他不开源啊，主线咋轻松合并啊？扣了啥帽子，说他不开源，也算是扣帽子？他之前是没开源啊，这是事实啊。

“想起了psp破解事件，伸手党成功劣币驱逐良币”，听着却像是在责骂SSR的作者是个“伸手党”，如果顺着你前面支持SSR作者的思路理解，又可以理解是在说那些要求SSR作者开源事其不继续开发的人是“伸手党”。

╮(╯▽╰)╭

**Comment by soulrenger** [comment]
回复你的，支持ssr作者，支持程序媛 发自网易邮箱大师 在2015年08月19日 18:39 ，ruleroller写道： @soulrenger 真没看懂你的回复，到底是支持SSR作者还是SS的作者，又是在说谁是“伸手党”。 “是单纯的抄？在我看来增加了很多主线不具有的功能，到头来还被人扣帽子”，好像是支持SSR的作者的做法，是啊，增加了主线不具有的功能，但他不开源啊，主线咋轻松合并啊？扣了啥帽子，说他不开源，也算是扣帽子？他之前是没开源啊，这是事实啊。 “想起了psp破解事件，伸手党成功劣币驱逐良币”，听着却像是在责骂SSR的作者是个“伸手党”，如果顺着你前面支持SSR作者的思路理解，又可以理解是在说那些要求SSR作者开源事其不继续开发的人是“伸手党”。 ╮(╯▽╰)╭ — Reply to this email directly or view it on GitHub.

**Comment by soulrenger** [comment]
如果你非要说骂的话，那我在骂你这类人，200kb的客户端，核心加密代理功能用c#语言实现出来需要几天？原作者只实现了win端的基本功能，ssr作者服务端和客户端都进行了改造，当然改造后的服务端还被原作者骂了实现的不好； 从你前面描述ss的作者的时间就是时间，ssr的作者的时间就不是时间？请求原作者增加udp功能支持，到你这里变成了“逼迫”，用词水平，移花接木堪称一绝。 是不是开源了马上又能多卖几个高级游戏线路？这么急着逼迫作者开源 发自网易邮箱大师 在2015年08月19日 18:39 ，ruleroller写道： @soulrenger 真没看懂你的回复，到底是支持SSR作者还是SS的作者，又是在说谁是“伸手党”。 “是单纯的抄？在我看来增加了很多主线不具有的功能，到头来还被人扣帽子”，好像是支持SSR的作者的做法，是啊，增加了主线不具有的功能，但他不开源啊，主线咋轻松合并啊？扣了啥帽子，说他不开源，也算是扣帽子？他之前是没开源啊，这是事实啊。 “想起了psp破解事件，伸手党成功劣币驱逐良币”，听着却像是在责骂SSR的作者是个“伸手党”，如果顺着你前面支持SSR作者的思路理解，又可以理解是在说那些要求SSR作者开源事其不继续开发的人是“伸手党”。 ╮(╯▽╰)╭ — Reply to this email directly or view it on GitHub.

**Comment by ruleroller** [comment]
@soulrenger 

我做不到字斟句酌，凭印象用了“逼迫”二字来转述了ssr作者的话，那还是请你看看ssr的作者自己的原话进行理解吧：“进而通过市场压力迫使作者把这个功能做出来”。（你这么厉害，应该早就知道了吧）

其它都是什么鬼，你骂我的以及你自己意淫出来的东西，我统统进行反弹，嘿嘿。

现在SSR作者开源了其项目，我很开心并送上迟来的赞赏，尽管他开源得晚了一些。

聊天是建立在相互尊重的基础上的，你如此激动和不尊重他人，且思路不清，语言表达能力也欠奉，我就不和你继续说下去了，你开心就好了。

**Comment by kcschan** [comment]
"另外，如果你发现某个需求是很有必要的，但和作者说了这个需求但作者不做，和你说“NO”，怎么办？正如三个月前我就和作者说过UDP功能很有用，但作者就说PC上用UDP不如路由器上做。结果呢，那就自己做一个，把功能实现出来，把其它人的需求也引发出来，进而通过市场压力迫使作者把这个功能做出来就行了。"

“说过的开源承诺一定会兑现”

作者的义务是遵守GPLv3许可，而非承诺开源。
简单得说就是发布软件的时候至少提供源代码形式，至于编译好的二进制却非必须。
而“承诺开源”则是先发布二进制，且许诺未来的某一时刻提供源代码

两者的区别应该是非常明显的

GPL是一种比开源协议限制更多(以强迫任何衍生作品开源)的许可协议

所以目前来看，作者不再侵犯@clowwindy 的著作权
本issue应该说已经解决了

**Comment by kcschan** [comment]
@breakwa11 

"我只是一直在奇怪作者为什么不直接邮件我，而宁愿帖子直接发牢骚"

因为原作者可以直接丢一份DMCA到这个代码库，然后全没了。
所以直接发帖子无可指责

**Comment by asdqwe876** [comment]
人云亦云，没有自己主见，又丢脸了，丢到国外了。

**Comment by cfcboy** [comment]
@breakwa11
CN人太多了。什么思想都有。各种武林第一!真是林子大了，什么鸟都有。
虽然你不更新了，也发后布了Final版。但是就目前来说我也够用了。
很遗憾你放弃了这个项目。如果有如果，你再开发类似的新作品，希望我还可以用到。。
大家说了那么多错与对。对于我来说，能用，好用，即是对的。。最起码你创新了。

**Comment by soulrenger** [comment]
@kcschan 对这个代码库来说，DCMA也没有意义，作者根本就没放源码，只有个说明文件，你dcma有什么用呢？
@ruleroller 使得一手好断章取义，最后的结局是，ssr作者不更了，和psp掐架事件一样的结局；
    从作者的角度来说，实现这个ssr确实使原作者放出了新版的服务端api，win客户端的功能添加，从这点来看，ssr的目的已经达到，然后就没有然后了

**Comment by sorz** [comment]
还是把这个当成一个单纯的版权问题就好，就事论事。
之前违反 GPL 这是客观事实，现在已经开源了，问题也解决，这个 issue 可以 close 了。
没必要也不应该在这里把这个话题扩大化，甚至延伸到作者人品、国人素质上… 这与本 issue 无关。

SSR 作者不想继续贡献代码也是他的自由，开源项目，都是无偿劳动，没人能要求什么。

**Comment by xuanhuan** [comment]
> 我不管上面那些大神出于什么目的要求作者开源。最起码我们这些小白用着作者的软件很舒服。功能也够实用。不管作者开不开源，最起码有作者来维护这个项目。而且还是免费的。如果作者以后不再更新，我就不知道还有谁以后会来维持这个项目，来方便我们这些使用者。我不懂代码。不管啥隐私，这个是我的事情。如果不相信作者，你可以不用。。你们以这种方式来叫作者开源。。我们这些使用应该咋办？？？

第一，这个软件不仅只有你一个用户，其次，作者违反了GPL。

**Comment by xuanhuan** [comment]
无论如何，SSR都是在SS基础上进行的修改，这是事实，应该开源的，不开源就是违反 GPL 。

**Comment by xcjiang** [comment]
不遵守协议这就是错，不要扯不相干的混淆试听。
跟你辛不辛苦没有一丝关系。
跟你牛不牛逼没有一丝关系。
跟你做了多少贡献没有一丝关系。
跟有多少用户对你翘首以盼也没有一丝关系。
如果大大方方的认个错，没有人会苛求你，何苦在这里狡辩？
