### ISSUE TITLE
ShadowsocksR-win-dotnet4.0-3.8.0.3在哪儿下载？？？

### ISSUE THREAD

**Issue by jeromeli002** [breakwa11/shadowsocks-rss#281]
ShadowsocksR-win-dotnet4.0-3.8.0.3在哪儿下载？？？提示更新可是没地方更新捏

**Comment by thelastfantasy** [comment]
同问，下载地址居然是 127.0.0.1:43110/shadowsocksr.bit/?ShadowsocksR-win-dotnet4.0-3.8.0.3.7z
还有btsync里最新的也是ShadowsocksR-win-3.8.0.1.7z

**Comment by yfdyh000** [comment]
需要用 https://github.com/HelloZeroNet/ZeroBundle/releases/
而且这次解压密码需要答题。

**Comment by jackxiao17** [comment]
用zeronet查看

**Comment by zhoufenfens** [comment]
解压缩密码给的题目也太难了

**Comment by jiashooter** [comment]
同意 对于不看B站的人 根本就不知道是什么 呵呵

2016年5月6日星期五，zhou <notifications@github.com> 写道：
