### ISSUE TITLE
windwos 安装报错

### ISSUE THREAD

**Issue by Sumzibuyu** [breakwa11/shadowsocks-rss#282]
我按照wiki里的资料安装python和openssl，手动下载了安装包 运行报错 无法使用
C:\shadowsocks-master\shadowsocks>python server.py
Traceback (most recent call last):
  File "server.py", line 32, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, \
  File "C:\shadowsocks-master\shadowsocks\../shadowsocks\asyncdns.py", line 93,
in <module>
    IPV6_CONNECTION_SUPPORT = detect_ipv6_supprot()
  File "C:\shadowsocks-master\shadowsocks\../shadowsocks\asyncdns.py", line 83,
in detect_ipv6_supprot
    s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
  File "C:\Python27\lib\socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 10047]

**Comment by breakwa11** [comment]
XP？

**Comment by Sumzibuyu** [comment]
2003

**Comment by breakwa11** [comment]
目前并没有考虑过windows运行服务端，另外你用代码确认是最新的吗？

**Comment by antikan** [comment]
3.8.0.2被win8自带杀毒隔离，以前版本从没遇到过。

**Comment by breakwa11** [comment]
@antikan 但我可是遇到得多了，诺顿，金山，瑞星，Macfee都遇到过误报毒了

**Comment by antikan** [comment]
另外，优先相同节点连接同一地址的选项选上后，重开后没保存。

**Comment by breakwa11** [comment]
@antikan 感谢提醒，现在才发现

**Comment by Sumzibuyu** [comment]
代码确定是最新的吧，就在这里下载的，win没办法了？？？？

**Comment by Sumzibuyu** [comment]
搞错了，我是安装服务端出错，提交错了位子，是https://github.com/breakwa11/shadowsocks这里下载的最新版

**Comment by yjd** [comment]
我是2k8的。能用。跑了一个go版和这个py版
