### ISSUE TITLE
win版客户端局域网连接必须使用用户名和密码

### ISSUE THREAD

**Issue by semglassie** [breakwa11/shadowsocks-rss#284]
win版客户端如果开启局域网连接的话必须要设置用户名和密码，留空就会无法连接，但是有些设备的http代理是不支持设置用户名和密码的，望改进

**Comment by breakwa11** [comment]
开启的话，在局域网内的地址段可以使用，而不能使用公网地址，你不会是使用公网地址吧？

**Comment by semglassie** [comment]
局域网地址必须是常规的局域网地址段吗？我自己设置的局域网地址段比较特别

**Comment by yfdyh000** [comment]
@semglassie https://github.com/breakwa11/shadowsocks-csharp/blob/200df6be8ff9a3d6eac47dc1605ac365ed93a084/shadowsocks-csharp/Util/Util.cs#L115

**Comment by breakwa11** [comment]
具体是什么？如果过于特别不在规范允许的范围内是不算的。。。

**Comment by semglassie** [comment]
明白了，十分感谢

**Comment by Eri5Ch** [comment]
然而 不管留不留白 都无法给电脑都无法给手机代理啊
