### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by rakor1986** [breakwa11/shadowsocks-rss#285]
启动的时候报错：
[root@localhost shadowsocks]# python server.py -c /etc/shadowsocks.json -d start
loaded collections.OrderedDict
IPv6 support
Traceback (most recent call last):
  File "server.py", line 28, in <module>
    import db_transfer
  File "/home/shadowsocks/db_transfer.py", line 5, in <module>
    import cymysql
ImportError: No module named cymysql
然后我尝试安装cymysql也报错了：
[root@localhost shadowsocks]# pip install cymysql
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting cymysql
/usr/lib/python2.6/site-packages/pip-8.1.1-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/pip-8.1.1-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached cymysql-0.8.7.tar.gz
Installing collected packages: cymysql
  Running setup.py install for cymysql ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lAwocS/cymysql/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rgwQW1-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.6
    creating build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/packet.py -> build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/cursors.py -> build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/__init__.py -> build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/charset.py -> build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/connections.py -> build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/times.py -> build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/converters.py -> build/lib.linux-x86_64-2.6/cymysql
    copying cymysql/err.py -> build/lib.linux-x86_64-2.6/cymysql
    creating build/lib.linux-x86_64-2.6/cymysql/constants
    copying cymysql/constants/__init__.py -> build/lib.linux-x86_64-2.6/cymysql/constants
    copying cymysql/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.6/cymysql/constants
    copying cymysql/constants/ER.py -> build/lib.linux-x86_64-2.6/cymysql/constants
    copying cymysql/constants/FLAG.py -> build/lib.linux-x86_64-2.6/cymysql/constants
    copying cymysql/constants/CLIENT.py -> build/lib.linux-x86_64-2.6/cymysql/constants
    copying cymysql/constants/COMMAND.py -> build/lib.linux-x86_64-2.6/cymysql/constants
    copying cymysql/constants/SERVER_STATUS.py -> build/lib.linux-x86_64-2.6/cymysql/constants
    creating build/lib.linux-x86_64-2.6/cymysql/tests
    copying cymysql/tests/test_SSCursor.py -> build/lib.linux-x86_64-2.6/cymysql/tests
    copying cymysql/tests/test_example.py -> build/lib.linux-x86_64-2.6/cymysql/tests
    copying cymysql/tests/__init__.py -> build/lib.linux-x86_64-2.6/cymysql/tests
    copying cymysql/tests/test_issues.py -> build/lib.linux-x86_64-2.6/cymysql/tests
    copying cymysql/tests/test_basic.py -> build/lib.linux-x86_64-2.6/cymysql/tests
    copying cymysql/tests/test_DictCursor.py -> build/lib.linux-x86_64-2.6/cymysql/tests
    copying cymysql/tests/base.py -> build/lib.linux-x86_64-2.6/cymysql/tests
    running build_ext
    building 'cymysql.packet' extension
    creating build/temp.linux-x86_64-2.6
    creating build/temp.linux-x86_64-2.6/cymysql
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c cymysql/packet.c -o build/temp.linux-x86_64-2.6/cymysql/packet.o
    cymysql/packet.c:12:20: error: Python.h: No such file or directory
    cymysql/packet.c:14:6: error: #error Python headers needed to compile C extensions, please install development version of Python.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lAwocS/cymysql/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rgwQW1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lAwocS/cymysql/
我对python不太懂，请问这个问题该如何解决呢？

**Comment by rakor1986** [comment]
Python版本是2.6.6

**Comment by jiashooter** [comment]
升级Python

2016年5月9日星期一，rakor1986 <notifications@github.com> 写道：

**Comment by breakwa11** [comment]
用源码git下来的方式使用cymysql就行了
