### ISSUE TITLE
ShadowsocksR android 无法使用

### ISSUE THREAD

**Issue by nyhyeah** [breakwa11/shadowsocks-rss#287]
大家用了吗？为何只有我一个人在问这个问题呢，我电脑的客服端可以用的，手机安装好扫描电脑的二维码配置的

**Comment by breakwa11** [comment]
手机版的确不能用

**Comment by breakwa11** [comment]
但现在没有人维护

**Comment by nyhyeah** [comment]
楼主知道可能是那个方面的问题吗？我把源码下载下来分析分析

**Comment by shiinamayuri** [comment]
我用的 google play 下的 Shadowsocks 正常能用

**Comment by BROBIRD** [comment]
@nyhyeah github上有啊 https://github.com/KagayamaKaede/ShadowsocksRDroid

**Comment by yjd** [comment]
ss原版的客户端2.8.3老版本应该可以。
