### ISSUE TITLE
netstat -ltnap | grep -c CLOSE_WAIT数值过大

### ISSUE THREAD

**Issue by Abclite** [breakwa11/shadowsocks-rss#289]
经常过了一段时间就无法连接SS了，用netstat -ltnap | grep -c CLOSE_WAIT查看发现数值都到1000多了，根据作者提示修改soft nofile和hard nofile，重启机器后用了几个小时还是这样。。。
请问如何解决。

**Comment by breakwa11** [comment]
已私聊解决
