### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by iamezzo** [breakwa11/shadowsocks-rss#290]
Good day, 
While accessing some sites, I receive subject error. 

For example: 
site 2ip.ru. If I will access it just as 2ip.ru, privoxy will show me the error but if I will google 2ip.ru and will access it from google, I will be able to access it. 
Actually, I don't know from where to start investigation of the problem. 
I was googling regarding this problem and found that I'm not alone:
https://github.com/breakwa11/shadowsocks-rss/issues/255 (I don't understand Chinese)
https://github.com/shadowsocks/shadowsocks/issues/459
https://github.com/shadowsocks/shadowsocks/issues/455

So, is it SS bug or what I am doing wrong?

**Comment by breakwa11** [comment]
Try the newest version in BTsync. BT key: BHS55LP54SO7A434QBB5Z2O6B7A45B2BX

**Comment by iamezzo** [comment]
Thanks, updated it to latest version. 

Again the same but different error. 

```
Your request for http://2ip.ru/ could not be fulfilled, because the connection to 2ip.ru (127.0.0.1) has been closed before Privoxy received any data for this request.

This is often a temporary failure, so you might just try again.

If you get this message very often, consider disabling connection-sharing (which should be off by default). If that doesn't help, you may have to additionally disable support for connection keep-alive by setting keep-alive-timeout to 0.
```

SS is not able http to https. 
If I will visit https://2ip.ru - it is working.
If 2ip.ru - it is not.

**Comment by breakwa11** [comment]
Have you more ss server? or all ss server you tried get the same problem?

**Comment by iamezzo** [comment]
@breakwa11 I have just 1 ss server. 
I will setup one more on another provider and let you know.

**Comment by iamezzo** [comment]
@breakwa11 I set up 1 more ss server but with another provider. 
The same issue but the second server is just telling me that "page is not working"

`The 2ip.ru page isn’t working

2ip.ru didn’t send any data.
ERR_EMPTY_RESPONSE`

**Comment by iamezzo** [comment]
One more error:

`No server or forwarder data received
Your request for http://amazon.com/ could not be fulfilled, because the connection to amazon.com (127.0.0.1) has been closed before Privoxy received any data for this request.

This is often a temporary failure, so you might just try again.

If you get this message very often, consider disabling connection-sharing (which should be off by default). If that doesn't help, you may have to additionally disable support for connection keep-alive by setting keep-alive-timeout to 0.`

**Comment by breakwa11** [comment]
I have tried firefox/chrome. it works well with SSR (redirect to https)
My VPS provider is Linode-jp
So I'm not sure what the problem is

**Comment by iamezzo** [comment]
@breakwa11 Mine providers are DigitaloOcean and Vultr. 
Will test on Linode and get back to you.

**Comment by iamezzo** [comment]
@breakwa11 the same problem on Linode also. 
It is definitely privoxy error. https://sourceforge.net/p/ijbswa/support-requests/1686/?page=1

**Comment by breakwa11** [comment]
Oh! I know why it works on my PC, because I'm using socks5 protocol, not http

**Comment by iamezzo** [comment]
@breakwa11 I switched to SOCKS5 and know I receive this error in Chrome
`The 2ip.ru page isn’t working

2ip.ru didn’t send any data.
ERR_EMPTY_RESPONSE`

Any suggestion?

**Comment by iamezzo** [comment]
@breakwa11 
It is a Google Chrome problem. In Firefox everything is OK.

**Comment by nonfxck** [comment]
我win2012国内服务器用SS翻墙也是这个问题.........但是我路由器里翻墙挺好
