### ISSUE TITLE
ss多ip怎样让数据按指定ip出口并且原路返回?

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#291]
我的一个linux机器有10个ip，ip分别是:
222.222.222.2(主ip)
222.222.222.3
...
222.222.222.10
我在上面跑了ss服务，目的是访问任意一个都可以。

现在的情况却是，不管我访问的是哪个ip，用www.ip138.com查看的ip都是222.222.222.2这个主ip的返回结果。

分析一下原因，由于ss是socks服务，不管客户端访问的哪个ip过来，服务器在对外访问的时候，走的都是缺省路由，也就会用222.222.222.2这个ip。

所以，虽然ss客户端与服务器之间连接用任意ip都可以，但是服务器去访问www.ip138.com时都会用222.222.222.2这个ip。

这样产生了一个问题，当我挂不同的ss的ip去注册fb账号时,不管我挂哪个ip，fb看到的都是我的主ip.

怎样才可以改成，我访问某个ip，那么数据就从自动从这个ip向外访问，并且按这个ip原路返回?

**Comment by breakwa11** [comment]
现在还不支持，以后会加上

**Comment by impig33** [comment]
现在有啥好办法能办到呢?

**Comment by breakwa11** [comment]
现在更新服务端就可以了

**Comment by impig33** [comment]
哪一个呢? 我只看到3.7.4.1的客户端

**Comment by rexchou** [comment]
@impig33 你的多IP出口是怎么处理的呢？

**Comment by langzidiy** [comment]
求具体配置步骤。

**Comment by laikitleung** [comment]
同求具体配置

**Comment by impig33** [comment]
不用配置 @laikitleung 现在的ssr安装好就是的
