### ISSUE TITLE
建议酱妹在zeronet版面加个讨论版

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#292]
RT,谢谢

**Comment by breakwa11** [comment]
自己维护麻烦啊，反正有现成的，放一起讨论吧

**Comment by impig33** [comment]
这个要搭梯子，好麻烦

2016-05-18 17:08 GMT+08:00 破娃酱 <notifications@github.com>:

**Comment by breakwa11** [comment]
我意思是直接用现成的讨论版，密码页有
