### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by jamesvip** [breakwa11/shadowsocks-rss#293]
出现很多[Errno 104] Connection reset by peer错误，iphone端google app时不时连接不上

**Comment by ant-sir** [comment]
解决了吗，我python client也遇到相同问题？

**Comment by breakwa11** [comment]
请提供更详细的信息

**Comment by python12450** [comment]
如果出现持续15min的重置那估计是被盯上了

**Comment by lingaoyi** [comment]
2016/07/06 06:55:54 error getting request 113.119.36.81:34784 47.89.20.19:80 read tcp 47.89.20.19:80->113.119.36.81:34784: read: connection reset by peer ，日志看到这个东西，然后SS就会突然断开了

我用梅林游戏模式V2 也会这样，出现了SS就断开了，必须要重新提交，好烦人。

**Comment by Tai7sy** [comment]
提供一个autoban脚本.

	for line in sys.stdin:#
		if 'can not parse header when' in line or 'exception from ' in line:
			ip = line.split()[-1].split(':')[0]
			pos = ip.rfind('.')
			if pos == -1:
				break
			ip = ip[:pos]+'.0/24'
			if ip not in ips:
				ips[ip] = 1
				print('suspicious: '+ip)
				sys.stdout.flush()
			else:
				ips[ip] += 1
			if ip not in banned and ips[ip] >= config.count:
				banned.add(ip)
				cmd = 'iptables -A INPUT -s %s -j DROP' % ip
				print(cmd, file=sys.stderr)
				sys.stderr.flush()
				os.system(cmd)

**Comment by usami-muzugi** [comment]
2016-07-21 22:30:05 ERROR    tcprelay.py:811 [Errno 110] Connection timed out
2016-07-21 22:30:05 ERROR    tcprelay.py:813 when connect to 136.66.193.131:2738 from ::ffff:121.12.41.156:59300

**Comment by usami-muzugi** [comment]
大量的[Errno 104] Connection reset by peer 与ERROR tcprelay.py:811 [Errno 110] Connection timed out
之前是晚间出现，现在平凡出现在各种时段。

**Comment by jamesvip** [comment]
经鉴定，是电信国际出口抽风丢包造成，换了线路就没这个问题。
