### ISSUE TITLE
多用户版端口开启问题

### ISSUE THREAD

**Issue by Tomzuo** [breakwa11/shadowsocks-rss#301]
Centos7 装了SSR多用户版和ss panel 。
防护墙是iptables，必须手动开启需要的端口吗？虽然可以开启一个段但是用户是不断增长的太麻烦了，有没有其他办法？自动开启端口？

**Comment by breakwa11** [comment]
暂没有办法

**Comment by falseen** [comment]
可以写一个脚本监测数据库的变动，然后根据情况执行iptables。
或者你熟悉python的话可以利用 switchrule.py 获取数据， 然后用python操作iptables。
不过我觉得这样做没什么意义，默认拒绝所有ip才有意义。
