### ISSUE TITLE
无法开机自动启动

### ISSUE THREAD

**Issue by mxs930907** [breakwa11/shadowsocks-rss#305]
![image](https://cloud.githubusercontent.com/assets/19668795/15707773/2f9c1064-282d-11e6-8764-6052c191e988.png)
依照教程，改为everyone全面控制也没有用。有没有什么方法，或者详细点的教程。

**Comment by breakwa11** [comment]
win10还需要手动增加一个键，或者直接更新为3812

**Comment by mxs930907** [comment]
需要手动增加什么键？我换到3812还是这样。

**Comment by breakwa11** [comment]
上级的Internet Settings也要对当前用户增加完全控制权限
