### ISSUE TITLE
提示需安装NET  4.0

### ISSUE THREAD

**Issue by L-Meteor** [breakwa11/shadowsocks-rss#31]
请问 ShadowsocksR 3.3.6 现需要安装 NET  4.0 了吗?前几个版本都不需要的!

**Comment by yfdyh000** [comment]
仔细看，同时提供了 ShadowsocksR-dotnet2.0-3.3.6.exe

**Comment by breakwa11** [comment]
打包的时候打错了，只有一个NET4.0

**Comment by leoxxx** [comment]
@breakwa11 
不补传2.0吗？

**Comment by breakwa11** [comment]
明天会重新打包的

**Comment by breakwa11** [comment]
已重新打包，直接发在了https://github.com/breakwa11/shadowsocks-csharp/releases

**Comment by leoxxx** [comment]
@breakwa11 有问题，无法运行。运行后出现停止工作。

**Comment by breakwa11** [comment]
已修正
