### ISSUE TITLE
请we多IP出口怎么弄？求思路或资料。

### ISSUE THREAD

**Issue by JasonVeryGood** [breakwa11/shadowsocks-rss#311]
多IP出口怎么弄？求思路或资料。

**Comment by Lyoko-Jeremie** [comment]
多出口服务器的话
入口根据你设置的绑定IP决定
出口根据你的服务器设置决定，一般是随机的，如果是v4-v6双出口就根据流量的协议决定

**Comment by JasonVeryGood** [comment]
@Lyoko-Jeremie 有什么办法能使 什么IP进什么IP出？

**Comment by breakwa11** [comment]
楼主你有多IP的话为什么不先测测看现在的是不是满足你的需求？
