### ISSUE TITLE
3.8.2 端口转发失败

### ISSUE THREAD

**Issue by agentmario** [breakwa11/shadowsocks-rss#312]
我已经在服务端配置里添加了 "forbidden_ip":"" 项，在本地 portMap 项中添加了转发服务器 ssh 端口的项目
```json
"22" : {
			"enable" : true,
			"id" : "32-00-08-CA-FC-......",
			"server_addr" : "127.0.0.1",
			"server_port" : 22
		}
```
但无法成功通过 ss 连入远程服务器，把 server_addr 改成我的另一个 VPS 的地址也无效
我的 ssh 客户端在提示 
Connecting to 127.0.0.1:22...
Connection established.
之后就一直没有动静了

**Comment by breakwa11** [comment]
是个BUG，已解决，等下个版本就好。。。

**Comment by breakwa11** [comment]
fixed
