### ISSUE TITLE
shell.py:50 'UDPRelay' object has no attribute '_forbidden_portset'

### ISSUE THREAD

**Issue by Aar0nJaw** [breakwa11/shadowsocks-rss#314]
RT
every time when i try to run something requested UDP Reply it shows 'shell.py:50 'UDPRelay' object has no attribute '_forbidden_portset'

**Comment by Aar0nJaw** [comment]
by the way,it s happening while im using the newest version

**Comment by breakwa11** [comment]
Already fix it.Please update
