### ISSUE TITLE
为了 chacha20 尝试安装 libsodium 之后导致 libcrypto 出错

### ISSUE THREAD

**Issue by agentmario** [breakwa11/shadowsocks-rss#317]
错误日志中显示
AttributeError: No symbol EVP_CIPHER_CTX_cleanup found in library libcrypto.so.1.1
使得服务端无法启动，有什么办法拯救吗

**Comment by breakwa11** [comment]
我不知道。。。

**Comment by SnowInJuly** [comment]
libsodium  libcrypto 冲突，什么系统你是

**Comment by agentmario** [comment]
ubuntu 14.04
2016年6月26日 10:50，七月飞雪 <notifications@github.com>写道：libsodium  libcrypto 冲突，什么系统你是

**Comment by breakwa11** [comment]
please reinstall
