### ISSUE TITLE
我下载的3.7.4.1的c#版客户端为什么没有tls1.2选项呢？

### ISSUE THREAD

**Issue by myveb** [breakwa11/shadowsocks-rss#318]
只有tls1.0

**Comment by wenliyang** [comment]
版本3.8.0 2016-04-17
1.移除tls_simple
2.增加tls1.2_ticket_auth

因为3.8.0版本才增加了这个

**Comment by ibucoin** [comment]
使用BitTorrent Sync来下载

**Comment by WLZLCX** [comment]
你需要在ZeroNet里更新SSR

**Comment by eromoe** [comment]
不能发个zip 包么。。。还是说 windows下 最新就是3.7.4.1?
