### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by clowwindy** [breakwa11/shadowsocks-rss#32]
Despite of the license problem, thanks for your hard working. I'm sorry for my rude words.

The license problem is rather a small problem, compared to other problems we face now.

If you choose to keep going, be careful and stay out of trouble. I believe you'll create something awesome.

Best wishes.

**Comment by BROBIRD** [comment]
In fact,it's 'thank you',not 'thanks'.😏

**Comment by dangger** [comment]
In a word,thanks @clowwindy & breakwa11 ,and all of the contributor of the shadowsocks.

**Comment by aprikyblue** [comment]
Anyway, thanks everyone for contributions in this regard

**Comment by bitinn** [comment]
Having said that, staying closed source does prevent wider adoption, security/privacy risk etc.

If this project does go on then I see no better solution than open source (hell, maybe even put it under Public Domain and let these go wild).

Just my 2 cents, I am sure both developers have better idea in mind.

**Comment by wszf5560** [comment]
Thanks for all contributors. The unity and the forgiveness could let us go further on the way of striving, and it is really funny the creativity and the mind can be restrainted by the so-called w@ll.

**Comment by acp134** [comment]
Anyway,thanks for all the contributors.We shall never forget the great works you have ever done.

**Comment by scymen** [comment]
Thanks, and be safe.

**Comment by Talent30** [comment]
watch your back be safe

**Comment by shengruoyu** [comment]
Thanks for all the contributors. There is no w@ll that can prevent the desire for freedom.

**Comment by soupsueapple** [comment]
Thanks

**Comment by panda7456** [comment]
Quote from a lyric
"Hey Jude' don't be afraid.  
You were made to go out and get her. "
Thank all the contributors who give us a chance to see the real world.
Take care of yourselves and fight for "her" ( our freedom).
Come on!

**Comment by acp134** [comment]
By the way,one of my friends said thank you to all of the contributors (he does not have a GitHub account) and farewell to @clowwindy .

**Comment by MixerW** [comment]
Thanks for all contributors.

**Comment by breakwa11** [comment]
@clowwindy thanks

**Comment by smileshadow** [comment]
Thank you for making us see the real world. All of you are heroes.

**Comment by Junzki** [comment]
Thank you very much.

**Comment by lixingcong** [comment]
So much Thanks to the developers of this project.Best Wishes.

**Comment by cielpy** [comment]
Thank you.

**Comment by ladrift** [comment]
Thank you. Best wishes for you.

**Comment by bakachao** [comment]
Thank you very much. Good luck!

**Comment by xfl03** [comment]
Thanks every contributors of shadowsocks. Do better in ZH, CW :)

**Comment by cgcgbcbc** [comment]
I would recommend that put at least a md5sum in the README for a closed source software

**Comment by Georges-Rush-St-Pierre** [comment]
Thanks,good luck to you

**Comment by mrken2004** [comment]
@clowwindy  @breakwa11  Thank you very much and please pay attention to safety.

**Comment by ARwMq9b6** [comment]
Warning :100: 
=========

@breakwa11 The ID named breakwa11 seems to be unsafe, please change to another one.

**Comment by Crepusculo** [comment]
Thanks,be safe

**Comment by zhengfaxiang** [comment]
Thanks for all the contributors!

**Comment by Eth4nZ** [comment]
thank u and best wishes for all contributors.

**Comment by FlyGoat** [comment]
Thanks, good luck.

**Comment by akw28888** [comment]
Thanks @clowwindy and Magic Conch.

**Comment by cuber** [comment]
Thanks all the way, good luck.

**Comment by nmapleaf** [comment]
Thanks, and be safe.

**Comment by azgh** [comment]
@breakwa11 @clowwindy Thanks you guys for contribution to shadowsocks user, hope you guys are safe, and project can be continued. BTW, less argument, more work together, people will remember what you did.

**Comment by HaoSilence** [comment]
Thanks all you guys .

**Comment by bleachbl** [comment]
thank you a lot for your work!

**Comment by fan123199** [comment]
Never give up!

**Comment by majinjing3** [comment]
Thank you！

**Comment by xuzhenglun** [comment]
Thank U very much!

**Comment by littlebearz** [comment]
thank you!

**Comment by OrangeYoung** [comment]
@clowwindy thank you!

**Comment by Manho** [comment]
thank you

**Comment by kehao95** [comment]
thank u

**Comment by careux** [comment]
----

* 看到如此和谐的景象还是感觉很温暖的呢 :blush:
* But why all you Chinese speak English here? :frowning:
* 对所有为开源世界作出过贡献的妹纸、汉子点个赞！:thumbsup:

----

&#160; &#160; &#160; &#160;对于此次事件中暴露出来的所有问题（包括但不限于：Licence、匿名、撕逼、国内开源社区氛围）或许都值得我们思考，有则改之，无则加勉。

**Comment by navigaid** [comment]
道一声珍重

**Comment by dbalee** [comment]
@clowwindy Thanks, and be safe!

**Comment by TacticalTwerking** [comment]
thanks to all guys who maintenance this PROJECT.

**Comment by lichunqiang** [comment]
:candle:

**Comment by sgsheg** [comment]
thank you.

**Comment by wongzigii** [comment]
Good luck.

**Comment by Picture88** [comment]
Thank u!
We'll never forget what you do for us.
Be SAFE
Good Luck.
[I HATE xxx GOV]

**Comment by ivenwinds** [comment]
Thank you.
Be safe.
God bless you.

**Comment by wangvisual** [comment]
楼主好人一生平安

**Comment by renyidong** [comment]
Hey! Everyone who say thank to breakwa11! She is not acontributor at all. She is merely a shameless license-breaker/ leecher/ thief. GPL states anyone who convey object code derived from a covered work must convey the source code together. 
By the way, releasing a security related work in binary only does NOT help improving its strength. Releasing the source code only helps white hats find out problem.

**Comment by printempw** [comment]
Thanks to @clowwindy & @breakwa11 for their struggle.
I prefer to regard @breakwa11 not as a license-breaker but as a good guy fucking GFW.

**Comment by cr0sswall** [comment]
@renyidong

The latest version 3.3.6 is already open source.
https://github.com/breakwa11/shadowsocks-rss

> 版本3.3.6
1.修正“自动禁用出错服务器”选项保存的问题
2.所有临时文件全部放到./temp/下
3.连接方式不同也视为不同服务器分别统计
4.删除升级提示检查
5.删除实验性功能代码并开源https://github.com/breakwa11/shadowsocks-csharp

I hope there will be less argument.

**Comment by SpartaEN** [comment]
@clowwindy @breakwa11  Thank you,good luck .Pls pay attention to your safety.

**Comment by AngryPowman** [comment]
Take care, thanks anyway.

**Comment by Jacob08** [comment]
thank you for everthing.

**Comment by LiGhT1EsS** [comment]
Thanks clowwindy & breakwa11 ,and all of the contributor of the shadowsocks. Thanks, and be safe!

**Comment by jyieidff** [comment]
@clowwindy 
Anyway,Thank you!

**Comment by Halry** [comment]
Thank you for helping me to open my eyesight.
Good luck:)

**Comment by Gillwindy** [comment]
Thank you.Wish you be safe.

**Comment by wenliyang** [comment]
Thank you.

**Comment by bytooyts** [comment]
thank u,be safe and no more

**Comment by WuWaA** [comment]
Many thanks indeed.

**Comment by SeanChense** [comment]
Thank you @clowwindy @breakwa11

**Comment by mogodes** [comment]
Thanks all the contributors. In my opinion, it is the best tool of fucking GFW.

**Comment by oldcai** [comment]
Thanks to all of you for your efforts in improving network situation inside Great Wall.

Don't be sad, you've changed the world big enough for old brother to fear.

**Comment by Zheaoli** [comment]
Thank you for everything

**Comment by jerryling315** [comment]
Thank both of you.

@xuzhenglun huh. Commented you the other day on Iptable <= shadowsocks forwarding issue. I resolved it by setting MASQUERADE

**Comment by wanliang1221** [comment]
Thanks to the people give us Free! And we will walk our way!

**Comment by XIAOSpider97** [comment]
Thank you, wish you can get rid of CN some day.

**Comment by eric6356** [comment]
Thanks.

**Comment by sundiontheway** [comment]
Thank you， best wishes.

**Comment by gnaggnoyil** [comment]
Thank you for your outstanding work.

**Comment by Boypeipei** [comment]
best wishes & stay safe.

**Comment by snnn** [comment]
Hope you wil be safe

**Comment by yamabu** [comment]
thank you

**Comment by flyher** [comment]
Thanks all the contributors.  and be safe!

**Comment by zhoufenfens** [comment]
thank you!

**Comment by swjz** [comment]
Thanks. be safe.

**Comment by calebx** [comment]
thank you, take care

**Comment by PaaandaChen** [comment]
LONG LIVE THE SHADOWSOCKS

**Comment by tdh62** [comment]
珍重，感谢

**Comment by tastypear** [comment]
thank you for your efforts

**Comment by kn007** [comment]
@clowwindy Hope you are well! Be careful. Be safe. Thank you so much for providing such great software.

**Comment by otherfish** [comment]
thx :pray:

**Comment by daizhibin** [comment]
thx god bless you

**Comment by zitaofang** [comment]
Thank you.

**Comment by GrassBerry** [comment]
No freedom,No code. Good luck!

**Comment by CN-Lyc** [comment]
thank you谢谢！

**Comment by supercong** [comment]
thank you!

**Comment by huilang-me** [comment]
Thank you.

**Comment by asasuou** [comment]
開発者の方々に感謝します。
有り難う御座いました。

**Comment by wqtty** [comment]
Thank you! To hell with GFW!

**Comment by celeron533** [comment]
@wqtty 
>Thank you! To hell with GFW!
'with' means 一起

**Comment by qiwihui** [comment]
Thank you! And may the force be with you.

**Comment by Biweijie-edu1** [comment]
对于将要推出的新版Shadowsocks虽然抱有怀疑，但是对于你的行为还是致敬。

**Comment by jiangzhouq** [comment]
Thank you !

**Comment by celeron533** [comment]
Thank you for your work! The project helped me a lot.

**Comment by rakitic** [comment]
I recommend the source code be handed to students abroad who are interested in the program and relatively safe for further development.
May you safe and sound! Thanks!

**Comment by baisong3777** [comment]
Thanks, and be safe.Best wishes.

**Comment by 476210180** [comment]
Best wishes!!
Long live SS!! We're on your side!!

**Comment by diligentpig** [comment]
thank you！

**Comment by vdwhite** [comment]
Thank You so much! 谢谢你！

**Comment by 178220709** [comment]
祝一切安好

**Comment by xuefliang** [comment]
有路由器端么？

**Comment by calvinxiao** [comment]
# Great Work!!!!

**Comment by jiangzhouq** [comment]
@xuefliang 
google: "openwrt shadowsocks"

**Comment by DaZui** [comment]
Thanks, and Good Luck.

**Comment by cdmask** [comment]
Good luck,man.

**Comment by mveplus** [comment]
This is war! There will be casualties of the system... 
This is not east vs. west, but open vs. closed.
We'll never stand a chance against closed ones, if we are not truly united and stay forever open!

Great thanks to all un-human efforts of all contributors to keep up this alive! And especially @clowwindy @breakwa11 and all the rest inside!

**Comment by malcolmyu** [comment]
But why all you Chinese speak English here? :frowning:

**Comment by aOJzQT** [comment]
@malcolmyu 也许是为了给外国友人围观提供便利

**Comment by hope1** [comment]
许可证的确是重要的问题，不过在现在的情况下，主要的原因不只在于对原作者著作权的损害了。希望开发者都能认识到开源和强制开源许可证的意义。

**Comment by IDGOD** [comment]
wow！

**Comment by liu-bai** [comment]
thank you！

**Comment by Fxhhahaha** [comment]
thank you

**Comment by andylovesrock** [comment]
@breakwa11 Thanks for your hard work. Would it be unsafe for you to manage this project in China? I agree that this project should be handed to someone who is abroad and with CS background. It's not only good for your safety but also for the sustainability of the project. 

I'd like to offer help but I major in stats and may not be capable. Do contact me if there is anything I can do.

**Comment by idailylife** [comment]
Thank you and take care.

**Comment by aesean** [comment]
Thank you! Best wish.

**Comment by superfls** [comment]
Thank  you!! move on and be carefull

**Comment by ChenXingbo** [comment]
@clowwindy thank you for your work!

**Comment by black-head** [comment]
@clowwindy @breakwa11 Thank you

**Comment by shuaiqingli** [comment]
@clowwindy Thank you! and I hope you will soon leave dangerous place

**Comment by lersh** [comment]
@breakwa11 & @clowwindy Thank you！

**Comment by huwsun** [comment]
谢谢你们！@clowwindy @breakwa11 
shadowsocks和shadowsockr都用过，现在shadowsocks我这里的确会有断开连接的情况，shadowsocksr开启了混淆协议就好一点

**Comment by heheboy** [comment]
@clowwindy  @breakwa11  Thanks!

**Comment by GongJianwei** [comment]
I'm sorry that I can't give it up.

**Comment by heheboy** [comment]
then don't give it up~

2017-02-04 1:31 GMT+08:00 没有字的回音 <notifications@github.com>:
