### ISSUE TITLE
ss-panel v3+manyuser(python) 好像流量统计不准确！

### ISSUE THREAD

**Issue by kanlidy** [breakwa11/shadowsocks-rss#324]
提示节点不支持流量。

我发现，现在的ss-panel流量信息中，是调用的user_traffic_log中的数据，而真实的流量信息在user这个表中的t,u,d三个字段。

如何把t,u,d三个字段的信息，同步写到user-traffic_log中对应的用户信息中去？！！！

**Comment by kanlidy** [comment]
我发现，现在的ss-panel流量信息中，是调用的user_traffic_log中的数据，而真实的流量信息在user这个表中的t,u,d三个字段。

**Comment by falseen** [comment]
ss会把流量信息写到u,d两个字段中，至于怎么调用，那就是ss-panel的事了。不过流量不准确应该是不存在的，毕竟那么多人在用。ss-panel的作者维护着一个go版本的ss，这个版本可以更好的跟ss-panel融合，你可以看看。

**Comment by kanlidy** [comment]
@falseen 你有没有注意user这个表与user-traffic_log这两个表！？是的，ss是写了，写到user中了。Go版本的地址是多少？ 我打算把ss-panel的后台php改一下，读user表，写到user-traffic_log中试一下。

**Comment by breakwa11** [comment]
以后会加的

**Comment by breakwa11** [comment]
但这并不是不准确
