### ISSUE TITLE
请问首包加随机字节问题

### ISSUE THREAD

**Issue by junweigu** [breakwa11/shadowsocks-rss#326]
作者您好，请问这个首包长度修改是在客户端修改还是服务端修改？可以告知在原版ss何处做修改吗？可否举例呢

**Comment by breakwa11** [comment]
无法修改

**Comment by junweigu** [comment]
您不是在ss r里修复了这一协议缺陷吗？
2016年6月30日 03:04，"破娃酱" <notifications@github.com>写道：

**Comment by breakwa11** [comment]
除非你也写一个支持你自己写的协议的服务端，否则只改客户端根本不可能
