### ISSUE TITLE
求助：每天晚上10点左右路由器上的SSR不能连接服务器

### ISSUE THREAD

**Issue by jack338c** [breakwa11/shadowsocks-rss#327]
每天晚上10点左右，同样的SS账号和设置，同一VPS,用PC客户端SSR能FQ，但是用路由器的SSR不能FQ（其它时段工作正常),但是换成日本服务器的SS账号路由器的SSR能FQ,

vps SSR是用git clone -b manyuser https://github.com/breakwa11/shadowsocks.git方式安装的

请问这是什么原因？

**Comment by breakwa11** [comment]
你找你的路由器固件作者问问

**Comment by jack338c** [comment]
才看到，忘记来说明了，是设置成auth_sha1，且时区差的问题
谢谢你的回复！
