### ISSUE TITLE
高dpi下显示问题

### ISSUE THREAD

**Issue by lich13** [breakwa11/shadowsocks-rss#329]
如图https://public.lightpic.info/image/82AB_577EE7990.jpg
只有服务器连接统计显示有问题
系统环境是win7 dpi 200%（已用自动调整大小解决 但是窗口还是没法放大 如图https://public.lightpic.info/image/AE73_577EEC3C0.jpg

**Comment by breakwa11** [comment]
不要最大化，右键自动调整列宽
