### ISSUE TITLE
'NoneType' object has no attribute 'sendto' when handling connection from XXXX(ClientIP)

### ISSUE THREAD

**Issue by Tai7sy** [breakwa11/shadowsocks-rss#334]
@breakwa11 
![qq 20160710142632](https://cloud.githubusercontent.com/assets/12840640/16711996/84157a18-46aa-11e6-846a-50a5d2ce3d71.png)

**Comment by breakwa11** [comment]
your server is ipv6 only?

**Comment by Tai7sy** [comment]
I have changed the 'False' in the 470 line in asyncdns.py into True to solve this problem temporarily.But I don't think it is a good idea.

**Comment by breakwa11** [comment]
twitter或其它地方私聊我给我SSH，我去测测看

**Comment by breakwa11** [comment]
已测完成，和我的代码毫无关系
