### ISSUE TITLE
What is the license for the contents in README?

### ISSUE THREAD

**Issue by jerryling315** [breakwa11/shadowsocks-rss#34]

**Comment by breakwa11** [comment]
呃，这个我不懂，求详解？

**Comment by XhstormR** [comment]
你这个软件使用的是什么许可证，开源还是闭源

**Comment by yfdyh000** [comment]
README有很不明显的写出，软件开源在 https://github.com/breakwa11/shadowsocks-csharp
因为GPL，所以还是GPL。新软件还没影。前情见 #28

**Comment by breakwa11** [comment]
GPLv3许可证

**Comment by jerryling315** [comment]
哦哦哦哦擦, 其实我是想问 README 的内容是什么 CC 协议, sorry

**Comment by breakwa11** [comment]
@jerryling315 readme没有什么协议，随便用。。。

**Comment by yfdyh000** [comment]
@breakwa11 如果没有明确说明，那么默认是保留所有权利的，别人不能随便用……
另外，这里的库“覆盖”更新很多版了，我一直以为是不想让别人引用/阅读的。

**Comment by breakwa11** [comment]
@yfdyh000 早已经被引用无数个地方了，比如 http://t.du9l.com/2015/08/qi-wen-gong-shang/

**Comment by jerryling315** [comment]
@breakwa11 你不应该让他们这么用的, 建议使用 BY-NC-SA 这样大多数圈内的非商业信息博客和个人网站都能用了也比较有 opensource 的精神

**Comment by yfdyh000** [comment]
@breakwa11 然而只要没明确允许，全文转载也是未授权行为（只放链接不算）。虽然确实有些槽点。虽然声明了协议也不一定能阻止。

**Comment by jerryling315** [comment]
@yfdyh000 是这个道理
