### ISSUE TITLE
win10 insider preview14393+3.8.3e

### ISSUE THREAD

**Issue by KyonCN** [breakwa11/shadowsocks-rss#341]
报错 超时 100%
 System.DllNotFoundException: 无法加载 DLL“libdl.so”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.Libcrypto.dlopen(String fileName, Int32 flags)
   在 Shadowsocks.Encryption.Libcrypto..cctor()

**Comment by breakwa11** [comment]
和这错误无关
