### ISSUE TITLE
shadowsocks客户端是否有日志文件？

### ISSUE THREAD

**Issue by luofeiyu** [breakwa11/shadowsocks-rss#345]
我在win7的客户端可以看日志，请问，linux版本的客户端在哪里看日志？
注意我问的是客户端的日志，服务器端的日志在这里  /var/log/shadowsocks.log

**Comment by breakwa11** [comment]
取决于你怎么运行

**Comment by luofeiyu** [comment]
如果我要在客户端也设置日志文件 /var/log/shadowsocks.log   应当如何写配置文件？

**Comment by breakwa11** [comment]
你运行的时候你把输出重定向到哪里就会到哪里，不重定向就输出屏幕（无文件）
