### ISSUE TITLE
联通宽带封锁了我的vps ip 怎么办呢？

### ISSUE THREAD

**Issue by luofeiyu** [breakwa11/shadowsocks-rss#346]
突然发现通过联通的宽带，ping  我的vps ip  ，延时巨高，导致ss无法使用了，请问，怎么办？
用移动的宽带使用这个vps ip没有问题，这下是新问题了。

**Comment by jameseroyi** [comment]
。。。。。你ip被封了  breakwa11能有啥办法 你用它干啥了

2016-07-25 16:32 GMT+08:00 luofeiyu <notifications@github.com>:

**Comment by geniusxiaoxiao** [comment]
重启光猫换个自己的IP后再试试

**Comment by BROBIRD** [comment]
延时高考虑是QoS而不是封锁吧
