### ISSUE TITLE
ERROR    tcprelay.py:116 creater encryptor fail at port XXXXX

### ISSUE THREAD

**Issue by wgf2008** [breakwa11/shadowsocks-rss#347]
系统 cnetos6 2.6.32-504.3.3.el6.centos.plus.x86_64
加密方式aes-256-cfb
单用户可以，换成mysql多用户就报这个错。
有遇到的妈?

**Comment by breakwa11** [comment]
请确认你的数据库是不是用sspanel v3的，以及method字段是否正确配置，这必然是配置的问题

**Comment by wgf2008** [comment]
是v3的啊，接上去有显示负载什么的，以前的是好的，method也是对的啊，我就改了混淆方式
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "m",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "verify_sha1_compatible",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}
这是我的配置

**Comment by breakwa11** [comment]
请确认你有没有任何用户修改为不支持的加密方式

**Comment by wgf2008** [comment]
原来支持自定义密码了。。。。谢谢了！
