### ISSUE TITLE
更新计划

### ISSUE THREAD

**Issue by breakwa11** [breakwa11/shadowsocks-rss#35]
目前，SS主要问题是TCP连接协议存在问题（可能现在已经被部分地区的GFW用于主动探测，之前SSR增加的TCP混淆功能在这个主动探测方式下不起作用，现在也去掉了这个功能的支持，现在已有不少用户反映使用一段时间后节点便会被封锁掉，可参考当年Tor网桥是怎么挂掉的），但大幅度改动的话就不是SS了，考虑使用打Patch的方式（之前我说的新的大改动实现会另起名字，尽量减少现在SS实现的变动），提升安全性的和抗探测能力的同时最大限度减少客户端的影响（具体的协议调整方式我会和现在的开发者联系讨论，可能会考虑使用目前TCP over UDP的数据包验证方式）。然后目前ShadowsocksR支持把原始流量封装为另一种流量，包含TCP over UDP以及UDP over TCP，前者为提升下载速度和安全性，后者为绕过屏蔽（比如学校或公司屏蔽了UDP流量），后者基本成熟，前者刚刚公开测试，还需要时间去稳定。两者都需要code review，客户端可能需要重构一版代码（好吧，我已经写吐了，各种C#特性不熟悉的情况下，以及多线程的大坑）。待成熟后再推广到其它客户端/服务端实现。

wiki的内容非常缺乏，需要大量写文档，部分文档会考虑从clowwindy那边复制过来整理。

除此以外，主要还有路由器上的实现跟进，以及ShadowVPN的改进（改进为允许**多点连接**，让其变得实用，但需要时间研究其实现看能否这样做），各种环境包括Linux/Android/iOS/Mac等等，我一个人不可能折腾这么多，很希望原作者**以匿名方式**和我联系。

目前已经出现SS的变种实现，如[https://github.com/shell909090/goproxy](https://github.com/shell909090/goproxy)，不过我的实现想法和他的实现貌似是完全相反的，到时候想一起讨论一下各种实现的抗干扰和安全性等问题。

其它问题：个人还是希望不要乱猜测些什么，比如说我是clowwindy的情人什么的，这简直是无中生有！但我不介意其它人怀疑程序中有什么“收集账号”，“监听私隐”，对于程序是否存在后门功能的怀疑我一点都不介意。只要不要研究我可能是谁谁谁的情人就好了，因为这不可能，我目前作为独立的单元存在。我个人还是很希望得到鼓励的，否则我会很缺乏动力:p

这个暑假我过的还挺充实的样子，不知道大家怎么样呢

**Comment by kingshdom** [comment]
能有人站出来继承作者的衣钵已经很不容易了，何况还是个妹子，希望作者在码代码的同时网络上注意隐蔽，注意安全，最后感谢一下

**Comment by printempw** [comment]
感谢作者，加油。
注意匿名哦

**Comment by cfcboy** [comment]
很感谢@breakwa11继续维护此项目，如果新项目有地址，希望到时候可以说一声！
上面提到的GOPROXY不知道作者试过好不好用。比如速度和稳定性上面。可以互相借鉴一下哈。

**Comment by wszf5560** [comment]
很不错的样子，支持你。
无论什么时候，匿名最重要。近两年由于类似的CODE引起的大麻烦太多了，正常的人无论什么方式被喝茶，心里总是有阴影和委屈的，一个有良知的开发者不应该受到这种待遇。
若是能相互间多讨论，交流自己的看法和想法，那就太好了。各自为伍不可取，而且会很累，毕竟对面是一个大集团。希望各路精英们能开团一次。
无论是新的或者补充更新原有的协议，有能力，而且还勇敢继续向前的人，就是英雄，就该受到尊重，所以那些说风凉话的就别捣乱了。

<b>最后希望各位作者，若是不能保证anonymous，请别发布和参与了。我们不想再经受更多的内疚，谢谢！</b>

**Comment by TearDownGFW** [comment]
https://github.com/breakwa11/shadowsocks-csharp/blob/master/shadowsocks-csharp/Controller/TDP.cs#L105-L126

“提升下载速度和安全性” 真厉害

无控制算法，发出去的超速包都会被运营商丢掉，用户带宽大则永远跑不到

介绍写的好看，代码全是垃圾

**Comment by TearDownGFW** [comment]
我建议你先去学习一下网络编程入门，了解一下 frame , window , flow control , error detection , error correction 等基本知识

**Comment by breakwa11** [comment]
@TearDownGFW 这我知道啊，说明的时候说了，实现只到刚好能用，还有好多东西还没写，包括发包控制，丢包预测，同步速率控制，自动策略选择，重定向，多服代理，界面上还需要设计对应的设置界面等等好大堆的东西，我知道很多人比我厉害，包括你在内，不如做点实事贡献点代码？我这要写的东西实在太多了，就算写好了还要考虑移植到其它语言和其它平台

**Comment by mveplus** [comment]
@breakwa11 - 甭管他是政府代理！玩老游戏有你！他的目的是摧毁，阻止和杀死你的未来努力!

**Comment by breakwa11** [comment]
@mveplus 你猜得很准确，根据他在其它博客和网站的留言，看得出来他没有使用匿名的方式，暴露出TearDownGFW所在地址为**北京市工业和信息化部**，也就是说我已经**被工信部的人盯上**，他在另一地方说，这个实现有明显的特征极容易被封杀，那么我相信大家都懂的，如果真的容易封杀，他肯定不会出来说话。前一帖子我其实已经感觉出来有问题，不过用相对比较客气的方式说出来。他其实压根没看明白代码，那个引用的代码段完全是引用错了，尽管他说的那个功能的确还没实现，我感觉只是他蒙对了，其实更大的问题并不在那里，我就先不细说了，看看他能看个啥程度。

**Comment by yfdyh000** [comment]
@breakwa11 具体而言呢？哪个留言？没搜到任何线索。

**Comment by breakwa11** [comment]
![a](https://cloud.githubusercontent.com/assets/8436963/9537106/0eb01d56-4d67-11e5-8a3f-a6fa5ed96c98.png)
考虑到链接会变动，直接先截图

**Comment by yfdyh000** [comment]
感谢。看起来挺有力的，挺讽刺的“内部人士”。
https://web.archive.org/web/20150828013911/http://www.zdfans.com/5531.html 已留存。

**Comment by redfrog999** [comment]
全力支持作者的努力和支持。共匪的五毛除了冒充专业人士，胡喷乱叫让人耻笑之外，也就是那点料啦。要不咋对得起砖家叫兽的荣誉称号嘛。哈哈哈。

**Comment by redfrog999** [comment]
共匪的五毛除了冒充专业人士，胡喷乱叫让人耻笑之外，也就是那点料啦。要不咋对得起砖家叫兽的荣誉称号嘛。哈哈哈。

**Comment by redfrog999** [comment]
共匪的五毛除了冒充专业人士，胡喷乱叫让人耻笑之外，也就是那点料啦。要不咋对得起砖家叫兽的荣誉称号嘛。哈哈哈。
另外，强烈建议breakwa11尽量少描述自己的生活近况和任何个人信息，所有五毛对你的攻击都会指向一个目标：尽可能多的获取你的个人信息从而对你进行威胁逼迫你放弃。一定要沉得住气，静得下心，努力推进目标就好，不用理会其他乱七八糟的五毛抹黑攻击。

**Comment by shuangzhijinghua** [comment]
不过工信部的人怎么可能会跟人家来撕逼，还是在zdfans上面呢？我看顶多就是蹭了工信部WiFi的某个键盘侠上来发的吧。

要知道人家可不会来跟你评论什么，要找直接找你本人删代码各种，不可能跟你论什么的。

David Tai <notifications@github.com>于2015年8月28日周五 上午10:18写道：

**Comment by bigoktesk** [comment]
@shuangzhijinghua 技术和对外的可能是不相干的部门,当然它们会相互配合

**Comment by farrellyang** [comment]
In my opinion , you should communicate with clowwindy about the develop trend of SS to make SS stronger.

**Comment by TearDownGFW** [comment]
@breakwa11 哈哈哈，我就是西北山沟里的，挂 HTTP 代理回个帖而已，本来想说你那个包尾部随机的算法有问题，有明显的特征，而且随机种子可被猜测，结果呢，一下子钓出你的小号以及你的水军们这么高的素质。

按你的智商，大概不会被工信部盯上，顶多就是闲的蛋疼的类似某十几岁的人来喷两句。

技术高点的人看见你的超高素质，都懒得管了

**Comment by yfdyh000** [comment]
@TearDownGFW 纯真IP库，完全匹配的才5个C段，最多255*5=1275个IP，概率真的太低。
这么巧的话，给出IP和发布页证明吧。

**Comment by TearDownGFW** [comment]
@yfdyh000 我来教教您

下载 IP 库的 txt 版，找到想要钓鱼使用的 IP 段，然后启动 nmap 进行扫描，懂了吗？

**Comment by yfdyh000** [comment]
@TearDownGFW 纯真IP库，地址反查IP，就那几个段，扫吧，我不想扫，就那么点有什么可扫的。
有漏洞就直说，就这样。

**Comment by bigoktesk** [comment]
我也觉得是工信部的爪牙的可能性更大 不过不用在意 只要做好匿名就行了用专门的帐号 用代理只访问github google twitter这些控制不到的站点 这样挺安全了 至于说技术差 那看实际的效果好了不用打嘴仗

**Comment by XhstormR** [comment]
@TearDownGFW 你要真想SS，就贡献代码；而不是在这里玩嘴皮子，勾心斗角；要我说，你还是去当狗仔队记者比较好，不要在这里浪费大家时间。

**Comment by mystical1226** [comment]
@TearDownGFW 有能耐就来贡献代码。充数贼货。

**Comment by bigoktesk** [comment]
如果是内部人士,帮忙审核代码其实也不错的

**Comment by akw28888** [comment]
沒有人強迫你必須使用這一個項目。
如果你認為這個項目的代碼不好，你可以修改並提交，或者你不要用。
人家沒幹嘛憑什麼你能批評他?

**Comment by greatdou** [comment]
感谢!

**Comment by breaking-gfw** [comment]
情人？gay??lesb?

**Comment by ljsrzc007** [comment]
注意隐蔽

**Comment by redfrog999** [comment]
这些不过是共匪五毛惯用伎俩，专门针对敢于挑战党棍，敢于打破封锁的专业人士，组织很多工科背景的五毛狗，注册多个马甲，冒充多个人，从多方面来否定你的工作，使用诸如：

1.你不行的，2.你根本就不懂，3.你的水平很差，4.你的代码有问题之类的，打击你的自信，让你对自己的工作产生怀疑，甚而否定自己的工作和专业水准，最后放弃自己着手的项目，就达到他们的目的了。

再或者从你的私生活入手，比如污蔑Phus.lu是Gay，渲染Breakwa11是谁谁情人之类的，企图摧毁你的公信力。多多观察，它们也就这几招。

以上都不管用，那就拼命收集特定目标的信息，协助公安在现实中把你找到，他们也可以分到人血馒头。所以，保护开发者个人隐私就极其重要了。五毛们吠叫什么，就由它们的主子操心好了。

**Comment by breaking-gfw** [comment]
匿名很重要，只可以说，而且必须要以最大的恶意应付党国

**Comment by Lyoko-Jeremie** [comment]
@TearDownGFW 
很简单..这里是GitHub....技术上有问题就推解决方案的Patch上来...推不上来就不要瞎BB..要B去逼乎BB去...
最烦这种什么都做不出什么都要BBB一下的键盘侠.
不管你是在工信部好还是在哪个山沟里掏泥巴..
你有能力就用代码证明自己..没有就闭嘴滚蛋.喝你妈奶去.
技术圈规则.爱玩玩不玩滚.

**Comment by wenliyang** [comment]
同意楼上的意见，没本事改进代码就闭嘴，哪儿远滚哪儿去

**Comment by ksn-cn** [comment]
@TearDownGFW SB玩意儿

**Comment by breaking-gfw** [comment]
@TearDownGFW 这么多人骂你，你就不吱声？哈哈

**Comment by TearDownGFW** [comment]
@breaking-gfw 有人嘴里喷粪，难道我还要吃进去再吐回来吗？

**Comment by ksn-cn** [comment]
@TearDownGFW  不看看自己什么德行，是你这个SB先喷的

**Comment by ksn-cn** [comment]
@TearDownGFW 有问题可以指正啊，瞎JB嘚瑟什么

**Comment by congcongwurui** [comment]
支持breakwa11,中国不缺少这些方面的专业人员，但缺少像你们这样有良知的专业人员，往大了说，你们才是中国未来的希望。希望可以坚持下去。

**Comment by breaking-gfw** [comment]
@TearDownGFW
"If you run into an asshole in the morning, you ran into an asshole. If you run into assholes all day, you're the asshole."

**Comment by breaking-gfw** [comment]
@TearDownGFW
問題是首先你彈鼻屎，結果被一群人以屎球回擊。
二，你放一下你那個代理出來給大家看看很難？
