### ISSUE TITLE
出错比例高，请解答

### ISSUE THREAD

**Issue by qinkaiyuan1982** [breakwa11/shadowsocks-rss#350]
出错比例高，请解答，linode Fremont和Dallas节点，重建过多次，结果如图，请解答，如还需提供相应材料，请告知。谢谢。
![qq 20160727092428](https://cloud.githubusercontent.com/assets/14988842/17161007/39ea893a-53dc-11e6-91ec-25b30a839173.png)

**Comment by geniusxiaoxiao** [comment]
参考此贴：https://breakwa11.blogspot.jp/2016/07/linode.html

**Comment by qinkaiyuan1982** [comment]
@geniusxiaoxiao 多谢，我去试一下。但是我的疑问是，如果不开80端口，开其他端口可以吗？80端口有待商榷啊。

**Comment by geniusxiaoxiao** [comment]
不可以，
1：这是为了伪装bing的http服务
2：目前暂80端口没有发现主动探测
所以使用80伪装http服务

**Comment by qinkaiyuan1982** [comment]
@geniusxiaoxiao 我现在没有测试80端口，因为现在状况又正常了，等再出错就试试。多谢。

**Comment by sunyh87** [comment]
运行子目录里的单用户出错比例一直保持0，运行根目录的服务器版出错比例保持40%以上，用上述方法不管用
![qq 20160808223638](https://cloud.githubusercontent.com/assets/20852855/17483437/954dab6e-5db8-11e6-900e-519308af9c89.jpg)

**Comment by geniusxiaoxiao** [comment]
我认为这是你自身网络原本就与VPS的线路链接非常差导致。
譬如ping值在300左右或者更高，另外丢包率也非常严重

**Comment by sunyh87** [comment]
那为啥运行单用户版的没有这种现象，直接PING vps 一直保持在200左右，日本的VPS。只要运行服务器版就出错比例奇高

**Comment by sunyh87** [comment]
![qq 20160809001415](https://cloud.githubusercontent.com/assets/20852855/17487185/5417e20a-5dc6-11e6-812a-1d4d64be81ab.jpg)

**Comment by geniusxiaoxiao** [comment]
贴出服务端及客户端日志。让作者看后分析回答/处理吧。

**Comment by sunyh87** [comment]
INFO: loading config from user-config.json
2016-08-10 15:42:37 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2016-08-10 15:42:37 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2016-08-10 15:42:37 INFO     db_transfer.py:131 db start server at port [1025] pass [jm7CLY] protocol [auth_sha1_compatible] obfs [tls1.2_ticket_auth_compatible]
2016-08-10 15:42:37 INFO     server_pool.py:128 starting server at [::]:1025
2016-08-10 15:42:37 INFO     server_pool.py:154 starting server at 0.0.0.0:1025

**Comment by sunyh87** [comment]
@geniusxiaoxiao @breakwa11 
客户端日志
[2016-08-10 16:12:08] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.HttpPortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2016-08-10 16:12:08] Void LogUsefulException(System.Exception)
Void PipeConnectionReceiveCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void runTryCode(System.Object)
Void ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

[2016-08-10 16:12:11] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.HttpPortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2016-08-10 16:12:11] Void LogUsefulException(System.Exception)
Void PipeConnectionReceiveCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void runTryCode(System.Object)
Void ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by breakwa11** [comment]
请使用非linode节点重试
