### ISSUE TITLE
小米路由UDP转发问题。

### ISSUE THREAD

**Issue by aqqcel** [breakwa11/shadowsocks-rss#352]
ERROR:[udp] remote_recv_bind: Address already in use

有TPROXY模块
mangle链规则如下
	ip rule add fwmark 0x01/0x01 table 100
	ip route add local 0.0.0.0/0 dev lo table 100
	iptables -t mangle -N SHADOWSOCKS
	iptables -t mangle -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
	iptables -t mangle -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
	iptables -t mangle -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
	iptables -t mangle -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
	iptables -t mangle -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
	iptables -t mangle -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
	iptables -t mangle -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
	iptables -t mangle -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
	iptables -t mangle -A PREROUTING -p udp -j SHADOWSOCKS
	iptables -t mangle -A SHADOWSOCKS -p udp -m set ! --match-set chnroute dst -j TPROXY --on-port 1081 --tproxy-mark 0x01/0x01

**Comment by BROBIRD** [comment]
> Address already in use
