### ISSUE TITLE
开启ss后使用迅雷提示下载失败

### ISSUE THREAD

**Issue by tomsux** [breakwa11/shadowsocks-rss#357]
在我开启ss后，使用迅雷精简版下载，提示下载失败，下载内容为google网站上的内容。
这个问题与端口1080无关。
改用pptp后可以使用迅雷下载。
应该是迅雷没有走ss的转发通道。

**Comment by breakwa11** [comment]
自己修改迅雷的代理设置

**Comment by tomsux** [comment]
迅雷精简版就没这个设置，还有其他方式吗

**Comment by breakwa11** [comment]
没有这个设置是你用的版本的问题，不属于SS的问题
