### ISSUE TITLE
version 3,看了wiki的多端口配置，但是Python server.py后，netstat查看了下，还是启动的1025端口和默认密码，how to fix?

### ISSUE THREAD

**Issue by StivenWang** [breakwa11/shadowsocks-rss#359]

**Comment by breakwa11** [comment]
你配置不正确

**Comment by StivenWang** [comment]
{
    "server": "x.x.x.x",
    "server_port": 23246,
    "password": "x.x.x.x",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}
不是类似这种配置吗？

**Comment by StivenWang** [comment]
卡在这里好久

**Comment by breakwa11** [comment]
配置不是只有这个，而且你这个是哪个配置文件，还有，你跑的是哪个server.py，其它配置文件呢？总之你看wiki检查配置文件
