### ISSUE TITLE
启动shadowsocks win 客户端无法使用google hangout

### ISSUE THREAD

**Issue by chenjl8** [breakwa11/shadowsocks-rss#360]
在win7 中启动shadowsocks 客户端后，连接其他google应用没有问题，但是hangout连接后没有声音和视频，只能输入文字，请问是什么原因造成的？使用全局代理也是一样的问题。

ss服务器为多用户板，前端为ss-panel 3.0

**Comment by breakwa11** [comment]
你反馈到hangout问他们为什么声音和视频不走代理

**Comment by mirokymac** [comment]
现hangout还是不走代理吗？
最近使用ssr连接，服务端为ssr最新版，客户端是Csharp版本的客户端，加密chacha20，协议auth_sha1，混淆http_simple
使用hangout 基本都是连接后3分钟断开 连接成功时音频视频都正常 暂时找不到原因

过两天抓包分析试试

**Comment by breakwa11** [comment]
@mirokymac 如果你确定是最新版本，那你客户端根本就不能用

**Comment by mirokymac** [comment]
@breakwa11 客户端不是最新版本 v4.0.3 服务端昨天pull了一次 至今使用正常

不能用是什么意思呢？ 愿闻其详

**Comment by breakwa11** [comment]
@mirokymac 那你服务端一定不是最新的

**Comment by mirokymac** [comment]
@breakwa11 我重新git一次试试
