### ISSUE TITLE
弱弱的问一句，服务器端怎么配置

### ISSUE THREAD

**Issue by idaokou** [breakwa11/shadowsocks-rss#362]
我之前是在网上随便找了个SS服务器端配置教程，在线在搬瓦工VPS上装了，并安装了加速器，现在基本可以看youtube 720p无压力。但是看@breakwa11 的说法，似乎服务器段要专门配置？求教各位，希望不吝赐教啊

**Comment by breakwa11** [comment]
我不知道你在说什么

**Comment by freedom8086** [comment]
重新装breakwa11的服务器端，下载SSR。建议你删除主机后重建，这样最干净。

**Comment by impig33** [comment]
看官方教程

**Comment by yjd** [comment]
github上就ssr写得最详细易懂。

**Comment by sanshengshi** [comment]
搬瓦工不是有一件安装吗@idaokou？你怎么安装的SSR服务器端！求教！
