### ISSUE TITLE
ShadowsocksR的PAC模式在win10周年更新后彻底的废了

### ISSUE THREAD

**Issue by ahua0734** [breakwa11/shadowsocks-rss#363]
ShadowsocksR的PAC模式在win10周年更新无法使用  只能开全局  开PAC模式win10的所有允许访问localhost的Metro程序包括Edge 都不走代理  都是只连了。。

**Comment by ahua0734** [comment]
3.8.3版本  Metro应用都是挂代理的  只有chrome 无太大影响  有时也会会打不开google的问题

**Comment by breakwa11** [comment]
这是win10的问题了吧

**Comment by ahua0734** [comment]
试过了  是系统问题  重灌了全新的IOS 后 无问题

**Comment by xbb123** [comment]
换一个PAC就可以
