### ISSUE TITLE
ssr服务端日志正常,但就是用不了

### ISSUE THREAD

**Issue by ESwordCn** [breakwa11/shadowsocks-rss#367]
![temp1](https://cloud.githubusercontent.com/assets/19360596/17441562/2bcb77c6-5b64-11e6-9081-81bea3b782b1.png)
![temp2](https://cloud.githubusercontent.com/assets/19360596/17441563/2c0ba85a-5b64-11e6-8c3e-e8acc77b0e13.png)

客户端日志显示:
无法加载 DLL“libdl.so”

**Comment by breakwa11** [comment]
服务端这个日志表示不正常
