### ISSUE TITLE
请教有关负载均衡的问题

### ISSUE THREAD

**Issue by wenliyang** [breakwa11/shadowsocks-rss#37]
同时用多个SS服务，有时候想测下速找个快的来用，就打开软件的“服务器负载均衡”
然后在“服务器连接统计”窗口中找到延迟小出错少的，关掉“服务器负载均衡”来用
但有一个问题，这时候即使取消“服务器负载均衡”选项，在“服务器连接统计”窗口中看到仍然在同时使用未被选中的服务器，即“服务器负载均衡”这个功能在打开后，除非退出软件重新运行，其实是无法关闭的么

使用的软件客户端版本是3.3.6

**Comment by wenliyang** [comment]
刚又试了下，是这种情况
例如有A、B、C、D四个服务器，先负载均衡，浏览网页一段时间，关掉负载均衡
然后先选A服务器，浏览网页，流量是走的A服务器，再选D服务器，但流量仍然是走的A服务器
即虽然切换了服务器，但仍然使用切换前的服务器

再试了下不开负载均衡，也是类似情况，选择不同服务器，但实际没切换成功，另，流量都是在“服务器连接统计”窗口中看的

**Comment by shuangzhijinghua** [comment]
要关掉浏览器才能马上切换到另一个节点，因为热切换里面还有TCP连接，没有切断是不会走另一个服务器的

wenliyang <notifications@github.com>于2015年8月28日周五 下午9:50写道：

**Comment by wenliyang** [comment]
试了一下楼上说的方法，确实，关掉浏览器重开后可以了
浏览器是用的Chrome，那这个是和浏览器有关么，而不是客户端软件问题

**Comment by shuangzhijinghua** [comment]
都是这样的，切换服务器只对新开的连接生效，原有连接不会切断，而现有的TCP连接体制就是保持TCP连接不断，一定时间之后才会超时切断连接

wenliyang <notifications@github.com>于2015年8月28日周五 下午9:54写道：

**Comment by wenliyang** [comment]
建议作者在软件说明里写一下，楼上的不说，真不知道这个

另，感谢解答

**Comment by breakwa11** [comment]
这个配置只对新建立的连接有效，现在的浏览器很喜欢重用之前的连接，如果打开的是同一连接的话。你可以使用手工方式断开，在服务器统计界面上，连接的一列，双击就行了，就断开对应节点当前所有连接，或者使用图标的右键菜单，有一个断开当前所有连接的菜单项

**Comment by wenliyang** [comment]
@breakwa11 刚看了下使用必读里的快捷操作提示，里面有写，以前看得不仔细，以后知道怎么做了，thx

**Comment by yjd** [comment]
我现在是同vps，多端口。目前选的是按次序负载均衡。
和随机哪个比较好？走的流量应该是一样的吧？

**Comment by breakwa11** [comment]
@yjd 纯随机和按次序差不多，一般应用的话，用低错误优先效果较好，如果你那里封锁问题比较严重，也可以试试定时切换

**Comment by yjd** [comment]
@breakwa11
收到，谢谢！我自己用的。都在同服务器上，原版ss开2个端口，ssR版开2个端口。
客户端连四个端口一起用。那就选低错误率了
