### ISSUE TITLE
建议：客户端的二级前置代理为空时，可做为socks服务器使用

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#373]
现在做本地代理服务器的软件不多，ssr客户端体积小使用方便，建议在二级前置代理为空的时候，ssr可以直接通过本地网关上网，并做socks服务器使用。

我爱酱妹，你们别抢！

**Comment by breakwa11** [comment]
完全不知道你在说什么

**Comment by impig33** [comment]
ssr客户端本身就是一个socks服务器，配置了ss服务器的话流量会走ss服务器。我的意思是，如果不配ss服务器或者二级前置代理为空的话，ssr客户端把流量走本地上网，对内还可以做代理服务器。

明白了筏?

**Comment by breakwa11** [comment]
不支持，你一定要这么做你可以把服务端配置在同一台机器上，或同网段的别一台机子上

**Comment by impig33** [comment]
好吧 : )
