### ISSUE TITLE
ssr ios客户端potatso连telegram无法正常刷新

### ISSUE THREAD

**Issue by yorkzhy** [breakwa11/shadowsocks-rss#374]
我用手机上的potatso连我美国用ssr协议的vps，telegram总是显示connecting，telegram规则都加上了，换原版协议用surge连同一个vps telegram可以正常刷新.
同样shadowrocket用ssr协议telegram也无法正常刷新
电脑上用ssr客户端telegram可以正常使用
ssr设置
加密:chacha20
协议:auth_sha1_v2
混淆：tls1.2_ticket_auth

**Comment by breakwa11** [comment]
这个去找potatso
