### ISSUE TITLE
求助在centos服务器上怎么做客户端的透明代理

### ISSUE THREAD

**Issue by elemaster** [breakwa11/shadowsocks-rss#377]
试了N多方法 怎么都不行- -来求助一下 在centos运行客户端 怎么把GFW网址转发到ss上

**Comment by breakwa11** [comment]
是要用ss-redir + iptables来做透明代理？

**Comment by sanshengshi** [comment]
大神！怎么用这个SSR免流？求个教程的链接🔗！谢谢！

**Comment by elemaster** [comment]
是的- -想做个透明代理

**Comment by elemaster** [comment]
使用了ss-redir 服务端提示 shell.py:50 IP 127.0.0.1 is in forbidden list, when connect to 127.0.0.1:1080 via port 10002

**Comment by breakwa11** [comment]
log说的很清楚啊，就是禁止访问127.0.0.1，你不能什么目标都转发
