### ISSUE TITLE
使用ssr多用户版时，同一端口不同密码，后登陆者无法连接。

### ISSUE THREAD

**Issue by hot36952** [breakwa11/shadowsocks-rss#379]
在必须使用同一端口时。
修改多用户配置，如：
"port_password":{
        "1234":"123456",
        "1234":"888888"
    },
当用户A使用123456登录后，可以连接网络；此时用户B使用888888登录，无法连接网络。
重启ssr服务后：
当用户B使用888888登录后，可以连接网络；此时用户A使用123456登录，无法连接网络。
请问如何处理？

**Comment by breakwa11** [comment]
这是废话，从来没有支持过单端口多用户
