### ISSUE TITLE
libd1.so

### ISSUE THREAD

**Issue by ilikecola** [breakwa11/shadowsocks-rss#382]
无法加载DLL"libd1.so"：找不到指定的模块。（异常来自 HRESULT：0x8007007E）

RSS版本：3.8.3
系统版本：Win10 （未更新一周年红石版本）
加密方式：chacha20-ietf
协议：auth_sha1
混淆：tls1.2_ticket_auth

![5v0s9_6xaye6yvm82417 q](https://cloud.githubusercontent.com/assets/12741416/17671400/6b461900-6349-11e6-997c-c9f6033dcd93.jpg)

**Comment by breakwa11** [comment]
请无视

**Comment by ilikecola** [comment]
但是无法正常连接服务器

**Comment by breakwa11** [comment]
“无法正常连接”具体是什么

**Comment by ilikecola** [comment]
HTTP测试不成功，无法透过代理打开网页
![9iu1h5pvu 6nf96 lb veso](https://cloud.githubusercontent.com/assets/12741416/17706015/fb315cc8-640c-11e6-8712-a4afa8ad6d55.png)

**Comment by breakwa11** [comment]
检查节点配置，以及更换加密方式试试
