### ISSUE TITLE
local.py运行后，无法正常进行代理连接

### ISSUE THREAD

**Issue by Acciente17** [breakwa11/shadowsocks-rss#385]
服务器端配置好以后，使用windows下的SSR软件可以正常连接，使用android下的SSR软件也可以正常连接。

在ubuntu系统下，使用local.py连接时，无法进行代理，看上去是连接超时（服务器设定timeout为60时，本地的终端中显示每1分钟发起了一次连接），此时浏览器转啊转啊什么都不会出现

服务器端改用普通的ss-libev尝试，本地改用origin协议和plain，发现结果一样

请问这是什么情况。。。

**Comment by breakwa11** [comment]
配置怎么写的

**Comment by Acciente17** [comment]
{
    "server":"我服务器的IP地址",
    "server_port":"我的服务器的监听端口",
    "password":"密码",
    "method":"chacha20",
    "protocal":"origin",
    "obfs":"plain"
}
这是我本地local.py用的配置文件。
python local.py -c config.json 以后，并无任何报错。

**Comment by breakwa11** [comment]
你居然没有写local字段配置监听地址，当然连不上

**Comment by Acciente17** [comment]
我虽然没有写，但是运行后已给出监听1080端口的提示（这不是默认端口嘛）
然后我老老实实在配置文件中加上了端口，结果一样是无法连接的。
{
"server":"我服务器的IP地址",
"server_port":"我的服务器的监听端口",
"password":"密码",
"method":"chacha20",
"protocal":"origin",
"obfs":"plain",
"localPort":"1080"
}

**Comment by breakwa11** [comment]
因为你的监听地址没有改，默认是127.0.0.1，仅本机能连接
