### ISSUE TITLE
求助mujson_mgr该怎么用,格式是怎样的

### ISSUE THREAD

**Issue by zwx1231** [breakwa11/shadowsocks-rss#388]
python mujson_mgr.py -p 8080 试了各种格式,不是报错就是没反应T^T. 用别的参数就提示我需要先-p设置端口

**Comment by breakwa11** [comment]
请直接执行python mujson_mgr.py查看帮助

**Comment by zwx1231** [comment]
不太明白应该怎样的格式设置端口

**Comment by breakwa11** [comment]
我再说一次，请直接执行python mujson_mgr.py查看帮助

**Comment by oydodo** [comment]
我也不太明白格式。。 用|分割也不行，加上了OPTION也不行

**Comment by oydodo** [comment]
帮助里面写的 python mujson_manage.py -a|-d|-e|-c|-l [OPTION]...，那后半部分-u,-k....写在OPTION的后面吗

**Comment by zwx1231** [comment]
是先输入第板块里的参数 再搭配第二板块 比如python mujson_manage.py -a -u 用户名 -p 端口发自网易邮箱大师
            在2016年09月04日 22:47，oydodo 写道:帮助里面写的 python mujson_manage.py -a|-d|-e|-c|-l [OPTION]...，那后半部分-u,-k....写在OPTION的后面吗

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/breakwa11/shadowsocks-rss","title":"breakwa11/shadowsocks-rss","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/breakwa11/shadowsocks-rss"}},"updates":{"snippets":[{"icon":"PERSON","message":"@oydodo in #388: 帮助里面写的 python mujson_manage.py -a|-d|-e|-c|-l [OPTION]...，那后半部分-u,-k....写在OPTION的后面吗"}],"action":{"name":"View Issue","url":"https://github.com/breakwa11/shadowsocks-rss/issues/388#issuecomment-244607464"}}}
