### ISSUE TITLE
ssr manyuser 多用户  执行 python server.py  之后 这样了 一直卡着 不动？

### ISSUE THREAD

**Issue by fockboom** [breakwa11/shadowsocks-rss#389]
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-08-19 00:39:33 INFO     util.py:85 loading libsodium from libsodium.so.18
/root/shadowsocks/shadowsocks/shell.py:59: UserWarning: Module shadowsocks was already imported from /root/shadowsocks/shadowsocks/__init__.pyc, but /usr/lib/python2.6/site-packages is being added to sys.path
  import pkg_resources
Shadowsocks 2.8.2
2016-08-19 00:39:33 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]

**Comment by breakwa11** [comment]
似乎是加载了不同的模块，你之前可能是手工安装了别的python包

**Comment by fockboom** [comment]
恩 我在装 ssr　manyuser  之前 安装了 shadowsocks python 和 shadowsocks libev   现在在重做 看看还会不会有这情况  .......  谢谢回复

**Comment by fockboom** [comment]
这次纯净安装  出现了： 环境 centos 6.5 32bit   nginx 1.10.1   PHP 5.6.X  MYSQL 5.5.x

执行：python server.py 卡在下面不动了... 

loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-08-19 05:22:43 INFO     util.py:85 loading libcrypto from libcrypto.so.10
Shadowsocks
2016-08-19 05:22:43 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]

**Comment by breakwa11** [comment]
你数据库配置好了吗？你数据库里有用户了吗？

**Comment by fockboom** [comment]
数据库 有一个 sspanelv3 的管理员账户   执行php xcat createAdmin 这句话创建的 然后 就用这个账号登陆的 链接不上、、、、

**Comment by breakwa11** [comment]
你这情况是没有SS用户，请自行去查user表里面的用户

**Comment by fockboom** [comment]
我看了表 一个admin  还有一个我用QQ注册的账号   然后看到2个用户 pro: orgin  obfs: plain

**Comment by breakwa11** [comment]
不，你还是没有去查看你的数据库的user表里的内容，把你user表里两个用户的所有字段信息都列出来看看

**Comment by fockboom** [comment]
谢谢作者的解答： 
................................................................................................................................................................................
我今天又重做了一次： 环境 centos 6.5 32Bit   nginx 1.10.1   php 5.6.4  mysql 5.5.x  python 2.6.6

user-config.json 配置：  


{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "m",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "rc4-md5",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}
usermysql配置：

{
    "host": "127.0.0.1",
    "port": 3306,
    "user": "root",
    "password": "mysql管理员密码",
    "db": "sspanelv3的db.sql",
    "node_id": 1,
    "transfer_mul": 1.0,
    "ssl_enable": 0,
    "ssl_ca": "",
    "ssl_cert": "",
    "ssl_key": ""
}

然后还有个设置我就把 API 改成了 sspanelv3
.......................................................................................................................................................
这是user 表中内容：

+----+-----------+---------------------------+------------------------------------------------------------------+--------+---+---+---+-----------------+------+----------+-------+--------+--------+------+--------------------+--------------------+---------------------+---------------------+------------+----------+--------+-------------+---------+-----------------+-----------+
| id | user_name | email                     | pass                                                             | passwd | t | u | d | transfer_enable | port | protocol | obfs  | switch | enable | type | last_get_gift_time | last_check_in_time | last_rest_pass_time | reg_date            | invite_num | is_admin | ref_by | expire_time | method  | is_email_verify | reg_ip    |
+----+-----------+---------------------------+------------------------------------------------------------------+--------+---+---+---+-----------------+------+----------+-------+--------+--------+------+--------------------+--------------------+---------------------+---------------------+------------+----------+--------+-------------+---------+-----------------+-----------+
|  1 | admin     | xxxxxxxxxxxxxxxxxxxxx.com | 6c03e9762415c89c64daf6773bd703073baac2710136932bef4e7421008a79c0 | 91X1e3 | 0 | 0 | 0 |      5368709120 | 1025 | origin   | plain |      1 |      1 |    1 |                  0 |                  0 |                   0 | 2016-08-20 02:24:06 |          5 |        1 |      0 |           0 | rc4-md5 |               0 | 127.0.0.1 |
+----+-----------+---------------------------+------------------------------------------------------------------+--------+---+---+---+-----------------+------+----------+-------+--------+--------+------+--------------------+--------------------+---------------------+---------------------+------------+----------+--------+-------------+---------+-----------------+-----------+
1 row in set (0.00 sec)
......................................................................................................................................................................
然后运行 python server.py

运行日志：

2016-08-19 05:22:43 INFO util.py:85 loading libcrypto from libcrypto.so.10
Shadowsocks
2016-08-19 05:22:43 INFO asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53

**Comment by breakwa11** [comment]
你更新一下再看看日志

**Comment by fockboom** [comment]
更新了 一直是这2行，我开机自启的，然后看日志，就是这2行一直未改变

2016年8月20日 23:13，"破娃酱" <notifications@github.com>写道：

**Comment by fockboom** [comment]
2016年8月20日 23:20，"肖志强" <xiaoandjack1994@gmail.com>写道：

**Comment by breakwa11** [comment]
我知道原因了，如果你在面板里没有添加节点，那么肯定会导致失败
你需要先在sspanel面板添加节点，必须在添加好后，再把面板上提供的节点id，填入你VPS的配置里
在这个地方我加上log警告提示吧

**Comment by fockboom** [comment]
谢谢，我以为节点都是后台数据库的事，前台只是显示后台...我想当然了...谢谢loli.....岗霸碟..古达塞...哦污奈哇斯基碟斯
