### ISSUE TITLE
我做了一个Ubuntu/Debian的一键安装脚本基于SS-R单用户版本

### ISSUE THREAD

**Issue by wangtongze** [breakwa11/shadowsocks-rss#39]
我做了一个Ubuntu/Debian的一键安装脚本，是基于单用户的，能帮我看看有没有需要我改进的地方吗？
https://github.com/wangtongze/ShadowsocksR-OneClick

**Comment by breakwa11** [comment]
wow，非常感谢，不过我对bash不熟悉，还要让其它人帮帮忙

**Comment by wangtongze** [comment]
有机会的话，麻烦帮我宣传宣传~~~。顺便说一下这个项目一定要加油哦，我很看好的！！

**Comment by shuangzhijinghua** [comment]
建议增加密码输入设置。

wangtongze <notifications@github.com>于2015年8月31日周一 下午3:52写道：

**Comment by breakwa11** [comment]
密码方面直接随机生成一个，安装好以后显示配置信息就好，更进一步甚至可以直接生成ss://xxxx这种链接方便剪帖板直接复制到客户端使用

**Comment by wangtongze** [comment]
@shuangzhijinghua 稍候我会添加的

**Comment by wangtongze** [comment]
@break11 最新版的脚步会在最后放出一个服务器二维码链接，后期我会让脚本把ss：//的地址也放出来

**Comment by infinilove** [comment]
看到社区这样积极，很感动

**Comment by hxdyxd** [comment]
其实自己学下linux也用不了多久。
