### ISSUE TITLE
安卓客户端开启混淆后box无法上传文件，请大家帮忙试下能否重现我的问题

### ISSUE THREAD

**Issue by qtjay** [breakwa11/shadowsocks-rss#391]
服务器是搬瓦工 洛杉矶 混淆协议是sha1-v2 +tls1.2  安卓系统是 4.2 客户端是ssr3.0.2.2 。
手机不管是nat模式还是VPN模式 box无法上传文件  
不使用混淆后 就可以正常上传使用
大家帮忙看看能否重现我的问题，谢谢

**Comment by wenliyang** [comment]
SSR 安卓客户端最新版 3.0.4.3，请升级再试

**Comment by qtjay** [comment]
@wenliyang 找不到最新版本啊？

**Comment by glzjin** [comment]
在telegram频道或者zeronet

**Comment by qtjay** [comment]
在我的手机用新版本上确实仍然 3.0.4.3无法上传。我不确定是不是我手机rom的问题，所以想问下其他人有没有相同的情况。
