### ISSUE TITLE
安卓客户端开启混淆后box无法上传文件。版本3.0.4.3

### ISSUE THREAD

**Issue by qtjay** [breakwa11/shadowsocks-rss#392]
早些时候提的issues 被关闭了。 我更新了版本还是无法上传。混淆sha1-v2+tls1.2.

**Comment by breakwa11** [comment]
新版本已经修了这个问题了，你确认了你的配置是正确的么？

**Comment by breakwa11** [comment]
而且，你如果觉得问题没解决，你应该重新打开原来的issue，并补充说明，别开一个新的issue

**Comment by breakwa11** [comment]
dup #391

**Comment by qtjay** [comment]
@breakwa11 不好意思github 还不怎么会用。

**Comment by qtjay** [comment]
@breakwa11 确认了，问题已解决。谢谢。

**Comment by breakwa11** [comment]
你怎么解决的？

**Comment by qtjay** [comment]
把网络换成电信、用新版客户端3.0.4.3 解决。 我猜测我的问题有多种因素的影响才变得很诡异，(移动的网络+酷派手机+旧版客户端)
