### ISSUE TITLE
ssl handshake timed out

### ISSUE THREAD

**Issue by qtjay** [breakwa11/shadowsocks-rss#396]
我有一台手机 酷派9976T 用原版 客户端 和 SSR客户端连接后 。点击检查网络连接会有
ssl handshake timed out 错误
访问非https 网站（不管是否被墙）都没问题
网址带https （没有被墙的）也没问题
只要网址带https （被墙）的网站全部打不开，
查ip 我已经显示是vps的ip了

而用其他手机都没问题
不知道是怎么回事。
rom 4.2.2 
linux version 3.4.39

**Comment by breakwa11** [comment]
强烈警告，使用SS不要用coolpad以及lenovo手机，内置的VPN功能有奇怪的问题

**Comment by breakwa11** [comment]
另外如果还遇到什么手机使用时有奇怪问题的，告诉我一声，部分国产手机的系统的VPN功能是残废的

**Comment by qtjay** [comment]
奇怪的是之前的都是好的，就最近才出现问题，而且刷机也没法解决。

**Comment by breakwa11** [comment]
尝试关闭UDP转发试试？

**Comment by qtjay** [comment]
试了多次发现，把网络换成电信后可以正常使用。酷派手机搭配移动网络就出问题了。

**Comment by breakwa11** [comment]
移动网络多数禁了UDP，所以请测试关闭UDP转发？

**Comment by qtjay** [comment]
UDP转发一直都是关闭状态，从来没有打开过。 为了全面测试，我等下试试在移动网络下打开UDP转发。

**Comment by windy003** [comment]
我的小米盒子也这样
