### ISSUE TITLE
作者  您好   有个问题

### ISSUE THREAD

**Issue by sunweike** [breakwa11/shadowsocks-rss#397]
一直无法解决    看了您的评论 说  防火墙问题   可是  我把防火墙都关闭了的    

还是报错     

INFO: loading config from user-config.json
2016-08-21 14:29:42 INFO     util.py:85 loading libcrypto from libcrypto.so.10
Shadowsocks 
2016-08-21 14:29:42 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
^CTraceback (most recent call last):

这个是  53端口被占用吗

**Comment by sunweike** [comment]
说明下   

我执行了这个语句          


chown -R www.www /home/wwwroot/default/
chmod 0755 /usr/local/nginx/conf/nginx.conf
chmod a+x /etc/openvpn/disconnect.sh
chmod a+x /etc/openvpn/kill
chmod a+x /etc/openvpn/login.sh
chmod 0755 /etc/openvpn/server.conf
mv /home/wwwroot/default/phpmyadmin /home/wwwroot/default/public/phpmyadmin
iptables -A INPUT -p tcp -m tcp --dport 1194 -j ACCEPT
service iptables save
service iptables restart
lnmp restart
所以我                 数据库需要加1194才可以访问的

**Comment by breakwa11** [comment]
更新服务端，重新运行，再看看log，多半是你node id设置错误

**Comment by sunweike** [comment]
是不是我   php环境没安装。。。我直接装ssr啦

**Comment by breakwa11** [comment]
我再说一次吧，请更新服务端，重新运行，再看看log，多半是你node id设置错误，另外麻烦看看wiki关于node id设置的部分

**Comment by sunweike** [comment]
node  id绝对没错的。服务端？更新有什么作用呀？不好意思。新手。问题多。带来麻烦啦。非常抱歉。


我现在网站的vps本身的线路运行十分正常

**Comment by breakwa11** [comment]
我去，给你建议你你不做，不做就算了是不是还得非要先问什么清楚作用才做啊，你如何知道“绝对没错”？如果真是错了呢？就会问问问，会不会做做做？我已经说了两次更新后再看看log，到现在你都没有更新也没有看log，我没有兴趣听你是不是新手，拿新手当成问问题的理由？
