### ISSUE TITLE
日志出现auto_block.py:62 Read hosts.deny from line 85

### ISSUE THREAD

**Issue by sunnoy** [breakwa11/shadowsocks-rss#398]
可以整成添加用户 也会分配端口  就是出现日志
auto_block.py:62 Read hosts.deny from line 85  无法连接

**Comment by sunnoy** [comment]
已解决，这个日志属于正常，发现是防火墙的锅

**Comment by lkddi** [comment]
我的centos7  下 也出现这个问题，防火墙关闭了 还是不行，求解
