### ISSUE TITLE
多用户版，用单用户方式。如何开机自启动？

### ISSUE THREAD

**Issue by cfcboy** [breakwa11/shadowsocks-rss#4]
刚试下，用教程的GIT可以开启TCP混淆。两个版本都可以。

下载的是多用户版本。没有搞MYSQL。

更改CONFIG.JSON（在一级目录）单用户可以用。启动方式是RUN.SH（在二级目录）

但是怎么添加到RC.LOCAL里面啊。我试了好多，都不行？

能不能做服务的方式，方便操作。

**Comment by breakwa11** [comment]
rc.local里面是怎么写的？

**Comment by zhangyongqi** [comment]
可以用supervisor来启动程序的

**Comment by cfcboy** [comment]
rc.local
这样写的：~/shadowsocks/shadowsocks/run.sh或nohup ~/shadowsocks/shadowsocks/run.sh
但是都不成功。
supervisord我还没有试。我试一下。
但是之前下载单用户版的，在supersord里面改成:python ~/shadowsocks/shadowsocks/server.py -c *.json，这样不行。。我试下run.sh

试了。command=~/shadowsocks/shadowsocks/run.sh，这样子不行。

**Comment by cfcboy** [comment]
我看了，run.sh里面的内容。是不是环境变量有问题？要指定文件的路径？

**Comment by cfcboy** [comment]
nohup python server.py a >> ssserver.log 2>&1 &
这里的server.py没有路径，server.py里面的内容也没有路径。
在别处调用的时候，是不是就不行了？在当前目前运行就没有问题。

**Comment by breakwa11** [comment]
更新一下，run.sh添加了设置运行路径，经测试现在正常了

**Comment by cfcboy** [comment]
我更新试下。 用哪种方式自启？rc.local或者supervisord?

**Comment by cfcboy** [comment]
感谢，更新后已经可以自启。用的是rc.local

supervisord的方式不行。

**Comment by breakwa11** [comment]
supervisord要用python /xxx/xxx/xxxx.py的方式启动

**Comment by cfcboy** [comment]
你那个教程，有点不全。对新手有些难度。希望可以添加全面一点。

**Comment by breakwa11** [comment]
当然不全，今天才刚写。。。但是写全面了又怕某些新手觉得太长，除非有什么快捷脚本，但写脚本又要考虑更多的情况

**Comment by cfcboy** [comment]
我是新手，自已弄的SH文件。感觉很快速啊。。我贴上来，你参考下。

yum install epel-release -y
yum install python-setuptools m2crypto supervisor git -y
easy_install pip
pip install cymysql

###ShadowsocksR###
git clone -b manyuser https://github.com/breakwa11/shadowsocks.git

cd shadowsocks
git pull

cd shadowsocks
chmod 777 *.sh

	cat >~/shadowsocks/config.json<<END
{
    "server":"0.0.0.0",
    "server_ipv6": "::",
    "server_port":80,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"imm",
    "timeout":300,
    "method":"aes-256-cfb",
	"fast_open":false
}
END

echo "~/shadowsocks/shadowsocks/run.sh" >> /etc/rc.local
./run.sh

iptables -I INPUT -p tcp --dport 80 -j ACCEPT
iptables -I INPUT -p udp --dport 80 -j ACCEPT
/etc/init.d/iptables save
/etc/init.d/iptables restart

**Comment by a1328788808** [comment]
大学得好好学这。
