### ISSUE TITLE
按照您的教程，搭建完单用户服务器，IP立马被封。GFW突然变得如此生猛？

### ISSUE THREAD

**Issue by BigeYoung** [breakwa11/shadowsocks-rss#400]
今天早上起来原来vultr上搭建Shadowsocks的服务器连不上去了。
就在朋友的指导下重新开了一个Shadowsocks服务器，并且使用单用户服务器教程搭建
最后一步我输入了 python server.py -p 443 -k password -m aes-256-cfb -o http_simple，密码什么都没改。
然后就没有反应了，我退出重新连接IP，发现连不上去了。
通过Ping发现整个中国大陆地区都连不上该IP了。
希望是我操作的问题...如果墙能高到这种程度那真的是太恐怖了

**Comment by breakwa11** [comment]
如果你的SSH连接没有通过别的加密代理，可能导致你的IP被墙

**Comment by lyd87880938** [comment]
IP被强了

**Comment by BigeYoung** [comment]
我再次在Vultr上创建了一个服务器，通过加密代理连接并配置ShadowsocksR，仍然是在输入密码快速运行后，提示服务器意外地断开连接。然后通过Ping.pe发现IP地址108.61.250.59在整个中国大陆境内都被封了...

**Comment by breakwa11** [comment]
不是，如果你是通过加密代理连接的话，那就不是被GFW封，是被vultr封了。。。

**Comment by Too-Naive** [comment]
不应该考虑一种情况吗...
你的那个混淆的加密方式已经被看出来了 那再次发现这种加密方式肯定是封第二次啊

**Comment by ShinoharaYuri** [comment]
昨天在vultr試了好幾個IP全被墻了
ping不通

**Comment by Too-Naive** [comment]
= =IP没有被墙
![](https://cloud.githubusercontent.com/assets/16496671/17916688/32ebbbbe-69e8-11e6-9d1e-a0f991b20c0c.png)
这是我 昨天得知的

**Comment by ShinoharaYuri** [comment]
如果這樣的話
找找在外國的朋友測試一下呢？
@Too-Naive

**Comment by azazjjyjjy** [comment]
出口故障的公告在哪里可以看到？
我也是vultr的那个IP段的，公司上海联通网络连上去很快，上海电信超时掉包80%+

**Comment by azazjjyjjy** [comment]
建议1楼把IP隐藏掉...

**Comment by Too-Naive** [comment]
@ShinoharaYuri 是国内的问题啊。。。。 国外又不能怎么样
@BigeYoung 麻烦您隐藏掉IP

**Comment by sunnoy** [comment]
443这个锅也要考虑一下，办瓦工一键就是这个端口，量太大了

**Comment by ShinoharaYuri** [comment]
@Too-Naive  
 > 是被vultr封了
我是指這句話

**Comment by Too-Naive** [comment]
@ShinoharaYuri 噢这样....其实有工具可以测试的....
但我总感觉ping.pe不靠谱

**Comment by devillaws** [comment]
最近连续两台sakura的VPS被GFW墙了，两个IP通过一些网站测试，显示出国内全部地区都PING不上，就香港台湾正常，服务器搭建的是shadowsocksmanyuser，想问@breakwa11 老师有无防止被墙的新招，难道是这边流量太大了？

**Comment by Too-Naive** [comment]
流量，密码，混淆方式，加密方式，端口 都是原因

**Comment by devillaws** [comment]
不知manyuser版本能否进行混淆，这边就是用的人比较多，想进行多用户管理限制流量跟到期时间

**Comment by Too-Naive** [comment]
用的人比较多的话就直接扔多台服务器上嘛...
据我所知 如果某个服务器流量特别大 肯定会触发预警(而且是新的服务器)
混淆方式肯定是有的吧不过好像只能用同一种？

**Comment by ShinoharaYuri** [comment]
@Too-Naive  每個端口可以單獨設置的

**Comment by Too-Naive** [comment]
我知道……但是数据库版？

On Aug 30, 2016 7:07 PM, ShinoharaYuri <notifications@github.com> wrote:

@Too-Naive<https://github.com/Too-Naive> 每個端口可以單獨設置的

**Comment by ShinoharaYuri** [comment]
貌似前段不支持？

**Comment by Too-Naive** [comment]
不懂 反正多端口可以我知道

On Aug 30, 2016 9:07 PM, ShinoharaYuri <notifications@github.com> wrote:

貌似前段不支持？

**Comment by breakwa11** [comment]
可以独立设置，但sspanelv3面板还没做完相关功能
