### ISSUE TITLE
希望白名单模式采取gfw_domain_whitelist的内容

### ISSUE THREAD

**Issue by czmecho** [breakwa11/shadowsocks-rss#402]
先感谢你的开发，这里我只有一点不成熟的小建议。
我对比了 [gfw_domain_whitelist](https://github.com/R0uter/gfw_domain_whitelist)白名单的内容，和你的SSR内置白名单内容，发现对方的更完善。希望SSR内置的也可以是更完善的白名单。

**Comment by yjd** [comment]
前面再加个cow吧。

**Comment by lbp0200** [comment]
https://github.com/blackgear/mono_pac
