### ISSUE TITLE
希望有人能做个级联的功能，如果有的话，有没有大神教我一下

### ISSUE THREAD

**Issue by loveyanbei** [breakwa11/shadowsocks-rss#407]
某个网络环境，inode拨号上网，只允许无线连接特定的热点，检测到了其他的interface立马断网，因此心生一计。

手头有有个三星平板刷了5.0系统，5.0有adb reverse反向映射端口功能，因此共享网络方法如下：
S1:安装android sdk platform tools（最新版）
S2:adb reverse tcp:port_android tcp:ssserver
S3:交叉编译ss-libev并且静态编译ssl到android设备，push到/data/local/tmp/
S4:执行 /data/local/tmp/ss-local -k pass -m table -s 127.0.0.1:port_android -l 1080 -b 0.0.0.0
S5:打开板子的热点，电脑连上，chrome设置代理上网

但是这样问题来了：这个ssserver不能翻墙！在命令里面也没有找到能级联的选项，求各位大神指导。

**Comment by breakwa11** [comment]
其实我还不明白你要干什么。。。

**Comment by loveyanbei** [comment]
@breakwa11
好吧，国家电网里面有个内网检查然而我是天天用npm maven sbt这种的，没网会蛋疼，办公室有一个能上网的机器，但是这个机器的东西会禁止你添加任何网卡，所以我就想出了这个路子。然而这个东西没法跳到我在vultr的server，这样是不能翻墙的

**Comment by loveyanbei** [comment]
@breakwa11
这个ssserver运行在一个墙内机器上面，不能翻出gfw。
我用了个ssserver在那个能上网的机器做了代理，然后用adb把代理端口走usb线传递给手机，比如ssserver监听电脑9999，adb把这个端口映射到手机的8888，手机上面开一个sslocal连接被映射的端口，暴露给局域网，这样就能让我的机器通过这个代理绕过检查，因为他们只检查有没有加网卡啊。

**Comment by loveyanbei** [comment]
请妹子原谅我zz的表达orz

**Comment by breakwa11** [comment]
你搞得太复杂了吧？能上网的那台机器开个端口转发，例如把本地1080转发到VPS上的SS端口，然后手机填写SS的时候，只要把服务器地址写为你那台机器的地址和1080端口不就好了

**Comment by loveyanbei** [comment]
@breakwa11
并不是手机去连，手机只是转发工具而已，这边有安全检查，电脑的无线网卡只能用做上外网拨号，任何其他网卡接入都会逃不过检查把网络断开。
我这个操作相当于把ssserver在电脑的监听端口映射手机上了，问题在于adb的监听只监听127.0.0.1，需要sslocal把它变成0.0.0.0，这就是我为啥不映射电脑的sslocal....能的话我肯定搞了。安卓的adbd只bind到127.0.0.1

**Comment by loveyanbei** [comment]
@breakwa11 安卓上面也不好搞ssh的端口转发，自己交叉编译的sshd/ssh没有主机密钥，ssh不能登录，也不太会配置，别人配置好的要钱，可是我也付不到啊，谷歌市场我去哪付钱（哭

**Comment by breakwa11** [comment]
我依然不清楚你到底打算怎么连接，到底网络有什么限制

**Comment by loveyanbei** [comment]
@breakwa11
理想的链条是：上网机 Server A -->一般网站

上网机 Server B --> Server C on vps -->不好上的网站

但是似乎没发这么配置呢

**Comment by loveyanbei** [comment]
如果可以直接转发socks5 那么就是 上网机 local --> server on vps -->不好上的网站
。那样的话在上网机开sslocal，然后把socks5映射给手机，这样连接手机热点的电脑可以走这个socks5，但是问题在于，adb reverse映射给手机的端口都bind在127.0.0.1，连接热点的机器不能看到啊

**Comment by loveyanbei** [comment]
![image](https://cloud.githubusercontent.com/assets/7147471/17957048/ff9947f2-6ac0-11e6-9d76-1d2eefc73ae5.jpeg)
你看这个，8888是电脑ssserver映射过来的，bind在127.0.0.1，无法改变，要不然我也不会在本地再编一个libev的locall了啊，那个sslocal就是为了把bind改到0.0.0.0，你看到那个1080没有，那个就是local的socks5

**Comment by loveyanbei** [comment]
似乎有办法了，shadowsockswindows的本地socks端口配合polipo转成http，但是不知为什么我的ss突然死亡了，症状是windows客户端突然100%出错，ios端正常，看起来像是抽风。

**Comment by guozixi** [comment]
SSRWindows端的设置里有个选项是允许来自局域网的连接，只要这个上网机和内网是通的就好办

**Comment by breakwa11** [comment]
不好意思，我还是没法理解你到底怎么连接的网络，到底有什么限制，而不是想知道你为什么要这么连接
你写的什么上网机 Server ABC都没有连在一起，完全不懂你表达什么

**Comment by loveyanbei** [comment]
@breakwa11 usb tunnel啊，利用usb线走手机绕开主机上检查软件的限制，然后手机把网络散出去，只是说bind地址造成了点问题，另外一个翻墙软件v2ray的两端就允许级联发送。
server B应该叫local B（汗
嘛问题算是解决了，上了v2ray车
