### ISSUE TITLE
建议支持动态端口连接

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#408]
最近明显封端口比较严重，一个端口流量稍大一点几分钟就不行了。

建议这样：
1.服务器指定一个动态端口范围，比如10000-11000、13579-24678 ... 可多个
2.客户端初次连接后，由服务器指定此次连接时间，比如5分钟，达到5分钟客户端自动断开换端口连接，到下一步。
3.客户端初次连接上后，会获取到多个下一次连接的端口号。比如3-5个，由客户端随机连接其中一个。

酱妹觉得怎么样?

**Comment by breakwa11** [comment]
暂不打算支持此功能，你可以自己在服务器开10个端口，然后客户端使用“按次序”的负载均衡策略

**Comment by yjd** [comment]
@breakwa11 接这里问下，ssr客户端怎么设置监听0.0.0.0。搜到一篇是用了netsh端口重定向。
目的挂到局域网服务器上，方便其他人用。省去每台开客户端。只需配置下浏览器

**Comment by yjd** [comment]
可以试下v2ray+kcp

**Comment by breakwa11** [comment]
@yjd 开局域网共享不就好了

**Comment by yjd** [comment]
@breakwa11 谢了，明白了。
