### ISSUE TITLE
SSR近期疑似屏蔽加强

### ISSUE THREAD

**Issue by blackfoxsar** [breakwa11/shadowsocks-rss#409]
RT 关注了这个项目后最近看到有几位仁兄都反映有这个问题，我这边也是遇到了相似的情况

现象就是，运行后的前半分钟还算正常，然后突然就超时
jp-tokyo (IP:PORT) timed out
再然后测试了一下发现这个IP在我所在的省内已经全部连不上了（PING都是TIMED OUT）
等待半小时后又恢复
已经跟机房确认过了对方网络没有问题，而且我也用PING工具证实只有我所在的地区（山东省）当时是上不去的
最神奇的是，如果我持续的PING/HTTP/SSH访问，都是正常的，为了测试，我连上服务器后开了一个MTR后盯着画面，然后再次切到SS直连的话，不到半分钟所有连接全部被切断，而同C段的其它IP均可以正常访问。
另外一个测试就是，我把我的服务器SSR STOP后，把tengine的端口从80指向了SSR之前常用的端口，然后去访问，发现并不会有任何问题。由此推断只可能是屏蔽的技术上有了加强
我个人的电脑只有一个windows defender，没有任何三方安全软件、管家类工具，SSR混淆开与否、更换端口、密码（本身密码就是随机生成的）、加密方式，均会出现这个情况。

**Comment by Neilpang** [comment]
JFYI,  我用原版 2.5.6,  原ss 协议, 没有任何问题.

**Comment by blackfoxsar** [comment]
@Neilpang 我更怀疑可能是地区性问题，某个地区/某个宽带运营商会管的严一点或者松一点

**Comment by guozixi** [comment]
我这里也被屏蔽，测试发现其他省市的ping都是正常的，唯独我这里ping不通、SSR连接不上，甚至这个VPS上原有的网站也打不开(HTTPS)

**Comment by guozixi** [comment]
昨天晚上开始ping不通，一直到现在也没恢复。只能联系主机商申请换IP了

**Comment by guozixi** [comment]
@blackfoxsar 很有可能

**Comment by guozixi** [comment]
开启 UDP Over TCP 试一试，我这里在没换IP的情况下暂时正常了。

**Comment by hyxxsfwy** [comment]
最近移动宽带也遇上了，SSR 连不上，用原版协议就没有任何问题，我觉得是 http-simple 混淆的锅。

**Comment by breakwa11** [comment]
@hyxxsfwy 我觉得是不是需要wiki写清楚一点，如果你原版协议能连，混淆连不上，请先联系你的服务商确定是不是改了其它的兼容混淆，因为改了混淆而你没改，而只确定能用原版，然后把锅甩给SSR，这情况我已经遇到N次了，这让我很为难

**Comment by breakwa11** [comment]
而且既然 `混淆开与否、更换端口、密码、加密方式，均会出现这个情况` ，那锅不在SSR上
