### ISSUE TITLE
改用 privoxy 之后，协议从 socks5 变为 http 吗？

### ISSUE THREAD

**Issue by dgeibi** [breakwa11/shadowsocks-rss#41]
平台：Windows 10，Chrome stable
还是因为我开过一次“允许来自局域网的连接”
之前 SwitchyOmega 下设置协议为 socks5 是可用的，但现在出现
 failed to recv data in handshakeReceive2Callback
协议改成 http 又可用了

**Comment by breakwa11** [comment]
你设置的什么端口？这个情况感觉有点怪怪的，有更具体的信息么

**Comment by dgeibi** [comment]
之前用 ss 开过一次“允许来自局域网的连接”，出问题了，换 ssr 还是一样，1080

**Comment by dgeibi** [comment]
而且 系统代理 都是正常的

**Comment by falseen** [comment]
我这边http和socks都可以，设置哪个都可以用。一直都是这样。

**Comment by breakwa11** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/557

**Comment by dgeibi** [comment]
果然卸掉迅雷后就正常了
