### ISSUE TITLE
tls1.2_ticket_auth 疑似被重点关注

### ISSUE THREAD

**Issue by nqzhang** [breakwa11/shadowsocks-rss#413]
用tls1.2_ticket_auth 加密的时候 经常能连然后中断一会 过会就好了
换到http_simple后一切正常 并且延迟降低了..

**Comment by breakwa11** [comment]
这不是重点关注，这是典型的tls的临时性干扰，也可能和你的VPS是哪里有关，你的是哪个商家的VPS？

**Comment by nqzhang** [comment]
do 新加坡 和台湾 v.center 都有发现

**Comment by breakwa11** [comment]
如果是这种，目前似乎唯一只有80端口跑http_simple能坚持较长的时间

**Comment by nqzhang** [comment]
好吧
