### ISSUE TITLE
请问，有没有可以限制用户单端口单人IP使用的功能？

### ISSUE THREAD

**Issue by i0ffer** [breakwa11/shadowsocks-rss#415]
首先膜拜一下大大_(:з」∠)_

我用的是单用户版，然后共享给朋友使用的
请问，有没有一个后端功能，可以限制用户，单个用户，只能使用单个端口
并且这个端口，只能同时由一个IP登陆呢？
准确的说，意思就是不想让两个以上的用户，共用一个端口和密码来上网
防止用户在不经我允许的情况下，擅自给多人共享

有没有什么功能，可以实现这个额……

**Comment by yjd** [comment]
没这功能。多用户版是按限制流量

**Comment by breakwa11** [comment]
使用auth_sha1或auth_sha1_v2协议（不能使用兼容），协议参数写最大同时客户端数量即可，例如写1，就是最多同时1个客户端使用（不按IP计算，只按客户端数据计算）

**Comment by i0ffer** [comment]
"timeout": 300,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "auth_sha1",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false

这部分，我该在哪个地方填1，才能达到1个客户端使用的效果？

**Comment by i0ffer** [comment]
问题2：这个参数，如果填写了3，是这台服务器最大只允许3个客户端登陆啊。还是单个端口只允许3个客户端？我这个服务器，设置了很多端口和配套密码的。

**Comment by breakwa11** [comment]
protocol_param是协议参数，针对的是单个端口
