### ISSUE TITLE
打开Google Drive编辑文档，一分钟左右开始断连

### ISSUE THREAD

**Issue by ffspace810** [breakwa11/shadowsocks-rss#416]
服务端有六台节点，还试过一些ss商家提供的免费帐号（ssr服务端支持插件），只要用ssr客户端打开Google Drive的文档，过一分钟左右页面上会提示正在尝试连接，文档无法继续编辑。原版ss3.0没有遇到这个问题。可否能查到具体原因？

**Comment by breakwa11** [comment]
客户端版本号？你原版倒说版本号啊。。。。。

**Comment by ffspace810** [comment]
不好意思，忘说了，ssr是最新版3.8.5.2，旧版本也有这个问题。

**Comment by breakwa11** [comment]
你在客户端有设置超时时间吗？或者开了负载均衡？

**Comment by ffspace810** [comment]
超时时间没找到设置的地方，是gui-config中的keepVisitTime和privoxy中的keep-alive-timeout这两个地方吗？没有做过改动。负载均衡关闭后试了一下还是一样。

**Comment by breakwa11** [comment]
不，是在选项设置里，空闲断开秒数

**Comment by ffspace810** [comment]
空闲断开秒数是0

**Comment by breakwa11** [comment]
你在浏览器里按一下F12，查看一下网络连接情况，看显示连接中的时候连接的什么

**Comment by ffspace810** [comment]
Request URL:https://0.docs.google.com/a/uworks.cc/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AEjpqHmoaJvITgCDzK3M/xdbcm.html?internal=false&gcp=%7B%22qlc%22%3Anull%2C%22elh%22%3Afalse%2C%22eoo%22%3Atrue%7D&rt=j&xpc=%7B%22cn%22%3A%22docs%22%2C%22tp%22%3A1%2C%22osh%22%3Atrue%2C%22ppu%22%3A%22https%3A%2F%2Fdocs.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.docs.google.com%2Frobots.txt%22%7D
Request Headers
Provisional headers are shown
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer:https://docs.google.com/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AEjpqHmoaJvITgCDzK3M/edit
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 LBBROWSER
Query String Parameters
view source
view URL encoded
internal:false
gcp:{"qlc":null,"elh":false,"eoo":true}
rt:j
xpc:{"cn":"docs","tp":1,"osh":true,"ppu":"https://docs.google.com/robots.txt","lpu":"https://0.docs.google.com/robots.txt"}




GET https://0.docs.google.com/a/uworks.cc/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AE…txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.docs.google.com%2Frobots.txt%22%7D net::ERR_TUNNEL_CONNECTION_FAILED(anonymous function) @ /static/document/client/js/812891867-kix_main_i18n_kix_app__zh_cn.js:1092c @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2056
VM638 data:text/html,chromewebdata:3921 Uncaught TypeError: loadTimeData.createJsEvalContext is not a function(anonymous function) @ VM638 data:text/html,chromewebdata:3921


不知道我拷的信息对不对。。

**Comment by ffspace810** [comment]
我把ss共享给局域网，同事设置好代理以后，也有一样的问题。

**Comment by breakwa11** [comment]
我自己测试的时候连接的是3.docs.google.com，没有遇到问题，还有另一网友遇到问题的同样是0.docs.google.com

**Comment by ffspace810** [comment]
(,,•́ . •̀,,)咋整

**Comment by ffspace810** [comment]
我自己的节点是linode美国和日本服务器，试过的免费ss的节点不清楚是哪里的服务器。

**Comment by breakwa11** [comment]
不对，这里你给的是连接成功的请求，有没有连接失败的？

**Comment by ffspace810** [comment]
这是consloe的信息：

he key "minimum-scale:1.0" is not recognized and ignored.
edit:1The key "maximum-scale:1.0" is not recognized and ignored.
edit:4GET chrome-extension://ghbmnnjooekpmoecnnnilnnbdlolhkhi/page_embed_script.js net::ERR_FAILED
 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)
3797523062-kix_main_i18n_kix_core__zh_cn.js:517 Blocked script execution in 'https://docs.google.com/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AEjpqHmoaJvITgCDzK3M/edit' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.$Ca @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:517lrb.O @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:1885(anonymous function) @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:107lrb.initialize @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:1884uwb @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:1993ywb @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2055cxb @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2070w.VHa @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2070Jl._createKixApplication @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2074KX_startKix @ edit:12(anonymous function) @ edit:12
/static/document/client/js/812891867-kix_main_i18n_kix_app__zh_cn.js:1092 GET https://0.docs.google.com/a/uworks.cc/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AE…txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.docs.google.com%2Frobots.txt%22%7D net::ERR_TUNNEL_CONNECTION_FAILED(anonymous function) @ /static/document/client/js/812891867-kix_main_i18n_kix_app__zh_cn.js:1092c @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2056
VM636 data:text/html,chromewebdata:3921 Uncaught TypeError: loadTimeData.createJsEvalContext is not a function(anonymous function) @ VM636 data:text/html,chromewebdata:3921
/static/document/client/js/812891867-kix_main_i18n_kix_app__zh_cn.js:1092 GET https://0.docs.google.com/a/uworks.cc/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AE…txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.docs.google.com%2Frobots.txt%22%7D net::ERR_TUNNEL_CONNECTION_FAILED(anonymous function) @ /static/document/client/js/812891867-kix_main_i18n_kix_app__zh_cn.js:1092c @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2056
VM636 data:text/html,chromewebdata:3921 Uncaught TypeError: loadTimeData.createJsEvalContext is not a function(anonymous function) @ VM636 data:text/html,chromewebdata:3921
/static/document/client/js/812891867-kix_main_i18n_kix_app__zh_cn.js:1092 GET https://0.docs.google.com/a/uworks.cc/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AE…txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.docs.google.com%2Frobots.txt%22%7D net::ERR_TUNNEL_CONNECTION_FAILED(anonymous function) @ /static/document/client/js/812891867-kix_main_i18n_kix_app__zh_cn.js:1092c @ 3797523062-kix_main_i18n_kix_core__zh_cn.js:2056
VM636 data:text/html,chromewebdata:3921 Uncaught TypeError: loadTimeData.createJsEvalContext is not a function(anonymous function) @ VM636 data:text/html,chromewebdata:3921

**Comment by ffspace810** [comment]
https://0.docs.google.com/a/uworks.cc/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AEjpqHmoaJvITgCDzK3M/xdbcm.html?internal=false&gcp=%7B%22qlc%22%3Anull%2C%22elh%22%3Afalse%2C%22eoo%22%3Atrue%7D&rt=j&xpc=%7B%22cn%22%3A%22docs%22%2C%22tp%22%3A1%2C%22osh%22%3Atrue%2C%22ppu%22%3A%22https%3A%2F%2Fdocs.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.docs.google.com%2Frobots.txt%22%7D

这个请求失败，失败信息：

Request URL:https://0.docs.google.com/a/uworks.cc/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AEjpqHmoaJvITgCDzK3M/xdbcm.html?internal=false&gcp=%7B%22qlc%22%3Anull%2C%22elh%22%3Afalse%2C%22eoo%22%3Atrue%7D&rt=j&xpc=%7B%22cn%22%3A%22docs%22%2C%22tp%22%3A1%2C%22osh%22%3Atrue%2C%22ppu%22%3A%22https%3A%2F%2Fdocs.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.docs.google.com%2Frobots.txt%22%7D
Request Headers
Provisional headers are shown
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer:https://docs.google.com/document/d/1VRyvg0zO_Ot0lnP8R4p7GC7AEjpqHmoaJvITgCDzK3M/edit
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 LBBROWSER
Query String Parameters
view source
view URL encoded
internal:false
gcp:{"qlc":null,"elh":false,"eoo":true}
rt:j
xpc:{"cn":"docs","tp":1,"osh":true,"ppu":"https://docs.google.com/robots.txt","lpu":"https://0.docs.google.com/robots.txt"}

**Comment by ffspace810** [comment]
我用的是公司的域名邮箱，是gmail提供的服务。

**Comment by breakwa11** [comment]
服务器的DNS是多少？

**Comment by ffspace810** [comment]
linode默认的：
domain members.linode.com
search members.linode.com
nameserver 106.186.116.5
nameserver 106.186.123.5
nameserver 106.186.124.5
nameserver 106.187.90.5
nameserver 106.187.93.5
nameserver 106.187.94.5
nameserver 106.187.95.5
nameserver 106.187.34.20
nameserver 106.187.35.20
nameserver 106.187.36.20
options rotate

**Comment by breakwa11** [comment]
你加个[dns.conf](https://github.com/breakwa11/shadowsocks-rss/wiki/Custom-DNS)写上8.8.8.8试试？

**Comment by ffspace810** [comment]
试了一下8.8.8.8，没有成功。

**Comment by breakwa11** [comment]
我测试了一下，终于知道怎么重现了，用chrome使用http代理会出现这个问题

**Comment by ffspace810** [comment]
我用IE还是有这个问题。。系统是win10

**Comment by breakwa11** [comment]
问题已解决，等下个版本就好

**Comment by ffspace810** [comment]
啊。。。什么时候出新版本。。。（渴望的眼神）

**Comment by ffspace810** [comment]
着急用。。。

**Comment by breakwa11** [comment]
你用chrome设置使用socks5代理，而不要使用http代理，可以临时解决这个问题

**Comment by ffspace810** [comment]
ok 我先用着，辛苦

**Comment by breakwa11** [comment]
已解决
