### ISSUE TITLE
求各位大神指教，我想在服务器上运行ss客户端，然后远程设备使用此服务

### ISSUE THREAD

**Issue by tonyzzp** [breakwa11/shadowsocks-rss#417]
我在自己电脑上运行，然后局域网内的其他设备也可以使用我电脑上的代理。
但在服务器上运行就不行，是什么原因呢？

防火墙设置没有问题。
在远程电脑上使用telnet也能连上服务器的1080端口，但是访问xxx:1080/pac浏览器提示未返回任何数据。

**Comment by breakwa11** [comment]
客户端不允许公网IP连接到客户端，除非指定用户名密码

**Comment by tonyzzp** [comment]
设置密码后是可以了。  但是好像不能用pac了?

**Comment by tonyzzp** [comment]
可以是可以了。但手机上只有浏览器可以。别的软件都不行。 哎。。。

**Comment by breakwa11** [comment]
因为只有浏览器支持密码验证，而且我搞不懂你为什么这么做，服务器上运行客户端是非常糟糕的做法

**Comment by tonyzzp** [comment]
我要在chromebook上用啊。 我本来是在chrome里安装插件使用vpn的，这样是可以。但仅对chrome有效，对系统内的其他程序是无效的。  只有在wifi里面设置代理才对整个系统有效。
我试过在我自己电脑上运行ss，然后给chromebook设置代理，这样是可以的。 但我总不能一直开着2台电脑啊，所以就想了这招。 

昨天我试着再另装了个x-wall配合ss使用，这样也是可以的。  但也都只能是全局代理。

**Comment by tonyzzp** [comment]
好像只要设置代理，所以的请求都会走代理，不能像ss一样设置白名单？

**Comment by breakwa11** [comment]
pac必须是127.0.0.1或内网才能访问，因为这不支持带密码

**Comment by breakwa11** [comment]
不过你可以本地开一个客户端，然后对PAC地址加参数来实现指定代理地址，如：
http://127.0.0.1:1080/pac?ip=192.168.0.100&port=8899&type=s5

**Comment by tonyzzp** [comment]
地址加参数？  这个我没听懂，怎么搞？
