### ISSUE TITLE
Shadowsocks主动探测代码

### ISSUE THREAD

**Issue by breakwa11** [breakwa11/shadowsocks-rss#42]
https://gist.github.com/breakwa11/069f6bf379aa84d89fa0

根据[#38](https://github.com/breakwa11/shadowsocks-rss/issues/38)用python编写，实现与文章略有差别
成功率目前看来相当高，如果探测失败，可以尝试修改后面的att_data
如有什么问题请轻喷

----------------
2015-09-12 13:50 GMT+8
补充一些简要说明，代码中：
`scan(16, "192.168.0.100", 8898, "\x2a"*6, "\x05"*6)`
表示以iv长度为16（适用于rc4-md5/所有aes），目标服务器IP 192.168.0.100，服务器端口8898
使用的扫描攻击字符串为`"\x2a"*6`，第二次确认攻击字符串为`"\x05"*6`，两个字符串必须不能一样
如果失败，那么随机修改以上两个字符串，只要保证其长度为6字节即可

如果服务器延迟不太大，那么正确判断的成功率非常高，任何安装了python的朋友均可复现。目前已有其它网友运行以上代码探测成功（需要目标为原版服务器）

另正在根据之前的讨论正在研究混淆响应接口，到时候可以让每个服务器在遇到错误的协议头的时候，不同的服务器可以有不同的响应

**Comment by falseen** [comment]
链接打不开，证书错误。

**Comment by breakwa11** [comment]
@falseen 你的DNS被劫持了吧？

**Comment by Qixingchen** [comment]
。。。你Github打不开在这回issue干嘛。。

2015-09-01 18:12 GMT+08:00 Falseen <notifications@github.com>:

**Comment by falseen** [comment]
翻墙之后可以打开了。我用的手机，可能是这个原因。

**Comment by mveplus** [comment]
@falseen 一样的， 链接打不开，证书错误。
```
fatal: unable to access 'https://gist.github.com/069f6bf379aa84d89fa0/': SSL certificate problem: Invalid certificate chain
abort: error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
fatal: unable to access 'https://gist.github.com/069f6bf379aa84d89fa0/': SSL certificate problem: Invalid certificate chain
svn: E175002: Unable to connect to a repository at URL 'https://gist.github.com/069f6bf379aa84d89fa0'
svn: E175002: OPTIONS of 'https://gist.github.com/069f6bf379aa84d89fa0': Server certificate was missing commonName attribute in subject name (https://gist.github.com)
```

So I fork it...

**Comment by yeahwu** [comment]
你们都是在什么鬼地方，这边免翻墙秒开！浙江

**Comment by yeahwu** [comment]
链接没有问题，免翻墙，秒开。

**Comment by mountainguan** [comment]
昨晚打开没问题，今天就打不开了

**Comment by librehat** [comment]
一个简单处理就可以让这个探测脚本无效了，地址头错误就返回一个随机字串。

在libQtShadowsocks的实现如： https://github.com/librehat/libQtShadowsocks/commit/720d3f394568629d7f1e37cbc69026beb6d9306f
repo主还是有心了，琢磨出这个特征。

**Comment by breakwa11** [comment]
@librehat 没错的，代码目前仅针对python版的服务端，调整过行为自然会导致原检测代码失效。但不幸的是你的返回随机串的方式会导致更容易主动探测，所以这种做法虽然有人提议，但我目前没有打算采纳。相信你仔细想清楚后你也能写出攻破你自己的实现的代码

**Comment by librehat** [comment]
@breakwa11 随机串的长度也是随机的，并没有什么明显特征，再不济返回一个静态HTTP页面或者重定向也都是办法。而你添加所谓混淆头的办法特征才是最明显的。

**Comment by breakwa11** [comment]
@librehat 有没有明显特征不是想当然的，我前面说过，可以直接通过写代码来识别，python版实现其实只有ipv4那个可以利用，你这个反而256个一里面一定能利用3个，降低了识别难度，因为如果正确匹配了，那么期待反应应该是立即断开连接，或连接超时，或连接了但什么都不动，不管哪种都是无立即返回的数据。而你实现为错了就返回数据，分明告诉探测的客户端说头部是错的

**Comment by librehat** [comment]
@breakwa11 你这是代入了服务器一定是Shadowsocks的前提，对于其他Web应用呢？显然对于你发送的这一些“乱码”，服务器也是会回应的。而且头部正确立即断开连接的前提是地址长度不正确。当然你可以说256位都穷举然后会发现有三位会出现连接成功的特征，所以这个办法还是要和auto ban结合，记录反复地址头错误的IP并且屏蔽。但是这对GFW并没有什么用，因为GFW可以用大量IP来进行穷举。

不用随机串，改用你的混淆头，请问高明在哪里？我还是真没看出来。

**Comment by librehat** [comment]
不过你说的另外253个全部返回随机数据确实也是一个特征，所以我又改进了，现在是 随机按照随机概率，返回随机长度的随机数据

https://github.com/librehat/libQtShadowsocks/commit/11fc564a9186b1211fe15636b3c23476df2c0d36

**Comment by breakwa11** [comment]
@libre 高不高明根本不是“看”出来的，还是那句，用代码说话，看你能不能写出代码，成功识别。正如你之前说的方案，我把如何攻击说出来，直接导致你更改代码实现，于是这个实现就不“高明”。例如libev版实现了抗iv重放攻击，依然存在攻击手段精准识别这是libev版ss服务端，只是代价稍大一些。所以说要是你觉得不“高明”，那讲讲你怎么识别出来吧

**Comment by breakwa11** [comment]
@librehat 对于你新修改的代码，我刚才看了一下，我只能说太想当然了，原攻击手段略修改一下依旧精准识别，这样没用的

**Comment by breakwa11** [comment]
@librehat 你那个issue不要急着搞，如果有新想法先发个邮件给我吧，或者发推也行，避免做无用功

**Comment by xxnet** [comment]
大家进入到实质技术探讨的阶段了。

说说我在老外维护的项目里感受到的一些体会，希望对大家有帮助。
   在讨论前，会非常注重礼貌，比如感谢、请。
   对自己说的话，非常保守，比如：个人怀疑、猜测、目前认为。。。
   从原则上说，就是尽量不冒犯人。

   因为本身探讨就是寻求思想的碰撞，但要大家都互相尊重。


不管如何，一切开始往好的方向走，值得庆贺！

2015-09-04 7:32 GMT+08:00 breakwa11 <notifications@github.com>:

**Comment by Adolf-L** [comment]
你们交流的这么火热，能不能给点资源让我们好进入你们的话题
