### ISSUE TITLE
V2有一些奇怪现象

### ISSUE THREAD

**Issue by lingaoyi** [breakwa11/shadowsocks-rss#420]
用上V2，明显V2速度比没有V2的快，但一些纠结是，打开FB，有时候FB图无法显示，但刷新一下又可以打开，然后打开Tweetbot提示无法连接，但刷新又是可以刷新，打开YouTube一些视频是没速度，然后刷下一下页面又可以了。

**Comment by breakwa11** [comment]
什么客户端啊
