### ISSUE TITLE
Help! config a domain as ssserver address, the domain got hijacked!

### ISSUE THREAD

**Issue by yeweishuai** [breakwa11/shadowsocks-rss#421]
Hi guys, I configured a domain name as my ss client server address, it works fine for a few months, but recently, I found the domain was hijacked!
I ping my domain, and got a strange ip 8.7.198.45, which is different from the ip I set in my domain provider!

After I reconfigure the ssserver address with my correct ip instead of the domain name, it works fine.

So, please help, I was wondering, if ssclinet should resolve the configured server domain address on ssserver!!!!

**Comment by breakwa11** [comment]
it resolve ss server address with local DNS

**Comment by breakwa11** [comment]
but you can custom DNS to resolve the server address
