### ISSUE TITLE
facebook上传视频错误，而原版SS却没有这种问题

### ISSUE THREAD

**Issue by bingowrt** [breakwa11/shadowsocks-rss#422]
我尝试在同一个服务器上上出facebook 视频，SS-RSS会出现未知错误，其他所有网站都没有问题。用的是AUth_sha1_v2和http-simple,并且设置了混淆参数

**Comment by breakwa11** [comment]
什么客户端及版本？（为什么每个人都要我问一遍

**Comment by breakwa11** [comment]
已N天无反馈，请自行更新到最新版本
