### ISSUE TITLE
[BUG] 无法使用 feedly 客户端

### ISSUE THREAD

**Issue by ToutyRater** [breakwa11/shadowsocks-rss#423]
版本：3.0.4.3
手机：Android 6.0.1
问题：
当 SSR 开全局时 feedly 客户端（一个 RSS 阅读器）无法连接网络，即 feedly 通过 SSR 代理无法连接网络，提示超时。
![photo_2016-08-31_23-17-39](https://cloud.githubusercontent.com/assets/20978410/18134503/1e64b636-6f8e-11e6-9d1c-63b796fc2258.jpg)
说一下我的测试过程及结果：
- 使用 SSR 客户端，有混淆，有协议插件，测试了美国、新加坡、日本、香港的 vps，feedly 均无法连网
- 使用 SSR 客户端，无混淆，无协议插件，测试了美国、新加坡、日本、香港的 vps，feedly 均无法连网
- 使用 SS 客户端，测试了美国、新加坡、日本、香港的 vps，feedly 均无法连网
- 使用 v2ray 客户端，vmess 协议，测试了美国的 vps，feedly 可以正常联网使用

对于测试的说明：

- 在以上所有的测试当中使用的都是全局模式，以确保所有网络连接都通过代理
- 因为我能登录使用的 vps 只有一台美国的，所以只有这一台安装有 SS/SSR，实验变量控制得不好
- 在我能控制的这台 vps 当中部署的 SS 服务是使用 v2ray 配置的，并没有用其它的 SS 软件，但连接到这个 SS 时，feedly 同样无法联网
- 所有测试都在 Android 上测试，测试对象都是 feedly 的 Andriod 客户端
- 使用 Android 浏览器，无论是 SS/SSR/v2ray 都可以正常访问 feedly 的官网

根据测试结果，这个 bug 应该是 SS 协议的锅，与 SSR 客户端无关，SSR 延续了 SS。

**Comment by breakwa11** [comment]
检查一下你自己是不是开了UDP转发

**Comment by breakwa11** [comment]
目前，不清楚feedly的请求方式是什么样的，但能确定如果不开UDP转发就会连接失败

**Comment by ToutyRater** [comment]
是的，没有开 UDP 转发

**Comment by breakwa11** [comment]
总之必须开启了才能用

**Comment by breakwa11** [comment]
建议同时把这个问题反馈到原版
