### ISSUE TITLE
关于绕过大陆ip的dns污染

### ISSUE THREAD

**Issue by nqzhang** [breakwa11/shadowsocks-rss#425]
客户端版本为3.8.5.2 系统win10 启用系统代理 pac模式为绕过大陆ip
表现是google打不开其他都正常

正在 Ping www.facebook.com [93.46.8.89] 具有 32 字节的数据:
这个是被污染到意大利的ip地址  所以会走ss 可以正常打开

正在 Ping www.google.com [120.196.0.5] 具有 32 字节的数据:
但是google污染到了国内的地址就不走ss无法打开了

**Comment by breakwa11** [comment]
菜单有写“慎用”，文档有说明必须在无DNS污染的情况下再使用这个PAC

**Comment by nqzhang** [comment]
但是其他模式分流欠缺非常严重 比如绕过大陆常见域名douyutv.com 都是走代理
gfwlist 连很多应该代理的网站也没有代理
有没有方法强制通过ss服务器的dns来判断ip是否属于国外

**Comment by breakwa11** [comment]
不能，你需要自己架设一个DNS，例如用DNS2SOCKS，在github上有
