### ISSUE TITLE
希望作者弄个单端口多用户的功能

### ISSUE THREAD

**Issue by a113003** [breakwa11/shadowsocks-rss#426]
这样多个用户只需要开一个端口就行了

**Comment by jameseroyi** [comment]
有什么意义呢？  方便刚回搭ss的人出来合租吗？

**Comment by glzjin** [comment]
微笑

**Comment by breakwa11** [comment]
@glzjin 到时候你得哭了😂

**Comment by hzjixiang** [comment]
因为137 138端口很有价值，大陆移动手机可以通过这个端口免流量上网，所以同样希望增加一个端口下多用户管理。

**Comment by onegooday** [comment]
开发者应该不会这么搞了，网络自由和偷用流量还是有本质区别的，虽然流量费太贵

**Comment by chinawrj** [comment]
@hzjixiang 江苏移动已经封锁了137/138端口...

**Comment by BROBIRD** [comment]
@chinawrj ~~你不会用咪咕吗？~~

**Comment by glzjin** [comment]
@breakwa11 宝宝不哭

**Comment by esdeathlove** [comment]
现在已经有了。
