### ISSUE TITLE
咨询 ssr有计划增加KCP？

### ISSUE THREAD

**Issue by yjd** [breakwa11/shadowsocks-rss#428]
实际测试同环境下，KCP速度确实要快。

**Comment by breakwa11** [comment]
无计划

**Comment by yjd** [comment]
收到。
Network Activity 确实要稳很多。
![qq 20160909100606](https://cloud.githubusercontent.com/assets/6856740/18373256/2b9b5f42-7675-11e6-88f7-a0efba843b35.png)

**Comment by wudimenghuan** [comment]
@breakwa11 同问，上游已经有KCP支持了，啥时候能加上呢
