### ISSUE TITLE
服务端安装源代码不能获取了

### ISSUE THREAD

**Issue by qingfengshi** [breakwa11/shadowsocks-rss#429]
按照安装教程进行安装，
git clone -b manyuser https://github.com/breakwa11/shadowsocks.git
但是服务器端现实不能获取代码，是不是这个地址过期了，还是被删掉了？

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks
自己看

**Comment by qingfengshi** [comment]
哦，多谢。
我是想安装shadowsocksR，是按照链接
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup
操作的。
你后面给的那个地址是院版shadowsocks的安装吧

**Comment by breakwa11** [comment]
这才是原版 https://github.com/shadowsocks/shadowsocks

**Comment by qingfengshi** [comment]
好吧，乱了乱了
后面给的那个地址貌似是较低版本的安装，页面里给的configuration没有混淆插件和protocol的配置。
我参考的链接（https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup）也是您主页上的……

**Comment by breakwa11** [comment]
我都说了那个是原版，原版没有混淆

**Comment by qingfengshi** [comment]
我之所以误认为是原版，是因为我之前安装shadowsocks时使用的命令也是“pip install shadowsocks”，因此我我才认为您后面给的链接是原版

**Comment by qingfengshi** [comment]
好吧……多谢了
我服务端可以连接上的啊

**Comment by breakwa11** [comment]
。。。。。。。怎么感觉我说东你说西呢，你明明说的是你服务端连不是github那个地址

**Comment by qingfengshi** [comment]
可能是我没说清楚，我从头表述一下。
我想在服务器上安装shadowsocksR，然后按照官方主页上的教程操作，教程的链接为：
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup
教程中使用git clone -b manyuser https://github.com/breakwa11/shadowsocks.git 获取源代码，但是安装过程中显示无法获取，因此发起了这个issue。
之后您给的那个地址（https://github.com/breakwa11/shadowsocks）中的教程，实际安装的是shadowsocks。

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks 这就是SSR，教程里安装的就是SSR

**Comment by qingfengshi** [comment]
好的，多谢了

**Comment by qingfengshi** [comment]
关于后面的问题，我不明白的是连接
https://github.com/breakwa11/shadowsocks 
和原始版本的安装链接
https://github.com/shadowsocks/shadowsocks/wiki/Shadowsocks-使用说明
里**都使用的是pip install shadowsocks命令**，我在pip库里找了一下，shadowsocks的最新版本是2.8.2，作者仍然是clowwindy，链接为：https://github.com/shadowsocks/shadowsocks/commit/7c08101ce8a673fafb22477e8ad720aa57114a1f
因此才有问题：您给的链接https://github.com/breakwa11/shadowsocks 安装的是不是shadowsocksR，或者手册有点问题？

**Comment by breakwa11** [comment]
所有东西以wiki为准 https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup
