### ISSUE TITLE
建议ssr安卓端监听dhcp ip

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#430]
经常在一些环境下，手机客户端是最方便的，比如在网吧，或者与人共享，但是安卓客户端现在监听的是127.0.0.1，建议下个版本可以直接监听网卡ip。

谢谢

**Comment by qingfengshi** [comment]
listen改为0.0.0.0试试

**Comment by impig33** [comment]
@qingfengshi 手机端哪能改?

**Comment by qingfengshi** [comment]
手机端我还没用过，当我没说。

**Comment by jhgongfu** [comment]
希望可以开热点共享ssr的翻墙

**Comment by impig33** [comment]
求酱妹回复

**Comment by breakwa11** [comment]
不属于我的处理范围

**Comment by impig33** [comment]
@breakwa11 酱妹ssr安卓作者是谁啊

**Comment by wenliyang** [comment]
这儿去问

https://github.com/glzjin/shadowsocksr-android
