### ISSUE TITLE
在ZeroNet上发布新版的时候能否顺便发布源码

### ISSUE THREAD

**Issue by samuelts** [breakwa11/shadowsocks-rss#432]
原来在 BitTorrent Sync 里面有源码，不过现在好像也没有同步更新了
如果是考虑一些原因不能直接发布源代码的话，建议也可以和二进制文件那样加上密码

**Comment by breakwa11** [comment]
你没看见不等于没有

**Comment by samuelts** [comment]
不好意思，那个位置不太显眼，所以没注意到

感谢您一直以来做出的贡献
