### ISSUE TITLE
SSR服务端内网穿透的情况下通过外网连接问题？

### ISSUE THREAD

**Issue by qiurigao** [breakwa11/shadowsocks-rss#433]
我的服务器没有公网ip, 我用ngrok做了内网穿透，可以将指定端口映射到外网域名的指定端口。
那么问题来了，这个内网端口是哪个呢？？
是直接浏览器设置1008端口代理，还是用正常的客户端连接端口？
客户端可以启用本地1080代理，但是好像服务端默认是禁止局域网代理的，是添加哪个参数才能支持？
或者压根就无法实现，怎么能自己代理自己呢
。。。但是内网穿透的原理就是经穿透服务器以内网的身份访问端口啊
可否麻烦解答下

**Comment by 1564143452** [comment]
阁下睡觉好晚
你想表达是你在内网运行了一个SSR SERVER，然后是在外网访问？
那假设这个SSR SERVER的监听端口是8989，然后你自然在这台电脑运行的ngrok CLIENT的端口设置也应该是8989了
如果不是这种情形，当我没说

**Comment by qiurigao** [comment]
端口问题已经解决了，可以连上。
但是。我还有一个客户端配置问题:
现在我想指定一个域名走代理，而且就一个域名，其他任何域名都不经过ss。如何配置？修改pac文件吗，文件格式怎么写？

**Comment by breakwa11** [comment]
你自己查PAC怎么编程，或找别人帮你写这个PAC吧
