### ISSUE TITLE
建议 【一个客户端多端口对应多IP】

### ISSUE THREAD

**Issue by 9191521** [breakwa11/shadowsocks-rss#434]
一个客户端多端口对应多IP
就是把本地端口选项放到没个服务器下面
不知道可不可行
每次要开三个不同版本的客户端表示很蛋疼呀

**Comment by 9191521** [comment]
Windows

**Comment by breakwa11** [comment]
以后会有的，但没这么快

**Comment by breakwa11** [comment]
仔细想了一下，你还是开三个客户端好了，至于你说开三个不同版本，肯定是你自己搞错了什么
