### ISSUE TITLE
json版多用户配置失败

### ISSUE THREAD

**Issue by Sayinore** [breakwa11/shadowsocks-rss#435]
服务商：DO
配置方法：[SSR一键安装脚本](https://shadowsocks.be/9.html)
类型：json多用户

我运行完配置脚本后，修改了`/etc/shadowsocks.json`，修改端口数为6个端口，启用不同的密码；并且用  

`firewall-cmd --permanent --zone=public --add-port=${portname}/tcp`  
`firewall-cmd --permanent --zone=public --add-port=${portname}/udp`  
允许那6个端口，可是现在仍然连接不上服务端。我能够排除GFW的原因，因为我仍然能够SSH。

服务端日志：

`2016-09-11 13:27:34 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]`
`2016-09-11 13:27:34 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [HIDED] method [aes-256-cfb] obfs [plain] obfs_param []`  
`2016-09-11 13:27:34 INFO     server.py:114 starting server at [::]:143`  
`2016-09-11 13:27:34 INFO     server.py:134 starting server at 0.0.0.0:143`  
`2016-09-11 13:27:34 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [HIDED] method [aes-256-cfb] obfs [plain] obfs_param []`  
`2016-09-11 13:27:34 INFO     server.py:114 starting server at [::]:23`  
`2016-09-11 13:27:34 INFO     server.py:134 starting server at 0.0.0.0:23`  
`2016-09-11 13:27:34 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [HIDED] method [aes-256-cfb] obfs [plain] obfs_param []`  
`2016-09-11 13:27:34 INFO     server.py:114 starting server at [::]:443`  
`2016-09-11 13:27:34 INFO     server.py:134 starting server at 0.0.0.0:443`  
`2016-09-11 13:27:34 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [HIDED] method [aes-256-cfb] obfs [plain] obfs_param []`  
`2016-09-11 13:27:34 INFO     server.py:114 starting server at [::]:194`  
`2016-09-11 13:27:34 INFO     server.py:134 starting server at 0.0.0.0:194`  
`2016-09-11 13:27:34 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [HIDED] method [aes-256-cfb] obfs [plain] obfs_param []`  
`2016-09-11 13:27:34 INFO     server.py:114 starting server at [::]:53`  
`2016-09-11 13:27:34 INFO     server.py:134 starting server at 0.0.0.0:53`  
`2016-09-11 13:27:34 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [HIDED] method [aes-256-cfb] obfs [plain] obfs_param []`  
`2016-09-11 13:27:34 INFO     server.py:114 starting server at [::]:80`  
`2016-09-11 13:27:34 INFO     server.py:134 starting server at 0.0.0.0:80`   

请问我该怎么办？如果需要，我可以提供SSH-Key。

**Comment by breakwa11** [comment]
防火墙设置问题
