### ISSUE TITLE
提个建议 不要一直做配置名称的改变

### ISSUE THREAD

**Issue by nqzhang** [breakwa11/shadowsocks-rss#437]
比如auth_sha1_v3，应该尽量在原auth_sha1_v2的基础上进行完善 而不是重新搞一个新的“”配置名字“
配置文件的字段变化也应该尽量少

比如3.8.5.2 之后又有了新的字段来控制系统代理 这会造成客户端的“不兼容” 部分用户非常难以跟进 毕竟ss应该不仅仅做到一群做技术的在使用 每一次这样的配置变更都需要别人换一次配置文件的话 是不是太麻烦了

**Comment by nqzhang** [comment]
比如 新版客户端没有tls1.0_session_auth 这种不兼容是否应该少点

**Comment by breakwa11** [comment]
这不可能

**Comment by StarryNightL** [comment]
这都是那些以此来赚钱的商家的话语，自用的话更改一下配置需要几秒
