### ISSUE TITLE
想写个前端web程序，但是没找到你的程序接口文档，求接口

### ISSUE THREAD

**Issue by dontlogin1** [breakwa11/shadowsocks-rss#439]
我想自己写个前端web程序，但是没找到你程序的接口文档，求接口
谢谢

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/C%23-API

**Comment by dontlogin1** [comment]
@breakwa11  
额，我想写个类似sspanel 的前端多用户管理程序，求相关的API

**Comment by breakwa11** [comment]
如果你指的是网页前端，并没有什么API，只要数据库字段匹配就行了

**Comment by dontlogin1** [comment]
@breakwa11 。美女，但是在sspanelv3模式下， 我不知道你的数据库具体有哪些字段，能不能给份文档，谢谢您。

**Comment by zhylmzr** [comment]
同上, 目前不知服务端的数据库设计支持哪些字段, 只能基于现有的sspanel的数据库修改

**Comment by breakwa11** [comment]
你查sspanel的数据库字段就知道了
