### ISSUE TITLE
PAC

### ISSUE THREAD

**Issue by L-Meteor** [breakwa11/shadowsocks-rss#44]
您好!在使用 ChnIPList 时,打开网页或观看 Youtube 视频时加载都很快,但观看土豆动漫视频时,却会显示为非中国大陆地区,无法收看,这个情况是这两天才出现的.后改为 GFWlist 则能正常收看土豆动漫视频,但加载其它被封网站或 Youtube 视频时,却异常的缓慢.请问这是怎么回事呢?谢谢!

**Comment by breakwa11** [comment]
gfwlist用url匹配，对于ip都是直连，chniplist会先dns解析再看要不要直连。你这种情况应该是使用了国外的dns，看国内网站时很可能就近解析到国外，从而产生这个问题。解决方法是直接用国内dns

**Comment by L-Meteor** [comment]
谢谢您的解答!

**Comment by L-Meteor** [comment]
更换DNS后,问题依旧,还是老实的用 gfwlist 吧!另外,请问首次使用 ShadowsocksR 时,gfwlist 或 chniplist 更新一次就可以了吗?还有就是,先更新了chniplist ,接着又选择更新 gfwlist,gfwlist 会覆盖先前 chniplist 的更新吗?疑问有点多,实在不好意思.谢谢!

**Comment by breakwa11** [comment]
有可能是因为没有清空系统的DNS缓存
更新后是立即生效的，重复更新会导致新的覆盖旧的

**Comment by L-Meteor** [comment]
谢谢!

**Comment by gitfreely** [comment]
我的一直是国内DNS啊，用chniplist时，优酷也是提示非大陆用户！

**Comment by breakwa11** [comment]
测试表示没有发现问题，确认一下系统代理模式是全局还是PAC
