### ISSUE TITLE
客户端混淆参数里的host设置好之后发送的请求会吧服务端的端口加上

### ISSUE THREAD

**Issue by utick** [breakwa11/shadowsocks-rss#441]
客户端设置成"www.google.com#Refer: www.ss.com"
服务端收到的请求变成了"Host: www.google.com:8989"
而不是"Host: www.google.com"

**Comment by breakwa11** [comment]
这是必须的，如果非80时不加端口，就会和浏览器行为不一样

**Comment by utick** [comment]
但是有时候某些检测系统会去检查Host，程序自动加上端口号就通过不了，希望可以把这个做成用户可选的，这样就可以精确定义完整的Host

**Comment by breakwa11** [comment]
你用80端口就不会加上了

**Comment by glzjin** [comment]
有某个并不稳定的版本实现了这个

**Comment by utick** [comment]
意思是这个功能会在未来加上吗 @glzjin

**Comment by glzjin** [comment]
这里这个版本加不加我并不知道—.—你有兴趣的话，可以自己试试那个变种版本

**Comment by utick** [comment]
@glzjin 在哪里可以找到？

**Comment by utick** [comment]
改了一下 http_simple.c 把端口去掉了 XD
