### ISSUE TITLE
python server.py -d start 后出错，翻不了。

### ISSUE THREAD

**Issue by quncan** [breakwa11/shadowsocks-rss#444]
![2016-09-15_232803](https://cloud.githubusercontent.com/assets/21148170/18556036/afbeb19e-7b9c-11e6-8246-15f95bbbec46.PNG)

请问需要user-config.json吗？

**Comment by 383771059** [comment]
你都没看清楚教程。看清楚了就知道了

**Comment by quncan** [comment]
详细：https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup

我是这样做的：

yum install git

git clone -b manyuser https://github.com/breakwa11/shadowsocks.git

修改配置文件user-config.json如下：

"server_port":9527,        
"password":"SMTxxxxxxx",    
"protocol":"origin",     
"obfs":"http_simple",   
"method":"aes-256-cfb", 

其他保持不变，出错后我怀疑是ipv6，就python server.py -d stop 后vi修改了配置文件把"server_ipv6": "[::]",删除了，但是依然出现这个情况。

请问我是哪里做错了还是漏了什么？

**Comment by 383771059** [comment]
你试试不用Jason来启动，而是直接输入命令行快速启动。
我给我的给你参考：
python server.py -p 填端口 -k 填密码 -m chacha20 -P auth_sha1_v2_compatible -o tls1.2_ticket_auth_compatible -d start

**Comment by quncan** [comment]
![2016-09-16_003026](https://cloud.githubusercontent.com/assets/21148170/18558200/cfd69b6a-7ba4-11e6-99c9-3b9ae1f86dd9.PNG)

出现新的情况了，加了-d start 就少了一些错误，没加上多了几个问题

**Comment by quncan** [comment]
这次我没修改json，一步一步跟着教程来做的...

**Comment by breakwa11** [comment]
没加上的时候那些信息表示正常在9527端口运行

**Comment by quncan** [comment]
对不起，这几天都出差了没办法上来，如果那些信息代表是正常的话，我这两晚再试试是否可行。谢谢啦
