### ISSUE TITLE
Shadowsocks-go主动探测代码

### ISSUE THREAD

**Issue by breakwa11** [breakwa11/shadowsocks-rss#448]
https://gist.github.com/breakwa11/756b15ef0c8499e9b03fbf1cb6b716fa

说明，仅针对Shadowsocks-go服务端有效，至少16次，至多32次连接尝试即可成功探测，脚本运行时间约15秒到40秒，判定难度比其它分支低得多，换言之安全性非常低，由于实现上的问题，不管OTA有没有开启均对此探测无免疫能力。

建议：此分支的服务端实现需要尽快修改以与其它分支行为一致，以避免弱安全性问题

**Comment by Aniark** [comment]
不@  go项目人员来看看吗？

**Comment by breakwa11** [comment]
@Aniark 是不是要 @cyfdecyf 这只？貌似他好久没动代码了

**Comment by Dwwwwww** [comment]
orvice的修改版是否同样能够被探测？

**Comment by breakwa11** [comment]
@Dwwwwww 当然能，我就是用那个版做在线版的测试的，本地则是用原分支测试

**Comment by Aniark** [comment]
@breakwa11 就目前的最新版python版ss和libve版ss，能够用类似的方法探测吗？

**Comment by breakwa11** [comment]
@Aniark 参见 https://breakwa11.blogspot.com/2016/09/shadowsocks.html

**Comment by v3aqb** [comment]
我的实现是unknown server

**Comment by breakwa11** [comment]
@v3aqb 你的实现在哪里
