### ISSUE TITLE
超时问题

### ISSUE THREAD

**Issue by merry200603** [breakwa11/shadowsocks-rss#449]
网络条件差的时候，会长时间无限超时，建议超过一定阀值后可以自动切换节点

另外，建议服务器记录数字取整即可，这样看起来会更一目了然

**Comment by breakwa11** [comment]
你有设置超时时间吗？

**Comment by merry200603** [comment]
超时设了10，在多次连接错误时会自动禁用节点转下一个，如果超时次数过多也可以切换节点就好了，虽然超时不一定意味着服务器不能访问，因此可以不禁用，不知道可不可以？

**Comment by breakwa11** [comment]
负载均衡模式用定时切换，就可以出错自动换

**Comment by merry200603** [comment]
不少网站对ip变动敏感，如果在一般模式下可以的话就更好了

**Comment by breakwa11** [comment]
开启 使用相同节点连接同一地址

**Comment by breakwa11** [comment]
你所谓的“一般模式”在SSR里就是节点固定不变，如要变，必须开负载均衡，至于怎么变，由所选策略决定
