### ISSUE TITLE
六台节点都被墙了。。。

### ISSUE THREAD

**Issue by ffspace810** [breakwa11/shadowsocks-rss#450]
服务端是最新版，客户端是3.8.7.0，中秋三天过后发现六台节点都连不上了，所有端口都不能连接，但除了我所使用的宽带（北京联通专线固定IP），外面的网络包括国内的服务器可以正常连接节点。。。ssr使用了大概半个月左右，会不会是被gfw发现了然后做了阻断。。

**Comment by ffspace810** [comment]
使用了tls1.2_ticket_auth_compatible和auth_sha1_v3_compatible

**Comment by breakwa11** [comment]
如无必要还是配什么协议就用什么，别设置兼容
