### ISSUE TITLE
客户端添加新节点逻辑问题

### ISSUE THREAD

**Issue by onegooday** [breakwa11/shadowsocks-rss#451]
**现状**：3.8.8.0版本目前添加新节点是在服务器列表末尾复制选定的焦点服务器节点信息。

**存在的问题**：有很多不同来源的ssr服务器节点分组，每组都是挨着的，对不同的组进行节点添加时，都新建到列表末尾了，移动到同组的位置要一直点击“上移”，在节点很多的情况下，相当不便利。

**建议**：服务器的添加逻辑改为在焦点服务器下面新建并复制焦点服务器节点信息，而不是在服务器列表末尾新建。

ps：上次在群里建议统计界面打开后焦点移动到当前使用服务器，很高兴实现了这个功能，谢谢。如果能把该焦点服务器展示于统计列表的中上方，而不是在倒数第二排就好了。

**Comment by breakwa11** [comment]
其实早就在计划里了，不过做法和你的不太一样，还没来得及做而已
