### ISSUE TITLE
3.8.5.0开始断流

### ISSUE THREAD

**Issue by Jouaoo** [breakwa11/shadowsocks-rss#452]
如题、3.8.5.0版本开始，
win10+chrome+SwitchyOmega，开启系统代理；
一天出现N次。
换其他客户端正常，android端同wifi下正常。
就网页会断，PC端TG正常。
日志里也没见啥错误，就是要关掉浏览器重新开启，又好了 。。 。过一会。。又断了。哭哭

**Comment by breakwa11** [comment]
服务端用的是什么版本

**Comment by Lnybb** [comment]
3.8.5.2 遇到同样的问题。表示3.8.9不知道去哪获取，看了BitTorrent Sync上也木有啊。

**Comment by L-Meteor** [comment]
3.8.9版本也有相同的问题!

**Comment by breakwa11** [comment]
那测试一下新的

**Comment by L-Meteor** [comment]
破娃酱,3.9.0的解压密码是多少啊?

**Comment by mikelei8291** [comment]
相同的问题
```
ShadowsocksR C#: At least 3.8.5 ~ 3.9.6 (latest)
ShadowsocksR manyuser: At least e8f6d87 ~ 2eaca2f (latest)
Windows: 10 (1607)
Chrome: At least 54 ~ 55.0.2883.11 dev
```
表现为浏览网页时页面加载到一半，或者刚开始加载就停止了，需要手动刷新页面才能继续加载，使用的是bypass China IP的系统pac配置，其他应用和软件没有明显感觉
试了试比较快速的复现方式可以打开一张 pixiv.com 的图，然后一直按 <kbd>→</kbd> 键切换下一张图片，不出意外换几张就会卡住
log文件里没有任何错误输出，所以一直也没有提issue，今天看到有人提我也反馈一下
