### ISSUE TITLE
更新PAC文件不成功。

### ISSUE THREAD

**Issue by lcyan** [breakwa11/shadowsocks-rss#453]
[2016-09-19 22:49:46] ShadowsocksR started on port 1080
[2016-09-19 22:49:56] [Error]connect to update server error
[2016-09-19 22:50:12] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-09-19 22:50:12] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-09-19 22:50:22] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-09-19 22:50:22] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-09-19 22:51:39] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-09-19 22:51:39] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-09-19 22:54:56] [Error]connect to update server error
[2016-09-19 22:59:17] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadPACCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-09-19 22:59:17] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadPACCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

**Comment by lcyan** [comment]
@breakwa11 是正常的，我用这个3.8.3e就可以用。用最新版的就包这个错误。

**Comment by breakwa11** [comment]
我意思是你得先确认你的节点在你的客户端里正不正常，我不管你用什么版本，麻烦看统计信息和log

**Comment by breakwa11** [comment]
第一张图我看不见版本号，而且这个log说明不是新版，麻烦更新了再说

**Comment by lcyan** [comment]
@breakwa11
![image](https://cloud.githubusercontent.com/assets/3824082/18638999/c7cf5e52-7ec4-11e6-9ff7-e73475c044ee.png)
[2016-09-19 23:55:31] ShadowsocksR started on port 1080
[2016-09-19 23:55:41] [Error]connect to update server error

**Comment by breakwa11** [comment]
那我问问，你在软件的DNS那有配置什么不

**Comment by lcyan** [comment]
@breakwa11 没有任何配置哦。就是扫描二维码添加的服务器，老版本没这个问题
![image](https://cloud.githubusercontent.com/assets/3824082/18673812/b90e3a94-7f7f-11e6-9491-ec9359ee0c7c.png)

**Comment by breakwa11** [comment]
你试试在dns那写上114.114.114.114呢

**Comment by lcyan** [comment]
@breakwa11 
![image](https://cloud.githubusercontent.com/assets/3824082/18677556/b47170c6-7f8b-11e6-9b0c-4f518f38748b.png)
可以了。谢谢。老版本是不需要设置这个东西的。

**Comment by breakwa11** [comment]
我查查具体问题

**Comment by L-Meteor** [comment]
3.9.0版本稳定更新!

**Comment by RichardSHIZE** [comment]
[2016-10-05 12:58:57] [Error]connect to update server error
[2016-10-05 13:01:16] ShadowsocksR started
[2016-10-05 13:01:26] [Error]connect to update server error
[2016-10-05 13:04:03] ShadowsocksR started
[2016-10-05 13:05:28] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-10-05 13:05:28] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-10-05 13:05:30] ShadowsocksR started
[2016-10-05 13:23:32] ShadowsocksR started
[2016-10-05 13:33:53] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-10-05 13:33:53] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

**Comment by RichardSHIZE** [comment]
我是校园网，以上问题听说学校采用深度包检测，不知道是不是。求教

**Comment by breakwa11** [comment]
@RichardSHIZE 先检查你的节点有没有问题

**Comment by RichardSHIZE** [comment]
没有，我刚用了下混淆协议就行了，我也不明白

**Comment by breakwa11** [comment]
@RichardSHIZE 你什么学校，不会是传说中的北邮吧？不过有开启混淆在这种地方肯定好很多

**Comment by RichardSHIZE** [comment]
@breakwa11 不是，是广东一所不知名的工科学校，还北邮...

**Comment by breakwa11** [comment]
@RichardSHIZE 很多学校都会建立自己的防火墙，这不奇怪。问题解决了就close一下吧

**Comment by elespec** [comment]
用了这么久了,我就想知道这个作者是汉子还是妹子....还是娘炮...
