### ISSUE TITLE
请问作者，下面这个IPTABLES命令对SSR多用户有效吗？

### ISSUE THREAD

**Issue by jack338c** [breakwa11/shadowsocks-rss#454]
iptables -A INPUT -p tcp --syn --dport ${SHADOWSOCKS_PORT} -m connlimit --connlimit-above 32 -j REJECT --reject-with tcp-reset

就是这条命令，本人试了，没效果

是不是要通过修改"protocol_param": "",参数可以达到目的？
这个要填10的整数还是奇数也可以？

方便时请帮解答了，多谢了！

**Comment by breakwa11** [comment]
参数填写的是客户端数量限制，而不是限制连接数

**Comment by jack338c** [comment]
好，明白了

**Comment by breakwa11** [comment]
至于限制连接数的iptables命令我不清楚，如果你确认了有效的请告诉我
