### ISSUE TITLE
安卓SSR客户端UDP问题

### ISSUE THREAD

**Issue by huaxinchan** [breakwa11/shadowsocks-rss#456]
如果用http_simple 混淆方式，UDP转发的数据没有混淆效果

**Comment by breakwa11** [comment]
不然你认为会怎么样

**Comment by huaxinchan** [comment]
我以为是先是TCP加了混淆再转成UDP

**Comment by shawndw** [comment]
ssr android 今晚會發布嗎?

**Comment by glzjin** [comment]
@shawndw fixing a issue.....

**Comment by shawndw** [comment]
@glzjin the day after tomorrow

**Comment by glzjin** [comment]
@shawndw Hold on,and i will send apk to big sister

**Comment by huaxinchan** [comment]
@breakwa11 希望UDP转发添加TCP混淆后再转UDP的选项
