### ISSUE TITLE
梅林更新了 v3和v4都这样？

### ISSUE THREAD

**Issue by lingaoyi** [breakwa11/shadowsocks-rss#458]
v3这样
Sep 25 10:15:39 rss-redir[3491]: remote recv: Connection reset by peer
Sep 25 10:15:39 rss-redir[3491]: Load obfs 'auth_sha1_v3' failed
Sep 25 10:15:39 rss-redir[3491]: Load obfs 'auth_sha1_v3' failed

v4这样：
Sep 25 10:14:27 rss-redir[1499]: getpeername: Transport endpoint is not connected
Sep 25 10:14:27 rss-redir[1499]: getpeername: Transport endpoint is not connected

**Comment by lingaoyi** [comment]
tls1.2_ticket_auth_compatible
auth_sha1_v3_compatible
v3必须要写成这样才可以用 Orz....

**Comment by breakwa11** [comment]
路由器上我就没写v3实现，我不知道你怎么用的

**Comment by lingaoyi** [comment]
@breakwa11 我这样能用算什么情况？https://www.dropbox.com/s/7ywe0pbgx8otad7/QQ20160925-0%402x.png?dl=0

**Comment by lingaoyi** [comment]
Sep 25 11:30:10 rss-redir[17660]: getpeername: Transport endpoint is not connected
Sep 25 11:30:10 rss-redir[17660]: getpeername: Transport endpoint is not connected
Sep 25 11:30:10 rss-local[17646]: getpeername: Transport endpoint is not connected

我切换到v4一直这样，服务器这样设置是对的吗？谢谢
https://www.dropbox.com/s/79hsw99ntjw1jlt/QQ20160925-2%402x.png?dl=0

**Comment by breakwa11** [comment]
协议加载失败等于在用原协议，所以服务端开了兼容才能用

**Comment by lingaoyi** [comment]
怎样在服务端开兼容啊？

**Comment by StarryVoid** [comment]
@lingaoyi 请查阅wiki

**Comment by lingaoyi** [comment]
其实我真的看不懂......

**Comment by StarryVoid** [comment]
@lingaoyi 默认开启了兼容模式

**Comment by lingaoyi** [comment]
我那样设置是正常嘛？

**Comment by ZeroClover** [comment]
在支持兼容模式的协议插件和混淆插件后带上`_compatible`就是兼容模式

Merlin目前的版本（2.8.9）似乎存在问题，建议先用V2或者原协议

**Comment by lingaoyi** [comment]
@ZeroClover @StarryVoid 
本地：
https://www.dropbox.com/s/kck15l0fupninyc/QQ20160925-4%402x.png?dl=0

服务器：
https://www.dropbox.com/s/fjrve0j9gicqecc/QQ20160925-3%402x.png?dl=0

正确吗？

**Comment by StarryVoid** [comment]
如果路由器支持v4，那么你配置没有问题。
然而如果不支持，那么你需要修改为原版协议与混淆

**Comment by lingaoyi** [comment]
2.8.9
   - update	update shadowsocks-libev binary to 2.5.3 release
   - update	update shadowsocksR-libev binary to latest (support auth_sha1_v3 and auth_sha1_v4 protocol)
   - update	add support for auth_sha1_v3 and auth_sha1_v4 protocol in web

梅林写着这样，算支持吧？

ep 25 13:57:38 rss-local[15139]: getpeername: Transport endpoint is not connected
Sep 25 13:57:38 rss-redir[15153]: getpeername: Transport endpoint is not connected
Sep 25 13:57:39 rss-redir[15153]: getpeername: Transport endpoint is not connected
Sep 25 13:57:39 rss-redir[15153]: getpeername: Transport endpoint is not connected
Sep 25 13:57:40 rss-local[15139]: getpeername: Transport endpoint is not connected
Sep 25 13:57:40 rss-redir[15153]: getpeername: Transport endpoint is not connected
Sep 25 13:57:40 rss-redir[15153]: getpeername: Transport endpoint is not connected
Sep 25 13:57:41 rss-local[15139]: remote_recv_cb_recv: Connection reset by peer
Sep 25 13:57:43 rss-redir[15153]: remote recv: Connection reset by peer
Sep 25 13:57:43 rss-redir[15153]: remote recv: Connection reset by peer

反正v4是这样。。。
