### ISSUE TITLE
关于switchrule.py设置

### ISSUE THREAD

**Issue by kkbbzjh** [breakwa11/shadowsocks-rss#459]
在switchrule.py中，如果这样，代表只有planA用户可以使用，
def isTurnOn(row):
	return row['plan'] == 'A'
	#return row['plan'] == 'B' # then judge here
那我想planA和B都能使用呢？怎么写？

**Comment by breakwa11** [comment]
row['plan'] == 'A' or row['plan'] == 'B'

**Comment by kkbbzjh** [comment]
好的，谢谢
