### ISSUE TITLE
能不能更新一个支持新协议的ss libev版本？

### ISSUE THREAD

**Issue by chazikai24** [breakwa11/shadowsocks-rss#46]
服务端已经部署了新的，开启了新ss协议，电脑端使用感觉非常的不错。
不过能不能跟进一下libev版本的ss？

**Comment by breakwa11** [comment]
这个协议还没稳定啦，还得等待反馈和测试信息，另外也在和libev的作者联系中

**Comment by chazikai24** [comment]
桌面端用了一下新协议，感觉还行，用了大概一周，就一两次短暂的抽风，感觉不像是gfw的问题，跟像是国际出口的问题

**Comment by sugarleon** [comment]
可惜没人开发安卓的客户端，也是不能启用。

**Comment by dengcb** [comment]
mac端和安卓端，哎

**Comment by sofs2005** [comment]
其实还需要一个路由器端

**Comment by farrellyang** [comment]
我觉得等新功能开发完备，稳定之后，可以搞libev版，方便在路由器上用，当然支持自动更新的话，不一定要等到开发完。
