### ISSUE TITLE
Json版多用户情境下怎么开启IPV6和FAST_OPEN

### ISSUE THREAD

**Issue by Thisdk** [breakwa11/shadowsocks-rss#460]
作者你好.您的SSR我从今年一直用到现在.感谢你为这个软件付出的贡献
我最近因为自己的服务器需要分享一些帐号给别人用.然后发现Json版多用户没有ipv6和fast_open的字段.不知道会不会默认开启.如果不会默认开启.怎么修改才能让多用户状态下开启这两个呢

**Comment by breakwa11** [comment]
在config.json或user-config.json里设置好就行了，这设置是全局的，不能各用户单独设置

**Comment by Thisdk** [comment]
好的,可以了.谢谢
