### ISSUE TITLE
server@merlin: Segmentation fault

### ISSUE THREAD

**Issue by koolca** [breakwa11/shadowsocks-rss#464]
通过entware安装python，运行结果如下：
python server.py -p 8888 -k password -m aes-256-cfb -o http_simple
loaded collections.OrderedDict
IPv6 not support
INFO: loading config from /jffs/ssr/shadowsocks/shadowsocks/../shadowsocks/../config.json
Segmentation fault
Python版本如下：
Python 2.7.11 (default, Aug 19 2016, 10:56:00)
[GCC 5.4.0] on linux2
这个何解？

**Comment by breakwa11** [comment]
@koolca 像是你的py自己挂了

**Comment by koolca** [comment]
谢谢 @breakwa11 
似乎也没有调试手段？

**Comment by breakwa11** [comment]
@koolca 尝试更换版本，或使用pypy

**Comment by koolca** [comment]
@breakwa11 此版本python可以运行goagent没有问题。merlin上好像没办法更换版本或者安装pypy，或许我不够熟悉。python有版本更新了我再试试。

**Comment by breakwa11** [comment]
路由器为什么要运行服务端？

**Comment by koolca** [comment]
@breakwa11 翻公司墙，路由器在国外/香港就更有用了

**Comment by breakwa11** [comment]
建议用路由器转发到PC上跑
