### ISSUE TITLE
win10用不了

### ISSUE THREAD

**Issue by YangYii** [breakwa11/shadowsocks-rss#466]
win10用不了咋办啊

**Comment by breakwa11** [comment]
@YangYii 这是win10的问题

**Comment by YangYii** [comment]
有办法解决吗

**Comment by breakwa11** [comment]
@YangYii 没有

**Comment by elitezhe** [comment]
什么用不了 挺正常啊

**Comment by YangYii** [comment]
是预览版的14936  用不了 ，其他的版本还可以用

2016-10-04 8:31 GMT+08:00 Zhang Zhe <notifications@github.com>:

**Comment by elitezhe** [comment]
14936是指win10 redstone? 我用着挺正常的啊

**Comment by YangYii** [comment]
是啊，我升级就用不了，现在都回滚了

2016-10-04 13:42 GMT+08:00 Zhang Zhe <notifications@github.com>:

**Comment by imshuhao** [comment]
测试了下 Win10 Preview Build. 14936用不了。

**Comment by breakwa11** [comment]
@imshuhao 能不能在tg上联系我一下

**Comment by breakwa11** [comment]
下一个版本应该会修好的

**Comment by didila** [comment]
我的经验，win10用不了都是防火墙作怪

**Comment by sunthx** [comment]
#482 

我的版本是 14946 。

以下是我的解决方案：

开启SSR后，win10需要指定代理。
默认是不开启任何代理的。

设置->网络->代理 

选择手动配置->输入本地代理IP与端口(127.0.0.1，8080)

应用

搞定
