### ISSUE TITLE
ssr client是否支持多server模式？

### ISSUE THREAD

**Issue by liuguojun** [breakwa11/shadowsocks-rss#467]
如果支持的话，怎么配置？ 以及多server之间是负载均衡？

**Comment by breakwa11** [comment]
你到底指哪个client

**Comment by liuguojun** [comment]
我的理解，ssr server一般的ss client连不上吧，必须要ssr 专用client ？

如果后端有多个可用ssr server，linux下ssr client能支持多server的json类型的配置文件吗？ （windows下我知道可以）

**Comment by breakwa11** [comment]
@liuguojun 谁说不能连的，请看wiki。目前仅windows的c#版可能负载均衡

**Comment by JillCheng** [comment]
@breakwa11 作者您好。我想请问，C#客户端里，2.0和4.0有什么区别？

**Comment by breakwa11** [comment]
@JillCheng 能用4.0就优先用，不能就用2.0

**Comment by 850176300** [comment]
@breakwa11 windwos版最新的客户端有一些混淆参数没有，不知道有没有其他地方可以找到最新的呀

**Comment by xiaomozhang** [comment]
问下楼主,我在centos中安装了https://github.com/breakwa11/shadowsocks-rss/wiki/Python-client-setup-(Mult-language) 的客户端,安装可启动成功了,但是在网页中用socket工具连接没有响应是怎么回事啊？
