### ISSUE TITLE
感觉 SS 的统计功能不错

### ISSUE THREAD

**Issue by brcm** [breakwa11/shadowsocks-rss#468]
SSR 有没有类似功能？
根据自己设定的统计对不同服务器评分，最后根据统计结果切换服务器。
感觉挺不错的。

**Comment by breakwa11** [comment]
@brcm 开负载均衡，可按延迟优先或低错误优先，或其它更多的方式，你可以比较一下

**Comment by brcm** [comment]
@breakwa11 感谢菊苣 ^^，不过觉得自写规则的话灵活度可能更高一点

**Comment by breakwa11** [comment]
我个人觉得必要性不高，并且其实SSR用到的参数比SS少得多

**Comment by brcm** [comment]
@breakwa11 了解的说。
一直感觉 SSR 的服务器统计列表功能比较直观。
蟹蟹菊苣
