### ISSUE TITLE
能否有更详细的单用户搭建教程？

### ISSUE THREAD

**Issue by wangtongze** [breakwa11/shadowsocks-rss#47]
1.单用户ssr是否需要设置mysql相关信息？
2.将force new tcp protocol改为true以后服务端直接运行 run.sh 就可以激活新tcp协议么？

**Comment by shuangzhijinghua** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup

**Comment by wangtongze** [comment]
那个文档没有说得太清楚

**Comment by wangtongze** [comment]
@breakwa11

**Comment by shuangzhijinghua** [comment]
不清楚在哪里？

**Comment by wangtongze** [comment]
@shuangzhijinghua 
1.单用户ssr是否需要设置mysql相关信息？
2.将force new tcp protocol改为true以后服务端直接运行 run.sh 就可以激活新tcp协议么？

**Comment by falseen** [comment]
单用户不用配置sql，直接运行子目录shadowsocks里的start.sh或server.py。

**Comment by wangtongze** [comment]
@falseen 将force new tcp protocol改为true以后服务端直接运行 run.sh 就可以激活新tcp协议么？

**Comment by shuangzhijinghua** [comment]
单用户直接执行shadowsocks/server.py，参数与py版ssserver一致

**Comment by wenson** [comment]
恕我愚钝，多用户版本，给一个人用。和单用户版本 有啥差别呢？

**Comment by falseen** [comment]
@wangtongze 看代码的话运行run.sh是会结束之前的进程然后重新运行的，但我没测试过。

**Comment by falseen** [comment]
@wenson 多用户版本有统计功能和数据库接口，是给站长用的。单用户版没有这些。另外单用户版也可以配置多用户。
