### ISSUE TITLE
SSR启动报错

### ISSUE THREAD

**Issue by Aniark** [breakwa11/shadowsocks-rss#472]
loaded collections.OrderedDict
IPv6 support
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "server.py", line 38, in run
    self.obj.thread_db(self.obj)
  File "/root/shadowsocks/shadowsocks/db_transfer.py", line 198, in thread_db
    db_instance = obj()
  File "/root/shadowsocks/shadowsocks/db_transfer.py", line 246, in __init__
    self.load_cfg()
  File "/root/shadowsocks/shadowsocks/db_transfer.py", line 252, in load_cfg
    with open(config_path, 'r+') as f:
IOError: [Errno 2] No such file or directory: 'usermysql.json'
系统：debian7

**Comment by breakwa11** [comment]
@Aniark 认真读wiki

**Comment by Aniark** [comment]
@breakwa11 没有找到以上报错的解决方案

**Comment by breakwa11** [comment]
你没有按照wiki的步骤来做

**Comment by Aniark** [comment]
@breakwa11 这是我保存的snapshot，用此snapshot重装系统后，启动出现报错，执行git pull更新仍然报错，除了重装系统还有办法？

**Comment by breakwa11** [comment]
我还是再说一次，你没有认真读wiki，首先你这运行的是多用户，如果你想运行单用户那么你运行错了。其次如果你就是想运行多用户，那么你得按多用户的配置方式来

**Comment by lingaoyi** [comment]
apt-get install build-essential 
wget https://github.com/jedisct1/libsodium/releases/download/1.0.10/libsodium-1.0.10.tar.gz 
tar xf libsodium-1.0.10.tar.gz && cd libsodium-1.0.10 
./configure && make -j2 && make install
ldconfig

这部执行了没有？ @Aniark

**Comment by lingaoyi** [comment]
原来你是用 debian7 ，我没搞过，wiki那个安装也是不成功，结果我是看别的教程才看懂...........Orz

**Comment by jillojill** [comment]
学习什么才能看懂你们说什么呢 我是遇到ss重新设置端口的问题 重新设置putty就遇到错误 说电脑拒绝 digitalocean 快要白造了


Sent from my Samsung device

-------- Original message --------

**Comment by Aniark** [comment]
@breakwa11 问题已解决，winrar解压备份压缩包会新生成同名目录并解压到该目录下，导致运行目录实际为：/shadowsocks/shaodowsocks/shadowsocks
将目录上移一层后可正常启动
my bad
