### ISSUE TITLE
3.9.3问题 没有连接数

### ISSUE THREAD

**Issue by hyphantom** [breakwa11/shadowsocks-rss#473]
![image](https://cloud.githubusercontent.com/assets/5511242/19218322/3486ed4e-8e29-11e6-95d8-6562bace010f.png)

大神 我更新了3.9.3 但是现在更新pac时都OK
但是用chrome时出现问题 无法开启连接
日志中也没有报错 3.7版本正常

**Comment by hyphantom** [comment]
3种模式都试过了

**Comment by breakwa11** [comment]
检查节点配置，部分协议在新版本里不再支持

**Comment by hyphantom** [comment]
额 好吧 应该是win10的问题 14942版本
3.7.4.1也不行了

**Comment by breakwa11** [comment]
@hyphantom 那试试3.9.4

**Comment by hyphantom** [comment]
明白 大神

**Comment by hyphantom** [comment]
3.9.4已经好了 谢谢大大 在2016年10月09日 15:00 ，破娃酱写道： @hyphantom 那试试3.9.4 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
