### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by EOmiao** [breakwa11/shadowsocks-rss#476]
建议对单一节点增加详细备注功能
即对SS进行详细节点说明，而不是单一的备注节点

备注：意大利
group：公共节点
详细说明：这是从 WWW.?????.COM 得到的节点

我表达能力不是很好，大概就上面这样

**Comment by breakwa11** [comment]
@EOmiao 用来干什么

**Comment by EOmiao** [comment]
节点太多太乱，用于区分节点信息
虽然这句话很蠢0.0.

**Comment by breakwa11** [comment]
@EOmiao 那你有用group来分组吗

**Comment by EOmiao** [comment]
有啊，我分组了，还是不够详细
我是按照地区分组，然后备注节点来源

**Comment by breakwa11** [comment]
@EOmiao 再详细的备注那还不是备注么

**Comment by mikelei8291** [comment]
@EOmiao 建议你直接把节点名称换成 `节点来源-节点位置国家代码&相同位置节点序号` 这样，拿你的例子来就写作 `www.***.com-ITA1`。这样既表明了来源，也表明了节点位置和节点序号
