### ISSUE TITLE
部署了python单用户服务端，客户端是C#版，QQ、迅雷都不能用是哪里配置错了吗？

### ISSUE THREAD

**Issue by Huayet** [breakwa11/shadowsocks-rss#478]
网页可以用 协议和混淆都是默认的，开启了UDP over TCP， ipv4和ipv6都测试失败了
网络环境：
客户端：校园内网
服务端：能连接外网的服务器

**Comment by breakwa11** [comment]
@Huayet 你都不说清楚具体什么配置，那我怎么回答你配置是不是有问题？？

**Comment by Huayet** [comment]
服务端配置文件：
{
    "server": "121.105.11.1",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "barfoo!",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "dns_ipv6": true,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}

**Comment by breakwa11** [comment]
@Huayet server那里没有必要则不要修改，协议那里客户端不再支持这个协议，另外不要使用默认端口

**Comment by Huayet** [comment]
谢谢指导~现在我改成了如下配置，QQ和迅雷仍然用不了，有可能是我这网络的问题？
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8833,
    "local_address": "127.0.0.1",
    "local_port": 3388,                    （这里填1080也不可以）
    "password": "barfoo!",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "dns_ipv6": true,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}

**Comment by breakwa11** [comment]
@Huayet 服务端不管local_port，ipv6你必须确定你有才开，最后麻烦检查防火墙，请提供Log

**Comment by Huayet** [comment]
IPv6是有的；
客户端log 最后一条是[2016-10-15 21:51:24] ShadowsocksR started
刚刚看了下，服务器防火墙是关闭了的；

**Comment by breakwa11** [comment]
@Huayet 我问的是服务端的Log

**Comment by Huayet** [comment]
- _ -  我是再win2003下运行的，是否不支持输出log到文件呢

**Comment by breakwa11** [comment]
@Huayet windows上运行服务端的情况我不清楚
