### ISSUE TITLE
YouTube视频有时候无法载入或好慢

### ISSUE THREAD

**Issue by lingaoyi** [breakwa11/shadowsocks-rss#479]
提个问题，就是YouTube视频，打开视频页面是无法载入视频或者载入很慢的样子，但只要一按刷新一下页面就很快载入到视频，看4K都很流畅的，就是经常性遇到这个问题。

Chrome浏览器

**Comment by poplar50** [comment]
我能插楼问一下你用的哪家哪个位置的vps作服务器的吗？

**Comment by lingaoyi** [comment]
阿里，香港和新加坡。

**Comment by breakwa11** [comment]
vps的首次连接可能被阻止并先探测，你用的什么协议和混淆

**Comment by lingaoyi** [comment]
@breakwa11 auth_sha1_v4, tls1.2_ticket_auth，梅林最新 2.9.9，最近情况越来越明显。

**Comment by breakwa11** [comment]
@lingaoyi 目前能100%确认，部分地区针对tls连接，首次连接会被丢包，非首次会概率性丢包，现象就是会超时，不使用tls改使用http_simple时无此现象，可能是针对tls刻章干扰

**Comment by lingaoyi** [comment]
@breakwa11 那我换一下测试 http_simple，其实之前v2 已经一直用着 http_simple，也是有一定几率出现。

**Comment by breakwa11** [comment]
你用路由器，还是C#客户端

**Comment by lingaoyi** [comment]
@breakwa11 就是路由器那种，梅林那个！

**Comment by lingaoyi** [comment]
改了http_simple之后，连GihHub都打不开，但奇怪Google和YouTube都能看，Dropbox和Instagram都用不到。

**Comment by breakwa11** [comment]
@lingaoyi 我想说句，问这问题的全是梅林的，有其它人问过一样的问题，可能要问问梅林

**Comment by lingaoyi** [comment]
@breakwa11 我给S大看看...........

**Comment by tianshi1987** [comment]
貌似我的梅林没有这个问题，用的是http_simple

**Comment by jillojill** [comment]
[root@centos-512mb-ams3-01 ~]# easy_intall pip
-bash: easy_intall: command not found
[root@centos-512mb-ams3-01 ~]# pip install shadowsocks
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): shadowsocks in /usr/lib/python2.6/site-packages


请教这个怎么解决 设置putty的时候出现的

**Comment by lingaoyi** [comment]
到最新版，我使用了v4和http_simple，还是会这样。

**Comment by breakwa11** [comment]
貌似有3.0.2还是啥版本来着是好的，你看看
