### ISSUE TITLE
路由器安装有SSR客户端和SSR服务端，手机端应该怎么设置？

### ISSUE THREAD

**Issue by liufanl** [breakwa11/shadowsocks-rss#480]
我的路由器上安装了SSR客户端，用于连接自己国外的VPS，所有GWFLIST的从VPS走。然后路由器安装了一个SSR服务端，用于安卓手机连接。现在的问题是，安卓手机端的DNS应该怎么设置，UDP转发应该怎么设置。我希望达到的目的是，手机端连上路由器的SSR服务端后，国内还是走国内网络，GWLIST的走VPS。但是目前看来，手机端DNS设置为国外DNS都会被污染。另外请教一下安卓端是怎么转发DNS请求的？

**Comment by breakwa11** [comment]
这个问题找其它人问，这里不回答这类问题

**Comment by jillojill** [comment]
[root@centos-512mb-ams3-01 ~]# easy_intall pip
-bash: easy_intall: command not found
[root@centos-512mb-ams3-01 ~]# pip install shadowsocks
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): shadowsocks in /usr/lib/python2.6/site-packages


请教这个怎么解决 设置putty的时候出现的

**Comment by breakwa11** [comment]
@jillojill 如果继续在别人的issue里刷，我就封了你
