### ISSUE TITLE
计算机睡眠再唤醒后退出ssr时Privoxy进程没有完全退出

### ISSUE THREAD

**Issue by mikelei8291** [breakwa11/shadowsocks-rss#481]
```
ShadowsocksR: 3.9.6
Windows: 10 (1607)
```
开启ShadowsocksR后计算机没有睡眠前退出ssr，`Privoxy (temp\ShadowsocksR.exe)` 及其运行库 `mgwz.dll (temp\mgwz.dll)` 会正常退出。而开启ShadowsocksR，然后计算机经过一次睡眠/休眠并唤醒后再退出ssr，`Privoxy (temp\ShadowsocksR.exe)` 及其运行库 `mgwz.dll (temp\mgwz.dll)` 会继续在后台运行

虽然目前看来并没有什么大的影响，但是我每次更新ssr时习惯直接删除temp文件夹，并且基本上会在好几次睡眠/休眠过后，所以每次都要先手动杀一下进程，感觉这样有点麻烦而已

**Comment by breakwa11** [comment]
@mikelei8291 更新时不必删目录

**Comment by mikelei8291** [comment]
@breakwa11 习惯问题，但是如果新版ShadowsocksR更新了Privoxy，然而此时该文件被进程占用，会出现什么情况呢？

**Comment by breakwa11** [comment]
@mikelei8291 会自动杀掉这个进程的

**Comment by mikelei8291** [comment]
@breakwa11 好吧，那我只能赶紧把强迫症(x)治好了
