### ISSUE TITLE
没有fs.file-max配置怎么办？

### ISSUE THREAD

**Issue by samjoeyang** [breakwa11/shadowsocks-rss#483]
centos，搬瓦工vps，sysctl文件里没有fs.file-max配置，自行补写了一行，刷新sysctl文件，报错

该怎么解决啊？

**Comment by didila** [comment]
怎么办？就别用搬瓦工啊，便宜的东西本来就是有缺陷的

**Comment by samjoeyang** [comment]
表情悲伤

> 
怎么办？就别用搬瓦工啊，便宜的东西本来就是有缺陷的

**Comment by breakwa11** [comment]
搬瓦工貌似不能改
