### ISSUE TITLE
编译breakwa11/shadowsocks-libev出错...

### ISSUE THREAD

**Issue by dNEryno** [breakwa11/shadowsocks-rss#484]
https://lh3.googleusercontent.com/LATsn7cJuLSn36sO0nCvGNCb2V6mkw29HxASWjn2PEiJBx0PxGq4uj8nclIjjWL078jvopVStO20coR2hNQit9ZTn-7cbR4Lsi07RKtYUHygsoIjRbWajSELTykL6tj-L1hkvzjR6FOFNoEd8x4uvIh39BW6bL0dJuzUUMtE_TZTnVYf-zBzhmfmeglDMa-ZwvjX50EYX-6AYqOs4UVon6CDixNM5mXeDTs0Wpo8HFGE0jKzvhu9Amj3i_32kBP1TtQzHrsR2Cd4oNJ1dDOD5_8-zNcRZ51ZH4yvasoQe9n1byAiWKL2Mox2zoAsEYlw6KZiQVZb7VFHW1Y_5d4FBQdHY1WnXaV_BrujQQbfxD4cZ5WkFUmcGVQB35WtKbaNUsKUht-MSe3WIpvPsqHkTtiDK-h3SUuGIez4KX5bbc3_XYY0xO4K3ktj71vYMMLyWQOPaVDRQde2t-B2wq5efyQY3pNHRXCmzyK01q0HDbc9OUQdoKinv8uVxehizDppD-TDIycXbP4LnSshHe52d85OxUq35fzpm8NGM93YCFNLK7o4VM9nN9LoWskxaV7sHbStO4ONwvW5M0RsV1Xm8SAkto2mp6wf35xZ_-RsxMXX2rrc=s0

**Comment by dNEryno** [comment]
如上图...

**Comment by jillojill** [comment]
[root@centos-512mb-ams3-01 ~]# easy_intall pip
-bash: easy_intall: command not found
[root@centos-512mb-ams3-01 ~]# pip install shadowsocks
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): shadowsocks in /usr/lib/python2.6/site-packages


请教这个怎么解决 设置putty的时候出现的

**Comment by jackwangshanghai** [comment]
交叉编译啊。 你 怎么Configure的。。还有为毛不opkg 既然是openwrt

**Comment by dNEryno** [comment]
不懂啥叫交叉编译....

**Comment by jackwangshanghai** [comment]
你编译用的电脑 就是X86指令系列，运行在 ARM上面 指令集不一样 这样就是交叉编译了
