### ISSUE TITLE
centos7中firewall是默认屏蔽shadowsocksR的端口的，如果使用Python版的多节点板，怎么自动开放所有有用到的端口？

### ISSUE THREAD

**Issue by kkbbzjh** [breakwa11/shadowsocks-rss#485]
centos7中firewall是默认屏蔽shadowsocksR的端口的，如果使用Python版的多节点板，怎么自动开放所有有用到的端口？端口管理的数据库在另一个服务器中，这个只是远程接过去的。

**Comment by breakwa11** [comment]
不知道，我从不管防火墙配置问题

**Comment by kkbbzjh** [comment]
哦~这样。那请问一下，连接到数据库的端口的那个函数？还是什么，例如：shadowsocksport这样一串的来代表SS的端口的东西，有吗？在那个文件能找到？我找过，但好像几个地方都有哈，不确定哪个是。
运行python server.py的时候，会打印一大堆东西，里面显示端口密码的，就是那个端口的表示，在哪里？
有点表述不清哈。。谢谢包容

**Comment by breakwa11** [comment]
你自己查查怎么开放一个端口段吧

**Comment by jillojill** [comment]
[root@centos-512mb-ams3-01 ~]# pip intall shadowsocks
ERROR: unknown command "intall" - maybe you meant "install"
[root@centos-512mb-ams3-01 ~]# pip install shadowsocks
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): shadowsocks in /usr/lib/python2.6/site-packages

请教这个怎么解决 设置putty的时候出现的

**Comment by jillojill** [comment]
[root@centos-512mb-ams3-01 ~]# easy_intall pip
-bash: easy_intall: command not found
[root@centos-512mb-ams3-01 ~]# pip install shadowsocks
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): shadowsocks in /usr/lib/python2.6/site-packages


请教这个怎么解决 设置putty的时候出现的
