### ISSUE TITLE
添加节点后是否能同时启用该节点

### ISSUE THREAD

**Issue by Ronaldo1109** [breakwa11/shadowsocks-rss#486]
是否能在 “编辑服务器” 界面 中添加节点的同时，立即启用这个节点，比如增加一个复选框，选中即启用。

(现在的操作应该是两步，先添加节点，然后右击图标→服务器→组→选择节点，如果是我孤陋寡闻了，请指教)

**Comment by wenliyang** [comment]
右击图标→服务器→服务器连接统计...

请先试一下这个功能

**Comment by breakwa11** [comment]
用服务器统计列表切换

**Comment by Ronaldo1109** [comment]
@breakwa11 可能是我写的太繁琐，没有表述重点，已经简化了问题。

因为我记得老版本是添加节点默认启用，后来版本更新后是添加节点不启用。是否能改由用户添加的同时决定是否启用。

**Comment by breakwa11** [comment]
@Ronaldo1109 我不想加这种没必要的，纯界面的选项
