### ISSUE TITLE
csharp客户端的更新链接有误

### ISSUE THREAD

**Issue by fnlctrl** [breakwa11/shadowsocks-rss#488]
ssr的csharp客户端提示我可以更新3.7.9，但那个链接却指向了官方版客户端的releases:
https://github.com/shadowsocks/shadowsocks-windows/releases?ShadowsocksR-win-3.7.9.7z

问题出在
https://github.com/breakwa11/shadowsocks-rss/blob/master/shadowsocksr-win.xml#L5-L6

但ssr的csharp客户端releases页面却没有这个版本:
https://github.com/breakwa11/shadowsocks-csharp/releases

请问这是什么情况 `_(:з)∠)_`

**Comment by breakwa11** [comment]
@fnlctrl 没有错误

**Comment by fnlctrl** [comment]
额 这两个页面都没有显示3.7.9这个版本，也没有ShadowsocksR-win-3.7.9.7z的链接可以下载啊

![11111](https://cloud.githubusercontent.com/assets/5557143/19520702/b79dfe80-9643-11e6-88b1-e5cfc09534e0.png)
![222222](https://cloud.githubusercontent.com/assets/5557143/19520703/b7c27b7a-9643-11e6-88b1-929b5c523491.png)

**Comment by fnlctrl** [comment]
所以是我漏看了什么文档吗？请明示。。。

**Comment by fnlctrl** [comment]
似乎在gitter找到了线索，如果是因为不想公开下载链接的话，那我理解了。。
