### ISSUE TITLE
建议改名

### ISSUE THREAD

**Issue by polong** [breakwa11/shadowsocks-rss#49]
改成一个是比较常用词汇的名字，因为shadowsocks这个词的特殊性，百度已经把所有shadowsocks关键词给一刀切屏蔽了，改一个常用词汇作为名字至少无法像这样一刀切屏蔽吧。

**Comment by farrellyang** [comment]
用百度，呵呵

**Comment by hope1** [comment]
@farrellyang 不可否认百度仍是也将是国内最广泛使用的搜索引擎，难道就这样拒绝传播？这种态度是不可取的。这屏蔽也不是百度的锅，任何其他公司都可能需要做同样的事，自我审查已经广泛到无法提出来作为道德审查的依据了。

**Comment by yeahwu** [comment]
叫“du niang”

**Comment by gitfreely** [comment]
叫Global travel

**Comment by falseen** [comment]
我觉得没必要改名，多起几个代名词就行了。比如前几天看到有人叫它“影末袜子”，感觉这个名字挺好的。

**Comment by hmmabc** [comment]
用百度搜不主动告诉GWF你要翻墙么？

**Comment by wenliyang** [comment]
改名没啥用吧

**Comment by fulljump** [comment]
叫这个：ying suo

**Comment by breakwa11** [comment]
例如叫做“改革开放”，正是这版本的含义

**Comment by falseen** [comment]
@breakwa11  噗。。这也太土了吧

**Comment by falseen** [comment]
我还是觉得暂时没必要改名，多起别名就行了。

**Comment by breakwa11** [comment]
正是别名，原名不会改的

**Comment by hitrust** [comment]
改革开放也不错，关键问题是这种类似的词，他们不可能屏蔽呀

**Comment by yeahwu** [comment]
改革开放，噗，妹子太油菜了！

**Comment by sxdxyxy** [comment]
能不能在新的功能里面记录局域网哪些用户在使用我的SS。

On 9/18/15, YeahWu <notifications@github.com> wrote:
> 改革开放，噗，妹子太油菜了！
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/breakwa11/shadowsocks-rss/issues/49#issuecomment-141139588


-- 
余晓云
三峡大学水利与环境学院
TEL：+86-717-6392165
MOB：+86-13307208008
MSN：yuxiaoyun@ctgu.edu.cn
QQ:23937286
blog: http://yuxiaoyun.blogspot.com
