### ISSUE TITLE
服务器端出现大量“ Connection reset by peer when connect to 8.8.8.8:53”怎么回事

### ISSUE THREAD

**Issue by gdtv** [breakwa11/shadowsocks-rss#490]
服务器用的是阿里云国内服务器。
已经在dns.conf里指定dns为：

> 223.5.5.5
> 223.6.6.6

服务器端启动的时候显示：

> asyncdns.py:324 dns server: [('223.5.5.5', 53), ('223.6.6.6', 53)]

客户端可以正常使用(尽量网速比较慢并且有时网页会刷不出来)。

但是在使用过程中服务器端出现大量错误：

> 2016-10-21 00:31:54 ERROR    tcprelay.py:844 [Errno 104] Connection reset by peer
> 2016-10-21 00:31:54 ERROR    tcprelay.py:846 when connect to 8.8.8.8:53
> 2016-10-21 00:31:55 ERROR    tcprelay.py:844 [Errno 104] Connection reset by peer
> 2016-10-21 00:31:55 ERROR    tcprelay.py:846 when connect to 8.8.8.8:53

请问这些错误是怎么回事呢？
谢谢

**Comment by breakwa11** [comment]
说明是有人的手机请求DNS，在没返回的时候就中断

**Comment by gdtv** [comment]
@ @breakwa11  只我有一个人在使用，我用的是中国电信4G网络，安卓手机，安卓的SSR客户端，请问这种情况是怎么发生的？怎么避免呢？谢谢。

**Comment by breakwa11** [comment]
@gdtv 手机的DNS请求自带了超时限制，就会产生这种log，你可以尝试修改你手机上的DNS，部分VPS请求8.8.8.8会有奇特的超时问题

**Comment by gdtv** [comment]
@breakwa11 我修改了手机上的/etc/resolv.conf文件(不知dns是不是在这个文件里改？)，改成了别的dns，并重启了手机、SSR客户端、SSR服务器端，但还是出现这个问题，不知怎么回事。

**Comment by breakwa11** [comment]
@gdtv 不是改这里，是改SSR客户端的DNS

**Comment by gdtv** [comment]
@breakwa11 我用的是这个客户端 ，好像没找到哪里可以设置DNS
https://apkpure.com/cn/ssr-%E5%BD%B1%E6%A2%AD%EF%BC%8Cshadowsocksr/in.zhaoj.shadowsocksr

**Comment by zhighest** [comment]
```plain
diff --git a/shadowsocks/tcprelay.py b/shadowsocks/tcprelay.py
index 13e010a..c58b4a9 100644
--- a/shadowsocks/tcprelay.py
+++ b/shadowsocks/tcprelay.py
@@ -489,6 +489,8 @@ class TCPRelayHandler(object):
                     data = self._handel_protocol_error(self._client_address, ogn_data)
                     header_result = parse_header(data)
             connecttype, remote_addr, remote_port, header_length = header_result
+            if remote_addr == '8.8.8.8':
+                remote_addr='119.29.29.29'
             common.connect_log('%s connecting %s:%d via port %d' %
                         ((connecttype == 0) and 'TCP' or 'UDP',
                             common.to_str(remote_addr), remote_port, self._server._listen_port))

```

**Comment by breakwa11** [comment]
@zhighest 这不应该这么改
