### ISSUE TITLE
代理规则的问题

### ISSUE THREAD

**Issue by liaobin** [breakwa11/shadowsocks-rss#491]
c#版本:3.9.6.2
代理规则:绕过局域网和大陆

在如https://detail.tmall.com/item.htm?spm=a230r.1.14.61.YkfBMB&id=523757140596&ns=1&abbucket=19 页面出现自动跳转到天猫国际的情况,切换规则到全局再换回绕过局域网和大陆就正常

**Comment by breakwa11** [comment]
解决了？

**Comment by liaobin** [comment]
没再重现,但是发现规则中少了116.31.100.*这段国内ip

**Comment by breakwa11** [comment]
@liaobin 具体段是多少，我去查查

**Comment by liaobin** [comment]
116.16.0.0	116.31.255.255	1048576  发现是包括在apnic那规则里的,但走的却是代理

**Comment by breakwa11** [comment]
我没有重现

**Comment by liaobin** [comment]
具体网站是http://www.yekepay.com/  代理模式为"不修改代理"时正常加载,代理模式为"全局模式",代理规则为"绕过局域网和大陆"时不能正常加载
