### ISSUE TITLE
编译 breakwa11/shadowsocks-libev base64.c 出错

### ISSUE THREAD

**Issue by rampageX** [breakwa11/shadowsocks-rss#492]
之前版本没问题， add auth_aes128_md5 & auth_aes128_sha1 (TCP only) 之后出的问题：

make[2]: Entering directory '/tmp/mnt/data/compile/shadowsocksR/src'
CC libshadowsocks_libev_la-local.lo
In file included from obfs.c:12:0,
from local.c:94:
base64.c: In function 'base64_decode':
base64.c:76:24: **error: array subscript is below array bounds [-Werror=array-bounds]
const signed char *base64de = base64de_table - BASE64DE_FIRST;
^~~~~~~~**

**Comment by breakwa11** [comment]
你试试改成：
```c
const signed char *base64de = (const signed char *)base64de_table - BASE64DE_FIRST;
```

**Comment by rampageX** [comment]
![2016-10-22_121711](https://cloud.githubusercontent.com/assets/994081/19616869/db9dc878-9851-11e6-9e28-87efd56134fd.png)

@breakwa11 还是一样哦

**Comment by breakwa11** [comment]
更新试试

**Comment by rampageX** [comment]
OK了，谢谢。
