### ISSUE TITLE
前端使用魔改V3但是后客户端无法正常链接，付详细配置信息。

### ISSUE THREAD

**Issue by wxhnizy** [breakwa11/shadowsocks-rss#493]
前端搭建完成正常访问以及注册http://www.72tenant.xyz/  后端搭建很多次 但依然无法正常链接服务器
运行调试service.py后网页节点显示正常 
![qq 20161022112425](https://cloud.githubusercontent.com/assets/21986327/19616608/3e3dad20-984a-11e6-92d2-6d39619de514.png)
调试信息：
![qq 20161022114805](https://cloud.githubusercontent.com/assets/21986327/19616730/6a277530-984d-11e6-84e6-0e33f751076b.png)

使用注册用户端口以及密码进行链接，网页不显示在线用户，客户端无法正常访问各种翻墙页面，客户端错误信息：
![qq 20161022112740](https://cloud.githubusercontent.com/assets/21986327/19616618/901c07cc-984a-11e6-8f32-8fd27fb1a00f.png)
检查fang'huo防火墙开启连续端口：
![o g x1xpbpcbvuo7p9 mimu](https://cloud.githubusercontent.com/assets/21986327/19616631/e0d20676-984a-11e6-9f4e-84e698d5db35.png)

![qq 20161022113347](https://cloud.githubusercontent.com/assets/21986327/19616649/6fee693a-984b-11e6-8791-f69f271e1acb.png)

保存生效防火墙并重启防火墙

完成以上步骤，但是客户端依然无法正常连接
![qq 20161022112740](https://cloud.githubusercontent.com/assets/21986327/19616657/86200a24-984b-11e6-88db-97f7220fdab6.png)
.config.php 文件只修改了 网站基本信息 以及 数据库信息，确认数据库信息无误。
![qq 20161022113721](https://cloud.githubusercontent.com/assets/21986327/19616669/eb772b64-984b-11e6-8ad6-8a3b32acac3b.png)
userapiconfig.py配置完整信息 这里也只做了 数据库信息修改，其他没有动 节点ID为3（网站以及SS是在同一个网站上做的测试数据库也在本站）
![qq 20161022113856](https://cloud.githubusercontent.com/assets/21986327/19616684/6eae2e38-984c-11e6-9082-00a6a6ce4d19.png)

以上就是我搭建SSV3的全部过程，我反复反复重新安装了很多遍 ，但是问题依然无法解决，我不知道我哪里做错了 ~防火墙也反复开启并关闭也不行，完全关闭防火墙也不行。如果你需要其他的信息我可以随时补充，万分感谢。

**Comment by breakwa11** [comment]
不是我的版本不要问我问题

**Comment by wxhnizy** [comment]
@breakwa11 但是我的后端使用的就是shadowsocks-rss 只不过 前端使用的 是魔改而已~

**Comment by breakwa11** [comment]
@wxhnizy 后端也不是我的版本，你要去找作者

**Comment by glzjin** [comment]
大兄弟 目测你这个后端也是我改过的

**Comment by wxhnizy** [comment]
@glzjin 大哥是的你说的对 就是你推荐的版本，我在你那里提问你不予理财~我附上了所有的配置信息～

**Comment by glzjin** [comment]
我忙。。。。我会抽时间看看的。。。

**Comment by wxhnizy** [comment]
@glzjin 这个问题貌似我并不是个案，他们重装后就正常了，而我一直过不去　～每次重装都是这个问题～好的谢谢

**Comment by asan1148** [comment]
我也遇到这个问题了  不知道如何解决

**Comment by chinawenxu** [comment]
一样的问题，前面节点列表里节点是正常的，但用的时候节点就是无法连接。
