### ISSUE TITLE
libev 版用  MbedTLS 库编译出错

### ISSUE THREAD

**Issue by rampageX** [breakwa11/shadowsocks-rss#495]
![2016-10-22_211642](https://cloud.githubusercontent.com/assets/994081/19619578/39066b1e-989d-11e6-8ecb-a783ea9660f1.png)

如图，OpenSSL 没问题。

**Comment by breakwa11** [comment]
哦，你在它提示的地方加上类型转换就好，或者等晚点我改

**Comment by breakwa11** [comment]
你更新看看还有没有问题

**Comment by rampageX** [comment]
好了，Thanks。
