### ISSUE TITLE
问个关于选项设置里dns的问题

### ISSUE THREAD

**Issue by liaobin** [breakwa11/shadowsocks-rss#496]
模式设为全局的话是以选项设置里的dns解析为准么,为什么dns设置成119.29.29.29的情况下,Facebook能正确打开呢?从nslookup来看解析应该是受污染的...

**Comment by breakwa11** [comment]
@liaobin 全局就根本没管dns好吧

**Comment by liaobin** [comment]
代理规则是绕过局域网及大陆

**Comment by liaobin** [comment]
另外代理规则切换的时候,只有重启客户端才能生效


![123](https://cloud.githubusercontent.com/assets/7258927/19624050/1e09955e-9918-11e6-83d3-c576c6e3baf2.jpg)

**Comment by breakwa11** [comment]
@liaobin 切换后是立即生效，另外你这图到底是什么站

**Comment by liaobin** [comment]
这站是ipip.net.

另外模式设为全局,代理规则为绕过局域网及大陆的情况下,选项设置里的dns解析结果不在delegated-apnic列表内的话,域名是直接交给远程dns解析吗

**Comment by breakwa11** [comment]
@liaobin 是的
