### ISSUE TITLE
请问shadowsocks-rss服务器端是否支持UDP转发

### ISSUE THREAD

**Issue by gdtv** [breakwa11/shadowsocks-rss#500]
请问shadowsocks-rss服务器端是否支持UDP转发

**Comment by Joney0210** [comment]
支持的，都有udprelay.py文件呢
但是不知道怎麼使用，以及怎麼測試。

比如在Shadowsocks-lib放在DDwrt時，有個-u 的參數可以下。但是我怎麼知道UDP 轉發了呢？沒有地方可以看到啊。
在OSX上我使用SahdowsocksX-R 1.3.7（1）, 在高級設置中也可以勾選啓用UDP replay，但是一樣問題，我在LOG檔案中都完全沒有看到UDP 字眼。

在Wiki 中，似乎也沒有找到UDP relay 的使用方法。python server.py -h 也是沒有看到使用方法。

**Comment by breakwa11** [comment]
@Joney0210 没有关闭的开关，要启动就开了UDP

**Comment by Joney0210** [comment]
這可以理解。
照這麼說，若是使用Shadowsocks-Lib版本在DDwrt上，是不是只要是連接上了，UDP relay就是開啓的呢？
能否提供一個測試方法？

**Comment by breakwa11** [comment]
直接用你需要用UDP的应用去测试
