### ISSUE TITLE
win7 日志显示没问题 但是无法翻墙

### ISSUE THREAD

**Issue by 000luc** [breakwa11/shadowsocks-rss#502]
在舍友的电脑上能够正常使用，我把系统升级成win10后莫名其妙又能用了，可是win10有点卡 而且用不惯 还是装回了win7 然后又用不了了 win7是下的官方纯净的

使用的是ssr 3.3.1     配置文件直接从网站上下载的应该没问题 手机能翻电脑却不能 

ssr日志就显示一句ShadowsocksR started on port 1080    能够上国内网站但却无法翻墙

尝试过其他版本也不行 ss也不行 全局PAC都试过了 小白不太懂电脑 尝试重装win7过后还是这样 实在找不到问题到底在那了

**Comment by breakwa11** [comment]
@000luc 3.3.1这版本是什么鬼

**Comment by 000luc** [comment]
@breakwa11 ..看错了是ssr 3.9.6.2 3.3.1是ss的

**Comment by breakwa11** [comment]
@000luc 检查exe的属性是不是有个锁定，要去掉

**Comment by 000luc** [comment]
@breakwa11 检查exe的属性 是指直接右键的那个菜单里的属性。。？ 属性里所有选项卡里都没有见锁定两个字啊

**Comment by breakwa11** [comment]
那再检查一下你的IE是不是开启了保护模式，要关掉

**Comment by breakwa11** [comment]
防火墙呢

**Comment by 000luc** [comment]
@breakwa11 关了防火墙也不行

**Comment by didila** [comment]
我一听到三种使用共用网络的环境都建议不要翻墙：宿舍、使用小型isp（例如长宽）、写字楼

**Comment by 000luc** [comment]
@didila 我是大学宿舍 但是没有共用吧 每个人单独电信的 有什么影响吗

**Comment by breakwa11** [comment]
你目前提供的信息无法确定原因，请提供更多的信息

**Comment by 000luc** [comment]
@breakwa11 我也找不到能反应问题的线索了…关闭吧
