### ISSUE TITLE
新版节点多用户配置文件如下 显示no usr in db 

### ISSUE THREAD

**Issue by jameseroyi** [breakwa11/shadowsocks-rss#508]
![screenshot_1](https://cloud.githubusercontent.com/assets/17232892/19758249/d5bb748a-9c59-11e6-917c-2f668fd950a0.jpg)
![Uploading 0~Z~GBB4A5TTW8X5C@570BN.png…]()

这是什么问题 求教

**Comment by breakwa11** [comment]
用户列表是空的

**Comment by jameseroyi** [comment]
不知道该怎么排查原因了 远程数据库是打开的 usermysql 也配置了～～

**Comment by breakwa11** [comment]
都说了，用户列表是空的，你查过这个列表没有

**Comment by jameseroyi** [comment]
没事了 我api接口搞错啦   谢谢～～

**Comment by jameseroyi** [comment]
搞定了 我api接口之前填错了 没事了 谢谢～～

2016-10-27 15:51 GMT+08:00 破娃酱 <notifications@github.com>:
