### ISSUE TITLE
服务端程序自动停止工作

### ISSUE THREAD

**Issue by suyuanhxx** [breakwa11/shadowsocks-rss#509]
我在centos上运行服务端脚本一段时间后，客户端就连不上了，然后直接start居然可以，端口没有被占用，说明服务挂了。我在好几台VPS上运行都是这样，我完全按照wiki上的步骤操作的。
客户端能不能不要搞那么深的目录结构，希望能够将部分组的节点默认放在一级目录下

**Comment by breakwa11** [comment]
检测log中的NOFILE_LIMIT
