### ISSUE TITLE
加密方式是否更新下chacha20, salsa20支持？

### ISSUE THREAD

**Issue by tudi1909** [breakwa11/shadowsocks-rss#51]
如题，现在需要可否更新下支持chacha20, salsa20加密方法？感谢

**Comment by tudi1909** [comment]
辛苦作者了

**Comment by akw28888** [comment]
@tudi1909 這兩個是支持的喔，不過需要先compile好libsodium
參考https://github.com/shadowsocks/shadowsocks/wiki/Encryption#salsa20-and-chacha20
