### ISSUE TITLE
关于 SS原版android客户端 连接 SSR服务端的问题

### ISSUE THREAD

**Issue by Wrecking-Ball** [breakwa11/shadowsocks-rss#510]
我想用 shadowsocks-android客户端（https://github.com/shadowsocks/shadowsocks-android/releases）

连接 SSR 服务端。
请问：1，SSR服务端的  协议  可以设置为 哪些？
           2，SSR服务端的  混淆  可以设置为 哪些？

**Comment by breakwa11** [comment]
所有支持兼容的协议和混淆
