### ISSUE TITLE
python服务端不能被iptables的nat表中的PREROUTING链REDIRECT目的端口

### ISSUE THREAD

**Issue by liufanl** [breakwa11/shadowsocks-rss#515]
作者，我在路由器上安装的是python服务端，版本是“2.9.6 2016-10-17”。nat表中的PREROUTING链有一条REDIRECT目的端口的规则。局域网内机器的能匹配这条规则，但是我从外网通过SSR客户端连接到SSR服务器端，然后服务器端转出的连接就不能匹配这条规则。我想请教一下，SSR服务端对外连接，是使用的路由器的WAN地址，还是LAN地址？这个连接有加密码？

**Comment by breakwa11** [comment]
你想想外网会通过NAT表？

**Comment by liufanl** [comment]
@breakwa11 服务器端是装在路由器上的。如果路由器上的服务器端用路由器的LAN地址，比如192.168.1.1，应该就需要过NAT表了吧？除非路由器上的服务器端直接用的WAN口的公网地址，就不需要走NAT了。不知道能不能把服务器端设置成走LAN地址？
