### ISSUE TITLE
请站说明新TCP协议等在SS服务端的设置方法

### ISSUE THREAD

**Issue by jang-u** [breakwa11/shadowsocks-rss#52]
自建SS服务端，未接触过windows以外的系统，折腾了好久才搞定

debian64，python版SS服务端

请教如何在服务端设置新TCP协议及其他RSS特有的协议？

方便的话，请说明针对不同系统，不同SS版本的服务端设置，本人还折腾过CentOS系统，SS还弄过libev等版本

谢谢

**Comment by falseen** [comment]
新协议服务端不用设置，部署新版服务端就行了，客户端要用的话勾选对应的选项就行了。

注意：用pip方式安装的都是旧版ss，新版ss的话要到这里下载 https://github.com/breakwa11/shadowsocks

**Comment by jang-u** [comment]
先谢谢楼上
本人小白，安装服务端折腾了三天，网上查了各种教程，最后用这个成功了：
---------------------------
首先更新系统
apt-get update
apt-get upgrade

因为是Ubuntu或者debian，所以用apt-get是很方便的

安装pip和m2crypto，pip安装shadowsocks
apt-get install python-pip python-m2crypto supervisor
pip install shadowsocks

建立配置文件 /etc/shadowsocks.json 
vi /etc/shadowsocks.json
{
    "server":"服务器 IP 地址",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"mypassword",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false,
    "workers": 1
}

建立/etc/supervisor/conf.d/shadowsocks.conf
vi /etc/supervisor/conf.d/shadowsocks.conf
[program:shadowsocks]
command=ssserver -c /etc/shadowsocks.json
autorestart=true
user=root

如果端口 < 1024，把上面的 user=nobody 改成 user=root。

在 /etc/default/supervisor 最后加一行 
ulimit -n 51200
----------------------------

小白完全看不懂上面是神马意思，机械的按上面的教程一步步做的，终于搞成了
现在有个不情之请，麻烦按上述一步步的顺序，把新服务端的搭建过程完整地讲一遍，否则怕搞坏了原来的服务端都不能用，谢谢

**Comment by shuangzhijinghua** [comment]
直接带参数启动不就行了，写配置文件多麻烦
ssserver -p 端口 -k 密码 -m 加密 -d start

jang-u <notifications@github.com>于2015年9月12日周六 上午12:01写道：

**Comment by falseen** [comment]
```
cd /root
git clone  https://github.com/breakwa11/shadowsocks.git
cd shadowsocks
```
* 建立配置文件 /etc/shadowsocks.json 
```
vi /etc/shadowsocks.json
{
"server":"服务器 IP 地址",
"server_port":8388,
"local_address": "127.0.0.1",
"local_port":1080,
"password":"mypassword",
"timeout":300,
"method":"aes-256-cfb",
"fast_open": false,
"workers": 1
}
```

* 建立/etc/supervisor/conf.d/shadowsocks.conf
（如果你的shadowsocks不在root目录的话，请自行替换成对应的目录）
```
vi /etc/supervisor/conf.d/shadowsocks.conf
[program:shadowsocks]
command= nohup  python /root/shadowsocks/server.py -c /etc/shadowsocks.json
autorestart=true
user=root

```

**Comment by jang-u** [comment]
谢谢
原来搭好的服务端要删掉吗？

**Comment by falseen** [comment]
想删就删，不想删留在那里也没什么。只是开机启动要取消掉。

```
[program:shadowsocks]
command=ssserver -c /etc/shadowsocks.json
autorestart=true
user=root

```
把你原来的这一段删掉，替换成我发的最后一段，就等于取消了原来的开机启动。

**Comment by jang-u** [comment]
感谢各位大侠，支持新TCP协议的客户端弄好了
本人小白，知道还有很多小白可能一头雾水，斗胆写个过程，供小白们参考，也请各位大侠指正

系统：Debian64
SS版本：就是这里的shadowsocks-RSS Python 版
使用软件：Xshell 和 Xftp，这两个比putty界面友好容易上手

更新系统（这步是否必须？不清楚的还是做吧，很快的）
apt-get update
apt-get upgrade

安装SS（这步好像不需要，请大侠指正）
apt-get install python-pip
pip install shadowsocks

安装python-m2crypto，据说装了这个加密会快一点
apt-get install python-m2crypto

安装git，不装下一步克隆出错
apt-get install git

克隆shadowsocks-RSS服务端
cd /root
git clone https://github.com/breakwa11/shadowsocks.git

创建/编辑配置文件（可以用xftp直接修改更直观）
vi /etc/shadowsocks.json
{
    "server":"my_server_ip",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"mypassword",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false
}

创建/编辑自运行文件
vi /etc/supervisor/conf.d/shadowsocks.conf
[program:shadowsocks]
command= nohup python /root/shadowsocks/shadowsocks/server.py -c /etc/shadowsocks.json
autorestart=true
user=root

重启
reboot

以后服务端升级了，只要再克隆一遍就可以了，对吗？
cd /root
git clone https://github.com/breakwa11/shadowsocks.git

**Comment by dengcb** [comment]
谁能告诉我，新协议要是想要在osx上用的话，有没有对应的客户端，之前用的shadowsocksX吧，现在呢？

**Comment by falseen** [comment]
@dengcb 暂时没有。

**Comment by dengcb** [comment]
@falseen 期待x客户端能早日支持新协议

**Comment by ruleroller** [comment]
@falseen 按照你提供的 git clone  https://github.com/breakwa11/shadowsocks.git ，这安装的是不支持新协议的manyuser版本吧？我安装之后，客户端勾选了‘TCP over UDP“，网页就打不开了。

manyuser版本也可以根据你的方法安装和使用吗？wiki里数据库到底是什么意思，这个必须按照它上面写的配置吗？

**Comment by falseen** [comment]
@ruleroller
那你用manyuser版试试 `git clone -b manyuser https://github.com/breakwa11/shadowsocks.git`

manyuser版跟master版在使用上差不多，git之后根目录的是多用户版(带数据库的)，子目录是单用户版。

数据库是给站长做网站用的，个人用户的话不用管，直接启动子目录的server.py就行了。

**Comment by sofs2005** [comment]
其实女神现在的教程已经很清楚了

**Comment by farrellyang** [comment]
最新单用户版配置文件里，我写了“obfs”的设置，最新客户端也选择了http_simple似乎能用，但release log里没说明单用户版现在支持obfs啊
