### ISSUE TITLE
建议把服务器连接统计移到一级菜单

### ISSUE THREAD

**Issue by yjd** [breakwa11/shadowsocks-rss#524]
新版每次要看数据得跑到二级去，鼠标移老半天才能定位到，非常不方便。和原来右键上移一下就到差距老大。
服务器连接统计和断开所有当前连接 移到一级菜单。
基本上服务器配置完，用到的最多功能也就这个

**Comment by breakwa11** [comment]
@yjd 请自行查wiki看看快捷操作

**Comment by yjd** [comment]
单击任务栏图标弹出服务器配置窗口，Shift+单击弹出选项窗口，而右键图标弹出菜单
中键点击任务栏图标弹出服务器连接统计窗口

双击托盘图标目前和单击重复了。建议把鼠标中建改成双击。人性化点。符合操作习惯。也方便。
以前用的gae系那些也都是双击出现状态窗口。
@breakwa11

比如我这渣鼠标滚动还可以。但是往下按硬得很要非常用力。

**Comment by breakwa11** [comment]
@yjd 这里根本就没有说有双击，哪来的双击

**Comment by yjd** [comment]
@breakwa11
应该是我双击托盘。第一次点就触发了单击功能。
别的语言是有单击，双击，右击事件。
有源码，我自己修改编译一个。。。
