### ISSUE TITLE
如何加速公司内部跨国vpn

### ISSUE THREAD

**Issue by bleachbl** [breakwa11/shadowsocks-rss#525]
公司内部建了个 vpn ，发布代码时是通过这个 ipsec vpn 连接到英国总部的服务器，但觉得速度比较慢 

请问有什么办法可以加速？目前有台美国 vps+shadowsocks 用来翻墙，有何办法可以利用这个资源来加速？

**Comment by sueccku** [comment]
先试试用美国的服务器连英国的速度怎么样，块的话先用美国的连英国的，然后ss回来，试试能不能好点，不过美国的服务器延迟基本都是200+，可能意义不大
