### ISSUE TITLE
什么时候开发mac版本呀？如果需要我可以帮忙开发

### ISSUE THREAD

**Issue by vbonluk** [breakwa11/shadowsocks-rss#526]
什么时候开发mac版本呀？如果需要我可以帮忙开发

**Comment by breakwa11** [comment]
已经有了

**Comment by vbonluk** [comment]
怎么没见放上项目的readme文件的？首页都没有看到mac版哦😄来个链接可好？

**Comment by breakwa11** [comment]
https://github.com/qinyuhang/ShadowsocksX-NG
https://github.com/yichengchen/ShadowsocksX-R
