### ISSUE TITLE
添加域名到pac，如何生效

### ISSUE THREAD

**Issue by iamcomein** [breakwa11/shadowsocks-rss#527]
请问是否是直接将域名添加到这里面，添加后保存时立即生效吗
如何添加ip呢
var white_domains = {"biz":{
"changan":1,
"kuangchan":1
},"cc":{
"2che":1,
"55g":1,
"7mo":1,
"chengche":1,
"dqccc":1,

**Comment by breakwa11** [comment]
其实并不建议自己改，改完不是立即生效的，要重启客户端

**Comment by wkingfly** [comment]
@iamcomein 不知道你用的哪个客户端， **ShadowsocksX** 可以编辑这个文件，即时生效的 

    vim ~/.ShadowsocksX/gfwlist.js
