### ISSUE TITLE
求VPS自建DNS教程

### ISSUE THREAD

**Issue by jang-u** [breakwa11/shadowsocks-rss#53]
现在用境外的DNS速度不快，想自建一个，请教几个问题

53端口暴露了，是否会导致VPS的ip地址被封锁？

debian 7.8 ，求个VPS自建DNS的详细教程
之前网上找到一个教程，照着做，最后显示53端口已被占用，没搞定

有说可以更改默认53端口到其他端口，但是客户端（windows）这边要怎么设置？

谢谢！

**Comment by shuangzhijinghua** [comment]
iptables -t nat -A PREROUTING -p udp -d VPS的IP --dport 5353 -j DNAT
--to-destination 8.8.8.8:53
iptables -t nat -A POSTROUTING -p udp -d 8.8.8.8 --dport 53 -j SNAT
--to-source VPS的IP

两条即可将VPS的5353端口转发至8.8.8.8的53端口，目前使用非标准端口DNS不受污染。

jang-u <notifications@github.com>于2015年9月12日周六 下午1:47写道：

**Comment by jang-u** [comment]
先谢谢楼上
本人小白，DNS尚未搭建成功
网上查过，有几个方案，楼上的是哪一种？

还有，windows里面怎么设置dns的端口是5353？

**Comment by shuangzhijinghua** [comment]
客户端必须借助端口转发工具把本机不得53转到VPS的5353端口，推荐passport。任何直接发网境外的DNS查询都会受到污染，不管目的地是哪里

jang-u <notifications@github.com>于2015年9月12日周六 下午1:55写道：

**Comment by breakwa11** [comment]
可以用dns2socks，让socks5代理可作为DNS服务器，然后本地搭建pdnsd做缓存
