### ISSUE TITLE
auth_aes128_md5协议在某Win10上无法使用，浏览器访问返回连接重置

### ISSUE THREAD

**Issue by LoadingZhang** [breakwa11/shadowsocks-rss#530]
用原版协议正常，用auth_aes128_md5就重置连接。
同一账号在其他设备上正常。

**Comment by breakwa11** [comment]
@512557852 检查服务端配置是否正确

**Comment by 512557852** [comment]
@breakwa11 正确的，因为同一账号相同参数在其他设备上能够使用

**Comment by breakwa11** [comment]
那请问具体配置是什么，什么客户端

**Comment by 512557852** [comment]
用的是aes-256-cfb/auth_aes128_md5/tls1.2_ticket_auth
客户端3.9.6.2
也是第一次碰到这情况，排查发现改成origin就好了

**Comment by breakwa11** [comment]
@512557852 请站在我的角度看看，如果要帮你解决问题，可能需要什么。你只给这个，当我是世界级猜谜语大师？你到底想不想解决问题的？麻烦服务端配置文件整个发来，以及客户端节点配置，连同密码，ip你可以删掉

**Comment by 512557852** [comment]
以下是C#客户端配置文件
{
    "index": 1,
    "random": false,
    "sysProxyMode": 2,
    "shareOverLan": false,
    "bypassWhiteList": false,
    "localPort": 1080,
    "reconnectTimes": 4,
    "randomAlgorithm": 0,
    "TTL": 60,
    "connect_timeout": 5,
    "proxyEnable": false,
    "pacDirectGoProxy": false,
    "proxyType": 0,
    "proxyHost": "",
    "proxyPort": 0,
    "proxyAuthUser": "",
    "proxyAuthPass": "",
    "proxyUserAgent": "",
    "authUser": "",
    "authPass": "",
    "autoBan": false,
    "sameHostForSameTarget": true,
    "keepVisitTime": 180,
    "isHideTips": false,
    "dns_server": "",
    "proxyRuleMode": 1,
    "token": [],
    "portMap": [],
    "configs": [
        {
            "remarks": "Japan_Tokyo",
            "server": "Hide",
            "server_port": 50245,
            "method": "aes-256-cfb",
            "obfs": "tls1.2_ticket_auth",
            "obfsparam": "",
            "remarks_base64": "SmFwYW5fVG9reW8=",
            "password": "EWsRSJ",
            "tcp_over_udp": false,
            "udp_over_tcp": false,
            "group": "Loading Shadows",
            "protocol": "auth_aes128_md5",
            "obfs_udp": false,
            "enable": true
        }
    ]
}

**Comment by 512557852** [comment]
服务用的赵大的后端，user-config.json内容如下
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "m",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "auth_sha1_v4_compatible",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "dns_ipv6": true,
    "connect_verbose_info": 0,
    "connect_hex_data": 0,
    "redirect": "",
    "fast_open": false
}

**Comment by glzjin** [comment]
发下服务端的完整日志

**Comment by 512557852** [comment]
因为换个电脑使用正常，觉得服务器端的问题可能性不大。
问题机上之前也能正常使用，在一次WIN10更新后无法使用auth_aes128_md5？不知道是否与此有关。
不知道C#客户端是否依赖系统某些文件导致的。
谢谢大姐姐和赵大

**Comment by 512557852** [comment]
服务器ss日志已清除，端口已正常开启
db_transfer.py:475 db start server at port [50245] pass [EWsRSJ] protocol [auth_aes128_md5_compatible] obfs [tls1.2_ticket_auth_compatible]
server_pool.py:138 starting server at [::]:50245
server_pool.py:165 starting server at 0.0.0.0:50245
当时客户端使用的时候tail -F ss日志，没有任何输出
