### ISSUE TITLE
PC版SSR客户端，在浏览器中不使用PAC，也会走分流

### ISSUE THREAD

**Issue by trlanfeng** [breakwa11/shadowsocks-rss#533]
系统：Win10
SSR客户端版本：3.9.6.2
因公司网络限制，很多网站都无法正常访问，所以默认在客户端中我使用PAC方式连接，但在chrome浏览器中，我使用switchyOmega插件，经常会想在此浏览器中全局代理使用，但通过协议方式时不会默认走全局，依然会分流。有什么解决办法可以让chrome全局走代理，而系统继续使用PAC方式。

**Comment by breakwa11** [comment]
@trlanfeng 请确认客户端的代理规则设置为全局

**Comment by trlanfeng** [comment]
感谢，设置代理规则后问题解决。
