### ISSUE TITLE
Hi dear Breakwa11, i can't use the c# api to modify the config

### ISSUE THREAD

**Issue by vtroop** [breakwa11/shadowsocks-rss#534]
Dear Breakwa11,
hi,
i want to use c# api to access the software. i follow the manual:
1. add token to the config
    "token" : {
        "testapp" : "123456"
    },
2. restart the software
3. http get to access it
 (http://127.0.0.1:1080/api?action=config&app=testapp&token=123456) 

However, i get 400 status response (Invalid header received from client.).
please, tell me what's the problem?

i'm grateful for your help.
THX again.

**Comment by breakwa11** [comment]
@vtroop sorry, there is a "auth" key must be set, you can find the value from config or PAC address

**Comment by vtroop** [comment]
@breakwa11 it works. Thanks a lot : )
