### ISSUE TITLE
为什么要用tcp over tcp

### ISSUE THREAD

**Issue by sueccku** [breakwa11/shadowsocks-rss#535]
tcp over tcp 已经被证明了不是一个好主意，为什么要用？查了好多资料，全是howto的，深层研究的很少，哪位大神来科普一下，另外求几篇深度解析ss原理的文章

**Comment by breakwa11** [comment]
你说的是什么鬼

**Comment by Laforeta** [comment]
http://sites.inka.de/bigred/devel/tcp-tcp.html

简单的说，两层TCP封装的流控和重传机制会相互干扰。在高延时高丢包的环境下效率会很差。但是这个也只是相对而言，IKEv2之类的协议默认走UDP模式也是这个原因，同时保留了TCP模式备用。

如果觉得链路质量需要进一步优化的可以用kcptun之类的udp转发工具。

**Comment by breakwa11** [comment]
和这项目有啥关系？

**Comment by sueccku** [comment]
这个问题停了吧，完全是我傻了个逼，传输的根本不是数据包，何来udp/tcp over xxx
