### ISSUE TITLE
怎么给PS4做代理呢。

### ISSUE THREAD

**Issue by hushlover86** [breakwa11/shadowsocks-rss#536]
不好意思，不知道在哪里问合适。
一直用SS看网页，然后用再弄个PPTP给游戏做代理。
后来发现实在好麻烦。。
看了SS更新，全能代理。
所以想问，是不是现在SS也能给游戏软件加速了。要如何操作呢。。
谢谢

**Comment by bugparty** [comment]
可以加速，你用的什么平台什么软件？

**Comment by hushlover86** [comment]
其实是想把整个PS4的网络都走SS。。。。

**Comment by bugparty** [comment]
大哥你会回答问题不

**Comment by hushlover86** [comment]
不太理解你说的平台是啥，软件是啥。。
系统：win 10
代理软件:shadowsocks-rss

**Comment by bugparty** [comment]
你可以下载proxifer，具体教程搜 用proxifer加速游戏

**Comment by hushlover86** [comment]
谢谢

**Comment by wkingfly** [comment]
**polipo** 也可以

**Comment by saladinxp** [comment]
proxifer 据说不支持udp转发
最好的办法是买个 华硕或者美国网件，刷梅林改版固件，然后路由器挂ss就能玩了
