### ISSUE TITLE
客户端界面右侧的二次元萌图有办法隐藏吗？

### ISSUE THREAD

**Issue by 70599** [breakwa11/shadowsocks-rss#537]
给不太熟的老同事用，有点羞耻

**Comment by breakwa11** [comment]
@70599 显示过一次二维码后保存下次默认隐藏

**Comment by yjd** [comment]
能否提供个启动外部程序的接口，方便配置。
这样设置开机启动ssr，顺带把cow，kcptun也都跑起来。

**Comment by breakwa11** [comment]
@yjd 这里不是你的issue，在别人的地方提问一律不回答

**Comment by yjd** [comment]
本来想自己改，vs真够庞大而且你的编译版本还是2015比较新。不了了之。准备自己写个dll

**Comment by yjd** [comment]
用dll。
![111](https://cloud.githubusercontent.com/assets/6856740/20922827/809d50fe-bbe4-11e6-8de3-39c94d6322b9.gif)

**Comment by biweijie751107089** [comment]
其实我是想知道如何再把这个调出来

**Comment by breakwa11** [comment]
@biweijie751107089 点一下让其显示二维码，然后左边节点列表点一下换一个
