### ISSUE TITLE
请教关于不同混淆方式对延时的影响的细节

### ISSUE THREAD

**Issue by cccatcc** [breakwa11/shadowsocks-rss#539]
在混淆文档中有看到，使用tls1.2_ticket_auth混淆方式会使延迟增加一次通讯往返时间，于是我特意下载了日服LOL客户端进行测试，在同一台电脑同一网络环境使用同一个自建节点（SAKURA东京），先后分别使用了tls1.2_ticket_auth与http_simple进行游戏，并确保所有UDP流量经过ShadowsockR，两次测试中游戏客户端右上角显示的延时几乎一致。请问是因为tls1.2_ticket_auth混淆方式只对首个数据包产生延时的影响吗？还是因为游戏客户端没有能够正确测得实际延时？如果是后者，请问有什么简便有效的方法测得不同混淆方式对延时产生的影响？

**Comment by breakwa11** [comment]
@cccatcc 仅影响连接在刚连接时的延迟，如果已经连接上，不管哪种混淆或协议怎么测延迟都是一样的
