### ISSUE TITLE
ShadowsocksR-dotnet2.0-3.4.2和ShadowsocksR-dotnet4.0-3.4.2有啥区别？

### ISSUE THREAD

**Issue by chumuye** [breakwa11/shadowsocks-rss#54]
ShadowsocksR-dotnet2.0-3.4.2和ShadowsocksR-dotnet4.0-3.4.2有啥区别？win10 64位用哪个好？

**Comment by aprikyblue** [comment]
目测只是.NET Framework版本的区别。。。
win10无所谓，自带4.0，遇到需要2.0的程序也会提示下载

**Comment by shuangzhijinghua** [comment]
哪个能用用哪个

Aprikyblue <notifications@github.com>于2015年9月12日周六 下午9:48写道：

**Comment by shikkoku** [comment]
无非就是.Net4.0是用版本较新的编译，免得在较新的系统版本中提示下载旧版本框架。
