### ISSUE TITLE
使用最新c#版本运行不久便自动退出 exe和签名文件应该没有问题

### ISSUE THREAD

**Issue by Dwwwwww** [breakwa11/shadowsocks-rss#544]
什么都不干就会炸 net2.0/4.0均如此 点端口设置也会炸而且会弹出来个提示框 Windows10 x64【只有我有这问题吗= =
![image](https://cloud.githubusercontent.com/assets/13995937/20863217/99bcc890-b9fe-11e6-8280-32221cb04728.png)

Details:

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。
************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.View.PortSettingsForm.GetDisplayText(Server s)
   在 Shadowsocks.View.PortSettingsForm.LoadConfiguration(Configuration configuration)
   在 Shadowsocks.View.PortSettingsForm.LoadCurrentConfiguration()
   在 Shadowsocks.View.PortSettingsForm..ctor(ShadowsocksController controller)
   在 Shadowsocks.View.MenuViewController.ShowPortMapForm()
   在 Shadowsocks.View.MenuViewController.ShowPortMapItem_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
ShadowsocksR
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.0.0
    基本代码: file:///D:/Workspace/Windows/Shadowsocks-win/ShadowsocksR-dotnet2.0.exe
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Drawing.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing.resources/2.0.0.0_zh-CHS_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
System.Configuration
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8745 (WinRel.050727-8700)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。
例如: 
<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by Dwwwwww** [comment]
顺便 为啥2.0的框是中文 4.0的是英文（手动滑稽）

**Comment by Dwwwwww** [comment]
校验文件在同一目录下
ShadowsocksR-4.0.0e-win.7z MD5：84732D97E7052097AAC173B5216614E7

**Comment by breakwa11** [comment]
看Telegram上的公告说明。。。
