### ISSUE TITLE
ss链接的生成规则

### ISSUE THREAD

**Issue by erguotou520** [breakwa11/shadowsocks-rss#546]
可以问下ss链接生成的规则是什么？就是`ss://xxx`这个链接的生成规则，另外qrcode应该就是由这个链接直接生成的二维码吧

**Comment by breakwa11** [comment]
ss链接见shadowsocks.org

**Comment by erguotou520** [comment]
但是ssr里不是有一些其它的参数么？这个没有影响么？

**Comment by breakwa11** [comment]
但你问的是SS，不是SSR

**Comment by erguotou520** [comment]
呃，好吧，ssr的链接是怎么个生成规则？

**Comment by breakwa11** [comment]
@erguotou520 wiki里写了，看看吧
