### ISSUE TITLE
对新协议的格式讨论。

### ISSUE THREAD

**Issue by wdhwg001** [breakwa11/shadowsocks-rss#55]
ss作为一个简单的协议，有着许多的遗留问题。
比较突出的是对丢包的不可控，以及对错误数据的不可控。

例如，在使用手机版twitter的时候，图片花屏率相当高。

这一次@breakwa11 为ss引入了crc32机制，所以我想到了更新协议，改善历史遗留问题的可能。

我抛个砖先，个人认为偏移环+crc是更可靠的方法：

    偏移(1byte)|[原ss数据包|CRC|随机数据]
    偏移使用密码进行简单的xor，以隐藏其数值较小的可能特征。
    []中的数据，以第[偏移]位为首部，进行环形偏移。
    包长度是不需要的，因为ss数据包本身是完整的。
    同样的，因为ss是一个预先约定加密方式的代理，所以版本号也是不需要的。
    偏移的存在极大的增加了数据的混乱程度，使得根据位数进行的分析从根本上变为了不可能，他们甚至连crc字段在哪里都无法确定。
    服务器端以合适的随机数初始化偏移，并追加不太长的随机字串，发送数据包。
    客户端的逻辑与服务器端相同，但请保证随机字串长度和偏移值均不相等，且两个随机字串中较小的不是较大的一部分。

唔……本想设计一个把偏移进行递减以充当ttl的设计的，不过tcp本身就存在一定程度的顺序维持…

以及题外话，我个人比较喜欢--relay-port和config中对relay-port的设置。转发至网站或者webserver或者其他服务这样的工作，应该交由其他的轮子去做，而不是ss…

以及题外话v2.0，可以将旧协议服务器端开在新协议服务器端的relay-port上，以完成对旧协议的兼容，同时再把其他的轮子挂在旧协议服务器端的relay-port上完成转发。

**Comment by breakwa11** [comment]
回答我一个问题，首包与第二包粘包的话怎么处理？

**Comment by wdhwg001** [comment]
@breakwa11 是我的问题。那么，尝试将“剩余长度”写至[]中如何？

    偏移(1byte)|[剩余长度|原ss数据包|CRC|随机字串]

这样呢？

**Comment by breakwa11** [comment]
原ss数据包的长度未知，这样会依赖于原数据包头的解释，而且既然有crc，这样偏移也没有什么意义，不会因为有偏移就会使破解难度发生变化

**Comment by sofs2005** [comment]
发现我服务器打开开关后勾和不勾新协议都能用

**Comment by falseen** [comment]
本来就是个可选项。

**Comment by wdhwg001** [comment]
@breakwa11 也罢，我只是单方面的觉得…
有偏移在弱密码下有优势
只改首包无法解决一直以来ss缺乏校验等问题
偏移可以替代crc，在性能较弱的情况下可以抽样检查，以改善性能

不过性能一类的没什么验证就是耍流氓，所以真的没有必要就当做是我在脑补好了。
