### ISSUE TITLE
请问 SSR无法使用iptables  转发吗

### ISSUE THREAD

**Issue by saladinxp** [breakwa11/shadowsocks-rss#550]
玩ps4的时候 原版ss不太支持派对，显示nat错误或者啥的，而ssr 就支持。
然后国庆的时候大家都知道了，阿里云HK抽风严重,我测试用国内线路转发到阿里香港，同样的命令原版ss就可以转发，而ssr就无法转发。 另一个朋友也遇到类似问题，他以为不能转发，我让他测试原版ss他也转发成了。
至于ssr版本，国庆的时候我测试了下，刚才我又下载最新版又测试了下，还是不能转发，所以请问这是咋回事呢。

我用的指令如下 ，当然ip和端口是瞎写的。
iptables -t nat -A PREROUTING -p tcp --dport 1234 -j DNAT --to-destination 123.123.123.123:1234
iptables -t nat -A PREROUTING -p udp --dport 1234 -j DNAT --to-destination 123.123.123.123:1234
iptables -t nat -A POSTROUTING -p tcp -d 123.123.123.123 --dport 1234 -j SNAT --to-source 234.234.234.234
iptables -t nat -A POSTROUTING -p udp -d 123.123.123.123 --dport 1234 -j SNAT --to-source 234.234.234.234

**Comment by breakwa11** [comment]
协议是什么，而且我写的文章里的UDP转发部分不是这样子的

**Comment by saladinxp** [comment]
@breakwa11 没用ssr协议, 有相关文章链接吗，我参考下，谢谢。

**Comment by breakwa11** [comment]
http://breakwa11.blogspot.com/2016/11/blog-post.html

**Comment by saladinxp** [comment]
@breakwa11 说实话，折文章一下就头疼了，不能用iptables 简单的转发吗。

**Comment by breakwa11** [comment]
我这文章不就是在回答你'能'吗，至于你头不头晕和我无关，只是想说你那样做是错的

**Comment by breakwa11** [comment]
@saladinxp 我委托网友测试了一下，这样转发是可以的

**Comment by saladinxp** [comment]
@breakwa11 hi ,我又测试了下，发现一个问题，因为我以前用的内网ip转发，这次换了外网ip用iptables转发就成功了， 所以不知道为何ssr 多用户数据库版本为啥内网转发不行呢，别人的另一个普通ss可以内网转发但很bug很多，例如ps4无法派队，很多游戏无法联机等，特别最近阿里云老抽风，内网转发很重要了。

另外，看到你的那个公告，希望你别太在意别人说什么，很多人啥都不知道，人云亦云，他们根本不知道啥情况，而支持你的人现在越来越多，就算某些人怎么不懂你，支持你的人依然会继续支持你，希望你能坚持住吧。

**Comment by breakwa11** [comment]
多用户的话，由于会使用来源IP来连接，所以内网转发，可能要设置一下 ignore_bind 来阻止使用内网地址导致连接失败

**Comment by saladinxp** [comment]
@breakwa11 谢谢，笨蛋再来问一次， ignore_bind 在哪里设置的。

**Comment by breakwa11** [comment]
配置文件user-config.json中添加一行
`"ignore_bind": "10.0.0.0/8,127.0.0.0/8,::1/128",`

**Comment by saladinxp** [comment]
@breakwa11 thanks 我去搞搞

**Comment by saladinxp** [comment]
@breakwa11 成功，thanks
