### ISSUE TITLE
可以通过改python文件来屏蔽通过ss访问某些网站吗

### ISSUE THREAD

**Issue by hdstar2009** [breakwa11/shadowsocks-rss#551]
不会python，不过看过ss服务器端的日志，用户连到ss服务器似乎是由ss程序先做域名解析（可能是我理解错误，我看到是提示访问网站同时会显示被访问网站的域名）。
所以我想，是否可以通过改python代码，如果是访问指定网站（例如youtube）就不做处理？
服务器小带宽，给人一看youtbube带宽就被占用满了。

**Comment by breakwa11** [comment]
单纯这样你还不如改hosts

**Comment by hdstar2009** [comment]
@breakwa11 
改hosts没用啊。改服务器上的hosts，指定youtube.com到127.0.0.1，ss客户端照样可以访问youtube。
而且我发现神奇的是，vpn类都不受hosts影响，一样可以访问。搞不懂。

**Comment by breakwa11** [comment]
@hdstar2009 重启ss服务端修改才生效

**Comment by glzjin** [comment]
自己在服务端里匹配然后屏蔽咯=、=2016年12月13日 下午4:57，hdstar2009 <notifications@github.com>写道：@breakwa11
改hosts没用啊。改服务器上的hosts，指定youtube.com到127.0.0.1，ss客户端照样可以访问youtube。
而且我发现神奇的是，vpn类都不受hosts影响，一样可以访问。搞不懂。
