### ISSUE TITLE
auth_aes128_md5在深圳上海已经不能用了

### ISSUE THREAD

**Issue by didila** [breakwa11/shadowsocks-rss#558]
最近两个星期
在深圳上海两地多个地区
auth_aes128_md5基本上一开就严重干扰
只剩下sha1系列的还可以用

**Comment by breakwa11** [comment]
我认为你需要一些数据或图表来证明你说的内容

**Comment by didila** [comment]
没有数据，只有手中100多个机器反应过来的处理结果
抱怨的都是auth_aes128_md5使用者，约30个，分布在上海和深圳、东莞
改其它协议就行了

**Comment by breakwa11** [comment]
auth_aes128_md5不兼容原协议的UDP，你应该问清楚他们是不是用在手机上当原版协议使用导致DNS失败

**Comment by didila** [comment]
不，都是电脑c# 3.9.6.2，开启了UDP OVER TCP
看了log几乎都是[Errno 104] Connection reset by peer和[Errno 32] Broken pipe
而且持续一整天

**Comment by breakwa11** [comment]
让他们换4.0.1再试试

**Comment by didila** [comment]
我再找几个人试试吧
我没让他们用4.0就是因为还要手动修改portMap实在太麻烦了

**Comment by breakwa11** [comment]
我说的是4.0.1，如果还要手动改，我干嘛让你更新到这版本

**Comment by flatcc** [comment]
上海原版都能用。
