### ISSUE TITLE
右键的服务器负载均衡选项挪个位置不？

### ISSUE THREAD

**Issue by polong** [breakwa11/shadowsocks-rss#56]
觉得ss-win的选项安置方式更符合逻辑吧。
![image 1](https://cloud.githubusercontent.com/assets/1086577/9836376/cb28a946-5a49-11e5-9a76-7c76d0b38176.png)
就是“服务器负载均衡选项”放进服务器列表中，并且可以把负载均衡方式整个列表入进去吧。选择某单独一个IP和选择某个负载方式应该是属于单选关系吧？

**Comment by shikkoku** [comment]
无非就是.Net4.0是用版本较新的编译，免得在较新的系统版本中提示下载旧版本框架。

**Comment by breakwa11** [comment]
当服务器列表数量达到50个的时候，这样找是不是太麻烦了？

**Comment by polong** [comment]
当列表到达五十个时，选什么不麻烦！hhh

**Comment by breakwa11** [comment]
用统计列表去选择服务器，加上在主菜单切换这些选项，不是好得多吗

**Comment by AnyoeDove** [comment]
= =超过50肯定选什么都麻烦啊 主要是当选择负载均衡时鼠标移到通知区时显示的仍旧是选中的ss服务器 而不是当前的服务器选择状态 是强迫症的困扰= =

**Comment by Forty-nine** [comment]
还是在外边比较好

**Comment by polong** [comment]
@AnyoeDove 知音啊，哈哈哈。我就是因为选了负载均衡后依然有某个服务器被固定选中所以各种别扭啊。
