### ISSUE TITLE
UDP无法监听

### ISSUE THREAD

**Issue by nutb** [breakwa11/shadowsocks-rss#561]
[root@jp_su shadowsocks]# lsof -i:3000
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python  2564 root   10u  IPv6  18825      0t0  TCP *:hbci (LISTEN)
python  2564 root   11u  IPv6  18826      0t0  UDP *:hbci

**Comment by breakwa11** [comment]
UDP本来就不用监听啊

**Comment by nutb** [comment]
是这样的，用两台服务器做测试一个是vultr，一个是网易蜂巢。
vultr无法转发udp，网易可以。网易是月初搭建的。
防火墙是设置好的，正常。

**Comment by breakwa11** [comment]
所以vu被更大的防火墙block了UDP

**Comment by nutb** [comment]
......很抱歉打扰了。应该是服务器问题，国外服务器测试了udp无法转发。国内都可以。
