### ISSUE TITLE
怎样使用udp传输?

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#562]
好像没有看到相关的使用介绍，s端和c端分别的怎么设置呢?

**Comment by impig33** [comment]
问题已经解决。

我的ssr服务端本来监听了443端口，在服务器上用lsof -i:443，看到443的tcp和udp都已经监听了。

但是到底能不能用呢?
在客户端勾上udp over tcp，然后浏览器上打开google，在服务器上使用tcpdump抓包：
tcpdump -i venet0:5 -p udp

确实看到了访问google的数据包。

谢酱妹，我爱你

**Comment by breakwa11** [comment]
具体要不要udp over tcp，先直接测试一下不打勾的情况，这个是UDP直接转发
如果打了勾，那是通过TCP来转发UDP，和UDP就没关系了

**Comment by impig33** [comment]
那是我理解错了，或者有地方搞的不对。

疑问是，我在服务端的端口是443，lsof -i:443确实看到了tcp和udp443都有监听，那么客户端使用时，数据会走哪个端口呢?

@breakwa11

**Comment by breakwa11** [comment]
@impig33 看你要用哪个

**Comment by impig33** [comment]
没有默认tcp或者udp吗? 还是说要专门进行配置? @breakwa11
