### ISSUE TITLE
小建议：4.0+版本的端口设置建议增加强制按组代理

### ISSUE THREAD

**Issue by yshtcn** [breakwa11/shadowsocks-rss#563]
一个小的建议。
目前的版本是4.0.1，Port Settings里的ForceProxy功能只能选择一个目标服务器（Servers ID）。如果可以按（Group）强制代理的话，端口设置会更实用一些。按组强制代理可以以负载均衡的方式实现。

目前，我如果要按端口区分目标路线，就不得不开启多个客户端。如果这个小建议可以采纳，就可以只维护一个客户端了。

**Comment by wenliyang** [comment]
在"服务器连接统计"里点击组名称，关闭不需要加入负载均衡的组

**Comment by yshtcn** [comment]
我并不是要关闭部分组。而是需要在一个客户端里实现不同的端口对应访问不同的组

**Comment by haoxuexiaoyao** [comment]
请问4.0+的版本在哪里下载啊
