### ISSUE TITLE
4.0.2版本连不上fonts.googleapis.com

### ISSUE THREAD

**Issue by yc-z** [breakwa11/shadowsocks-rss#568]
今天更新了下4.0.2，发现有fonts.googleapis.com的网页始终打不开，chrome始终显示正在等待fonts.googleapis.com的响应，代理规则选全局就又能打开了，换回4.0.1后不用全局也可以秒开，是不是新版本有bug，还是个人问题？

**Comment by breakwa11** [comment]
@yc-z 看你的模式设置，包括PAC和代理规则

**Comment by yc-z** [comment]
只有在代理规则为全局的情况下（PAC每一种都试了一遍），才能连上fonts.googleapis.com，后来在chrome装了Proxy SwitchyOmega，用了gfwlist的规则（默认应该是包含fonts.googleapis.com），但也打不开网页。

**Comment by breakwa11** [comment]
@yc-z 如果你的DNS是污染的，代理规则目前还是要设置为全局

**Comment by yc-z** [comment]
我在hosts里加了fonts.googleapis.com的香港sni代理，dns应该解析到hosts中的地址，而那个地址可以使用，即使关了ssr，google、youtube等都能使用，会不会是ssr选项设置中的dns出了问题，那个我用的是阿里的。

**Comment by breakwa11** [comment]
@yc-z 里面的DNS你设置为什么，目前并没有读取host

**Comment by yc-z** [comment]
223.5.5.5

**Comment by breakwa11** [comment]
@yc-z 那你验证一下用这个DNS解析出来的结果，应该是这个DNS的结果被污染成国内导致的

**Comment by yc-z** [comment]
不好意思，找到原因了，好像是pac和代理规则的问题（代理规则选择绕过局域网也行），DNS解析到的是203.208.43.110，应该不是dns污染的结果。不过问题是我没有开启二级代理，两者为什么会冲突。

**Comment by breakwa11** [comment]
@yc-z 并不是冲突，任何一个决定要直连，最终结果都是直连

**Comment by yc-z** [comment]
与选项设置的二级（前置）代理中的开启代理是否选中无关吗？如果没有选中，代理规则无论选择哪一种，应该都不影响pac规则的效果（前提是pac规则没变），我的这种情况好像是影响的。

**Comment by breakwa11** [comment]
@yc-z 这和二级代理没有任何关系

**Comment by yc-z** [comment]
明白了，谢谢
