### ISSUE TITLE
为什么像openconnect等特征明显的都没出问题，反而ssr这样的特意做过混淆的会被封？

### ISSUE THREAD

**Issue by sueccku** [breakwa11/shadowsocks-rss#572]
为什么像openconnect这样的特征相当明显的（都几乎把“我是vpn”写在脸上了）都没出问题，像openvpn这样几乎没特意混淆，用的人相当多，过了这么多年才出问题，出问题也是有时连接不稳定，反而ssr这样的特意做过混淆的会被封，而且一封就是彻底的成片的封？gfw到底卖的什么药？难道是ssr混淆的思路有问题？还是传说中的“最大的特征就是没有特征”

**Comment by breakwa11** [comment]
从你发的issue来看，我很难不怀疑你是五毛，从你发过的这两个issue来看就不像是同一个人发的，而且还是发新版本的时候来发这issue，很难不去怀疑你是因为看到更新于是发个带攻击性质的issue。而且我猜你不打算回复，因为前一issue你对我爱理不理的。前一issue还在求“深度解析”，现在却问新手都知道答案的问题大放阴谋论，这手法我看着就觉得眼熟，你不觉得你是在搞笑吗

**Comment by sueccku** [comment]
刚去翻了下，看到前一个是我朋友用我号发的，他看我号在登录着心血来潮发的，sorry，话说别想着每一个人都是在攻击你啊，不就是gpl协议吗，根本不是啥大事，思科的盈利性商业产品不是用gpl协议过一年后才发源码吗，还有国内一堆公司连用的什么源码都不说，个人用gpl协议过后补个源码就完事了，那些攻击的只是因为你会有反应才喷的，你看看那种怎么喷都没反应的公司，最后觉得没意思就不喷了。
还有那些说安全问题的，有的服务器都是买的别人的，还整天怀疑安全，那些人完全是没事yy，不要管就好了
我们只谈技术，有一点自信，几乎所有相关软件都用过，也几乎全研究过原理，但是跳出技术来看，反而发现好不好用和费不费劲做混淆好像没啥直接联系，只是想看看有没有人能能提供什么灵感，主要是有个搞大数据分析的朋友认为对机器学习来说机器认为的特征有时和人认为的特征的完全不一样，想看看有没有人能能提供什么灵感，没想到作者竟然回复了，有点受宠若惊
还有说点个人浅薄的看法：1.用python写的vpn软件给人有点不靠谱的感觉（心里作用？），为什么不全用c/c++开发2.为什么不采用证书那一套东西3.为什么不用tap/tun那一套4.为什么要区分单用户和多用户，只设置一个用户的的多用户，多用户的管理方法也不是很主流，这会让维护人员很麻烦啊5.应该把通道建立之后的东西空出来，是nat还是桥接，要不要经过代理，是ndp还是dhcpv6，都应该让使用者自行配置啊，直接定在端口上局限性太大，也不利于用户使用所有网络功能6.应该弄个小软件来显示服务端的健康状况以及对其进行简单的监控和控制7.建议弄个把所有技术问题汇总在一起的白皮书8.别费精力做负载均衡了，那根本不是vpn软件该做的事啊
就是点个人的小见解，说的不对的话......尽情的嘲笑吧~

**Comment by breakwa11** [comment]
在我回答你之前，请说明SSR哪里被成片的封

**Comment by sueccku** [comment]
以前山西有一部分地区，现在深圳有，上海好像挺多的，偶尔会有点新疆的

**Comment by breakwa11** [comment]
我严重认为你一定是搞错了什么，SS不是VPN，而且感觉你没有用过SS，否则你怎么可能和我说TAP/TUN？还dhcp。。。。我无语了。另外你说这种大面积被封，你肯定又是搞错了什么，我不知道你搞错了什么，肯定是把什么东西理解错了

**Comment by breakwa11** [comment]
话题就此结束吧，你先把你的错误认识纠正了
