### ISSUE TITLE
代理规则切换失效

### ISSUE THREAD

**Issue by Noaha11** [breakwa11/shadowsocks-rss#574]
4.0.2版本使用1080端口的http代理，规则切换无效，一直处于全局代理状态

**Comment by breakwa11** [comment]
你说的规则是指哪个

**Comment by Noaha11** [comment]
就是一级菜单里的“代理规则”。也就是说privoxy的bypass.action不会变

**Comment by breakwa11** [comment]
@Noaha11 先更新一下到4.0.3再试试看

**Comment by Noaha11** [comment]
@breakwa11 更新了4.0.3也有同样问题

**Comment by breakwa11** [comment]
现在不会使用bypass.action，你到底期望的结果是什么样？你设置的是什么

**Comment by breakwa11** [comment]
我想起一个事，你有没有保留delegated-apnic.txt
如果没有，那等于全局

**Comment by Noaha11** [comment]
@breakwa11 只改过gui-config.json，delegated-apnic.txt是默认自带的。
想达到的效果就是绕过大陆网址比如淘宝京东。我设置了绕过局域网和大陆，但是测试发现并没有绕过，京东提示from overseas

**Comment by breakwa11** [comment]
唔，这个并不保证一定准确，如果JD有国外的CDN，且你的DNS也解释到国外去了，那自然就是这样了

**Comment by breakwa11** [comment]
更新
