### ISSUE TITLE
PC端无法连接到ssr啊

### ISSUE THREAD

**Issue by cntink** [breakwa11/shadowsocks-rss#575]
在路由上已经设置了gfwlist翻墙模式，然后想在PC端上试试，结果翻不成功，这是为什么呢？手机、路由器和PC用的都是不同的端口，手机和路由都可以正常使用，换到路由下面的PC端上就不行了。。

**Comment by guliujian** [comment]
这样给出信息并不能让别人很好地帮你解决问题啊。

**Comment by cntink** [comment]
额，就是同一个服务器，开了3个端口，手机在4G下用一个端口可以翻，路由在宽带下用另一个端口也可以翻，电脑在路由下用第三个端口就不能翻了，服务器防火墙也停掉了的！

**Comment by guliujian** [comment]
你在路由下面的电脑提示啥呢，还有能不能ping通服务器呢？

**Comment by wangchunming** [comment]
POP3 110端口翻墙不限速！！！！！ 不用任何混淆

**Comment by guliujian** [comment]
你这样会玩坏的
