### ISSUE TITLE
4.02 4.03 win10系统下 会产生一些莫名奇妙的问题

### ISSUE THREAD

**Issue by dnxbice** [breakwa11/shadowsocks-rss#577]
我的操作系统是WIN10 X64 更新了4.02以后如果设置了开机启动 那么启动一会以后 系统会变的非常卡 双击任何程序 都提示“错误: 系统资源不足，无法完成请求的服务。 ”  关闭程序以后 一切正常
今天又更新了4.03版本 刚更新完的时候 测试运行一切正常 但是设置了开机启动以后 问题又出现了 如之前的描述 关闭以后 又正常了 如果不设置开机启动 等开机以后 手动启动 4.02有一定的机率会出问题 但是4.03好像运行的很好 不知道这是怎么回事
愿大神看到以后 能给个回答 再此先谢谢大神一直以来的作品 非常好用 感谢

**Comment by dnxbice** [comment]
补充一下 开始我以为是系统的问题 所以换了一台机器 重装WIN10打好补丁 没有其它的什么软件 做测试 还是如此 不知道是什么问题 退回到之前的3.9.6.2就无此问题 但是3.9.6.2每次开机都会提示更新到4.02版本 不知道这个提示能不能关闭

**Comment by breakwa11** [comment]
@dnxbice 我还从来没有测试过win10的情况，待我安装个测测，你其它操作系统呢？

**Comment by dnxbice** [comment]
https://github.com/breakwa11

**Comment by dnxbice** [comment]
WIN7无此问题 WIN8没测试 目前常用WIN10 @breakwa11

**Comment by ilikecola** [comment]
Win10 运行无此问题

**Comment by dnxbice** [comment]
@ilikecola 是设置的开机启动吗？ WIN10什么版本？我是10.0.14393.351

**Comment by dnxbice** [comment]
PC睡眠前如果开着SSR 等唤醒以后 也会有问题 @breakwa11 [https://bjbgp02.baidupcs.com/file/ebf9d1478f7d095fea4001f6038eb473?bkt=p3-1400ebf9d1478f7d095fea4001f6038eb473e5af5bef00000000ec9f&fid=2924199815-250528-677206165025728&time=1482802535&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-dU7IVnCAuBoxKu%2Fj0N8aFlEmF6s%3D&to=fbjbgp&fm=Yan,B,G,bs&sta_dx=60575&sta_cs=&sta_ft=png&sta_ct=0&sta_mt=0&fm2=Yangquan,B,G,bs&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400ebf9d1478f7d095fea4001f6038eb473e5af5bef00000000ec9f&sl=81068110&expires=8h&rt=sh&r=151603655&mlogid=8381879666174704034&vuk=2924199815&vbdid=1988392953&fin=QQ%E5%9B%BE%E7%89%8720161227093219.png&fn=QQ%E5%9B%BE%E7%89%8720161227093219.png&uta=0&rtype=1&iv=0&isw=0&dp-logid=8381879666174704034&dp-callid=0.1.1&hps=1&csl=10&csign=SRiyuekoQGHzC4utt0%2B1HGHnjR8%3D](url)

**Comment by dnxbice** [comment]
PC睡眠前如果开着SSR 等唤醒以后 也会有问题 @breakwa11 
[https://pan.baidu.com/s/1boYHMlL](url) 这是系统日志记录下的错误 基本上都是类似这样的错误

**Comment by cqhtyi** [comment]
Win 10 Enterprise 14393.576 (x64)
ShadowsocksR-win-4.0.3
7*24小时开机，没有出现过这种问题。

**Comment by tphz** [comment]
我也用win10 ，没有此问题。

**Comment by dnxbice** [comment]
@tphz 那真是奇怪了 关了就好 开机启动就不行 不开机启动 等一会再用也没事 换上个版本就没问题

**Comment by breakwa11** [comment]
新版本可能已经解决了，请等新版本发布

**Comment by ilikecola** [comment]
@dnxbice 和老版本一样开机自启，建议检查防火墙 杀毒软件啥的

**Comment by breakwa11** [comment]
请测试新版本

**Comment by dnxbice** [comment]
@breakwa11 新版已经无问题 谢谢大神
