### ISSUE TITLE
ipv6无法使用

### ISSUE THREAD

**Issue by kozora** [breakwa11/shadowsocks-rss#58]
本地查看日志显示time out

**Comment by breakwa11** [comment]
测试了一下，访问ipv6.google.com没有问题，ipv6的检测结果正常

**Comment by kozora** [comment]
也不知道哪里出错了，全部按照教程来的，就算是直接绑定ipv6地址一样本地日志是time out

**Comment by farrellyang** [comment]
最新的服务端安装后只能监听ipv6的tcp/udp端口，ipv4的没有，很奇怪啊

**Comment by breakwa11** [comment]
@farrellyang 可以同时收v4和v6的连接的，v6的监听了v4的就算要监听也不行了，所以只监听一个就行

**Comment by farrellyang** [comment]
@breakwa11 多谢，我用netstat -ntulpa查看只显示了v6的，但v4可以连接，才疏学浅不懂莫怪哈；另外启动服务端的命令nohup python /root/shadowsocks/shadowsocks/server.py -c /etc/shadowsocks.json执行后，好像不是在后台执行，我在后面加上 &可以了，但随后的ssh命令行显示有点问题

**Comment by farrellyang** [comment]
@breakwa11 是因为配置文件里server的v4和v6分开的吧？以前用的go版本只有一个server项，但v4和v6都能连接

**Comment by farrellyang** [comment]
@kozora 国内高校最近ipv6经常抽风，可能是这原因

**Comment by breakwa11** [comment]
@farrellyang 有的人的服务器有多个IP的时候，就不能用默认的值，需要指定一下IP了，这时候有用，可以4和6监听不同的IP来源，这时候就可以分别同时监听，但只配置一个就办不到了

**Comment by farrellyang** [comment]
@breakwa11 懂了，这样分开比较好

**Comment by dartall** [comment]
服务端用的windows版的libqtshadowscoks ，本地监听设置"server":"::",让v4通过v6传到客户端。
从3.4.2 版本的客户端开始，发现不能接受数据。是因为3.4.2开始的客户端强制要求服务端分别监听的原因？ windows 版有无解决办法？@breakwall11

**Comment by breakwa11** [comment]
@dartall 测试过服务端配置V6地址，客户端也通过V6地址连接，服务端版本为libqtshadowsocks，一切正常。同样测试了一下用V4地址，也是正常的。到底你怎么设置的，另外说你遇到的问题的时候最好发log

**Comment by dartall** [comment]
{
	"server":"::",   
	"server_port":xxx,
	"local_port":1080,
        "password":"xxx",
	"timeout":600,
	"method": "rc4-md5"
}
我的配置如下。

**Comment by breakwa11** [comment]
@dartall 服务端加客户端的log，因为一直不明白你说的无法接收数据具体是什么

**Comment by dartall** [comment]
我刚才有测试了。试了几种写法都不行。	 "server_ipv6":"::", "server":"::",或加上v4的写法。
这是客户端log
[2015-09-20 17:48:43] Shadowsocks started
[2015-09-20 17:49:07] Shadowsocks started
[2015-09-20 17:49:14] [Error]connect to update server error
[2015-09-20 17:49:19] Shadowsocks started
[2015-09-20 17:53:31] Shadowsocks started
[2015-09-20 17:54:02] [Error]connect to update server error

我客户端使用时原版选项。
主机因为没传送数据，所以没产生什么log。
Qt: Untested Windows version 10.0 detected!
Initialising ciphers...
RC4-MD5 (rc4-md5) initialised.
Can't get address from . Using localhost instead.
Running in server mode.
TCP server listen at port 8831

**Comment by breakwa11** [comment]
@dartall 你的服务端获取IP失败，只监听了本地地址，当然根本不接收外面的连接
`Can't get address from . Using localhost instead.`

如果你的服务端没有V6地址，就不要那样写，要么直接写你的服务端准确的外网地址，保证正确

**Comment by dartall** [comment]
以前3.4.1 以前的版本可以啊。虽然也只监听了本地地址，但可以接受连接。这不是监听所有v6地址的意思吗？
那如何写？是直接写服务端电脑的v6地址？

**Comment by breakwa11** [comment]
@dartall 这和客户端是什么版本没有关系，是你服务端的问题
`直接写你的服务端准确的外网地址`这是指服务端配置

**Comment by dartall** [comment]
额。我不是强调了。3.4.1之前版本，即使出现log所显示的没获取地址，仍可以正常传输数据。这肯定与客户端版本的不同机制有关。

我知道是服务端配置，刚才我把server换成本地的v6地址，不行。服务端v4是无线路由分配的192.168类地址。你说的外网是指v4的公网地址吗？

实在不行，我就用3.4.1也可。

**Comment by breakwa11** [comment]
@dartall 你是开多重代理？那这样直接用v4地址应该没有问题吧，具体你的网络环境和配置是怎么样的？3.4.1之后的版本都没有对网络部分改些什么，这种情况似乎不应该

**Comment by dartall** [comment]
我今天折腾明白了。问题出在客户端电脑的avast防火墙：可能因为程序没带签名，而被自动拦截了。添加例外并信任之后，就可以了。而3.4.1 可以的原因是被自动信任，具体原因不清。的确不是你开发客户端网络协议的问题。

谢谢你的耐心回答。也感谢你开发的非常棒的客户端。
