### ISSUE TITLE
现在更新是在哪里发布最新版？

### ISSUE THREAD

**Issue by SuperCatss** [breakwa11/shadowsocks-rss#580]
之前在zeronet，但是现在zeronet的版本 还在2.9.6
用的版本是4.0.3
打开wiki日志 ，提示最新版是4.0.3
打开关于 ，提示最新版是 4.0.2
原谅我是强迫症。。
还是想搞清楚。。
大佬来回答下啊

**Comment by yjd** [comment]
现在直接在github发布了

**Comment by SuperCatss** [comment]
那最新的是4.02 还是03？
