### ISSUE TITLE
想问下4.0.3域名连接失败，换成ip就成功是啥原因？

### ISSUE THREAD

**Issue by yinws** [breakwa11/shadowsocks-rss#582]
服务器处填域名连接失败，换成ip就成功，域名解析没有问题。

**Comment by breakwa11** [comment]
但这明显就是DNS的问题，你在软件内填写一下DNS试试

**Comment by stardock** [comment]
我用域名连接没问题的，请不要使用godday之类的墙外服务商，在国内是不解析的
我现在使用的是百度域名服务，更新超快没的说

**Comment by alittledream** [comment]
肯定dns

**Comment by 01186** [comment]
自己dns設置問題...

**Comment by yinws** [comment]
恩，可能是我遇到的问题太奇葩了。
如果有人可以域名连接的话那应该我是个例，但是好几个说域名解析问题，其实这个我一开始就说域名解析没问题了，因为在原版SS正常，手机端也正常，CMD里面ping也正常。电脑设置的是腾讯和114的DNS，然后在SSR里面设置DNS还是失败。
最后我只能归结为电脑系统问题了。。。

**Comment by breakwa11** [comment]
但没人知道你怎么填写的，你也没给出你那边的解析结果，如果你介意地址，你可以考虑用email或twitter发私信问
