### ISSUE TITLE
Wingy 无法识别当前服务器二维码

### ISSUE THREAD

**Issue by madordie** [breakwa11/shadowsocks-rss#583]
[客户端](https://github.com/shadowsocksr/ShadowsocksX-NG/releases) 能够正常连接。
Wingy 显示无效配置

**Comment by breakwa11** [comment]
@madordie Wingy目前还不支持SSR链接格式

**Comment by madordie** [comment]
厉害厉害，我试了一下，如果加了混淆就不行了。不加是OK的。不过客户端好似并不好使。。有推荐的Mac客户端么？

**Comment by breakwa11** [comment]
https://github.com/shadowsocksr/ShadowsocksX-NG
