### ISSUE TITLE
ShadowsocksR C# v4.0.3 运行一段时间后所有连接全部断开

### ISSUE THREAD

**Issue by SLAPaper** [breakwa11/shadowsocks-rss#584]
OS Version: Windows 10 Build 14986
Program Version: ShadowsocksR C# v4.0.3

Problem: After running a period of time (eg. several hours), all the connection will lost (connection count equals 0, no traffic, no error/ time out/ empty connection). Recover after turning off SSR and reopenning.

Wonder if there's something wrong with my settings or operations? Is there any way to furder detect what the problem is? Thank you very much!

症状：计算机运行一段较长时间（若干小时）后，所有连接全部断开（服务器连接统计中所有连接数为0，无流量，没有错误、超时和空连），关闭SSR再重新打开会恢复。

是不是我的操作或者配置有什么问题？有什么可以进一步定位或者排查的方法？谢谢！

**Comment by Oldbai** [comment]
Windows 10 Build 14393.576 经测试也是同样的问题。

**Comment by breakwa11** [comment]
等我弄个win10环境查查原因

**Comment by breakwa11** [comment]
更新一下版本看看

**Comment by Oldbai** [comment]
更新版本V4.0.4已经解决，谢谢

**Comment by SLAPaper** [comment]
更新后问题未再复现，感谢。
No represent after upgrading, Thanks!
