### ISSUE TITLE
4.x局域网代理问题

### ISSUE THREAD

**Issue by evanxyf** [breakwa11/shadowsocks-rss#585]
更新前用3.9.2，局域网代理不管电脑手机一直好使，更新到4.x之后局域网的电脑没问题，手机却用不了了。

**Comment by breakwa11** [comment]
问题表达不具体

**Comment by evanxyf** [comment]
操作系统Win10 企业 2016 LTSB 14393.576
ssr设置一直都是PAC模式使用GFWList、代理规则绕过局域网及大陆、允许本地局域网通过8080端口链接
服务器只使用一个，rc4-md5、auth_sha1、http_simple
3.9.2使用正常，本机及同内网的所有电脑和所有手机都能连通且效果很好，
从第一个4.x版本开始同样的设置只有电脑能连通，手机不管是ios、android、wp都不能连通。
只能大致说明一下是这样的一个问题，真诚希望能解决，如需log或其他信息请明示！

**Comment by evanxyf** [comment]
局域网的设备通过设置自动代理配置连接到http://ip:8080/pac

**Comment by breakwa11** [comment]
PAC地址不正确，请从软件内复制正确的PAC地址，PAC菜单里有

**Comment by evanxyf** [comment]
问题是之前都是使用/pac都可以的，现在还要连着后面那串，手机输入实在麻烦。
现在还有个问题就是ssr本机的ie不管是PAC模式还是全局都连不上外面了，PAC还是用GFWList，代理规则还是用绕过局域网及大陆。

**Comment by evanxyf** [comment]
SSR本机：PAC模式不通外面，全局模式内外不通。
手机尝试用IP:端口直连不使用PAC，效果和以前一样。是否局域网电脑也可以这样走？

**Comment by breakwa11** [comment]
可以，这等于全部走规则

**Comment by catcat520** [comment]
其实就是新版修改了pac规则导致的，至于为什么这么做就不清楚了
