### ISSUE TITLE
安装ss-panel v3时出现的错误如何解决（见图）

### ISSUE THREAD

**Issue by ziluopao** [breakwa11/shadowsocks-rss#588]
在安装后，打开网站，出现如图所示提示错误，不知原因所在，如何解决呢？
我用的环境是centos6.4 64Bit 
<img src="https://raw.githubusercontent.com/ziluopao/myss/master/155555.jpg"/>

**Comment by glzjin** [comment]
你为什么不去 sspanel 那边问问呢？2016年12月29日 上午10:11，ziluopao <notifications@github.com>写道：在安装后，打开网站，出现如图所示提示错误，不知原因所在，如何解决呢？

**Comment by ziluopao** [comment]
对，我不大会用github,这个主意好，我去那边问一下，多谢提醒哈！

**Comment by breakwa11** [comment]
如果继续把开发当客服，那我只能把你封掉
