### ISSUE TITLE
4.0.3版本内存占用

### ISSUE THREAD

**Issue by retaw106** [breakwa11/shadowsocks-rss#594]
win+r打开msinfo32，可以看到ssr4.0.3的最小工作集非常大，达到4194300。而3.9.6版本则无此问题，最大工作集仅为1380。
测试环境：ssr-dotnet4.0, win7/win10。
该问题会导致virtualbox的虚拟机分配内存减少，我之前一直给虚拟机分2g内存，昨天突然运行不起来了，报错“Unable to allocate and lock memory. The virtual machine will be paused. Please close applications to free up memory or close the VM”，把虚拟机内存减到1280m才可以。后来发现是ssr导致的。
截图如下：
![qq 20161230121359](https://cloud.githubusercontent.com/assets/14174063/21559649/181024d0-ce8b-11e6-83ea-2e94979895a3.png)
![qq 20161230121513](https://cloud.githubusercontent.com/assets/14174063/21559650/1a763dc2-ce8b-11e6-8d92-7d3631230f29.png)

**Comment by breakwa11** [comment]
好奇怪，我查查

**Comment by dnxbice** [comment]
不知道和系统日志有没有关系 我出错的时候 都是先丢失系统日志 然后系统各种资源不足

**Comment by breakwa11** [comment]
我这边也是这个数字，但启动是正常的

**Comment by retaw106** [comment]
ssr运行是没问题的，但内存占用会影响到其他程序

**Comment by breakwa11** [comment]
这个问题会在新版本里修正好
