### ISSUE TITLE
这样安装ShadowsocksR C#版本4.0.2对吗

### ISSUE THREAD

**Issue by ziluopao** [breakwa11/shadowsocks-rss#595]
#@SLAPaper
看到breakwall的ShadowsocksR C#版本4.0.2的介绍中说，**安装方法**见https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup
因为**我还是一小白**，所以装到这一步
**获取源代码**

git clone -b manyuser **https://github.com/shadowsocksr/shadowsocksr.git**
有点迷茫了。
我是这样理解的，上面的获取地址是以前的，不是ShadowsocksR C#版本4.0.2的，要想用4.0.2
必须换地址，而4.0.2的地址是https://github.com/breakwa11/shadowsocks-rss.git
所以安装的句子要改一下，改成为
git clone -b manyuser https://github.com/breakwa11/shadowsocks-rss.git
其他的安装时使用的语句不变。
_不知这样理解对吗_？请原谅我的无知！谢谢哈！

**Comment by breakwa11** [comment]
4.0.3可以在github上直接下载，https://github.com/shadowsocksr/shadowsocksr-csharp/releases

**Comment by breakwa11** [comment]
按wiki，地址改好了
