### ISSUE TITLE
安装命令错误？

### ISSUE THREAD

**Issue by a1328788808** [breakwa11/shadowsocks-rss#6]
root@zyh:~# git clone –b master https://github.com/breakwa11/shadowsocks.git
Too many arguments.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
是我人品不好么。试了好几遍都不行。

**Comment by breakwa11** [comment]
-b 符号有问题，我修正一下wiki，你重新打一次减号就行

**Comment by a1328788808** [comment]
这句可以执行了，单用户需要再进入shadowsocks二级子目录再执行python server.py，又提示错误了。麻烦再看下。。

**Comment by cfcboy** [comment]
你可以看HELP命令行。你下载的单用户版本。要指定json配置文件。

python server.py -c */shadowsocks.json
