### ISSUE TITLE
PC端扫描二维码时的问题

### ISSUE THREAD

**Issue by jinshijie** [breakwa11/shadowsocks-rss#600]
试了一下，其他的都扫描正确，唯独协议和混淆没有扫进去?是否是没设置的原因
<img src="https://raw.githubusercontent.com/jinshijie/tupian/master/%E4%BA%8C%E7%BB%B4%E7%A0%81.png"/>

**Comment by breakwa11** [comment]
你扫描的是原版的URL吧

**Comment by jinshijie** [comment]
哦，我明白了，原来是这样，谢谢大神 @breakwa11
