### ISSUE TITLE
紧急求助大神，求问为什么上不了网

### ISSUE THREAD

**Issue by theratlesnake** [breakwa11/shadowsocks-rss#601]
我在网上找到了一个SS的免费账号，在SSR上试了可以上网，但是自己手动选择了协议和混淆就上不了网，求大神解答原因。（原本使用默认的协议origin和默认的混淆plain就可以上。）各路大神求解

**Comment by breakwa11** [comment]
@theratlesnake 必须服务器支持，否则你客户端设置是没用的

**Comment by bugparty** [comment]
mdzz,你得按照服务方的配置来。

**Comment by bugparty** [comment]
@breakwa11 新年快乐，破娃酱

**Comment by guliujian** [comment]
这个需要客户端服务端采用相同的才行

**Comment by theratlesnake** [comment]
@breakwa11 噢，我是昨天才安装SSR的，之前从没听过，我想再问问大神，如果我购买了VPS，是不是要自己手动配置？本人技术很菜。

**Comment by theratlesnake** [comment]
@bugparty 噢，你会配置VPS吗？

**Comment by theratlesnake** [comment]
@ guliujian 噢，谢谢你

**Comment by theratlesnake** [comment]
大家新年快乐

**Comment by bugparty** [comment]
@theratlesnake 是的，没有教程么？我从源码变异的

**Comment by theratlesnake** [comment]
@bugparty  您是指的这个教程吗？https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup

**Comment by jinshijie** [comment]
这个问题可能性多了去了，就好比，你对别人说，为什么你肚子痛，那有N种可能，比如，你可能不注意卫生乱吃，也有可能你受凉了，当然也有可能....................也有可能.......................,你提供的信息别人无法准确判断，只能猜，当然是没有奖的竟猜！

**Comment by theratlesnake** [comment]
@jinshijie 只是问个vps教程而已。

**Comment by dimi360** [comment]
淡定
