### ISSUE TITLE
 运行python server.py的时候卡住，求助，万分感谢！

### ISSUE THREAD

**Issue by andy817** [breakwa11/shadowsocks-rss#602]
之前的都ok，然后运行到这里，就会卡住
![problem](https://cloud.githubusercontent.com/assets/10892833/21579977/f483434e-d00b-11e6-9816-0dfbde337665.JPG)

如图，到这里就不动了。。。求助。
3306端口已经开启。

**Comment by andy817** [comment]
![3306](https://cloud.githubusercontent.com/assets/10892833/21579995/fbca1fa0-d00c-11e6-9a68-5b4a0b148286.JPG)
我又查看了3306.。。有两个，这个是？？？还没有开启？

**Comment by breakwa11** [comment]
LOG里显示开的端口是4，为什么已经start了你还要纠结
