### ISSUE TITLE
协议不支持auth_aes128_md5_compatible取值了吗？

### ISSUE THREAD

**Issue by Mac0ne16** [breakwa11/shadowsocks-rss#606]
今天部署错误信息提示错误不支auth_aes128_md5_compatible 然后把后面的_compatible才正常～～

**Comment by breakwa11** [comment]
@Mac0ne16 是的，auth_aes128的两个协议不支持compatible

**Comment by zxishere** [comment]
哪些协议支持呢？ 看wiki没有更新，看是否方便的时候更新下吧

**Comment by breakwa11** [comment]
其它的以obfs说明文档为准
