### ISSUE TITLE
版本4.0.2无法连接, 自查未发现明显错误, 望帮助

### ISSUE THREAD

**Issue by imtyz001** [breakwa11/shadowsocks-rss#607]
电脑端采用ShadowsocksX-NG版本 1.3.2 (1), 附上电脑端截图, 单用户配置截图, log截图
<img width="323" alt="2017-01-03 17 12 12" src="https://cloud.githubusercontent.com/assets/11791130/21603593/6859ac62-d1d9-11e6-8915-c99daa79a50d.png">
<img width="587" alt="2017-01-03 17 12 59" src="https://cloud.githubusercontent.com/assets/11791130/21603596/6b3daabe-d1d9-11e6-914b-a6ed7b1cae52.png">
<img width="771" alt="2017-01-03 17 13 44" src="https://cloud.githubusercontent.com/assets/11791130/21603594/689e2860-d1d9-11e6-811e-5bbc7fceb8a6.png">

**Comment by imtyz001** [comment]
已经阅读过https://github.com/breakwa11/shadowsocks-rss/issues/597, 自查后还是找不到错误点.

**Comment by breakwa11** [comment]
用非SSR客户端连接SSR服务端，连得上才怪，你说的版本号也是错的，你搞什么鬼

**Comment by imtyz001** [comment]
一开始是可以连接上的，后来重新建了一个就不行了；版本号我是直接复制了read me.md的版本号……
