### ISSUE TITLE
为啥今天开始SSR总是断网呢？

### ISSUE THREAD

**Issue by cxlovemg** [breakwa11/shadowsocks-rss#609]
我使用了最新版的4.04客户端，服务器端配置也是正常的呀！总是断网，需要10几分钟才能恢复！

**Comment by breakwa11** [comment]
@cxlovemg 你需要提供具体的配置信息，程序LOG，以及服务器所在服务商

**Comment by ziluopao** [comment]
是啊，不具体，那和猜谜没啥区别
