### ISSUE TITLE
添加多条线路问题

### ISSUE THREAD

**Issue by andy817** [breakwa11/shadowsocks-rss#612]
已经在一个vps上做好一条线路了，想再用别的vps，再加一条线路，这个时候怎么做？我试了直接按照不同vps后端的安装方法，修改对应的serverinfo.py和 usermysql.json后，运行会产生ip占用问题（多开了ss服务端），导致两台服务器都宕机。。。请大神指导。。。

**Comment by breakwa11** [comment]
@andy817 VPS上加线路？完全不懂你要干什么

**Comment by andy817** [comment]
已有一个节点，再加一个节点，ip不同，第二个服务器怎么部署？我按照不同vps部署的教程，修改serverinfo.py和 usermysql.json对应内容，但是会出现WARNING IPV4 error: [Errno 98] Address already in use 的问题，毕竟一个网站只有一个节点不够用，想请教一下。   第二胎服务器的怎么搭建，才不会出现这个占用的问题呢？

**Comment by breakwa11** [comment]
两个节点怎么可能会冲突？如果你用的是两台不同的VPS

**Comment by andy817** [comment]
@breakwa11 就是参照这个教程https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup(manyuser-with-mysql) 安装第二个服务器时，usermysql.json中修改host为第一台服务器ip，修改serverinfo.py中后台节点服务器列表相应的ID，，，就是这样的方式添加的第二个节点，运行一会就出错。
我找到有个人跟我问题类似https://github.com/breakwa11/shadowsocks-rss/issues/190，，他说解决办法是：”服务端配合自带./run.sh脚本启动，就可以了， 没有发生问题了，我之前使用 cd /root/shadowsocks
nohup python server.py & 自己手动开机加载会有问题 ，现在./run.sh脚本启动服务端已经没有发生了”我再次重装时，没有用nohup了，使用脚本自带的./run.sh启动服务器，，，但是运行一会还是出现了问题。
我有几个问题：
1. 我添加第二个服务器的方式是否正确？
2. 我对#190问题的理解正确吗？有没有搞错方向？
如果都是对的，那我再试试，如果有理解不对的，请大神多多指教。
（在同一ip下即同一台VPS下，建站，搭建服务器都成功了）

**Comment by breakwa11** [comment]
serverinfo.py 是什么鬼？

**Comment by breakwa11** [comment]
我要听的是你怎么配置的，而不是要听你到底怎么解决这个问题（何况你也没解决），我现在连你从哪里clone的服务端也不知道，你修改的文件是哪个我也不知道，你怎么配置我也不知道，你之前怎么运行的我也不知道，你服务器是怎么分配的我通通不知道

**Comment by andy817** [comment]
前端用的是这个https://github.com/Ahref-Group/SS-Panel-smarty-Edition
服务端用的是https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup(manyuser-with-mysql)
总体参照http://www.hopol.cn/2016/09/599/
不清楚这个搭配是否正确，有没有错误。
配置、修改都是按照教程的
同一ip下都没问题，就是第二台服务器（第二个ip）出错。

完全自己摸索中，问题没有讲清，十分抱歉，抱歉。

**Comment by breakwa11** [comment]
https://github.com/kjukjuatnk/ss-panel-v3-mod
请用这个面板

**Comment by tianzi77** [comment]
你的问题解决了吗？我现在也想添加多台 没找到教程
