### ISSUE TITLE
manyusers 数据库版，今天更新了之后如果不改user-config.json的method，所有端口启动都用这个method，原来则可以读数据库对应设置好的method的

### ISSUE THREAD

**Issue by j0hnnie** [breakwa11/shadowsocks-rss#613]
如题

**Comment by breakwa11** [comment]
@j0hnnie 你没有修改api interface

**Comment by rufengsuixing001** [comment]
谢谢j0hnnie ,我终于知道单用户版为啥更新了之后连不上了,混淆方式下面的总的会覆盖上面单端口设置里的混淆

**Comment by rufengsuixing001** [comment]
`{
    "server":"0.0.0.0",
    "server_ipv6": "[::]",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "80":{"password":"xiaojiesaigao","ofbs":"http_post","protocol": "auth_aes128_md5"},
        "443":{"password":"xiaojiesaigao","obfs": "plain"},
        "12345":{"password":"xiaojiesaigao","ofbs":"http-simple","protocol":"auth_aes128_md5"}
    },
    "timeout":300,
    "method":"chacha20",
    "protocol": "origin",
    "protocol_param": "",
    "obfs_param": "",
    "redirect": "",
    "dns_ipv6": true,
    "fast_open": true,
    "workers": 2
}`
结果80,12345,客户端只能用plain,连接

**Comment by breakwa11** [comment]
@rufengsuixing001 当然啊，用的ssr协议，ss当然连不上

**Comment by rufengsuixing001** [comment]
@breakwa11 
我用的是粉色的ssr安卓客户端,无论怎么设置,ofbs字段失效为plain.

**Comment by breakwa11** [comment]
你的问题别在别人的issue里问，我只回答提问者的问题

**Comment by dingmuqi** [comment]
@breakwa11 请问在哪修改 api interface的？

**Comment by breakwa11** [comment]
看wiki

**Comment by dingmuqi** [comment]
我使用的是多用户数据库版本
这是 user-config.json
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "9UQep9wk0MbU",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol":"origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}
这是userapiconfig.py
# Config
API_INTERFACE = 'sspanelv3' #mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)
UPDATE_TIME = 60
SERVER_PUB_ADDR = '127.0.0.1' # mujson_mgr need this to generate ssr link

#mudb
MUDB_FILE = 'mudb.json'

# Mysql
MYSQL_CONFIG = 'usermysql.json'

# API
MUAPI_CONFIG = 'usermuapi.json'

然后我找到的就是这个 API_INTERFACE 不知道可对 
然后现在运行 server.py的话 
util.py:85 loading libcrypto from libcrypto.so.10
2017-01-17 15:16:29 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-01-17 15:16:29 INFO     shell.py:80 ShadowsocksR 3.0.2 2017-01-08
2017-01-17 15:16:29 INFO     db_transfer.py:227 current process RLIMIT_NOFILE resource: soft 65535 hard 65535
2017-01-17 15:16:29 INFO     db_transfer.py:194 db start server at port [1025] pass [zXv1x3] protocol [origin] method [rc4-md5] obfs [plain]
2017-01-17 15:16:29 INFO     server_pool.py:128 starting server at [::]:1025
2017-01-17 15:16:29 INFO     server_pool.py:154 starting server at 0.0.0.0:1025
2017-01-17 15:16:29 INFO     db_transfer.py:194 db start server at port [1026] pass [RA92C4] protocol [origin] method [rc4-md5] obfs [plain]
2017-01-17 15:16:29 INFO     server_pool.py:128 starting server at [::]:1026
2017-01-17 15:16:29 INFO     server_pool.py:154 starting server at 0.0.0.0:1026

显示是 method [rc4-md5]

**Comment by dingmuqi** [comment]
对了 前端我使用的是 ss-panel 3.4.5

**Comment by breakwa11** [comment]
没错啊，你设置的是"method": "aes-256-cfb",
然后你定义以使用数据库的，所以都成了rc4-md5，一点问题都没有

**Comment by dingmuqi** [comment]
但是我ss-panel 3.4.5数据库里面节点设置的也是 aes-256-cfb 方式

**Comment by dingmuqi** [comment]
已找到原因 原来ss-panel 3.4.5 数据库每个用户都有自己的加密方式  谢谢了
