### ISSUE TITLE
偶尔出现System.Net.WebException

### ISSUE THREAD

**Issue by VoyagerII** [breakwa11/shadowsocks-rss#615]
环境有上网行为控制，不排除这个可能。
大概1-2个月出现一次，多台服务器测试无问题。
服务器记录无问题。大概20分钟到1小时就好了。
请问有什么解决方案吗？

V 4.0.3
ShadowsocksR-dotnet4.0.exe

`[2017-01-06 10:23:54] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-01-06 10:23:54] Void LogUsefulException(System.Exception)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Main(System.String[])

`

**Comment by breakwa11** [comment]
请更新版本，这个LOG看不出任何问题，我也不清楚你具体遇到了什么问题

**Comment by VoyagerII** [comment]
好的，谢谢。暂时应该不会遇到了。
具体我也不太清楚是什么原因引起的，只有在公司的网络环境下才会遇到。
我再描述一些吧。

log只有上面的错误
服务器链接统计也正常，错误、超时、空链都为0
上下行都有变化但是只有几个字节
过一段时间就自己好了
以前的版本也遇到过几次
其他网络通信正常
