### ISSUE TITLE
求教：指定端口走指定IP

### ISSUE THREAD

**Issue by angeldustneo** [breakwa11/shadowsocks-rss#619]
求教大神 ，我看到了曾经有这样一个ISSUES:
https://github.com/breakwa11/shadowsocks-rss/issues/291
我目前也需要给指定的端口绑定指定IP的功能
我看到这个功能貌似后来实现了。。。ISSUE 关闭了。。但是如何配置实在是没有想法 。。。

请问这个功能当前版本还能正常使用么 ？
另外我找了一下WIKI 并没有找到如何配置的方法 。。。。
是不是需要开多份SHADOWSOCKSR 服务端来实现？
求大神给个说明书链接。。。

谢谢~

**Comment by breakwa11** [comment]
不需要配置，什么IP进就什么IP出

**Comment by angeldustneo** [comment]
感谢大神那么神速的回复，小弟先去实验了~

**Comment by angeldustneo** [comment]
大神，小弟实验失败了，不知何故 。。。。
电脑上现在有2个网卡，绑定了2个地址 。。
目前从eth0:0 进来的信号，他照样从 eth0,出去，还是显示的主IP的地址 。。。

user-config.json 是这样写的。。用的是SS-PANEL-MOD的后端。。
"server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1"


ifconfig 是这样的：
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp

auto eth0:0
iface eth0:0 inet static
address 172.27.0.122
netmask 255.255.0.0

不知道为何无法原路返回。。。求大神讲解

**Comment by esdeathlove** [comment]
ifconfig -a 结果发下2017年1月12日 上午2:00，angeldustneo <notifications@github.com>写道：大神，小弟实验失败了，不知何故 。。。。
电脑上现在有2个网卡，绑定了2个地址 。。
目前从eth0:0 进来的信号，他照样从 eth0,出去，还是显示的主IP的地址 。。。
user-config.json 是这样写的。。用的是SS-PANEL-MOD的后端。。
"server": "0.0.0.0",
"server_ipv6": "::",
"server_port": 8388,
"local_address": "127.0.0.1"
ifconfig 是这样的：
The loopback network interface
auto lo
iface lo inet loopback
The primary network interface
auto eth0
iface eth0 inet dhcp
auto eth0:0
iface eth0:0 inet static
address 172.27.0.122
netmask 255.255.0.0
不知道为何无法原路返回。。。求大神讲解

**Comment by angeldustneo** [comment]
eth0      Link encap:Ethernet  HWaddr 02:00:46:20:00:04  
          inet addr:172.27.0.172  Bcast:172.27.255.255  Mask:255.255.0.0
          inet6 addr: fe80::46ff:fe20:4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:102213211 errors:0 dropped:0 overruns:0 frame:0
          TX packets:130580812 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:20900921143 (20.9 GB)  TX bytes:24194307661 (24.1 GB)

eth0:0    Link encap:Ethernet  HWaddr 02:00:46:20:00:04  
          inet addr:172.27.0.122  Bcast:172.27.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

求楼上大神和 破娃大神讲解 。。。
都是通过端口转发的方式 。。不知道是不是 XEN的机器不行 。。。。
一定要KVM 直接绑定公网IP -3-?

**Comment by breakwa11** [comment]
问题是这是内网地址
