### ISSUE TITLE
女神 能不能增加一个单一tcp连接流量达到某值强制断开功能

### ISSUE THREAD

**Issue by jfc8000** [breakwa11/shadowsocks-rss#62]
我的意思是 当单个tcp流量达到一个值的时候就强制断开这个tcp连接 最好可以手动指定这个值
还有时长 一个tcp连接不管还有没有流量 到一定时间也强制断开
这样可以一定程度避免gfw的流量匹配

再次感谢 你是我的女神

**Comment by breakwa11** [comment]
这样会导致下载和看视频会出问题

**Comment by jfc8000** [comment]
不会 至少youtube不会 而且还会减少卡顿

**Comment by falseen** [comment]
这个还有待验证，但不管怎么样说，有一点必须明确，那就是必须对视频和下载等大流量连接做特殊处理。
