### ISSUE TITLE
何时能重温啪啪啪时的感觉

### ISSUE THREAD

**Issue by ziluopao** [breakwa11/shadowsocks-rss#623]
记得第一次用老版的shadowsocks时，其快感让我惊呆了，只听的啪啪啪鼠标指哪打哪，所向披靡！人整个进入不断颤抖的状态，不仅是墙外，墙内也是如此，当时真的感觉似乎自己没有了墙的界限！而现在用shadowsocks4.0.3真的完了，打开速度就和牛拉的车一样，那么问题来了，何进才能重返美丽的卡萨不兰卡呢？

**Comment by wongsyrone** [comment]
老兄，你的文采很棒

**Comment by ziluopao** [comment]
文采棒有个P用，我真功夫棒才是Number !

**Comment by bugparty** [comment]
这样真的好吗  @breakwa11

**Comment by shmily0827** [comment]
@ziluopao shadowsocksR就是大垃圾啦，回去用shadowsocks就好啦。你不觉得你脑子有个坑？

**Comment by bugparty** [comment]
....五毛现在都会玩github了？
