### ISSUE TITLE
前端配置的v2，用最新ssr提示以下问题

### ISSUE THREAD

**Issue by b956536180** [breakwa11/shadowsocks-rss#626]
<img width="346" alt="qq20170110-1 2x" src="https://cloud.githubusercontent.com/assets/6139002/21807146/41b7aa10-d778-11e6-9d2d-b59a38c15e11.png">
<img width="592" alt="qq20170110-0s 2x" src="https://cloud.githubusercontent.com/assets/6139002/21807147/420ca128-d778-11e6-969f-58e96c367126.png">
<img width="1377" alt="qq20170110-0 2x" src="https://cloud.githubusercontent.com/assets/6139002/21807148/420daa14-d778-11e6-87ce-0405c5294a43.png">
上面是配置过程，前端配置的v2，遇上日志上的问题
我怀疑v2上的节点列表并没有协议混淆导致的，账户密码确定无误。

**Comment by b956536180** [comment]
截图的地方有个问题，加密没有错，截图错了。。。
正确的截图

**Comment by breakwa11** [comment]
解决了？

**Comment by b956536180** [comment]
谢谢大神，解决了，我发现ss原版的不兼容这个，，，看了更新日志之后才发现，谢谢，@breakwa11
