### ISSUE TITLE
python local.py can not working

### ISSUE THREAD

**Issue by sunnoy** [breakwa11/shadowsocks-rss#629]
**my json**

{
    "server": "*********",
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "timeout": 300,
    "workers": 1,
    "server_port": 888861,
    "password": "J0k6gQ",
    "method": "aes-256-cfb",
    "obfs": "http_simple",
    "protocol": "auth_aes128_md5"
}
 **the client log**
INFO: loading config from us.json
2017-01-12 19:09:56 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-01-12 19:09:56 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [J0k6gQ] method [aes-256-cfb] obfs [http_simple] obfs_param []
2017-01-12 19:09:56 INFO     local.py:54 starting local at 127.0.0.1:1080
2017-01-12 19:09:56 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

**the firefox give me  the log**
The proxy server is refusing connections

I have been  workout it for two days ...........

**Comment by breakwa11** [comment]
"server_port": 888861,
这是什么鬼

**Comment by ziluopao** [comment]
估计是协议没射好

**Comment by sunnoy** [comment]
"server_port": 888861,  = "server_port": ××××, shift键似乎抽风了。。。  

配置文件在ss panel上复制的，手机，win都可以链接，重装过的Linux mint 就不行了  配置过程按 wiki来的

**Comment by breakwa11** [comment]
服务端log呢，以及你的DNS有问题

**Comment by sunnoy** [comment]
@breakwa11 的确是dns的问题，以前是自动获取可以连接，重装过系统就没有更改，现在更改手动设置dns为114.114.114.114可以连接。好像是很高深的原因，有个小伙伴一样的配置自动获取就可以连接 不过他的是Ubuntu，我的mint手动设置才可以。

**Comment by breakwa11** [comment]
asyncdns.py:324 dns server: [('127.0.1.1', 53)]

这个LOG写着，DNS没有配置，是坏的

**Comment by sunnoy** [comment]
明白了  谢谢你肯花时间解答！
