### ISSUE TITLE
求支持linux

### ISSUE THREAD

**Issue by Qingmu** [breakwa11/shadowsocks-rss#632]
似乎只有win和mac版本呐，我强行把参数修改到shadowsocks-rss里面，似乎有很多参数对不上...LINUX下如何弄？？

**Comment by breakwa11** [comment]
@Qingmu 那python版本是啥，ssr-libev又是啥

**Comment by Qingmu** [comment]
用的是python版本，但是参数是c#版移过去的

**Comment by breakwa11** [comment]
@Qingmu python版用python的文档

**Comment by Qingmu** [comment]
对着文档参数看着呢~但是有些参数不晓得怎么转过去，比如C#版的`id`，在python那版并没有见对应的参数，不然直接照着改就好了...我懒了，没看源码，要是有个脚本大概能json格式转换过去就好~~

**Comment by breakwa11** [comment]
@Qingmu 你照着config.json改不就好了吗，而且wiki上明明有写
