### ISSUE TITLE
怎么设置才能实现中转服务器的功能

### ISSUE THREAD

**Issue by xinjiangdabiaoge** [breakwa11/shadowsocks-rss#633]
国外的vps已经搭建了ssr，但是直连效果不理想，想从国内服务器中转一下，国内的服务器应该怎么设置才能实现这个功能呢

**Comment by lizongzeshunshun** [comment]
haproxy?

**Comment by breakwa11** [comment]
用iptables或别的代理软件或SSR自己的转发功能

**Comment by xinjiangdabiaoge** [comment]
大神，我从网上找的方法，不过用了之后连接不上，能不能给指导一下哪里出了问题，应该怎么做
ssr服务器地址：45.32.72.251 端口：9001 国内vps地址：123.56.30.149  
# Generated by iptables-save v1.3.5 on Sun Jan 15 21:41:30 2017
*nat
:PREROUTING ACCEPT [85:4632]
:POSTROUTING ACCEPT [183:11957]
:OUTPUT ACCEPT [183:11957]
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 45.32.72.251:9001
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 45.32.72.251:9001
-A POSTROUTING -d 45.32.72.251 -p tcp -m tcp --dport 9001 -j SNAT --to-source 123.56.30.149
-A POSTROUTING -d 45.32.72.251 -p udp -m udp --dport 9001 -j SNAT --to-source 123.56.30.149
-A POSTROUTING -d 45.32.72.251 -p tcp -m tcp --dport 9001 -j SNAT --to-source 123.56.30.149
COMMIT
# Completed on Sun Jan 15 21:41:30 2017
# Generated by iptables-save v1.3.5 on Sun Jan 15 21:41:30 2017
*filter
:INPUT ACCEPT [703:84981]
:FORWARD ACCEPT [90:4596]
:OUTPUT ACCEPT [1411:116973]
-A INPUT -p udp -m udp --dport 8989 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8989 -j ACCEPT
-A INPUT -p udp -m udp --dport 1080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1080 -j ACCEPT
-A INPUT -p udp -m udp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p udp -m udp --dport 9001 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9001 -j ACCEPT
COMMIT
# Completed on Sun Jan 15 21:41:30 2017
