### ISSUE TITLE
服务端SSR,初次运行server.py时提示  ImportError: No module named cymysql 

### ISSUE THREAD

**Issue by Sea-Flying** [breakwa11/shadowsocks-rss#638]
云主机centos6.5, 运行yum install MySQL-python 后还是不行，是不是系统python缺个库，但我是小白菜鸟，不懂怎么搞啊

**Comment by breakwa11** [comment]
@Sea-Flying 菜鸟可以原谅，但是出问题不看wiki，连步骤都不按wiki的来，都提示得这么清楚的情况下，那就不可原谅
