### ISSUE TITLE
关于ssr udp外发不免问题

### ISSUE THREAD

**Issue by xcrl** [breakwa11/shadowsocks-rss#639]
请问一下，同样是云免，为什么op能全免，ssr不能……

**Comment by xcrl** [comment]
不论如何，先感谢ssr作者，起码说作者已经尽力了

**Comment by xcrl** [comment]
求安卓端ssr udp转成tcp免的方法，谢谢

**Comment by breakwa11** [comment]
@xcrl SSR不支持免，你别想了

**Comment by wnxkiwi** [comment]
ssr是混淆和半匿名 udp只是个协议 普遍存在的网路协议  跟tcp与ip一样的在通讯上传输层协议 说白了就是ssr的附属功能
要免流也是从流量混淆上入手呀 udp不能吧

xcrl <notifications@github.com> 於 2017年1月19日星期四 寫道：
