### ISSUE TITLE
有个大问题，关于pac.

### ISSUE THREAD

**Issue by sxdxyxy** [breakwa11/shadowsocks-rss#64]
当我们选择代理模式为PAC模式后，就会自动修改本机代理地址为http://127.0.0.1:1080/pac?t=201509211715022636，每次重新启动以后，会根据系统自动的重新生成一个地址，但是这样就会有个问题，我想把这个pac地址给我局域网的同事，可是每次重启服务器就换这个地址的话，就相当的不便。看能不能把这个固定，或者可以指定成一个固定的地址。

**Comment by breakwa11** [comment]
只要把前面的127.0.0.1改为你的机器内网地址就行，其它不用管

**Comment by sxdxyxy** [comment]
我给别人的地址是http://192.168.23.121:1080/pac?t=201509211715022636, SS不重启一点儿问题都没有，可是只要服务器重启，这个自动代理脚本就变了,pac?t后面的部分变了，别人就不好使了。

**Comment by sxdxyxy** [comment]
后来发现其实给别人的地址只要填http://192.168.23.121:1080/pac 就可以了，真正有问题的不是这个问题，而是重启SSR就可以了。所以看来最新版本的有问题，莫名的假死。

**Comment by breakwa11** [comment]
是哪个最新版本？假死是什么情况？

**Comment by sxdxyxy** [comment]
最新版本3.44，经常假死，我换回3.4.3了，很稳定，一个星期都没有问题。

**Comment by sxdxyxy** [comment]
反正也不是死了，就是不能代理了，重启SSR就可以了，但过不了多久又不行了，原以为是远程服务器的问题，但我监测实际上都没有请求。

**Comment by CloudnuY** [comment]
sxdx=SXU? 
![image](https://cloud.githubusercontent.com/assets/14636247/10004618/448f408c-60e5-11e5-987e-2cb2e8c006b7.png)

**Comment by somebird** [comment]
请教一下怎么样换回3.4.3版，小白请教！

**Comment by sxdxyxy** [comment]
亲爱的，经过近一天的测试，我发现不是你的软件的问题，是firefox的问题。我现在删除了firefox 用Chrome和ie没有什么问题。不过任在测试过程中。

**Comment by somebird** [comment]
楼上的楼主，怎么样选择RSS过去的老版本？

**Comment by sxdxyxy** [comment]
直接把老版本的SSR放到你的目录里面，直接运行就行了，记得先退出新版本的程序。

**Comment by sofs2005** [comment]
这个pac地址是本机地址，直接用是不行的。。。

**Comment by sxdxyxy** [comment]
在局域网是可以的，我的手机上网，还有办公室其它同事的上网都是通过pac上的。

**Comment by sxdxyxy** [comment]
老大，这个帖子，可以结帖了。我现在用的也很稳定。
