### ISSUE TITLE
请问有没有shadowsocks-libev和shadowsocksR的性能对比

### ISSUE THREAD

**Issue by sin-zx** [breakwa11/shadowsocks-rss#640]
网上找的大多数是安全性/加密方式的对比,想问下性能方面两者如何?

**Comment by sin-zx** [comment]
@breakwa11

**Comment by breakwa11** [comment]
你到底指什么性能，还有，你发了issue为什么还要单独AT一下，嫌我收到的各种干扰消息不够多么

**Comment by sin-zx** [comment]
抱歉. 想问的是搭建完之后网络连接速度的对比,不知道有没有过这种对比试验

**Comment by jameseroyi** [comment]
感觉是时候把中文wiki撤了。。最近的issue简直看不下去😂😂


2017年1月19日 18:25，"chrysalis" <notifications@github.com>写道：

**Comment by sin-zx** [comment]
@jameseroyi 请问有什么问题吗?是问题太低级还是怎么?

**Comment by breakwa11** [comment]
你很牛啊，才在这发完不算，还要是别两个地方各发一个，我拒绝回答你的问题

**Comment by jameseroyi** [comment]
你觉得呢？


2017年1月19日 18:28，"破娃酱" <notifications@github.com>写道：

**Comment by sin-zx** [comment]
因为相对比各版本的差异,网上查又查不到什么资料,全是您的黑历史.
如果作者人品这样的话那也没什么可说的....问个问题不回答尽说些有的没的....

**Comment by breakwa11** [comment]
我又不是必须回答你的问题，更不是客服，你同一个问题非得把所有地方像垃圾一样发满，像发广告一样才觉得舒服么

**Comment by jameseroyi** [comment]
你不会自己测试吗  各个地区 ISP不同 QoS不同 有必要这样？人家是开发者 又不是客服 wiki写的你看得懂看 看不懂给你讲了你也一样不会懂

2017年1月19日 18:33，"破娃酱" <notifications@github.com>写道：
