### ISSUE TITLE
请问各位菊苣哪个混淆方式网络开销小一点？

### ISSUE THREAD

**Issue by Just2co** [breakwa11/shadowsocks-rss#648]
本人通过在服务器上搭建SS-R服务，并且利用auth_sha1协议,http-simple的混淆方式，来达到欺骗广西移动计费服务器，达到上网的目的，之前我用的是VPN，因为比较费电，所以后来改成了比较省电的SS，但是现在出现了新问题，就是以前用VPN的时候，一天到晚都开着4G流量，然后连上VPN，上网一点，才被移动扣了几百K，现在用SS-R,虽然免去了几千兆流量，挂一天还是要扣掉几十兆，我就感觉我现在用的这个方式网络开销有些大，能不能换用其他网络开销小一些的混淆协议？混淆方式必须要选http-simple的，这个没办法换！

@breakwa11 你对各种混淆协议很了解，能介绍一些网络开销小一些的协议，我来测试一下吗？现在的auth_sha1跳点比较厉害，用来免流上网扣的有点多，感谢回复！

**Comment by breakwa11** [comment]
非法用途不提供任何信息

**Comment by zh-lab** [comment]
hahaha

**Comment by Just2co** [comment]
请把这个问题删掉！谢谢！

**Comment by breakwa11** [comment]
只能你自己删
