### ISSUE TITLE
对于视频观看中的一下问题

### ISSUE THREAD

**Issue by zhangyunhai210** [breakwa11/shadowsocks-rss#649]
没有详细看过ss原理，所有可能会说出一些错误观点，能原谅并指出万分感谢
在看土鳖视频的过程中，发现当加载完一段数据后，再次发起连接会先处理需要发送的信息，一个视频中多次发生，请问有什么办法可已解决类似这种流数据的多次加载问题吗？
如果对于这种流数据进行惰性加载的话，是否具有可行性？

**Comment by breakwa11** [comment]
@zhangyunhai210 我看不懂你在说什么

**Comment by zhangyunhai210** [comment]
类似下载完一个小数据文件，然后马上又需要下另一个小数据文件，但是在两次下载之间，因需要处理报头（?）等信息，需要等待一段时间，导致两次数据交互间有着一段时间的流量真空期

**Comment by breakwa11** [comment]
我还是不知道你说啥，我不要听你猜，你到底遇到什么

**Comment by zhangyunhai210** [comment]
看视频看了一会就卡一会

**Comment by caoge12138** [comment]
youtube的分段缓存嘛

**Comment by zhangyunhai210** [comment]
@caoge12138 请问有什么插件或者其他解决办法吗？

**Comment by chncwang** [comment]
我以前也经常碰到这种情况，解决方案就是不用电信的ADSL，用移动的或联通的都没这种问题

**Comment by zhangyunhai210** [comment]
@chncwang 南方啊，电信垄断，一个小区里面只能上电信，考虑要不要弄个国内服务器进行中转，但想着有没有其他办法办法解决这种问题

**Comment by chncwang** [comment]
我试过用阿里云做私人代理，直接代理进程被杀……

**Comment by chncwang** [comment]
竟然有只能上电信的小区……

**Comment by chncwang** [comment]
电信对海外的出口流量紧张，会策略性丢包的，比如每2个包给你丢1个

**Comment by zhangyunhai210** [comment]
@chncwang 我的想法是有没有可能，取消掉youtube的分段缓存，直接一次性缓冲完，但上午查了下，土鳖本身好像对这种行为进行了拒绝措施，所以很苦恼，现在

**Comment by Antairez** [comment]
@zhangyunhai210 youtube center disable dash playback.

http://lifehacker.com/preload-entire-youtube-videos-by-disabling-dash-playbac-1186454034

**Comment by zhangyunhai210** [comment]
@Antairez oh,thx,but i think I have to carefully study the network protocol
