### ISSUE TITLE
UDP 转发的问题

### ISSUE THREAD

**Issue by zydycjr** [breakwa11/shadowsocks-rss#653]
你好 我在arukas 上建了一个SSR服务器。 有两个问题，1就是自己建的端口映射都没问题。 可是启动以后 能ping通。但是网页测试fail。
2就是用了别人建的SSR 但是UDP转发还是不行，听说UDP的转发应该是默认开启的是吗？ 还是需要改一下设置

**Comment by zydycjr** [comment]
新年快乐。谢谢这么快的回复！ 请问第一个问题 自己用malaohu/ssr-with-net-speeder 建的SSR都fail。 用CentOS然后git clone 也是 失败，是有什么地方我没注意到吗？

**Comment by breakwa11** [comment]
@zydycjr 不是我的repo我不管

**Comment by zydycjr** [comment]
好嘞。。谢谢啦！

**Comment by zydycjr** [comment]
不好意思 多问个问题， 在docker中端口映射 是选TCP还是UDP 8989端口？

**Comment by breakwa11** [comment]
都要

**Comment by zydycjr** [comment]
好嘞！请关闭

**Comment by breakwa11** [comment]
为啥你不自己关

**Comment by zydycjr** [comment]
不好意思。不知道能自己关可以了
