### ISSUE TITLE
目测这个软件已经被深度包检测了

### ISSUE THREAD

**Issue by loveyanbei** [breakwa11/shadowsocks-rss#654]
最近本来是给ss换线路提速的，一开始换到vultr美区，搭好以后用plain的混淆/协议，能用，但是一天以后就挂了，连ssh都没了只能走网页终端。
第二次换到vultr新加坡，用了ssr的auth_sha1+tls的混淆，依然在一天后被封禁。
有没有一样遭遇的兄弟？

**Comment by loveyanbei** [comment]
顺便贴个tracert

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Jan 29 19:06:02 2017 from 1.198.34.37
root@i-xsdqhuks:~# traceroute 45.76.159.246
traceroute to 45.76.159.246 (45.76.159.246), 30 hops max, 60 byte packets
 1  192.168.100.1 (192.168.100.1)  0.166 ms  0.160 ms  0.185 ms
 2  10.60.24.1 (10.60.24.1)  0.368 ms  0.364 ms  0.357 ms
 3  10.16.22.140 (10.16.22.140)  0.358 ms  0.355 ms  0.358 ms
 4  * * *
 5  172.16.0.25 (172.16.0.25)  1.212 ms  1.613 ms  1.510 ms
 6  202.97.47.141 (202.97.47.141)  1.355 ms  2.592 ms  2.871 ms
 7  202.97.47.133 (202.97.47.133)  18.984 ms  18.546 ms  6.357 ms
 8  * * *
 9  183.2.241.225 (183.2.241.225)  1.479 ms 183.2.241.205 (183.2.241.205)  1.256 ms 183.2.241.233 (183.2.241.233)  1.446 ms
10  183.2.253.33 (183.2.253.33)  3.044 ms  3.032 ms  3.016 ms
11  183.59.14.229 (183.59.14.229)  4.182 ms  4.221 ms 183.59.5.226 (183.59.5.226)  4.310 ms
12  202.97.64.117 (202.97.64.117)  9.718 ms  9.721 ms  11.678 ms
13  202.97.33.222 (202.97.33.222)  4.646 ms * 202.97.91.178 (202.97.91.178)  7.721 ms
14  202.97.91.230 (202.97.91.230)  8.359 ms 202.97.60.214 (202.97.60.214)  106.217 ms 202.97.60.90 (202.97.60.90)  5.723 ms
15  202.97.60.214 (202.97.60.214)  108.149 ms ae-2.r31.tokyjp05.jp.bb.gin.ntt.net (129.250.2.155)  116.873 ms  105.818 ms
16  * ae-2.r31.tokyjp05.jp.bb.gin.ntt.net (129.250.2.155)  124.659 ms  124.642 ms
17  ae-3.r00.sngpsi05.sg.bb.gin.ntt.net (129.250.7.21)  174.361 ms  183.045 ms *
18  ae-3.r00.sngpsi05.sg.bb.gin.ntt.net (129.250.7.21)  175.011 ms 116.51.18.134 (116.51.18.134)  191.696 ms  182.976 ms
19  vl803-ds1-b5-r1251.sgp1.choopa.net (45.32.96.34)  173.048 ms  172.577 ms  175.967 ms
20  * vl803-ds1-b5-r1251.sgp1.choopa.net (45.32.96.34)  176.703 ms *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
root@i-xsdqhuks:~# 

从自己机器和青云的traceroute最后一跳都是一个地址，百度显示此地址属于米国，我表示很方。

**Comment by loveyanbei** [comment]
重新建了个实例换了ip就通了

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Jan 29 19:13:55 2017 from 1.198.34.37
root@i-xsdqhuks:~# traceroute 45.32.116.59
traceroute to 45.32.116.59 (45.32.116.59), 30 hops max, 60 byte packets
 1  192.168.100.1 (192.168.100.1)  0.179 ms  0.170 ms  0.200 ms
 2  10.60.24.1 (10.60.24.1)  0.316 ms  0.319 ms  0.333 ms
 3  10.16.22.140 (10.16.22.140)  0.331 ms  0.319 ms  0.300 ms
 4  * * *
 5  172.16.0.29 (172.16.0.29)  1.955 ms  1.839 ms  2.143 ms
 6  202.97.47.141 (202.97.47.141)  1.640 ms  1.351 ms  1.400 ms
 7  202.97.47.133 (202.97.47.133)  6.801 ms  5.669 ms  4.920 ms
 8  183.6.195.85 (183.6.195.85)  7.467 ms  7.468 ms  7.515 ms
 9  183.2.241.221 (183.2.241.221)  1.337 ms 183.2.241.245 (183.2.241.245)  1.446 ms 183.2.241.213 (183.2.241.213)  1.492 ms
10  183.59.12.97 (183.59.12.97)  2.516 ms  2.533 ms 183.59.15.237 (183.59.15.237)  3.589 ms
11  183.61.223.174 (183.61.223.174)  3.666 ms 183.61.220.250 (183.61.220.250)  8.276 ms 183.61.223.174 (183.61.223.174)  3.647 ms
12  202.97.64.125 (202.97.64.125)  8.786 ms * 202.97.35.202 (202.97.35.202)  2.722 ms
13  202.97.33.186 (202.97.33.186)  10.477 ms 202.97.91.226 (202.97.91.226)  6.345 ms 202.97.33.198 (202.97.33.198)  14.173 ms
14  p64-7-1-0.r27.tokyjp05.jp.bb.gin.ntt.net (129.250.66.9)  91.156 ms  91.128 ms  91.145 ms
15  ae-2.r31.tokyjp05.jp.bb.gin.ntt.net (129.250.2.155)  115.399 ms  86.126 ms p64-7-1-0.r27.tokyjp05.jp.bb.gin.ntt.net (129.250.66.9)  92.559 ms
16  ae-2.r31.tokyjp05.jp.bb.gin.ntt.net (129.250.2.155)  117.554 ms  88.138 ms ae-5.r21.sngpsi05.sg.bb.gin.ntt.net (129.250.7.39)  175.697 ms
17  ae-3.r00.sngpsi05.sg.bb.gin.ntt.net (129.250.7.21)  167.713 ms *  160.521 ms
18  116.51.18.134 (116.51.18.134)  190.984 ms ae-3.r00.sngpsi05.sg.bb.gin.ntt.net (129.250.7.21)  161.134 ms 116.51.18.134 (116.51.18.134)  182.041 ms
19  116.51.18.134 (116.51.18.134)  184.439 ms vl803-ds1-b5-r1251.sgp1.choopa.net (45.32.96.34)  186.255 ms 116.51.18.134 (116.51.18.134)  183.061 ms
20  * vl803-ds1-b5-r1251.sgp1.choopa.net (45.32.96.34)  187.363 ms  187.768 ms
21  * * *
22  * * *
23  * * *
24  * * *
25  * * 45.32.116.59.vultr.com (45.32.116.59)  137.625 ms
root@i-xsdqhuks:~#

**Comment by loveyanbei** [comment]
兄弟们一起分析分析这是运营册的锅还是国家的锅，我感觉后几跳已经过了出口但是却无法建立联系，如ssh和shadowsocks，看起来像是运营商挂了，但是话说回来，几天内连续刮掉两个主机，是有点不太正常。

**Comment by breakwa11** [comment]
@loveyanbei 请确定使用最新协议，以及混淆没有填写参数，tls混淆需要节点有域名解析

**Comment by esdeathlove** [comment]
你换个VPS服务商呢？

**Comment by loveyanbei** [comment]
@esdeathlove xd啊我充了一百几十块,好心疼的.暂时不考虑换服务商,至少要支持银联/bitcoin的支付才能考虑.

**Comment by loveyanbei** [comment]
@breakwa11 那么就只能用http?

**Comment by loveyanbei** [comment]
{
 "server":"45.32.116.59",
 "server_port":"80",
 "password":"xxxxxxxxxxxxxxxxxxxx",
 "local_address":"127.0.0.1",
 "local_port":"1080",
 "method":"aes-256-cfb",
 "timeout":400,
 "fast_open":false,
 "workers":4,
 "protocol":"auth_sha1_v4",
 "obfs":"http_simple",
 "obfs_param":"github.com,raw.githubusercontent.com,nicovideo.jp,bilibili.com,qq.com,youtube.com,google.com,elastic.co"

}
我看看这配置,多久会完蛋吧

**Comment by breakwa11** [comment]
协议最好用auth_aes128_md5，加密用rc4-md5就行，混淆用http_simple可以试试，服务端并不需要写混淆参数，请看说明再写参数，最好填写redirect，以及workers这个你写了等于没写，还有一个是记得改系统最大文件数

**Comment by vtroop** [comment]
楼主方便说下什么地区运营商吗

**Comment by silentstage** [comment]
我以前出现过类似情况，因为不懂Linux，觉得修改端口参数很麻烦，在Centos7下面才用最简单粗暴的办法就是把防火墙卸载了，这个命令好找。结果每天刚开始都能用，服务器一天不到就ping不通连不上，但是从Vultr控制台能进。开始以为是GFW，连续一周后发现是自己操作问题。现在用的Vultr日本，正常运作4个月了。你可以参考下

**Comment by loveyanbei** [comment]
@silentstage firewalld和selinux我开实例就disable掉，但是这个和fw没关系，重新用deb/ubuntu我也关了ufw，而且默认fw的配置都是放行ssh，我的那几个实例ssh都没了。

**Comment by sueccku** [comment]
被封了的vps试试能不能被ping通，看看vultr给没给你发工单，是不是被ddos了，或者占用资源太大暂时给你关了，我也用的vultr，从来没遇到这种情况

**Comment by tonyzhangbo78** [comment]
我也遇到过，刚上来就不能用，境外能ping通，推断是被墙了，果断发工单，说明情况重新换了一个ip就好了

**Comment by breakwa11** [comment]
看起来现在超过1天是正常的了？

**Comment by stardock** [comment]
你可以试试用winmtr做一下追踪看看，我这儿一切正常

![default](https://cloud.githubusercontent.com/assets/11665205/22494310/517f3918-e871-11e6-970a-194e80f2d291.png)

**Comment by zhangzhezh** [comment]
你这种情况是IP之前就已经被黑了，你就算是正常的HTTP，正常的SSH，只要长时间有流量一样被干，具体表现为持续流量一段时间，然后断流10分钟，或者还有另外一种情况TLS SHA1握手过后就会出现断流 一段时间，Ping也不通，等于就是完全断网，一段时间后会自行恢复，跟SSR已经无关，已经超出了深度包检测的范畴。这时你用任何工具都是没办法Bypass的。。

**Comment by sueccku** [comment]
楼上说的对，对有的ip稍微有点动作立马断流一段时间，然后就自动好了，对有的ip，怎么倒腾都没事

**Comment by Justsoos** [comment]
楼主的逻辑不对劲。gfw 搞你，遵循这个优先级：
http > plain proxy > ssh > ssl > ss (ssr) 
IP被封了，不能直接怪优先级最低的，而应该考虑前面几个。

**Comment by Justsoos** [comment]
http://cdn.aixifan.com/player/filter/ban.json  
可以试试，把这个json内容curl post 你vps 的80 口，很容易就会被ban，而充分加密，去协议特征的ss 并不容易引发gfw 的动作。

**Comment by vtroop** [comment]
@Justsoos 老哥稳

**Comment by breakwa11** [comment]
麻烦楼主及时反馈最新情况

**Comment by w-tim** [comment]
提供些其他信息。自建的linode服，作者建议的“协议最好用auth_aes128_md5，加密用rc4-md5就行”，今天手贱试了下，用了10分钟后就怎么也连不上了，协议修改为一直稳定使用的auth_aes128_sha1,加密用aes_256_cfb后一切正常。上海电信。我觉得rc4-md5是靠不住的了。尽管一直谨记那句“ssr是用来混淆，而不是加密的“

**Comment by breakwa11** [comment]
@w-tim 拜托，linode本来就是重点对象，没封只是运气好

**Comment by loveyanbei** [comment]
@Justsoos 我的vps没有任何其他服务,只有ss,以前的vps还跑了个flask去抓取中国数字时代呢....都没过事情
换的这个主机目前没被封,但是ss连接质量感人,准备过两天再跳区看看.
一开始是a经常远端域名解析失败,改了resolv.conf以后,发现只是没了那个解析失败的提示,本机代理的chrome会提示ERR_EMPTY_RESPONSE,sslocal也没有任何输入,是输出被关了么..

**Comment by loveyanbei** [comment]
而且诡异的是,新加坡的这个服务器我用shadowrocket做客户端上1024很顺,跑github和google就像吃屎一样.

**Comment by loveyanbei** [comment]
@sueccku 服务商没有通知我,并且我web终端操作网络是正常的.

**Comment by breakwa11** [comment]
请问，你在使用auth_aes128_md5还遇到问题吗？

**Comment by loveyanbei** [comment]
最新实验的结果是访问elastic.co和program-think.blogspot.com基本就是打不开,换了ip和密码改善了

**Comment by breakwa11** [comment]
你到底用的什么客户端

**Comment by loveyanbei** [comment]
电脑是linux的sslocal,用的ssr的sslocal
ipad是shadowrocket
chrome就给我这个
This site can’t be reached

program-think.blogspot.com unexpectedly closed the connection.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_CLOSED

**Comment by loveyanbei** [comment]
感觉不管怎么调,明显没以前连接顺畅了,是不是最近中央决定整治vpn,墙高了

**Comment by loveyanbei** [comment]
总体来说,翻出去的成功率是急剧下降的,整个体验完全不行了...

**Comment by Justsoos** [comment]
@loveyanbei  人挪活，树挪死。没必要纠缠一个新加坡vps，翻墙这事儿，就是个工具而已。
换个线路，可能结果吓死你。这几天我在用樱花免费docker ，3分钟建一个SSR+Kcptun，出国百兆能跑满速。
需要待在一棵树上吊死自己么？没意义

**Comment by loveyanbei** [comment]
@Justsoos 我是在日区美区几个来回跑.....vultr那么多区,我一般都是一个不行就换区换实例.
以前的108.61开头的实例用的挺好的,但是我被maven中央库封了,然后就想换个ip换个区看看,接着就是这样了.

**Comment by loveyanbei** [comment]
vultr最近分给我的ip都是45.x.x.x,使用的感觉就是,狂按十几次f5也不一定刷出来一次,就很气了.

**Comment by breakwa11** [comment]
@loveyanbei 对于linode/vultr/do这此早就被玩坏得差不多的，我就不说什么了

**Comment by loveyanbei** [comment]
@breakwa11 估计是被真理部重点关心了吧
只能等几个月换个新开的服务商了

**Comment by loveyanbei** [comment]
狠下心去买了香港阿里云,去掉了所有的混淆用了origin协议,解决.
看来还是马爸爸让人放心.

**Comment by theratlesnake** [comment]
@Justsoos 老哥你部署的SSR+Kcptun会过一段时间就上不了吗？我的不知道为什么用个半个小时左右就掉线，然后要过一阵才可以上，不知道是不是我的Kcptun客户端管理工具设置不对，还是哪里的问题，老哥可以分析一些么？

**Comment by theratlesnake** [comment]
@breakwa11 我是刚搭建好ssr+Kcptun，电脑端可以用，但是安卓端不会用也，好像在ssr安卓客户端没有看到【Kcptun】选项，怎么办？

**Comment by breakwa11** [comment]
@theratlesnake SSR不支持KCPTUN

**Comment by theratlesnake** [comment]
@breakwa11  嗯，https://www.htcp.net/2690.html  有人修改了SSR加入了Kcptun，破娃看看有问题么？

**Comment by stardock** [comment]
@theratlesnake  只是客户端加入了kcptun，  kcptun会破坏ssr 协议。所以用这个软件 目前就是  ss + kcptun, 或者纯属SSR。在一个客户端上面把两个方案合并了而已。

**Comment by dimi360** [comment]
我用日本服务器搭建的SSR一直在用，没什么问题
没有你们说得问题～
ssr://MTUzLjEyNS4yMzUuMTc4OjMxMzcwOmF1dGhfc2hhMTpjaGFjaGEyMDpodHRwX3NpbXBsZTpZbVZ1Wm5jdVkyND0vP29iZnNwYXJhbT1NVEUwTGpJMU5TNHlNREV1TVRZeiZyZW1hcmtzPTVhV1U1cFMtNTcyUlltVnVabmN1WTI0SzVhU2E1NnV2NVktajc3eWFNekV6TnpBdE16RXpOekV0TXpFek56SXRNekV6TnpNdE16RXpOalE9

**Comment by theratlesnake** [comment]
@dimi360 老哥你有安装Kcptun等加速吗？我不加速的话，看youtube最低画质都卡，太慢了

**Comment by theratlesnake** [comment]
@stardock  请问下老哥，你用的也是樱花服务器吗？
