### ISSUE TITLE
关于如何把数据包丢到ss通道里的问题

### ISSUE THREAD

**Issue by sueccku** [breakwa11/shadowsocks-rss#655]
因为很多家用网络bgp配的很坑，绕路现象很严重，为了有更好的体验，决定先在国内找一个bgp不坑的vps，让国外的vps（一下简称avps）先连到国内vps（bvps），然后用户只要连到bvps就行了，nat在bvps上，如图：
avps----（1通道）（一个通道）----bvps ----（2通道）（来自不同客户端的很多连接）----客户端s   为了照顾用户需要，2通道是openvpn，1通道是ss
问题是ss是sockvpn，但数据到了bvps都成数据包了，怎么让ss能像tun那样可以往里丢数据包（上次这么说被鄙视了，大体就是这个意思，或者说往sockvpn里丢数据包学名叫啥）？

**Comment by breakwa11** [comment]
SS是socks5接口，不是sockvpn，说实话我很难明白你在说什么，但你可以用openvpn自带的设置socks5代理通过SS来连接

**Comment by sueccku** [comment]
要想从一个电脑到另一个电脑上建立一个虚拟通道，可以选择通道内虚拟哪一层，可以选择建立一个虚拟的数据链路层，典型的就是tap，也可以选择虚拟一个ip层，典型的就是tun，像ss这样，是虚拟一个sock层，不就是socksvpn了吗

**Comment by breakwa11** [comment]
@sueccku 我去，又一个理解错误的家伙，这是VPN不是socks，socks也不是VPN，这种东西从来就不存在

**Comment by sueccku** [comment]
我没说过sock是vpn，从来没说过，这么说吧，openvpn的tun模式你知道吧，那你说能不能把这种东西简称tunvpn（大家都是这么叫的）

**Comment by breakwa11** [comment]
@sueccku 我知道你的意思，但你就理解错了，你在理解错误的情况下提出一个无法实现的需求，那就没有人能解决了。要么你修正你的理解重新表达你想干什么，要么按照我第一个回复解决

**Comment by sueccku** [comment]
我的理解错了.....求教，网上教程奇少，希望作者科普下，我见过很多人都有这样的理解

**Comment by breakwa11** [comment]
@sueccku 不，解释socks5的文章太多了，我建议你先找你附近或网上认识的这方面懂点的把问题和他说一下，让他帮整理表达，甚至他就能帮你解决，发issue时的内容有写这个，这里不适合什么都不懂的人发问题，你发了表达不清楚我也无法理解的话也只会浪费时间

**Comment by hfhxx** [comment]
@sueccku 关于你的想法，可以用 https://github.com/shadowsocksr/shadowsocksr-libev
的相关工具（ss-redir，ss-nat），其实就是 ssr的透明代理，类似
https://github.com/bettermanbao/openwrt-shadowsocksR-libev-full 实现的功能。

2017-02-02 14:08 GMT+08:00 破娃酱 <notifications@github.com>:

**Comment by Justsoos** [comment]
目测楼主这个小白，要的就是多级（多层）链路代理，只不过他的确不知道这个名字。
在国内作个跳转服务器 b vps，到国外a vps 之间用SSR
破墙娃一顿解释，反而把楼主搞迷糊了，哈哈
