### ISSUE TITLE
在路由端或者安卓端启用udp转发后youtube速度直线下降

### ISSUE THREAD

**Issue by haruhitamako** [breakwa11/shadowsocks-rss#658]
试过多种协议和混淆，youtube速度无法突破1000k，关闭后速度能达到带宽最大值。这是我在服务端的udp设置不当还是其他什么原因吗？希望能帮忙解惑，谢谢

**Comment by esdeathlove** [comment]
因为 YouTube 走了udp 加之 udp被QoS太严重的原因。要么 udp over tcp，否则无法解决。2017年2月5日 上午10:39，haruhitamako <notifications@github.com>写道：试过多种协议和混淆，youtube速度无法突破1000k，关闭后速度能达到带宽最大值。这是我在服务端的udp设置不当还是其他什么原因吗？希望能帮忙解惑，谢谢

**Comment by haruhitamako** [comment]
@esdeathlove 感谢回答。看来只能重新换回魔改版安卓端和openwrt了
