### ISSUE TITLE
3.4.4版把前置Socks5代理取消了吗？

### ISSUE THREAD

**Issue by redfrog999** [breakwa11/shadowsocks-rss#66]
用了下最新版RSS，发现前置Socks5代理设置界面没有了，只能在config.json里边改了，好麻烦，侠女下个版本能恢复吗？thx。

**Comment by breakwa11** [comment]
在右键菜单的“全局配置”里面，所有与节点无关的，全部放那边了

**Comment by redfrog999** [comment]
原来如此，看来这样的一致性简洁界面会持续下去了。习惯了也不错。期待更多的改进和对GFW的突破。

**Comment by breakwa11** [comment]
那么可以试试新版本3.5.0
