### ISSUE TITLE
单独修改port 似乎不起效

### ISSUE THREAD

**Issue by wuly12345** [breakwa11/shadowsocks-rss#662]
尝试python mujson_mgr.py -e -u xxxx -p 1002
用单独修改port 号， 命令没有报错， 但是貌似没有修改成功。 只能手动去修改配置文件实现。不知道这个是不是BUG

**Comment by breakwa11** [comment]
@wuly12345 不允许单独改port，只能新建立一个，删除旧的

**Comment by wuly12345** [comment]
Thanks
