### ISSUE TITLE
Wiki里的一点微小的错误，算是错别字级别吧~

### ISSUE THREAD

**Issue by Harry12138Mac** [breakwa11/shadowsocks-rss#663]
位置：
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup#%E5%AE%A2%E6%88%B7%E7%AB%AF

【注：以下客户端只有windows客户端和python版客户端可以使用SSR特性，其他原版客户端只能以兼容的方式连接SSR服务器（SSR可兼容SS客户端）。】

Android APP: SSR-android
iOS APP： Shadowrocket
MAC APP：ShadowsocksX-NG, ShadowsocksX-R

这些都可以加进去呀

**Comment by breakwa11** [comment]
@Harry12138Mac 你可以自己直接编辑wiki
