### ISSUE TITLE
请教一下，开启了Win客户端，Telegram还是不能登录，应该如何设置？

### ISSUE THREAD

**Issue by hupisha** [breakwa11/shadowsocks-rss#665]
不好意思，开启了Win客户端，Telegram还是不能登录，应该如何设置？谢谢了
是pac模式， 规则是【绕过局域网和大陆】
我家里路由器已经添加了Telegram的ip段
`WAN+149.154.160.1/32
WAN+149.154.160.2/31
WAN+149.154.160.4/30
WAN+149.154.160.8/29
WAN+149.154.160.16/28
WAN+149.154.160.32/27
WAN+149.154.160.64/26
WAN+149.154.160.128/25
WAN+149.154.161.0/24
WAN+149.154.162.0/23
WAN+149.154.164.0/22
WAN+149.154.168.0/21
WAN+91.108.4.0/22
WAN+91.108.56.0/24
WAN+109.239.140.0/24
WAN+67.198.55.0/24
WAN+91.108.56.172
WAN+149.154.175.50`

公司这个我没开通SS功能，所以没法添加了用，只能我单机运行客户端。

麻烦大家了

**Comment by breakwa11** [comment]
@hupisha 拜托，TG又不管你IE的代理设置，更不支持你的PAC

**Comment by breakwa11** [comment]
自己去修改TG的代理设置，这么小白的问题就不应该在这里出现，谢谢

**Comment by hupisha** [comment]
好的，谢谢。麻烦您了

2017-02-14 15:02 GMT+08:00 破娃酱 <notifications@github.com>:
