### ISSUE TITLE
privoxy port conflict while SSR client polygamy [enhancement]

### ISSUE THREAD

**Issue by Arthur2012** [breakwa11/shadowsocks-rss#666]
版本：SSR C# client win-4.1.1
现象：同时开多个SSR客户端时，会报privoxy端口冲突。
建议：由于privoxy的配置文件privoxy.conf是在temp目录下由SSR客户端每次启动自动创建，其端口号的设定未考虑SSR多开情况，造成冲突，且即使用户修改privoxy.conf也会在下次启动失效。有2个解决方法：随机生成privoxy端口；或者由用户自定义privoxy端口号写在gui-config.json文件内。

**Comment by breakwa11** [comment]
@Arthur2012 你确定你用对了客户端？

**Comment by Arthur2012** [comment]
@breakwa11 版本是SSR 4.1.1。
这个端口冲突情况在依次打开每个SSR客户端的时候**并不会发生**，但在**随系统自动启动情况下会发生**。
具体我的机器上，同时开着一个SS 3.3.5，和3个SSR 4.1.1。3个SSR所在目录见下图，有意思的是，每次都是是“ShadowsocksR-win-4.1.1 - 副本 (2)”与“ShadowsocksR-win-4.1.1 - 副本”会报privoxy端口冲突，其它互相之间并不会冲突。似乎文件夹路径和名称参与了随机端口的生成，但漏把字符串"(2)"计入了。
请核查。
![image](https://cloud.githubusercontent.com/assets/25565376/22964471/d09f1024-f393-11e6-87bc-ac5d2f40969a.png)
![image](https://cloud.githubusercontent.com/assets/25565376/22964540/2c33fe0e-f394-11e6-9993-abc62f9cb0a9.png)

**Comment by breakwa11** [comment]
下个版本改改随机的方式好了

**Comment by breakwa11** [comment]
请更新

**Comment by Arthur2012** [comment]
经验证，SSR随系统启动多开时privoxy报端口冲突的问题，4.1.2已不再发生。
