### ISSUE TITLE
关于SSR使用的一点小小的建议

### ISSUE THREAD

**Issue by nehcnoel** [breakwa11/shadowsocks-rss#668]
首先感谢楼主的无私奉献，给我们提供了这么好的工具。
因为平时需要经常在PAC和全局模式之间来回切换，想请问楼主是否考虑出一个快捷键功能呢（自定义或者其他）？
期待你的答复，谢谢~

**Comment by breakwa11** [comment]
@nehcnoel 暂不考虑，请使用浏览器插件

**Comment by Dwwwwww** [comment]
神tm楼主

**Comment by lbp0200** [comment]
@nehcnoel https://github.com/blackgear/mono_pac

**Comment by JonasGao** [comment]
@breakwa11 你回答了，倒是关闭呀  ┗( T﹏T )┛

@lbp0200 哎哟，你这个不错的样子
