### ISSUE TITLE
关于新版本混洗插件疑问

### ISSUE THREAD

**Issue by zd423** [breakwa11/shadowsocks-rss#67]
更了服务端至最新，没看到config.json有这个obfs字段，开启了混洗插件obfs  http_simple启用无法访问

**Comment by breakwa11** [comment]
是不是用的分支不对，或者config.json曾经修改过的原因（会导致git pull更新失败）？

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks/blob/manyuser/config.json
分支上是有的

**Comment by zd423** [comment]
config。json只改了加密方式rc4-md5，分支用的你项目最新的！

**Comment by zd423** [comment]
我是运行的这个命令安装的
git clone -b manyuser https://github.com/breakwa11/shadowsocks.git
是命令路径版本不对吗

**Comment by breakwa11** [comment]
路径是对的。出现问题的服务端log发我看一下吧

**Comment by zd423** [comment]
[zd423.Linode.东京锐速200M旗舰版(106xxxxx)] connection timeout
[2015-09-22 19:40:06] Shadowsocks started

查看我的那个config没有那个字段，新装的环境也一样没有那字段，直接手动添加可以？

**Comment by breakwa11** [comment]
如果没有那字段那是不对的，而且不能在vps上原来的路径执行clone操作，试试开一个新的文件夹试试

**Comment by cfcboy** [comment]
@zd423 删除原来的config.json文件，然后重新git pull就可以更新了。不然提示错误。

**Comment by zd423** [comment]
@cfcboy 谢谢，可以了！

**Comment by zd423** [comment]
@breakwa11单用户分支版  运行git pull不行啊fatal: Not a git repository (or any of the parent directories): .git
  单用户分支版怎么升级！config

**Comment by cfcboy** [comment]
@zd423 你可以用多用户的git源，然后用ss目录下的ss目录的run.sh（调用的是上级ss目录的config.json）

**Comment by breakwa11** [comment]
单用户分支目前还不支持，功能还没有合并在单用户分支，可以直接用多用户分支执行子目录来代替

**Comment by zd423** [comment]
@breakwa11 @cfcboy  恩目前这样可以了！

**Comment by simonsmh** [comment]
@breakwa11 是否能够考虑一下合并内外文件夹内容，thx！

**Comment by falseen** [comment]
现在根目录的是多用户版，子目录的是单用户版。没必要合并。
