### ISSUE TITLE
怎么在Ubuntu 上配置客户端？

### ISSUE THREAD

**Issue by repairwa11** [breakwa11/shadowsocks-rss#670]
有在Ubuntu上成功使用的案例吗？通过终端命令行搞定的那种！

**Comment by breakwa11** [comment]
@repairwa11 看wiki

**Comment by weizengyong** [comment]
没看明白怎样在ubuntu上配置客户端

**Comment by 12550763176** [comment]
同问，照着配置了一下，报错
配置/etc/shadowsocks-libev/config.json，运行后报错
2月 22 12:53:04 base ss-server[15979]:  2017-02-22 12:53:04 ERROR: bind: Cannot assign requested address
2月 22 12:53:04 base ss-server[15979]:  2017-02-22 12:53:04 ERROR: Could not bind
2月 22 12:53:04 base ss-server[15979]:  2017-02-22 12:53:04 ERROR: bind() error
2月 22 12:53:04 base systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
2月 22 12:53:04 base systemd[1]: shadowsocks-libev.service: Unit entered failed state.
2月 22 12:53:04 base systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

**Comment by breakwa11** [comment]
@12550763176 你运行的是SS服务端，和SSR没有关系

**Comment by wangchunming** [comment]
没想到SSR用http_simple域名写360,com速度立马就上去了，然后端口我用1080，以达到伪装socks代理明文上网的目的

**Comment by git-hcLee** [comment]
ubuntu16.04下按照wiki上的步骤一点点做的，这个代理在win下可以用，但是运行后也出错
2017-04-07 20:59:43 INFO     local.py:54 starting local at 127.0.0.1:1080
2017-04-07 20:59:43 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]
2017-04-07 20:59:55 ERROR    tcprelay.py:969 [Errno 32] Broken pipe
2017-04-07 20:59:55 ERROR    tcprelay.py:971 remote error, when connect to www.google.com:443

**Comment by sinderyminami** [comment]
ssr-libev目前只有linux的客户端
https://www.gitbook.com/book/neroxps/compile-shadowsocks-rss-libev/details
这个教程比wiki里那个详细点。
