### ISSUE TITLE
win10无法安装软件

### ISSUE THREAD

**Issue by yyh905509** [breakwa11/shadowsocks-rss#671]
出现问题如下：
Unexpected error, ShadowsocksR will exit. 
System.Reflection.TargetlnvocationException: 调用目标发生了异常
--> System.DI I NotFound Exception: 无法加载 DLL"Iibsscrypto": 找不到指定的模块. (异常来自 HRESULT:0x8007007E)。
在 Shadowsocks.Encryption.MbedTLS.mdS(Byte[] input, lnt32 ilen,
Byte[] output)
在 Shadowsocks.Encryption.MbedTLS.MDS(Byte[] input)
在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[]
password, Byte[] key)
tt Shadowsocks.Encryption.IVEncryptor.I nitKey(Stri ng method,
String password)
tt Shadowsocks.Encryption.NoneEncryptor .. ctor(String method,
String password)
--- 内部异常堆栈跟踪的结尾 ---
在 System.RuntimeMethodHandle.lnvokeMethod(Object target,
Obj ect[] arguments, Signature sig, Boolean constructor)
在 System.Reflection.Ru nti meConstructorl nfo.I nvoke(Binding Flags
invokeAttr, Binder binder, Object[] parameters, Culturelnfo culture)
在 Shadowsocks. Encryption. EncryptorFactory .Get Encryptorlnfo(String
method)
在 Shadowsocks.View.Config Form .. ctor(ShadowsocksController
controller, UpdateChecker updateChecker, lnt32 focuslndex)
在
Shadowsocks.View .MenuViewControl ler.ShowConfig Form(Boolean
add Node)
在
Shadowsocks.View.Menu ViewController .. ctor(ShadowsocksControlIer
controller)
在 Shadowsocks.Program.Main(String[] args)

win10系统。

**Comment by breakwa11** [comment]
@yyh905509 你把EXE放在什么目录了

**Comment by yyh905509** [comment]
C盘download目录

**Comment by breakwa11** [comment]
@yyh905509 检查exe文件有没有锁定属性，有就取消，并放在其它目录，不要在C盘

**Comment by yyh905509** [comment]
@breakwa11 OK 换了目录现在可以用了
