### ISSUE TITLE
Shadowrocket 无法通过扫描二维码添加 IPv6 节点

### ISSUE THREAD

**Issue by HolosLee** [breakwa11/shadowsocks-rss#674]
iOS 10.3 Public Beta 3，Shadowrocket 2.1.2，扫描 Windows 客户端 IPv6 服务器配置二维码会提示「无效的配置 url」，IPv4 正常导入，是因为 Shadowrocket 不支持 SSR IPv6 节点的导入吗？

**Comment by breakwa11** [comment]
去shadowrocket那边反馈这个问题
