### ISSUE TITLE
查看日志时出现几个error

### ISSUE THREAD

**Issue by luluijn** [breakwa11/shadowsocks-rss#675]
017-02-22 10:08:06 INFO     server.py:142 starting server at 0.0.0.0:808
017-02-22 10:08:06 ERROR    shell.py:50 [Errno 98] Address already in us
017-02-22 10:19:37 INFO     server.py:46 current process RLIMIT_NOFILE r
ce: soft 1024 hard 4096
017-02-22 10:19:37 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53)
017-02-22 10:19:37 INFO     server.py:106 server start with protocol[aut
1_v4] password [luluijn] method [rc4-md5] obfs [http_simple] obfs_param
017-02-22 10:19:37 INFO     server.py:122 starting server at [::]:8080
017-02-22 10:19:37 ERROR    shell.py:50 [Errno 98] Address already in us
017-02-22 10:19:37 INFO     server.py:142 starting server at 0.0.0.0:808
017-02-22 10:19:37 ERROR    shell.py:50 [Errno 98] Address already in us
 

该怎么修复，ipv6我禁用了，有没有关系

**Comment by luluijn** [comment]
原来我在user-config设置的端口是8080然后运行开机自启命令，再运行后台运行8080端口导致端口重叠，改回user-config端口8388就行了再运行多次开机自启命令就可以了。题外话@breakwa11,有没有命令重建ssr或者整个删除再重装？

**Comment by luluijn** [comment]
新问题联一段时间后2017-02-23 08:25:13 ERROR    tcprelay.py:932 [Errno 111] Connection refused
2017-02-23 08:25:13 ERROR    tcprelay.py:934 remote error, when connect to 183.2.186.153:53
2017-02-23 08:27:28 INFO     tcprelay.py:1215 port 8080 connections up to 25
2017-02-23 08:27:42 ERROR    tcprelay.py:932 [Errno 111] Connection refused
2017-02-23 08:27:42 ERROR    tcprelay.py:934 remote error, when connect to 125.39.46.36:53

**Comment by breakwa11** [comment]
如果不影响使用这个不需要管

**Comment by luluijn** [comment]
好的，谢谢。
