### ISSUE TITLE
Protocol spec?

### ISSUE THREAD

**Issue by riobard** [breakwa11/shadowsocks-rss#676]
@breakwa11 I'm working on refining the Shadowsocks [protocol spec](https://github.com/shadowsocks/shadowsocks-org/wiki) and it came to me that I still don't know anything about the changes shadowsocksR has made so far (sorry for being late to the game). I'm wondering if there is any documentation on the protocol that shadowsocksR speaks? Specifically, is there any detail on the protocol for user authentication in multiuser mode?

Really appreciate your excellent work here. Please ignore all the negativities towards you and keep pushing forward! 👍

**Comment by breakwa11** [comment]
写个中文吧，我这种英语渣表示不懂，万一理解错了就不太好了吧

**Comment by riobard** [comment]
简单来说就是有没有协议文档 😂

**Comment by breakwa11** [comment]
有，但不全，文档已经不是最新的，有啥想问的？

**Comment by riobard** [comment]
有计划整理更新一下么？刚整理完 shadowsocks 的协议

**Comment by breakwa11** [comment]
@riobard 因为目前参与者少，没有什么动力更新文档，有啥问我就好了，你可以在这问，或用twitter私信

**Comment by riobard** [comment]
竟然一时不知从何问起……那能不能简单描述一下 shadowsocksR 和 shadowsocks 在协议上的区别呢？

**Comment by breakwa11** [comment]
@riobard 相对原协议的话，增加了抗重放，数据包验证，客户端认证及数量限制，带padding，支持keepalive

**Comment by riobard** [comment]
不好意思我刚才表达得不是很清楚。我比较想了解的是在协议层面，也就是实际传输的字节流，有什么不同呢？您可以对照比如 https://github.com/shadowsocks/shadowsocks-org/wiki/Protocol 简单描述下在字节流上添加或者更改了什么呢？谢谢！😊

**Comment by riobard** [comment]
如果可以的，我想也写一份类似的文档描述 ssr 的协议细节

**Comment by breakwa11** [comment]
@riobard 在本repo的文件里有最新版协议的描述文档

**Comment by riobard** [comment]
多谢！我看到 https://github.com/breakwa11/shadowsocks-rss/blob/master/auth_aes128.md 有一部分，但似乎没找到多用户支持相关的一些协议细节，不知道能在什么地方看到？

**Comment by breakwa11** [comment]
@riobard 你要了解多用户部分干什么呢

**Comment by riobard** [comment]
想看看怎么实现的，学习一下 :)

**Comment by breakwa11** [comment]
@riobard 但是以你的实力应该早就想好实现方案了吧？

**Comment by riobard** [comment]
然而并没有 😂

**Comment by riobard** [comment]
这里 https://github.com/shadowsocks/shadowsocks-org/issues/54 给出了一个基础框架，但是之后如何做多用户认证还并没有考虑。想先学习一下现成的做法是怎样的，免得做无用功。

**Comment by breakwa11** [comment]
@riobard 我的做法你肯定看不上的，你知道了后肯定吐血，说：（居然敢做成这样子，和没加密不是没区别了吗）这样子

**Comment by riobard** [comment]
竟然如此没有自信？😂

**Comment by breakwa11** [comment]
@riobard 所以还是建议你自己考虑一个，我的方法不存在安全性，但仅仅过个防火墙还是没问题的

**Comment by riobard** [comment]
好吧，那我先看看源码能不能看明白，不懂再来问～

**Comment by breakwa11** [comment]
@breakwa11 简单的方式给你说明个，比如ss的OTA，有个MAC过程，这部分的key使用用户自己的密码而已

**Comment by riobard** [comment]
对了，ssr 的 reference 实现是 c# 版本吗？还是 python?

**Comment by breakwa11** [comment]
@riobard python/c#/c三种语言都有实现

**Comment by sunsan05** [comment]
有没有可能支持QUIC
