### ISSUE TITLE
windows端用NetTypeTester测试以及实际使用无法UDP转发

### ISSUE THREAD

**Issue by jetray** [breakwa11/shadowsocks-rss#679]
在使用过程中是正常的，也没有感觉到什么不对，主要是使用电脑代理PS4时发现UDP是直连的，没有代理效果，用NetTypeTester测试网络类型是Symmetric，公网IP未变为服务端IP，服务端用nmap 127.0.0.1只显示了ssh的22端口和SSR的443端口，netstat -aun倒是能看到有三个UDP端口其中一个就是443……也不知道是我测试错误还是配置错误

**Comment by breakwa11** [comment]
版本号呢，还有你怎么用电脑代理ps4的。客户端平时并不会开启udp端口，除非有udp请求
