### ISSUE TITLE
负载均衡策略可否添加“高带宽”？

### ISSUE THREAD

**Issue by Siyuanm** [breakwa11/shadowsocks-rss#68]
如题，客户端的服务器统计信息中有历史最高速度，因此可否考虑添加“高带宽”的负载均衡策略，优先使用目前可用服务器中带宽最高的，这应该对看YouTube很有帮助，因为当前GFW会对大流量直接reset。

翻墙数载，直到今年4月GoAgent实在太难用了，才了解的SS，借在github的第一个issue，感谢phuslu、xxnet、clowwindy和breakwa11妹子的努力，真的谢谢你们！

**Comment by wenliyang** [comment]
GFW会对大流量直接reset，高带宽就能解决这个问题？没明白

**Comment by breakwa11** [comment]
没有采用这个值来做策略是因为最高速度值并不靠谱

**Comment by ARwMq9b6** [comment]
爱你！
<img src="http://img3.ph.126.net/kk0yZpTuKr2NKZG6PXToCQ==/3213036859152743933.gif" />

**Comment by Siyuanm** [comment]
@wenliyang 我的思路是这样的，看YouTube肯定需要速度快，但GFW会对大流量reset（从我这个地区来看，reset的时机不一定），因此如果有按高带宽负载均衡，则不管GFW何时reset，下一个服务器都一定是速度最快的，最适合看YouTube的。而不是说这个负载均衡策略可以避免reset现象。

@breakwa11 感谢妹子回复，这倒也是，目前的最高速度只是瞬间速度，确实不靠谱。可否速度持续XX秒再记为最高速度呢？这样是否会靠谱一点？这只是我作为一个小白用户的一点思路，也许实现起来不方便或者这个负载均衡策略本身并不可靠，总之见笑啦 :wink:

**Comment by breakwa11** [comment]
如果不是大流量下载，最高速度肯定不会高，而平时刷个网页又根本测试不出来最大带宽，但不高的又不会去选，这些全矛盾了

**Comment by Siyuanm** [comment]
一个思路是，启用这个“高带宽”之前进行一次所有服务器的带宽测试（测试时间短一些，以免在这个环节就被reset）
但问题是如何选择带宽测试文件，以及实现的具体方式，似乎目前这种细枝末节的功能还提不到日程上，看Issues，SS协议上还有不少东西要解决，这个待以后再说吧 :laughing:

**Comment by OpenWeb321** [comment]
就弄上高带宽这个功能吧，很多用户需要，每次看个视频，卡出翔了，明明很多服务器都有几兆的下载速度，就是不会自动选择这些服务器。。。
