### ISSUE TITLE
建议启用动态端口

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#680]
就像ftp的pasv模式一样，先连接上一个协商端口，然后约定下一个数据传输端口，经过一定时间，或者完成一个传输后，换而 连接另一个端口，这样服务端端口范围可以开到放大，被拦截的可能性就小了。

酱妹感觉吼不吼哇

**Comment by yfdyh000** [comment]
https://github.com/breakwa11/shadowsocks-rss/issues/408
