### ISSUE TITLE
这两个地址是同一个项目吗?

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#681]
总在两个间跑来跑去，有点晕了

https://github.com/breakwa11/shadowsocks-rss
https://github.com/shadowsocksr

**Comment by JonasGao** [comment]
一个是组织地址。另一个是订阅项目地址。不是同一个

**Comment by JonasGao** [comment]
@breakwa11 我觉得这个可以关了。。。。
