### ISSUE TITLE
锐速下，原版的ss多用户（不走数据库）跟SSR（数据库版多用户）效果差异很大

### ISSUE THREAD

**Issue by j0hnnie** [breakwa11/shadowsocks-rss#686]
不知道为什么，原版的SS直接编辑文件多用户管理，用了锐速，看youtube的时候都能上到10000kb/s以上，但是SSR的数据库版 最多3000kb/s，是不是我有设置问题呀？

**Comment by j0hnnie** [comment]
用的是chacha20

**Comment by breakwa11** [comment]
同一个服务器吗？同一个端口吗？同一个协议吗？具体哪个语言哪个版本？你都没说

**Comment by breakwa11** [comment]
再有一个问题，你这种表现能重现吗？即间隔10分钟再测试结果是一样的
你确定不是因为先跑的SS因流量过大被临时限速后再跑的SSR吗？你的SSR上有配置限速参数吗？
更关键的问题是，SSR主要考虑的不是速度，如果你要考虑速度，那你用SS不就好了
一切的速度问题都是玄学，不属于程序问题范围

**Comment by Daniel-scx** [comment]
我还是比较支持原版SS
