### ISSUE TITLE
希望加入自动清理ssserver.log日志的功能

### ISSUE THREAD

**Issue by ouyangmland** [breakwa11/shadowsocks-rss#687]
今天去查看log日志的时候发现日志文件300+MB了，按这个速度继续加下午年底突破1G没啥问题！
文件增大都没啥事。主要是查看的时候记录的日志的太多了。查看起来比较麻烦！我觉得每次记录3周的日志就可以了，太久之前的也没多少人会去查看。能不能加入这种功能呢！运行一年就记录一年的日志是不是有这个必要。作者可以考虑下我的建议！

**Comment by chncwang** [comment]
设计上，管理日志不该是翻墙服务负责的事情吧

**Comment by Z4HD** [comment]
可以试试手动删除或者服务器定时删除/清空日志文件？

**Comment by 01186** [comment]
日志切割为什么要交给代理程序做...
想要弄的发自己logrotate...

**Comment by wangchunming** [comment]
你难道不会写个crontab规则让其自动删除log文件？
玩linux的有些很容易就可以实现的问题不会自己折腾？

**Comment by ouyangmland** [comment]
是啊，我不会写，这软件自己生成的日志，我还要给他善后，做的不完善，我只是建议，还要我去写定时。我去写这些东西，还来建议什么真逗！

2017-06-27 9:21 GMT+08:00 王春明 <notifications@github.com>:

**Comment by Z4HD** [comment]
@ouyangmland 自行开发分支，请
