### ISSUE TITLE
羊驼

### ISSUE THREAD

**Issue by catshitz** [breakwa11/shadowsocks-rss#688]
羊驼

**Comment by breakwa11** [comment]
就这么闪来闪去除了让自动隐匿图标失效，也让自定义图标没有意义，加这个有什么重要意义？

**Comment by JonasGao** [comment]
这个小功能 SS-Windows 那边倒是有..... 显然不是重要功能，对于强迫症和控制欲比较强的人比较好使

**Comment by JonasGao** [comment]
这素质也是醉了.....

**Comment by breakwa11** [comment]
@JonasGao 而且这是第二个issue，他在我这问了两个issue，两个都在close后改内容改标题

**Comment by JonasGao** [comment]
默默为天朝未来祈祷.......

**Comment by GoodspeedWong** [comment]
@破鞋醬 妳辛苦了
