### ISSUE TITLE
surge不能使用SSR客户端的socks5代理

### ISSUE THREAD

**Issue by yshtcn** [breakwa11/shadowsocks-rss#690]
SSR客户端是最新的4.1.3.1，这个版本修复了[socks5不需要密码的bug](https://github.com/shadowsocksr/shadowsocksr-csharp/issues/100)之后，我就无法使用surge的socks5代理访问局域网的客户端了。

我去信Surge作者询问，作者建议我查看一下SSR客户端的日志，我查看了一下就一句重复的内容：
Socks5 Auth failed

而我使用Proxifier代理测试工具使用socks5带密码测试则能测试通过。

**Comment by breakwa11** [comment]
那你的客户端配置了用户名密码了？

**Comment by yshtcn** [comment]
对，我SSR配置了用户名和密码，并打开了接受局域网的连接。
然后在surge里也配置了用户名和密码。当surge里设置为HTTP的时候，就可以测试通过。
使用socks5的时候，就会这样。

**Comment by breakwa11** [comment]
那说明surge发送的请求是 05 01 00 ，这是错的
应该是 05 01 02 或 05 02 00 02

**Comment by yshtcn** [comment]
问题已解决，surge作者表示：

> 问题已确认，新的 Surge Mac Beta 版本已经修正了该问题，iOS 版本将在下个 TF 版修正。
