### ISSUE TITLE
无法访问Google域名

### ISSUE THREAD

**Issue by lwp2070809** [breakwa11/shadowsocks-rss#694]
具体表现为: 其他所有被墙网站访问均正常, IP也正常 (ip138显示为服务器地址), 但是经常性无法访问google.com以及google的大部分域名, android客户端显示SSL握手超时，必须在服务端重启数次SSR服务才能正常访问.
混淆插件为tls1.2_ticket_auth 无参数, 协议插件为auth_aes128_md5 无参数, 加密协议chacha20. 服务端部署在centos7上,客户端为windows和android, 均为最新版. (注: 原协议, 不混淆, aes-256-cfb也会出现这种情况).
是VPS本身的问题还是其他BUG呢....求教.

**Comment by breakwa11** [comment]
@lwp2070809 你调整一下DNS呢

**Comment by lwp2070809** [comment]
@breakwa11 路由器修改DNS 223.5.5.5为8.8.8.8之后依旧无法访问https://www.google.com, 显示响应时间过长, 但是youtube.com和诸如design.google.com又是正常访问的, 实在是费解. 安卓SSR客户端依旧报SSL握手超时错误。

**Comment by breakwa11** [comment]
@lwp2070809 我说的是你的VPS的DNS

**Comment by lwp2070809** [comment]
VPS的DNS从建立起一直没有变过
cat /etc/resolv.conf 
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
我重新建立了一个服务器，使用新的IP，发现新服务器可以正确访问google，旧服务器无论怎么更改协议和混淆之类的都没有效果，只能认为我这边的网络封锁十分严重了....

**Comment by breakwa11** [comment]
可能是google屏蔽了你旧服务器的IP
