### ISSUE TITLE
使用SSR版本下载文件下载过程中断

### ISSUE THREAD

**Issue by okyaa** [breakwa11/shadowsocks-rss#695]
服务端已更新到最新版本（至今日，重新用git pull同步），客户端更新到ShadowsocksR-4.1.4-win，使用Chrome + SwitchyOmega下载文件出现断流现象，例如下载http://opengapps.org/网站的GAPPS文件。
加密方式尝试chacha20和aes-256-cfb均存在同类问题，协议使用auth_sha1_v4，混淆使用http_simple、tls1.2_ticket_auth，使用兼容和不使用兼容模式均有此问题，更改协议使用origin，混淆使用plain也不行，客户端更改为原版的也存在此问题，下载文件不全，服务器使用的是搬瓦工的服务器，服务端改用shadowsocks-libev下载文件正常。
但是现在存在的问题是如果使用原版的不带协议和混淆的shadowsocks，运营商会很快封锁掉我的电脑客户端IP，导致不能上网。如果需要其他LOG，我会后续提供。

**Comment by nehcnoel** [comment]
个人感觉应该是你SSR服务器的问题，你例如里的文件我已经下载好，截图供你参考。PS：文件有点大，约651MB，无奈网络太慢，不然可以帮你传到网盘上
以下是我的一些个人看法，供
![tim 20170313163311](https://cloud.githubusercontent.com/assets/23116473/23847279/a6f06434-080c-11e7-9304-5ea8649d5f85.png)
![tim 20170313164207](https://cloud.githubusercontent.com/assets/23116473/23847280/a6f1e1c4-080c-11e7-84e1-97c3a695daad.png)
![tim 20170313164239](https://cloud.githubusercontent.com/assets/23116473/23847281/a6f61a50-080c-11e7-859e-dd15202aad8c.png)


参考。
其实用SSR之后就无需再用switchyomega插件，因为SSR自带的pac够用且支持系统级代理，推荐一个我目前用的还不错的代理配置：PAC模式（系统代理模式）+更新PAC为绕过大陆常见域名列表（PAC）+全局（代理规则）。

**Comment by breakwa11** [comment]
我用v4下载了一下，文件是完整的，对比了MD5也是完全一致，建议使用下载器下载以解决断点续传的问题

**Comment by okyaa** [comment]
我再试一下吧！谢谢各位大神！或者可以试一下我的服务器。
ssr://MTA0LjEyOC44My4xNzY6MTAyNzphdXRoX3NoYTFfdjQ6YWVzLTI1Ni1jZmI6aHR0cF9zaW1wbGU6Y1hkbGNuUXhNak0wTlEvP29iZnNwYXJhbT0mcmVtYXJrcz1RbGRIJmdyb3VwPVUxTlM

**Comment by okyaa** [comment]
@nehcnoel 使用你的配置使用IE下载成功。

**Comment by nehcnoel** [comment]
该配置理论上适应于任何浏览器，当然也就不需要chrome的其他代理插件了
