### ISSUE TITLE
Start SSr manyuser without DB/Panel

### ISSUE THREAD

**Issue by itskeKs** [breakwa11/shadowsocks-rss#696]
hey guys,

i dont speak Chinese, so sorryfor that :) i am just using gtranslate to understand how to setup SSr. I am running into an issue when i try to start SSr without any database. Since ss-panel is in chinese and everything else too, i just want to use SSr without any panel/login and so on. Is there any way how i can run SSr without any kind of Database?!

Also is there anykind of documentation (even in chinese) for both of the limitation settings within cobfig.json?

Thanks in advance,

Chris

**Comment by breakwa11** [comment]
@itskeKs use mudbjson mode

**Comment by itskeKs** [comment]
@breakwa11 ty for fast reply. Any help on limitations within config.json?

**Comment by breakwa11** [comment]
use mudbjson mode or run with user-config.json
if your plan is running server for you only, you can edit user-config.json then run the server. Not recommended to modify config.json

**Comment by itskeKs** [comment]
figured it out. thanks a lot :)
