### ISSUE TITLE
关于**使用域名白名单（仅http代理）**相关问题

### ISSUE THREAD

**Issue by nehcnoel** [breakwa11/shadowsocks-rss#697]
你好，破娃酱
在使用**白名单模式**期间，大部分时候IP能自动识别并智能使用翻墙软件，但总有几个网站（比如taobao.com  jd.com）无法正确识别IP，请问该如何将这些网站添加到白名单中？
期待你的回复，感激不尽。
代理配置如下：
系统代理模式：全局模式
代理规则：全局
服务器：使用域名白名单（进http代理）+ssr服务器信息
![tim 20170314162323](https://cloud.githubusercontent.com/assets/23116473/23892044/015f4436-08d4-11e7-948b-4892b0eb0c28.png)
![tim 20170314163147](https://cloud.githubusercontent.com/assets/23116473/23892043/015e3244-08d4-11e7-9b8a-473d426f72e8.png)
![tim 20170314163316](https://cloud.githubusercontent.com/assets/23116473/23892045/018f7c00-08d4-11e7-99e1-fca204febb20.png)

**Comment by breakwa11** [comment]
你可以自行编辑域名白名单文件 bypass.action

**Comment by arukasgirl** [comment]
@breakwa11 可以在协议文档里加上ssr支持的加密方式么

**Comment by nehcnoel** [comment]
@breakwa11 请问编辑后如何生效呢？
目前我的操作过程是退出软件，编辑bypass（在最后加入_.taobao.com_&_.jd.com_），登录软件，取消白名单模式，勾选白名单模式，清理浏览器缓存，登录tb（或者jd），还是提示海外版。

**Comment by nehcnoel** [comment]
@breakwa11 请问编辑后如何生效呢？
目前我的操作过程是退出软件，编辑bypass（在最后加入  .taobao.com  或者  .jd.com），登录软件，取消白名单模式，勾选白名单模式，清理浏览器缓存，登录tb（或者jd），还是提示海外版。

**Comment by breakwa11** [comment]
@nehcnoel 这个需要你使用http代理（而不是socks5代理）才生效，应用场景很小，所以建议用代理规则，不过现在代理规则还不支持自定义

**Comment by nehcnoel** [comment]
@breakwa11 好的，多谢。

**Comment by nehcnoel** [comment]
@breakwa11 不好意思，还有个问题，请问代理规则中的IP是基于什么内容进行判断的？

**Comment by breakwa11** [comment]
@nehcnoel dns结果

**Comment by nehcnoel** [comment]
@breakwa11 是基于我lan里设置的DNS吗，如果是，有没有建议的DNS地址呢？

**Comment by breakwa11** [comment]
114或1.2.4.8吧
