### ISSUE TITLE
服务器端如何弄混淆TCP协议头？

### ISSUE THREAD

**Issue by LisonFan** [breakwa11/shadowsocks-rss#7]

**Comment by cfcboy** [comment]
获取源代码

单用户版（个人用户使用这个）
git clone –b master https://github.com/breakwa11/shadowsocks.git

多用户版（个人用户或ss站长使用这个）
git clone –b manyuser https://github.com/breakwa11/shadowsocks.git

用官方源就可以了。

安装教程：https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup
