### ISSUE TITLE
希望能像adbyby那样拦截ip 元素之类的

### ISSUE THREAD

**Issue by gyx99** [breakwa11/shadowsocks-rss#701]
希望能通过配置服务端过滤指定域名和元素

**Comment by Love4Taylor** [comment]
服务端必须以非root用户启动
`iptables -t nat -m owner --uid-owner SS用户 -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-port 过滤软件端口`

**Comment by breakwa11** [comment]
no plan for this
