### ISSUE TITLE
使用google cloud platform建了ssr，流量异常问题

### ISSUE THREAD

**Issue by stawhen** [breakwa11/shadowsocks-rss#705]
近期google那边搞活动，体验一年，所以去申请了一下，在centos上建了个ssr，速度相当快。
用的是chacha20，auth_sha1_v4，http_simple。
结果那天晚上在没有使用的情况下，google后台显示跑了9个G的流量。
查了下谷歌后台，cpu一直有脉冲状的使用，
![screenshot_20170321-110219](https://cloud.githubusercontent.com/assets/26564039/24134923/488c9114-0dd5-11e7-899d-6453f61bc4e2.png)
请问这个情况和我选用的加密和混淆方式关系大吗？
另外，问下有没有同样使用google的？
感谢！

**Comment by bugparty** [comment]
不可能没人用

**Comment by stawhen** [comment]
我查了后台的流量数据，图里显示确实没有。。。
![screenshot_20170321-110549](https://cloud.githubusercontent.com/assets/26564039/24137679/e0435a1c-0de2-11e7-86fd-bdc546e74105.png)
 所以非常不解，而且cpu一直有脉冲的占用。
 @bugparty

**Comment by aglent** [comment]
不使用时 CPU大约2-5%之间波动
流量偷跑就不清楚了没遇到过

**Comment by stawhen** [comment]
@aglent 你也是google的VPS？流量使用正常么？

**Comment by aglent** [comment]
@stawhen 是的 平时用的不多 目前没发现问题
看图里 20日后半夜到21日上半夜有网络活动
或者再观察几日

**Comment by evenardo** [comment]
@stawhen 我也用了，没发现问题。

**Comment by kagurainroy** [comment]
可以问一下是用哪种信用卡申请gcp的么？

**Comment by sinderyminami** [comment]
流量异常可能是google标记了你的账户

**Comment by JimTang67** [comment]
刚来的小白，买了个bandwagon的账号又买了个潘多拉路由器，配置完后经常掉线，怎么解决呀？求各位大佬给点建议！

**Comment by zhaoxitao** [comment]
Google Cloud 在哪里查看已使用的流量啊? 我居然没找到。。。
