### ISSUE TITLE
撩一下小姐姐，呵呵呵呵哈哈哈哈哈哼哼哼哼哼

### ISSUE THREAD

**Issue by aliluys** [breakwa11/shadowsocks-rss#708]
之所以写中文，本issue是写给打算写给乱发中文问题的人看的

1. 不欢迎小白，不回答诸如软件如何使用，如何搭建，如何配置，使用速度不快，如何提速等等和软件问题无关的问题，或把开发者当成客服的问题
2. 这里用于反馈软件可能的Bug，软件潜在的问题，和软件功能需求及讨论
3. 同一个issue不得在不同repo重复发，除非你发现发错地方（这种情况下你自行删除错误的issue），否则直接关闭且不回答问题，严重者拉黑名单
4. 建议你把问题事先在其它社区或和其它使用者讨论过，以确认不是密码错误，协议或插件错误，或服务器防火墙没关诸如此类本来应该自己解决的问题
5. 在你确认你需要发问题时，请尽可能提供详细的信息，包括服务端客户端具体版本，及相应log，及相应配置。如信息明显过少，则不一定会理你

确认你读完以上内容后，请删除以上所有内容，然后写下你的问题

Please remove all above then write down your issue

**Comment by breakwa11** [comment]
如果发无意义内容，那么会拉黑名单

**Comment by bugparty** [comment]
最近怎么都是小学生

**Comment by Nehalem-Lf** [comment]
右上角watch有660个人，你发这个有660个人收到email，死了亲妈吧？

**Comment by JonasGao** [comment]
@Nehalem-Lf 别骂人，不太好。
@breakwa11 这种一看就完全不是开发人员，纯属闲着没事干的。我觉得不用后续判断，可以直接拉黑......

**Comment by bugparty** [comment]
为啥不去twitter撩。。。。
感觉issue还是有个审核比较好

**Comment by aliluys** [comment]
首先，很抱歉给你们带来了困扰，我确实不是一个开发人员，我甚至都不是计算机专业的学生，我对编程才刚入门，有点兴趣。但是我不明白有的人会说出像屎一样的话，如果你觉得我浪费你的时间，那你ignore就好了啊，你有这骂人的功夫不如去敲几行代码，或者说你其实根本就没什么破事可干。发这个我仅仅是开个玩笑，不知道能得罪这么多大神，呵呵
