### ISSUE TITLE
有谁了解或实现过 SS + LDAP 的方案么？

### ISSUE THREAD

**Issue by AlvisZhang** [breakwa11/shadowsocks-rss#710]
感觉有妹子的地方应该人气就大

问下有没有谁了解或实现过？ 或者 radius + ss 方案也成啊。

ss 包括 SS & SSR 。

**Comment by breakwa11** [comment]
@AlvisZhang LDAP是什么鬼？

**Comment by AlvisZhang** [comment]
是个老鬼 [http://baike.baidu.com/item/LDAP](url)

简单说就是已目录形式组织数据结构的一种方法，常用于企业的统一认证方案中作为数据源。

就比如说 shadowsocksr-mu 的 mudbjson模式 中的 user 和 pass ，实际是从 ldap 中实时遍历来的。

使用场景举个例，我给来公司上班的小朋友们提供了 SS 服务，但不想离职的人还能免费使，可也不想定期更改密码。就可已通过 ldap 维护有效的用户列表，ss-servers 可以定时通过 filter 从 ldap 中获取有效的用户信息，组成可用加密字符串。

跟 mysql 的 mu API 类似，数据源不一样，但不是给站长用，是给企业内运维用，现在如过想这样用，就是做个脚本把 LDAP 里的用户信息和 MU 的 mysql 做转换同步。

懒得写脚本，想做伸手党，所以问问有没有勤快的做过，最好是直接访问 LDAP 的

**Comment by breakwa11** [comment]
@AlvisZhang 那直接用SSR呀

**Comment by AlvisZhang** [comment]
@breakwa11 直接用SSR不是还得人工维护 mudbjson 或者通过 Panel 维护用户信息么，我这不是懒么。

**Comment by breakwa11** [comment]
如此少见的需求没有计划，我也没有环境

**Comment by chncwang** [comment]
这个方案的构想很有道理

**Comment by evenardo** [comment]
@AlvisZhang  自己不写~
