### ISSUE TITLE
server用命令行运行时，那个参数是指定obfs_param的？

### ISSUE THREAD

**Issue by burndown** [breakwa11/shadowsocks-rss#711]
wiki没看到，dockerfile里也没找到，如果想在docker里运行的ssr也指定obfs_param的时候用什么参数呢？

python ~/shadowsocksr/server.py -p $SERVER_PORT -k $PASSWORD -m $METHOD -O $PROTOCOL -o $OBFS

**Comment by breakwa11** [comment]
@burndown -g 混淆参数， -G 协议参数

**Comment by burndown** [comment]
多谢！
