### ISSUE TITLE
关于SSR的防火墙规则

### ISSUE THREAD

**Issue by CyshallChan** [breakwa11/shadowsocks-rss#712]
VPS用的centos7.2，防火墙用的iptables，SSR的监听端口是8388，规则如下：

# sample configuration for iptables service
# you can edit this manually or use system-config-firewall
# please do not ask us to add additional ports/services to this default configuration
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 8388 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT
COMMIT

规则已经允许了8388端口了但是还是无法代理，只能关闭防火墙才代理正常。
请教下破娃酱是我规则写错了还是啥？

**Comment by CyshallChan** [comment]
@breakwa11

**Comment by breakwa11** [comment]
`-A INPUT -p tcp --dport 80 -j ACCEPT`
你改这样试试？这和SSR根本没有关系

**Comment by haliy369** [comment]
firewall-cmd --zone=public --add-port=8388/tcp --permanent
firewall-cmd --reload

我以前也遇到过，Google说是CentOS 7 的系统已经将默认的防火墙修改了。

**Comment by evenardo** [comment]
@CyshallChan
解决了么

**Comment by evenardo** [comment]
@CyshallChan 你开了udp端口没有, iptables 里面没有开放udp端口, 默认INPUT开放, 但是你加了accept , 好像默认其他就关了.

**Comment by CyshallChan** [comment]
@evenardo 已经解决了，我把我另外一台VPS防火墙规则复制了一份，但规则之前我也比对过一样的，很奇怪。

**Comment by TainKung** [comment]
@CyshallChan 
**问题在于规则顺序**
iptables 是*规则链*，数据包只有上一条规则处理才会进入下一条规则。
这行`-A INPUT -j REJECT --reject-with icmp-host-prohibited`把所有的包都 reject 了，所以在这条规则后 append 的规则其实都没有效果了。

**Comment by CyshallChan** [comment]
@TainKung 好的，了解了，感谢！
