### ISSUE TITLE
关于协议和参数的问题

### ISSUE THREAD

**Issue by yunyu2017** [breakwa11/shadowsocks-rss#714]
请教一下SSR的协议类型、协议参数以及混淆类型、混淆参数怎样设置？如何选择以及设置符合自己需求的参数？小白问题，还请姐姐指点一下，或者给个搜索方向，搜索SSR 协议 参数 ，大多都是仅关于免流方面的设置😂都不讲理😂

**Comment by yfdyh000** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/obfs
