### ISSUE TITLE
这个问题我只想说,妹子很强大,是否可以整合KCP那样就比较好了

### ISSUE THREAD

**Issue by Zachary-Zaki** [breakwa11/shadowsocks-rss#717]
...最后妹子可以撩么?  >>_<< !~~~

**Comment by breakwa11** [comment]
@Zachary-Zaki 不会整合KCP

**Comment by waeart** [comment]
为什么要整合KCP，想用KCP可以自己安装。

**Comment by Zachary-Zaki** [comment]
@breakwa11 整合KCP可以在程序里面执行KCP的exe就行了,给一个配置端口就行了,开发量并不大,整合到一起到时候使用起来也比较方便,不用开两个窗口 一个dos 一个ssr  - - !!! 一个窗口就OK了,当然不是每个人像breakwa11一样强大,最后妹子可以撩么 >>_<<~~ 这是一个很严肃的问题,咳咳...很严肃的,如果能出一个java版本的ssr学习下就好了,我不会C#呜呜...不然我自己就加上这个功能了....

**Comment by Zachary-Zaki** [comment]
@breakwa11 我可以教你的...这个我会... 在C#里面执行CMD命令 
第一. 把KCP.exe程序放在你的程序目录下
第二 获取当前KCP的路径
第三 执行CMD命令%路径%KCP.exe -r "KCP_SERVER_IP:4000" -l ":8388" -mode fast2 
第四 提示保存成功   - - !! OK 了这个功能就开发完成了

**Comment by asmadeus08** [comment]
TCP BBR is much faster.

**Comment by Nehalem-Lf** [comment]
说真的，kcp挺难用的，ISP的udp限制很厉害，所以我都用回锐速了
