### ISSUE TITLE
RC4跟chacha20哪个省电一些？

### ISSUE THREAD

**Issue by Just2co** [breakwa11/shadowsocks-rss#726]
经测试，在路由器里面使用SSR客户端，开启RC4加密，网速要快一些，尽管chacha20专门针对ARM精简指令集CPU做了优化，但也真是针对aes加密来优化的，跟RC4流加密比起来，仍然慢！现在的问题是，RC4跟chacha20加解密比起来，哪个更省电一些？我不需要考虑安全性，因为我的很多网络服务都是基于https的，并且经过境外VPS中转传输。

**Comment by breakwa11** [comment]
没有必要，用rc4-md5足够了

**Comment by Just2co** [comment]
@breakwa11 我也是这样认为的，之前看过别人的测试数据，加解密20MB数据话费CPU运算时间测试，rc4要0.15秒，chacha20要0.45秒，rc4-md5要0.169秒，CPU运算时间越短，应该越省电。所以rc4及其衍生加密算法是最省电的。顺便搭顺风车问一下，rc4-md5-6是啥东东？为什么搜索引擎搜索不到任何信息？是不是@breakwa11你的新发明啊？

**Comment by breakwa11** [comment]
rc4-md5-6和rc4-md5的唯一区别，是rc4-md5-6使用6字节的IV，rc4-md5使用16字节的IV，即rc4-md5-6缩短了IV的长度
