### ISSUE TITLE
梅林游戏模式是这样提示？

### ISSUE THREAD

**Issue by lingaoyi** [breakwa11/shadowsocks-rss#727]
Apr  3 16:12:31 rss-redir[8876]: [udp] remote_recv_recvfrom fragmentation
Apr  3 16:12:32 rss-redir[8876]: [udp] remote_recv_recvfrom fragmentation
Apr  3 16:12:33 rss-redir[8876]: [udp] remote_recv_recvfrom fragmentation
Apr  3 16:12:36 rss-redir[8876]: [udp] remote_recv_recvfrom fragmentation
Apr  3 16:12:43 rss-redir[8876]: [udp] remote_recv_recvfrom fragmentation

X1游戏模式地平线3和派对无法语音，后台提示这个。

**Comment by breakwa11** [comment]
新版本应该好了，等更新吧
