### ISSUE TITLE
如果不需要新协议，是否需要更新客户端？

### ISSUE THREAD

**Issue by daoxunchen** [breakwa11/shadowsocks-rss#73]
你好，首先非常感谢你做的这个客户端，用着非常好。
我用的是收费的ss，服务端肯定就没有你的新功能。。。
希望能在更新日志中写明是否有对原有功能的bugfix，这样就可以确定每次更新时，我的客户端是否需要及时跟进，谢谢了
中秋快乐！！！

**Comment by falseen** [comment]
不需要。3.5是测试版本，不会主动推送。另外，新版服务端可以兼容旧版客户端。

**Comment by breakwa11** [comment]
收费的不一定没有，可以问问
3.5.0现在推送了

**Comment by simonsmh** [comment]
其实ss其他分支版本都在更新，比如ss-windows和ss-libev。
ssr is another choice :)

**Comment by falseen** [comment]
但都是各搞各的。。。

**Comment by falseen** [comment]
但都是各搞各的。。。

**Comment by jang-u** [comment]
各搞各的好，不会被一网打尽

**Comment by falseen** [comment]
@jang-u ss的优势是协议简单，各平台都支持。如果各搞各的话，那各个平台之间就会不兼容。最关键的是，ss的生态圈会被破坏，之前积累的优势也将不复存在。想想ss用了多长时间才建立起了这么完善的生态圈吧，想再建立一个难度不是一般的高。
