### ISSUE TITLE
更新之后使用finalspeed kcptun 无法连接

### ISSUE THREAD

**Issue by sugarleon** [breakwa11/shadowsocks-rss#732]
下午git pull更新服务端后，没办法连接。版本3.1.2

之后发现协议是auth_aes128_md5 auth_aes128_sha1的时候用kcptun finalspeed无法连接。其他的协议都可以。

日志什么都没有。

以后是没办法用这两个协议配合finalspeed或者kcptun使用了吗？

    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 443,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "x",
    "method": "chacha20",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {}, // only works under multi-user mode
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": true

**Comment by breakwa11** [comment]
更新一下服务端
