### ISSUE TITLE
请问如何限制每个端口的连接数！

### ISSUE THREAD

**Issue by Taering365** [breakwa11/shadowsocks-rss#737]
SSR如何限制每个端口的IP连接数量，貌似现在暂时只能通过其他补丁!

**Comment by breakwa11** [comment]
SSR不建议限制IP数量，支持限制客户端数量

**Comment by Taering365** [comment]
请问我要限制一个端口的客户端连接数量，应该怎么做呢？

**Comment by june5910aaaa** [comment]
多看看readme和wiki 作者不是客服 非技术问题 不建议开issue讨论

**Comment by breakwa11** [comment]
用auth_aes128_*协议然后看文档中的参数解释

**Comment by Taering365** [comment]
好的，明白
