### ISSUE TITLE
centos5.6 执行bash initcfg.sh报错invalid option -n

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#738]
centos5.6 32位系统，执行下面命令时报错：

bash initcfg.sh cp: invalid option -- n

用cp --help确实没有-n参数，能否单独的更新系统的某个组件，让系统支持cp -n参数?

怎解?

**Comment by breakwa11** [comment]
你的系统实在是太老了，我从来没管过centos5，我只弄过6和7

**Comment by breakwa11** [comment]
你自己去掉-n直接执行就好了，不过其它的话我就不知道会怎么样了
