### ISSUE TITLE
ssr Linux 客户端 python版感觉特别慢

### ISSUE THREAD

**Issue by hkurj** [breakwa11/shadowsocks-rss#742]
用c#的win版  感觉不错,但是在Linux下用python的突然会断线,而且看youtobe的速度也慢了点
而且好像好久更新了

**Comment by breakwa11** [comment]
`而且好像好久更新了` 是什么意思

**Comment by hkurj** [comment]
就是local.py  好久没更新了 不知道卡是不是这个原因

2017-05-05 14:54 GMT+08:00 破娃酱 <notifications@github.com>:

**Comment by breakwa11** [comment]
@hkurj debian目录还三年没动呢，是不是可以说停更了？

**Comment by hkurj** [comment]
就是询问一下  那应该是我这网络的原因了

2017-05-06 8:19 GMT+08:00 破娃酱 <notifications@github.com>:
