### ISSUE TITLE
ssR多用配置问题

### ISSUE THREAD

**Issue by greedisgod** [breakwa11/shadowsocks-rss#743]
{
    "server":"0.0.0.0",
    "server_ipv6": "[::]",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "80":"password1",
        "443":"password2"
    },
    "timeout":300,
    "method":"aes-256-cfb",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "redirect": "",
    "dns_ipv6": false,
    "fast_open": false,
    "workers": 1
}
多用户配置如上，单用户配置在下，，对应单用户配置修改，客户端不能连接。不明白问题原因。
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8989,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "948130850H",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "chacha20",
    "protocol": "auth_sha1_v4_compatible",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": "",
    "fast_open": false,
    "workers": 1

}
谢谢

**Comment by imtyz001** [comment]
再确认一下客户端和服务器端的对应端口、密码、加密方式、协议和obfs看看？这几个有一个不对都会连接不上的

**Comment by greedisgod** [comment]
好感动，，谢谢您，我自己处理好了。

来自liuyuntong@outlook.com

发件人: imtyz001
发送时间: 2017年5月4日 18:28
收件人: breakwa11/shadowsocks-rss
抄送: greedisgod; Author
主题: Re: [breakwa11/shadowsocks-rss] ssR多用配置问题 (#743)

再确认一下客户端和服务器端的对应端口、密码、加密方式、协议和obfs看看？这几个有一个不对都会连接不上的
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Avast 防毒软件已对此电子邮件执行病毒检查。
https://www.avast.com/antivirus
