### ISSUE TITLE
4.1.5版“端口设置”失效？

### ISSUE THREAD

**Issue by Franinc** [breakwa11/shadowsocks-rss#745]
4.1.5 .net4.0版，未勾选“优先相同节点连接同一地址”
默认本地端口1080，使用节点A
“端口设置”中添加本地端口1081，使用节点B；添加本地端口1082，使用节点C。均为强制代理。
浏览器为chrome加SwitchyOmega扩展，扩展中添加三个代理服务器分别为使用本地1080，1081和1082端口
使用1080端口时，ip和ssr的“服务器连接统计”走的流量均为节点A。
而扩展切换到1081或1082时，ip和ssr的“服务器连接统计”走的流量仍然为A。
重启SSR后回到只走A的情况。
在“服务器连接统计”中关闭A后，BC能正常切换，开启A后回到只走A。
试过切换强制代理和规则代理，无效。
曾等待一段时间（只成功过一次）后，扩展在三个端口间随意切换可以正常使用ABC，“服务器连接统计”也是正常在ABC间切换。
试过4.0.6版倒是立即生效，但选择B时“服务器连接统计”中ABC均会产生连接。

**Comment by breakwa11** [comment]
未重现，能否更详细说明一下状况，来个图最好
这个功能我自己也一直在使用，如果有问题我肯定发现了，所以肯定是哪里做的和你的不一样

**Comment by Franinc** [comment]
检查了一下配置，发现问题出在"randomAlgorithm"上，默认为0，而出问题的配置为5，改为0后问题解决。

**Comment by breakwa11** [comment]
@Franinc 那应该只要不为5应该都对

**Comment by breakwa11** [comment]
@Franinc 确实是5的问题，修好了，下个版本就行了

**Comment by Franinc** [comment]
感谢w

**Comment by vonsis** [comment]
这个端口设置的面板逻辑可能有问题，我在这折腾了1小时才明白需要先点添加，然后在右边配置，确定。

而我总是先配置，然后添加，确定：bang！端口已被占用！   黑人问号盘旋1小时

**Comment by breakwa11** [comment]
@vonsis 编辑节点你不是先添加再编辑的吗
