### ISSUE TITLE
关于windows客户端，使用proxifier全局代理问题

### ISSUE THREAD

**Issue by rHyAc** [breakwa11/shadowsocks-rss#746]
试了下用proxifier，发现不能像ss那样的设置进行全局代理，各位大佬有什么办法

**Comment by evenardo** [comment]
Windows下要开local监听，而且是http协议，不是socks 。

rHy_Ac <notifications@github.com>于2017年4月28日周五 00:14写道：

**Comment by rHyAc** [comment]
如果打开local监听

**Comment by rHyAc** [comment]
@evenador 如何打开local监听？

**Comment by evenardo** [comment]
有个能设置本地局域网监听的菜单，还能设置DNS，设置负载均衡的方法什么的，那个菜单能设置。设置的是http代理。

rHy_Ac <notifications@github.com>于2017年4月28日周五 14:46写道：

**Comment by rHyAc** [comment]
@evenordo 你说的二级(前置)代理？如果是，哪里的服务器ip填127.0.0.1？服务器端口填1080？

**Comment by breakwa11** [comment]
@rHyAc 你不用理他，他其实完全不知道你问什么
至于你的问题，你设置一下客户端是直连，其它的代理到客户端不就好了？不是很容易的么

**Comment by evenardo** [comment]
嗯，说错了，在领导的批评指示下，专门打开Windowspc 操作了一下，跟我说的那个无关，我Windows
ssr客户端没变化，装上proxifer就能用，什么都没设置。话说这东西我用了两三个星期了，你从官网下载试试。  www.procifier.com

破娃酱 <notifications@github.com>于2017年4月28日周五 22:55写道：

**Comment by rHyAc** [comment]
@evenardo @breakwa11 已解决问题，导致问题的原因与proxifier和ssr无关，谢谢帮忙
