### ISSUE TITLE
3.5.1 manyuser 分支下运行遇到问题。

### ISSUE THREAD

**Issue by afdnlw** [breakwa11/shadowsocks-rss#75]
![qq 20150928100804](https://cloud.githubusercontent.com/assets/1336195/10126670/4743f9d8-65c9-11e5-9823-c8362dbc54a9.jpg)，这个是什么原因啊？

**Comment by falseen** [comment]
数据库没配置，你是要运行多用户还是单用户？
多用户的话配置下数据库。
单用户的话进入子目录运行。
具体见wiki。

**Comment by afdnlw** [comment]
thanks，刚看到  注:多用户版需配合 ss-panel 等前端使用。先研究下试试看，，
