### ISSUE TITLE
manyuser(mudbjson)中的使用流量是否会每月清零？

### ISSUE THREAD

**Issue by zhongfly** [breakwa11/shadowsocks-rss#752]
在manyuser（mudbjson）中，每个用户用transfer参数设置了流量限制，那么用户的使用流量会每月自动清零吗？
这个流量限制是指上传加下载流量的总和吗？

**Comment by breakwa11** [comment]
@zhongfly 程序里没有“自动”这两个字

**Comment by zhongfly** [comment]
所以它限制的是从用户创建后的总流量，只能手动清零，对吗？

**Comment by breakwa11** [comment]
是，要定时做什么请自己写脚本
