### ISSUE TITLE
安卓SSR3.3.71协议没有auth_china_a这个选项?

### ISSUE THREAD

**Issue by thisisjin** [breakwa11/shadowsocks-rss#755]
PC端的有这个协议。但是安卓端的没有。
所使用的服务提供商要求用此协议。。
看到客户端没有有点头疼，有什么解决办法么

**Comment by breakwa11** [comment]
@thisisjin 那就没办法了，这还在实验阶段，不知道你那为什么这么快上线这个。。。

**Comment by thisisjin** [comment]
@breakwa11   0A0,好悲伤。我IOS的小火箭跟安卓的SSR都没这个选项，好悲伤。我去找服务提供商，要他改改协议好了

**Comment by Comah** [comment]
还真快 先等娃再压力测试一段时间才会正式上各平台

**Comment by lw960105** [comment]
安卓ssr看不到密码怎么办
