### ISSUE TITLE
部署json版ssr时语句错误

### ISSUE THREAD

**Issue by wyxls** [breakwa11/shadowsocks-rss#756]
在运行./logrun.sh后用tail.sh翻看日志发现的

File "/root/shadowsocksr/server_pool.py", line 49, in __init__
    self.dns_resolver = asyncdns.DNSResolver()
  File "/root/shadowsocksr/shadowsocks/asyncdns.py", line 280, in __init__
    self._parse_hosts()
  File "/root/shadowsocksr/shadowsocks/asyncdns.py", line 334, in _parse_hosts
    if "#" in line:
TypeError: 'str' does not support the buffer interface

**Comment by breakwa11** [comment]
@wyxls 更新再试试

**Comment by wyxls** [comment]
@breakwa11 
重新clone了一遍重新部署，还是一样

**Comment by breakwa11** [comment]
为什么clone而不是pull

**Comment by wyxls** [comment]
之前git pull发现改动很多出error了，索性重新部署一遍，这个有影响吗？

**Comment by breakwa11** [comment]
那你clone不可能再出现相同的东西

**Comment by wyxls** [comment]
所以我也很奇怪，都rm清空了

**Comment by breakwa11** [comment]
你回答没有信息量的内容的话我帮不了你的
