### ISSUE TITLE
我的Win10版VPN突然翻不了墙了

### ISSUE THREAD

**Issue by Kellen1997** [breakwa11/shadowsocks-rss#759]
你好，我是一个月前买了一年你们的VPN 但是最近几天，我电脑上开VPN后就上不了网，无法翻墙打开google youtube facebook这些网站，而且国内的网站也基本用不了（没开VPN网络是好的）。 但是，我的iphone上面用你们的VPN 毫无问题，依然流畅。 我的电脑是win10的，我重新下载软件了好几次，也试过很多方法，但是还是不行。

**Comment by xunice13** [comment]
...追到git上来了，问题是这里不卖VPN啊

**Comment by dopenw** [comment]
你好，我每天都会收到你们各种小白的问题，拜托小白有问题先谷歌，我关注shadowsocks r是为了留意
shadowsocksr的动向，不是一天为了收到你们的资询。我真的比较佩服breakwa的耐心，谢谢你们肯定
shadowsocksr，但是请给高质量的提问，不要浪费大家的时间。谢谢

**Comment by Kellen1997** [comment]
为什么啊？我点开那个VPN的帮助他就自动跳到github上了，不是这里反馈问题的那去哪里反馈啊？  难道要我看看是不是vpn的源代码有问题啊……

**Comment by dopenw** [comment]
请问你的shadowsocksr账号密码及相关参数是谁提供给你的。你说你翻不了墙，你又提供不了详细说明，这种问题你自己先找找是不是网络设置，宽带提供商，shadowsocksr账号提供商，以及win10的设置是否有问题。这里不卖VPN，请确认是ssr的问题，再说好吗

**Comment by Kellen1997** [comment]
e...  账号密码都是我的，之前在官网买了一年 。 我用的就是ssr，也不不知道哪里出问题了

**Comment by Kellen1997** [comment]
之前连上了什么网都用不了，今天下了一个SS-Recover-500or502or504的脚本，那个500 internal privoxy error的问题没了，也可以上国内的网，但是google facebook这些上不了……
