### ISSUE TITLE
WinHTTP Web Proxy Auto-Discovery Service占用大量CPU

### ISSUE THREAD

**Issue by Kxzuir** [breakwa11/shadowsocks-rss#761]
仔细查看了日志，没有发现特别异常的情况。
从大概4.2.0（或更早的一两个版本）开始出现。目前使用4.2.3。
SSR工作在PAC(gfwlist)，开启负载均衡(SelectedFirst)的模式下，其他选项均为默认。有大约16个节点，其中有1-2个不可用。
计算机有三块网卡，Wi-Fi、Ethernet和Remote NDIS Compatible Device(USB共享网络)。
日常使用时Wi-Fi有公网IPv6和只能访问内网的IPv4地址，USB共享网络只有IPv4地址，可访问公网。二者DNS地址均为119.29.29.29。Ethernet不插网线。
症状具体表现为大概每2-5分钟该服务会突然占用70%以上的CPU（并伴随100M-300M内存占用），持续约5~10s，随后恢复。关闭SSR后该服务不再有上述现象。
该症状并非立刻出现，一般出现在电脑开机几个小时后。

**Comment by breakwa11** [comment]
最简单的方法是停用这个服务，绝大多数情况下都用不到

**Comment by Kxzuir** [comment]
哦，好的。顺便问一下AotoBan为啥不可选了

**Comment by breakwa11** [comment]
这功能没有意义了，而且判断不准确

**Comment by Kxzuir** [comment]
了解，感谢告知。

**Comment by Kxzuir** [comment]
找到一个类似的，https://github.com/shadowsocks/shadowsocks-windows/issues/879 ，大概没有解决，sigh
