### ISSUE TITLE
4.2.3 服务器记录 里的统计功能异常

### ISSUE THREAD

**Issue by wangwill** [breakwa11/shadowsocks-rss#762]
截图如下：

![image](https://cloud.githubusercontent.com/assets/9379983/25814888/1e953276-345e-11e7-9a43-8f64d0fdcb17.png)
![image](https://cloud.githubusercontent.com/assets/9379983/25814910/34d05566-345e-11e7-96d2-7e7eae9d6877.png)
![image](https://cloud.githubusercontent.com/assets/9379983/25814932/4aefc9ee-345e-11e7-9027-ec3f9f633896.png)

**Comment by leepoi** [comment]
也没个说明，让人家开发者自己猜嘛。。。。。

**Comment by wangwill** [comment]
最高   那个显示不正确啊

**Comment by breakwa11** [comment]
更新记录都不看，浪费时间
