### ISSUE TITLE
ubuntu更新后无法代理带有参数的url

### ISSUE THREAD

**Issue by RevolverOcelotA** [breakwa11/shadowsocks-rss#763]
客户端：<code>uname -a:   Linux localhost 4.8.0-51-generic #54~16.04.1-Ubuntu SMP Wed Apr 26 16:00:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux</code>
客户端：sudo iptables --list:   
<pre>Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination</pre>
ss有相同问题，并不是刚更新就发现的，所以不排除有其他因素，不过最有可能是因为系统更新
不是网络问题，同局域网的手机可以使用，重启到windows7也没问题，两边配置文件是完全一样的：
<pre>{
    "server": "服务器ip",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "密码",
    "method": "aes-128-ctr",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "timeout": 600,
    "udp_timeout": 300,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": true
}</pre>
应该不是浏览器问题，用polipo设置全局代理后，curl可以正常访问www.google.com，但是<kbd>www.google.com/?search.*</kbd>会无法建立连接
使用ss也是同样问题，而且ss客户端和服务端都没有任何输出，正常情况应显示错误信息或connecting xxx from xxx，没读过源码，不过像是url解析错误了
客户端hosts：
<pre>127.0.0.1       localhost
127.0.1.1       mikesmith</pre>
客户端resolve.conf:
<pre>nameserver 127.0.0.1</pre>
应该是ssr自动改的

服务端hosts：
<pre>127.0.0.1       localhost
127.0.1.1       guest
0.0.0.0 api.map.baidu.com
0.0.0.0 ps.map.baidu.com
0.0.0.0 sv.map.baidu.com
0.0.0.0 offnavi.map.baidu.com
0.0.0.0 newvector.map.baidu.com
0.0.0.0 ulog.imap.baidu.com
0.0.0.0 newloc.map.n.shifen.com

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02:: ip6-allrouters

127.0.0.1 localhost
::1       localhost

111.222.333.444 ssl.tracker.com ssltracker
222.111.333.444 www.tracker31.com tracker31

:: api.map.baidu.com
:: ps.map.baidu.com
:: sv.map.baidu.com
:: offnavi.map.baidu.com
:: newvector.map.baidu.com
:: ulog.imap.baidu.com
:: newloc.map.n.shifen.com</pre>

服务端resolve,conf:
<pre>nameserver 108.61.10.10
nameserver 8.8.8.8
nameserver 8.8.4.4</pre>
我改成过208.67.220.220自己又变回来了</pre>

**Comment by breakwa11** [comment]
@RevolverOcelotA 那你浏览器直接设置用socks5呢

**Comment by RevolverOcelotA** [comment]
@breakwa11 试过火狐浏览器 设置-高级-连接 里设置使用代理，为所有协议使用相同代理和插件和autoproxy插件，socks5代理

**Comment by RevolverOcelotA** [comment]
@breakwa11 刚才用chromium成功了，怀疑curl不行是因为对socks5的支持，但是重装火狐还是不行。。。。。。

**Comment by RevolverOcelotA** [comment]
是开了远程dns的，找到原因了，dns只开了udp没开tcp，不懂为什么dns查询会用tcp协议，之前没开都没问题（汗）
