### ISSUE TITLE
被墙了一个礼拜我的shadowsocksR终于恢复了

### ISSUE THREAD

**Issue by Kellen1997** [breakwa11/shadowsocks-rss#765]
折腾了一个礼拜，之前一直被抢，我每天各种看翻墙的知识，求助大佬，终于把我的VPN搞好了。我个人看，shadowsocksR的ssr确实比ss快，对于win10版的软件我认为应该增加服务器测试速，这样可以方便选择较好的服务器，像ios版一样。但是我觉得win10版的确实没有ios上面稳定。还有个问题，我官网下的客户端是win10版的3.9.1  但是看Github上都发布四点多版本了，但是我在github上面下载不了，能不能放到官网上去啊。

**Comment by Nehalem-Lf** [comment]
没有官网，github就是官网，谢谢

2017年5月11日 下午8:47，"Kellen1997" <notifications@github.com>写道：

**Comment by imtyz001** [comment]
我觉得可能又是被奸商误导买了账号的？

**Comment by Kellen1997** [comment]
没有官网？ https://www.socketpro.co/zh 这个不是吗？？？ 我这边下的服务里，买了一年vip  然后服务器打开里面就有这个github的页面

**Comment by yfdyh000** [comment]
@Kellen1997 不是。Shadowsocks官网是 https://shadowsocks.org/ ，SSR见 https://github.com/breakwa11/shadowsocks-rss

你那个网站只是第三方卖服务的。首页页脚的关于、条款、支持、链接都是空的，还有个隐藏的ICP备案号。

**Comment by imtyz001** [comment]
嗯的确是被奸商骗了 表示同情、理解与无奈

**Comment by Kellen1997** [comment]
不是吧…… 但是我的VPN好像用着好好地，那边下载下来是3.9.1版本 看Youtube很流畅，google秒开。 所以你们都是github上面下载的服务器吗？

**Comment by imtyz001** [comment]
GitHub只是代码和源程序 服务器是要自己搭建的，你买了奸商搭建的服务器 安全性和稳定性都存疑
Kellen1997 <notifications@github.com>于2017年5月13日 周六10:57写道：

**Comment by imtyz001** [comment]
这公司也是比较猛
ICP备案主体信息	
备案/许可证号: 蜀ICP备16024233号  审核通过时间: 2016-09-13 
主办单位名称: 成都语弦网络科技有限公司  主办单位性质: 企业 

ICP备案网站信息	
网站名称: 语弦网  网站首页网址: www.socketpro.co
网站负责人姓名: 颜语  网站域名: socketpro.co

**Comment by h2y** [comment]
第三方网站除了你自己搭建慢，还不稳定，并且容易跑路，也就没啥缺点了。
哈哈。

**Comment by Kellen1997** [comment]
so,  你们服务器都是哪里搭的，阿里云上面搭服务器好用么？

**Comment by bugparty** [comment]
这种备案的不安全，你的浏览记录都会被记录
