### ISSUE TITLE
能不能在局域网分享里面加个密码验证？

### ISSUE THREAD

**Issue by sxdxyxy** [breakwa11/shadowsocks-rss#77]
现在局域网分享有时候是不可控制的，能不能加个密码验证？

**Comment by breakwa11** [comment]
可以的，之前其实也想到这个问题，现在有个临时的解决方案，用privoxy转为http代理并设置验证密码。之后的版本会加上socks5验证密码

**Comment by sxdxyxy** [comment]
如何设置？

**Comment by breakwa11** [comment]
简单一点的话用CCProxy也行

**Comment by breakwa11** [comment]
对了，浏览器（FF和chrome）貌似不支持带验证的socks5代理，所以可能还是必须转成http代理来配置验证

**Comment by shuangzhijinghua** [comment]
chrome装插件，Firefox自带socks5验证，这不是浏览器必须有的？

BreakWa11 <notifications@github.com>于2015年9月28日周一 下午7:49写道：
