### ISSUE TITLE
[需求] 多开一个本地port，专门用于负载均衡

### ISSUE THREAD

**Issue by zhangciwu** [breakwa11/shadowsocks-rss#770]
如题
例如：
1080端口为目前已有的本地端口
1081端口为负载均衡专用端口，从这里进去的流量会使用一定的配置规则随机分配列表中的服务器

因为我有同时的  程序A使用固定服务器 和 程序B使用负载均衡多服务器 的需求，
所以不知道方便实现不

谢谢~

**Comment by yfdyh000** [comment]
复制一份、改本地端口，再开一个SSR。

**Comment by zhangciwu** [comment]
@yfdyh000 的确可以
不过多开之后，第二个instance的流量统计有点问题，最高上传，最高下载永远是0
（版本 4.2.3，  .net4  ， win7）

**Comment by zhangciwu** [comment]
@yfdyh000 
的确可行，小小副作用是可能某服务器增加了一个连接

**Comment by breakwa11** [comment]
@zhangciwu 不是下载很难更新最高速度

**Comment by zhangciwu** [comment]
@breakwa11 
不知道是不是问题，我这里描述一下吧
比如A服务器目前下载30KB，但是最高下载是0
而且一直是0，但是大概过了几分钟后最高下载就正常了

**Comment by breakwa11** [comment]
用久了你就习惯了
