### ISSUE TITLE
关于SSR的两个问题

### ISSUE THREAD

**Issue by nehcnoel** [breakwa11/shadowsocks-rss#771]
你好，破娃酱
非常感谢你为SSR做的贡献，让大家能使用到这么好的工具。
我有两个问题想请教：
1、目前软件中有gfwlist选项可供选择，请问SSR有自动更新此列表功能不？
2、我现在想访问中国网站时直连访问中国外的网站时用代理，请问该如何配置？  （我尝试过用全局、绕过局域网和大陆，但解析部分网址时速度比较慢，是不是哪里配置的不对？）

以上，望解答，多谢。

**Comment by breakwa11** [comment]
@nehcnoel 1 有
2 设置系统DNS，或客户端的DNS配置

**Comment by nehcnoel** [comment]
1、不好意思，我好像没找到选项，能否告知？
2、客户端的DNS配置具体在哪个文件？

以上，烦请解答，多谢。

**Comment by breakwa11** [comment]
@nehcnoel 菜单不是有更新为gfwlist吗？你直接在选项里改不就好了吗
