### ISSUE TITLE
请问使用ssr的auth_chain_a协议，以及plain，外套kcptun加速， 混淆还起作用吗？

### ISSUE THREAD

**Issue by kangshoo** [breakwa11/shadowsocks-rss#772]
请问使用ssr的auth_chain_a协议，以及plain，外套kcptun加速，那么混淆还起作用吗？
目前测试速度很好，但是不知道会不会因为kcptun暴露主机
之前看一个文章说，外套kcptun之后，混淆就失效了，特来求证，谢谢

**Comment by breakwa11** [comment]
@kangshoo 要这么做干嘛不直接用origin协议呢

**Comment by kangshoo** [comment]
@breakwa11 ，谢谢您这么快回复，按您的意思，就是外套kcptun使用之后，混淆确实失效了？所以直接用oringin，没必要auth_chain_a？
不用kcptun，我的vps太慢了

**Comment by breakwa11** [comment]
@kangshoo 用什么都没有意义，只管能传输过去就行了，不管混淆还是协议

**Comment by kangshoo** [comment]
@是的，但是我怕配合使用kcptun被发现得快，被毙的快

**Comment by breakwa11** [comment]
你用kcptun本来就应该算好过几天或者运气好点过两三星期你的UDP就会被封或至少限制得不能用
