### ISSUE TITLE
建议win客户端新版本恢复对一些老的协议的支持

### ISSUE THREAD

**Issue by bluefcomic** [breakwa11/shadowsocks-rss#776]
Win版4.2.3之后更新的版本（包括最新的4.3.1）
发现有部分老的协议已经不被支持了（例如auth_sha1）
即使手写也无法指定（4.2.2版本手写协议名是可以使用的）

如果可能的话还是希望恢复对一些较早版本协议的支持

**Comment by jpacg** [comment]
不支持旧协议很好啊，对抗GFW就要与时俱进，如果不需要混淆可以用原版的SS。

**Comment by bluefcomic** [comment]
这确实也有道理……只是有一部分服务器自己没法调整所以还是想能保留部分老协议的支持……

**Comment by breakwa11** [comment]
No
