### ISSUE TITLE
是否可以增加一个关闭更新提示的选项

### ISSUE THREAD

**Issue by redfrog999** [breakwa11/shadowsocks-rss#78]
开发者是否可以增加一个关闭更新提示的选项呢？有的站还没有，可能也不打算部署新的TCP协议服务端，这样旧版也能继续用，何况旧的版本还有其他用途。但是每次启动都会弹出一个更新提示，一不小心就点击到会启动ie，比较烦人，能增加一个关闭跟新提示的选项就好了，希望breakwa11考虑看看。THX。

**Comment by breakwa11** [comment]
新版也能用原协议啊，旧版的用途是啥？
对了，有人说你被定位了是什么情况

**Comment by redfrog999** [comment]
是这样滴，有些网络环境下直接连通是不行滴，我就需要用一个RSS作为前置，再开启一个RSS作为后端，作为前置的那个RSS用旧版本的连接的服务器是没有部署NEW TCP的，估计也不会部署了，我希望在现在的工作环境下启动RSS程序后，不要突然弹出那么大两个升级提示，呃，这不太好，可以选择的话，我希望把这个升级与否作为可选项，由我来控制，这对某部分用户应该非常有用。XX-NET就有个选择：不升级，比较方便。希望你予以考虑。

另外，关于定位问题，根据本人权威证实，绝无此事。现时环境平安是福，大家互助取暖啦。

**Comment by breakwa11** [comment]
所以我说新版本也支持原版协议，兼容性上是没有任何问题的

**Comment by redfrog999** [comment]
哈哈，女侠，兼容确实没问题，我就想要个升级与否的开关选项，用的时候把升级提示给关掉，然后我自己上来看有没有新版本就好了。

**Comment by breakwa11** [comment]
其实我正在做另一种升级提示方式，这样不关心的人直接无视就行了，想升级的可以随时点击，不至于过一会儿提示框消失点不到

**Comment by tardis2012** [comment]
女侠？breakwa11是女攻城狮？

**Comment by breakwa11** [comment]
@tardis2012 是半个宅女，但不是攻城狮。。。

**Comment by redfrog999** [comment]
好啊，期待新版本以一种优雅的方式来提醒想升级和不想升级的墙民。当然再加个软开关也是很好滴。攻城狮？？嘻嘻。

**Comment by breakwa11** [comment]
@redfrog999 弄成了有提示但点击不弹窗，然后有需要的人自己点菜单

**Comment by yfdyh000** [comment]
@breakwa11 这样不是更迷惑了，意思是点击气泡没效果，还需要自己用检查更新菜单？
以及，检查更新菜单在无更新时无反馈，也是很奇怪的。

同样非常希望有参数能关闭自动更新，有时更新挺频繁，手动更新挺麻烦。
而且用户或许更想要旧版的界面/功能设计，但却要忍受每次提示。

另外，更新麻烦的其中一点，每次的exe文件名是不同的，要么改启动项，要么改exe名称。不统一一下吗，exe的版本信息，以及用文件夹分类，应该足够了吧。

**Comment by breakwa11** [comment]
@yfdyh000 手动更新我打算去掉，并不是自己用检查更新菜单，这个不一样
exe文件名不同有什么问题？为什么要改名字？

**Comment by yfdyh000** [comment]
放了快捷方式到“启动”文件夹，换新版本就会失效，必须改名或者换新的快捷方式。

**Comment by redfrog999** [comment]
@breakwa11 默想了下，这个方法可行，另外加个选项：自动更新软件，留个方框，勾上就像你设计的那样，可以默认不勾上；不勾上了就彻底静默，我们安心干活，软件 low profile 运作。是不是更加人性化些呢？

**Comment by falseen** [comment]
我也觉得应该增加个提示开关，毕竟有那么多强迫症患者（我就是其中之一）。。。

**Comment by breakwa11** [comment]
![ssu](https://cloud.githubusercontent.com/assets/8436963/10164865/9f5e0840-66ee-11e5-9cd4-6a6ff0f65c30.png)
目前设计是这样子

**Comment by redfrog999** [comment]
@breakwa11 我咋觉得缺乏点美感捏。我建议把这个选项放到服务器界面的二维码下边：启动自动检测最新版，留个小框让用户自己选择，是否检测；检测到后把下载地址放出，用不同颜色标识以便识别，需要升级的点击直接到下载地址了，多方便呢。

**Comment by falseen** [comment]
放到全局设置里比较合适吧，或者像其他选项一样放到右键菜单里，打勾则关闭更新提示，不打勾则开启更新提示。

**Comment by breakwa11** [comment]
@redfrog999 放到那里就没人看了，在更新前更不会知道去那里看

**Comment by redfrog999** [comment]
@breakwa11 或者折冲一下，把更新的开关放到服务器设置区域的二维码界面下，默认开启更新提示，然后把提示的内容放到右键，实现你的设计目的。这样都可以照顾到。像我这样不需要更新的直接关闭掉就可以了。

**Comment by mountainguan** [comment]
我也想不更新啊，我想设置好给别人用，不用更新= =

**Comment by yjd** [comment]
@breakwa11
竟然是女的，太厉害了

**Comment by breakwa11** [comment]
没有什么情况都不会有更新提示了
