### ISSUE TITLE
服务器端设置混淆参数和客户端设置混淆参数有什么区别呢？

### ISSUE THREAD

**Issue by czmecho** [breakwa11/shadowsocks-rss#782]
是说服务器端一旦设置混淆参数，客户端必须设置相同的混淆参数，而服务器端如果不设置混淆参数，客户端可以设置各种混淆参数，是这样的吗？

**Comment by freedom8086** [comment]
服务端不设置混淆，客户端也不能设置，同步设置才行。

**Comment by breakwa11** [comment]
@freedom8086 错，请看wiki

**Comment by czmecho** [comment]
@breakwa11 重新编辑一下问题，
是说服务器端一旦设置混淆参数，客户端必须设置相同的混淆参数，而服务器端如果不设置混淆参数，客户端可以设置各种混淆参数，是这样的吗？

**Comment by czmecho** [comment]
@breakwa11 我知道了，看来还是要仔细看wiki。

服务端的混淆插件，http_simple或http_post有混淆参数，用逗号分开若干个host，表示客户端仅能使用以上任一个host连接，而留空表示客户端可以使用任意host。
