### ISSUE TITLE
mudb方式支持端口redirect吗？

### ISSUE THREAD

**Issue by do21** [breakwa11/shadowsocks-rss#788]
不好意思打扰破娃酱。

我看了mujson_mgr.py脚本好像没这个功能。
是可以直接写在mudb.json吗？
是遵循单用户配置那样的格式吗？

谢谢！

**Comment by breakwa11** [comment]
user-config.json

**Comment by do21** [comment]
没想到破娃的博客上写得比wiki详细很多……希望能合并到一起~
