### ISSUE TITLE
按教程安装服务器端“获取源代码”失败

### ISSUE THREAD

**Issue by ganganray** [breakwa11/shadowsocks-rss#79]
按照下述教程：
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup

做到“获取源代码”一步时，要求我输入Username for 'https://github.com'以及Password for 'https://github.com' 我输入自己github的用户名密码后显示
“fatal: HTTP request failed”

我随便输入一组用户名密码时，显示“fatal: Authentication failed”。说明我输入自己的github用户名密码是对的咯？HTTP request failed 是怎么回事？请问如何应对？

**Comment by breakwa11** [comment]
git clone不需要输入用户名密码，你用的命令不对吧

**Comment by ganganray** [comment]
好像是我前面加了sudo，所以要求输入用户名密码。不加直接输入
git clone -b manyuser https://github.com/breakwa11/shadowsocks.git
就好了。

谢谢。
