### ISSUE TITLE
有关ulimit的疑似bug

### ISSUE THREAD

**Issue by BROBIRD** [breakwa11/shadowsocks-rss#790]
在多台机器上实验过，已经按照ulimit修改要求修改完成，如果直接使用python server.py启动，输出的
`current process RLIMIT_NOFILE resource: soft * hard * `       *处的值为修改后的值
但是如果用service启动（CentOS7 systemctl脚本），则输出
`current process RLIMIT_NOFILE resource: soft 1024 hard 4096`

**Comment by breakwa11** [comment]
那是启动脚本的问题不是软件的问题

**Comment by BROBIRD** [comment]
使用的是Wiki中给出的脚本。

**Comment by breakwa11** [comment]
那个我不维护
