### ISSUE TITLE
Google play 必须全局模式才能下载app

### ISSUE THREAD

**Issue by hippyk** [breakwa11/shadowsocks-rss#792]
如题，白名单模式可以浏览，但是无法下载

**Comment by leepoi** [comment]
我这里选择绕过局域网和大陆，下载妥妥的

**Comment by hippyk** [comment]
@leepoi 确实可以，我选的是“仅代理大陆无法访问的”

**Comment by leepoi** [comment]
我试了，仅代理大陆无法访问的确实下载不了，不过，这个应该属于利用gfwlist的，好像属于黑名单。gfwlist纯手工维护的，肯定很多更新不及时的，我平时都是绕过大陆的，就算这样，play有特定应用也不能下载，这些应用的共同点就是国产的在play商店的应用，必须全局才能下载，绕过大陆模式都不行

**Comment by coolypf** [comment]
去系统的下载管理器里把“迅雷加速”之类的功能关掉。

**Comment by hippyk** [comment]
@coolypf 如果是迅雷的问题，应该所有模式都不行吧？

**Comment by coolypf** [comment]
你关了试试吧。

**Comment by slaeensh** [comment]
请把android的系统下载加入代理
另外一些app可能调用系统浏览器，所以某些特定情况下也是要一同进行操作的

**Comment by wystanchen** [comment]
转自：https://www.zhihu.com/question/54306291
-----------------------
用其他软件（比如浏览器）科学上网正常么？如果这个梯子使用别的应用正常，只有用 Google Play 一直等待下载，那么你可以试试我这个方法：
1、在应用管理里找到系统应用 “下载” 或 “下载管理器”
2、清除这两个应用的数据
3、强行停止这两个应用（没反应不要紧，只要按过强行停止即可）
再试试吧，应该就可以下载了，如果还不行，重启手机后应该就可以了。
我也遇到过这个问题，连在中国局域网内下载都是一直等待下载，用这个办法成功解决问题！
-----------------------
可以试试看，我三星s7 edge国行，用这种方法解决了ss开启“绕过局域网和国内地址”后，play商店只能浏览不能下载的问题。

**Comment by hippyk** [comment]
我也换成了 “绕过局域网和大陆”，反正是不用全局了

**Comment by emersonyoung** [comment]
我大概是在上个月play无法打开，一直使用 “绕过局域网和大陆”
android 7.0
需要重新安装才能用，但是一阵子后又无法使用。
其他5.0和4.0设备一切正常。
