### ISSUE TITLE
可否增加自动临时弃用在本次运行中出错比例高的服务器的功能

### ISSUE THREAD

**Issue by ARwMq9b6** [breakwa11/shadowsocks-rss#8]
近期加入的“重试次数”功能很贴心，服务器出错时会切换到其他服务器完成本次任务。不过有些出错率高的服务器总是被访问，然后出错，

可否加入临时弃用它们的功能？

**Comment by breakwa11** [comment]
有一个手工对指定服务器关闭使用的功能，在服务器统计里的“开”列表，不知道这是不是你想要的功能？

**Comment by ARwMq9b6** [comment]
@breakwa11 嗯！谢谢，这就是我想要的功能。

我还想让确定无效的服务器在本次运行时被 ShadowcoksR 关进小黑屋，可以“先斩后奏”，也可以不“奏”。

**Comment by breakwa11** [comment]
曾经有自动丢小黑屋的功能，但发现会有误杀，所以还一直没有加上

**Comment by ARwMq9b6** [comment]
@breakwa11 俺发现那些延迟为 - 的，即 tcping server:port 没有回应的一定是“罪大恶极”的，证据确凿，可不经审批，就地正法的。

俺一不输出革命，二不输出­饥饿和贫困，三不去折腾你们，他们的服务器端口却没开，还有什么好说的。
