### ISSUE TITLE
个人用户版服务器端是否支持不同端口分别定义不同混淆协议？

### ISSUE THREAD

**Issue by ganganray** [breakwa11/shadowsocks-rss#80]
按照教程中的配置

{
    "server":"0.0.0.0",
    "server_ipv6": "[::]",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
         "80":"password1",
         "443":"password2"
    },
    "timeout":300,
    "method":"aes-256-cfb",
    "obfs":"http_simple",
    "fast_open": false,
    "workers": 1
}

80、443两个端口都使用http_simple混淆。不知能否分开定义混淆方式？

**Comment by falseen** [comment]
暂时还不能，不过看代码的话，要支持的话似乎也不难。看breakwall的意思吧。

**Comment by ganganray** [comment]
谢谢。有时候不同网络环境需要不同混淆，有的客户端不支持混淆。所以，支持分开定义还是有意义的吧。期待有关更新。

**Comment by falseen** [comment]
已经支持了。
更新下代码，按照这个下面的示例进行配置（稍后会更新到wiki）：

```javascript
{
"server":"0.0.0.0",
"server_ipv6":"::",
"local_address":"127.0.0.1",
"local_port":1080,
"port_password":{
    "8388":["password1","http_simple"],
    "8389":["password2","random_head"]
},
"timeout":300,
"method":"aes-256-cfb",
"obfs":"http_simple",
"fast_open": false,
"workers": 1
}
```

**Comment by ganganray** [comment]
Thank you!

**Comment by cfcboy** [comment]
@falseen 还未更新到WIKI啊。。。怕到时候忘了，做个记号。
还有就是Android版本的SS2.8能不能支持新协议？
2.77的好像不行。。。

**Comment by breakwa11** [comment]
@cfcboy 还不支持

**Comment by breakwa11** [comment]
@ganganray 有用的，在前面没有指定混淆的端口就会用后面的默认值

**Comment by cfcboy** [comment]
@breakwa11 感谢回复，手机端不支持就有点蛋疼了。。。不方便啊。服务端也不能换成老版本吧。。唉。只能等了。

**Comment by breakwa11** [comment]
@cfcboy 新版本服务端一直能支持原版协议

**Comment by cfcboy** [comment]
@breakwa11 已测试。可以用。之前用的是联通3G。。。IP可能被和谐了。。联通WIFI就可以
