### ISSUE TITLE
訂閲地址

### ISSUE THREAD

**Issue by candy2107** [breakwa11/shadowsocks-rss#801]
找了半天都沒有訂閲地址的使用説明 , 能否把這個訂閲的用法寫進wiki裏面?

**Comment by wenliyang** [comment]
Wiki里有写

https://github.com/breakwa11/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3

**Comment by candy2107** [comment]
wiki裏面沒寫怎麽加密啊 
默認的那個訂閲地址數據加密過了
沒辦法用base64直接解碼
