### ISSUE TITLE
复制ssr://链接到win客户端后，ip地址与实际不符。

### ISSUE THREAD

**Issue by breakwa11fans** [breakwa11/shadowsocks-rss#802]
破娃你好

环境：centos 7 64bit 
服务端：json多用户版
客户端，windows客户端 4.4.4

使用json多用户配置出现问题如下：

使用python mujson_mgr.py添加了一个用户。

复制ssr://链接到win客户端后，ip地址与实际不符。

修改该ip为实际地址后可正常上网。

求获取正确ip的解决方法。。。

谢谢

**Comment by breakwa11** [comment]
userapiconfig.py设置ip
