### ISSUE TITLE
兄弟们帮忙，有时候500错误500 Internal Privoxy Error

### ISSUE THREAD

**Issue by bbhxwl** [breakwa11/shadowsocks-rss#808]
刚开始我自己测试的，没问题，给别人测试，他这个错误，然后我自己再访问一下，也是这个错误了。
另外我修改服务器ip的话
用下面的可以
 var config= ss.GetConfiguration();
            config.configs[0].server = "45.32.49.18";
            ss.SaveServersConfig(config);

所有修改config的，都可以用SaveServersConfig吗？
![qq 20170609145455](https://user-images.githubusercontent.com/26525599/26964419-ee7561e0-4d23-11e7-918f-e45da14d2f84.png)

**Comment by wangchunming** [comment]
如果没有返回dns的话一般就会出现这个错误。
