### ISSUE TITLE
关于服务器连接统计的界面

### ISSUE THREAD

**Issue by Arnaud-Github** [breakwa11/shadowsocks-rss#81]
![qq 20150930094312](https://cloud.githubusercontent.com/assets/11697277/10182523/c27399a8-6757-11e5-908d-b37c1963e833.jpg)
![qq 20150930094315](https://cloud.githubusercontent.com/assets/11697277/10182526/c6795d6c-6757-11e5-8faa-c02c5c0937f8.png)
这里留下了空白处。。。是什么 用途。。没有固定呀。。强迫症表示受不了
![qq 20150930094318](https://cloud.githubusercontent.com/assets/11697277/10182529/ca2ea2b4-6757-11e5-9681-a3758f9ed4ad.jpg)
强迫症理想当中是这样的。。而且那个字体。。能换成微软雅黑吗
![qq 20150930094512](https://cloud.githubusercontent.com/assets/11697277/10182544/f3e2beec-6757-11e5-8ef2-57d8fb93706a.jpg)
这个注释删掉不行吗。。。然后加个服务器IP或者域名隐藏 星号代替什么的。。![qq 20150930094531](https://cloud.githubusercontent.com/assets/11697277/10182549/0022d0ca-6758-11e5-809c-0aff7e873227.jpg)

不要骂我说我只知道伸手啥。。我也没能力改，作者要是愿意修改这些，表示非常感谢，不愿意我也没办法，谢谢~

**Comment by Arnaud-Github** [comment]
okay

**Comment by Arnaud-Github** [comment]
= =

**Comment by breakwa11** [comment]
有一个不好调整的情况是当有垂直滚动条的时候

**Comment by Arnaud-Github** [comment]
@breakwa11 服务器列表多，出现滚动条吗？好吧，我也没有把这个考虑进去。。、

**Comment by Arnaud-Github** [comment]
可以

**Comment by breakwa11** [comment]
已解决
