### ISSUE TITLE
小建议，mudb更人性化

### ISSUE THREAD

**Issue by manyang901** [breakwa11/shadowsocks-rss#810]
mujson_manage.py 能否加入类似 “--method”之类的选项
mudb.json的上下行流量能否按G计算而不是字节？甚至自动分KB、MB、GB计算。或者加入mudb流量统计工具？
不懂python，不然就发pr了
小事情还要麻烦开发者，惭愧

**Comment by breakwa11** [comment]
@manyang901 -m不就是method吗？显示不是默认用G的吗

**Comment by manyang901** [comment]
嗯但是每次想到pasword就用了-p 然后……
上下行流量默认显示是byte啊，总流量才是G

**Comment by breakwa11** [comment]
你可以用-e修改，显示那个我看看

**Comment by breakwa11** [comment]
上下行流量本来就会自动使用不同的单位，你说的问题根本不存在

**Comment by manyang901** [comment]
好吧，版本没更新，sorrt

**Comment by manyang901** [comment]
sorry
