### ISSUE TITLE
无法代理上网

### ISSUE THREAD

**Issue by holyen** [breakwa11/shadowsocks-rss#813]
whmcs+ssr
使用mac 版shadowsocks(粉色版和原版)均无法正常代理上网
配置文件如下
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "ssr123",
    "method": "aes-256-cfb",
    "protocol": "verify_sha1_compatible",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {}, // only works under multi-user mode
    "additional_ports_only" : false, // only works under multi-user mode
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}
寻求帮助,感谢大神

**Comment by breakwa11** [comment]
@holyen 谁教你用这个协议的

**Comment by holyen** [comment]
@breakwa11 他的是正常使用了

**Comment by breakwa11** [comment]
我不知道你说什么，请回答我前面的问题

**Comment by li-sky** [comment]
有一定可能是应用了其他的混淆插件。
