### ISSUE TITLE
安卓SSR最新版订阅功能会出现问题

### ISSUE THREAD

**Issue by zimonianhua** [breakwa11/shadowsocks-rss#816]
安卓SSR最新版订阅功能会出现问题
一开始能添加订阅，但是从订阅更新的服务器信息只有期中的一半
之后不能添加订阅，不知道为什么

同一个订阅源电脑没问题

**Comment by breakwa11** [comment]
@zimonianhua 你的订阅内容格式可能有问题

**Comment by zimonianhua** [comment]
谢谢，找到问题了

**Comment by miaovpn** [comment]
@zimonianhua 请问大佬是怎么解决的？这功能出来后在安卓上一直没成功过

**Comment by zimonianhua** [comment]
@miaovpn 你生成方式是按规则来的吗
