### ISSUE TITLE
节点配置正确性测试

### ISSUE THREAD

**Issue by breakwa11** [breakwa11/shadowsocks-rss#82]
针对现在越来越难判断出节点的 密码/加密方式/混淆方式 的配置是否正确，需要单独做一个手工判断环节

**Comment by falseen** [comment]
如何手工判断？

**Comment by breakwa11** [comment]
在github上弄一个特定页面，内容预定义，然后客户端访问，返回内容必须精确与预定义的内容一样，我的思路是这样

**Comment by falseen** [comment]
我还是不明白这样做的意义是什么。

**Comment by breakwa11** [comment]
已实现
