### ISSUE TITLE
ss-server经常断线block ip，restart就好，很快又不行

### ISSUE THREAD

**Issue by jaykangta** [breakwa11/shadowsocks-rss#820]
Update前ss-server断线一般频繁，基本上几个小时一次，更新了最新版坚持不了10分钟，log截图如下：

Jun 22 03:00:01 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: UDP relay enabled
Jun 22 03:00:01 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: initializing ciphers... aes-256-cfb
Jun 22 03:00:01 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: tcp server listening at 0.0.0.0:9527
Jun 22 03:00:01 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: udp server listening at 0.0.0.0:9527
Jun 22 03:00:01 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: running from root user
Jun 22 03:00:03 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: failed to handshake with 115.192.115.74: invalid address type
Jun 22 03:00:04 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: socket: Address family not supported by protocol
Jun 22 03:00:04 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: connect error
Jun 22 03:01:25 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: getpeername: Transport endpoint is not connected
Jun 22 03:01:25 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: block all requests from 115.192.115.74
Jun 22 03:01:25 iZj6cgbxmrjvoyt8hbhaejZ /usr/local/bin/ss-server[640]: block all requests from 
115.192.115.74

**Comment by breakwa11** [comment]
这东西不关我的事，找作者去

**Comment by jaykangta** [comment]
那个我是想探讨下这个问题出在哪儿，bug在哪儿这样， @breakwa11 大大有什么思路吗？
