### ISSUE TITLE
对于最新版使用的规则文件，是不是应该用 ACL （当前 Android 版使用的），便于维护？

### ISSUE THREAD

**Issue by laincat** [breakwa11/shadowsocks-rss#827]
当然这只是想法，并不是什么建议或者什么。

当然当前维护一份自己的规则会有很多好处，但是如果能直接调用原有的通用规则（格式），就可以节约学习成本和维护成本。

(另外分享个 https://github.com/ACL4SSR/ACL4SSR ACL规则。给 Android 用户 😀)

**Comment by breakwa11** [comment]
@laincat 因为设计不一样，强行用一样的格式会导致C#版本的规则功能缩水

**Comment by laincat** [comment]
嗯好的，表示理解。那我还是转换一个玩去，有规则玩后，其他模式都可以消失了。

（如果有 debug 界面就更好了，能直观显示出规则运作状态。）

在这还是很感谢 小姐姐。

**Comment by breakwa11** [comment]
@laincat 可以通过LOG来DEBUG，有显示每个连接怎么走

**Comment by laincat** [comment]
好的，我研究研究。再次感谢。
