### ISSUE TITLE
请问最新版本的SSR是否已经自带了UDP转发功能？

### ISSUE THREAD

**Issue by i0ffer** [breakwa11/shadowsocks-rss#828]
首先，感谢破娃酱大大，给我们提供了这么好的程序，让无数人收益！
目前，我已经通过查阅这里的wiki文档和通过互联网搜索到的知识，成功在一台韩国VPS上面搭建了SSR，目前运行良好，无任何问题，搭配Pandavan路由器，非常好用!
【但是现在有一个问题就是】：由于我主要的需求是玩外服游戏，如果能够使用UDP转发功能的话，是如虎添翼的。所以我想问一下，这个最新版的SSR是否已经自带了UDP转发功能？如果已经带了，应该怎样开启它？如果没有带，我应该去寻找哪些相关插件支持？

PS：希望大大百忙之中能够抽出时间来看一下我的问题，如果能够解决，不胜感激！
由于是初涉这个领域，完全是自学的，所以希望能够得到一个比较详细便于小白理解的答案，谢谢！

**Comment by 01186** [comment]
udp over tcp

**Comment by breakwa11** [comment]
你无法关闭UDP转发功能

**Comment by i0ffer** [comment]
啊……原来已经默认开启了UDP么？太好了
