### ISSUE TITLE
3.5.2 版本为何移除rc4加密方式

### ISSUE THREAD

**Issue by L-Meteor** [breakwa11/shadowsocks-rss#83]
订购的服务都是启用默认为rc4-md5的加密方式,刚看完更新说明,3.5.2 版本移除rc4,那以后的版本不是都无缘使用了吗?女神,这是怎么回事啊!?

**Comment by falseen** [comment]
移除的是rc4，而不是rc4-md5 。另外虽然rc4-md5没删，但不推荐用，怀疑其已经被GFW破解。

**Comment by hu895183198** [comment]
要我说直接用AES-256-CFB好了，这两种加密方式似乎资源消耗差异不大

**Comment by L-Meteor** [comment]
谢谢各位的解答,现就去下载更新!

**Comment by louy2** [comment]
MD5 已经不安全了，RC4 是可以暴力。最近连 DH 交换协议都证明不安全了。

如果可能的话还是用 Salsa20 之类的吧。
