### ISSUE TITLE
json版多用户配置具体是怎么配置的

### ISSUE THREAD

**Issue by 467600474** [breakwa11/shadowsocks-rss#836]
接着，通过使用脚本mujson_mgr.py添加端口及相应的加密、协议、混淆等配置，这边没看懂，vi打开mujson_mgr.py里面没看懂

**Comment by Axulai** [comment]
同问。和文档写得不一样，自己看半天也没搞懂

**Comment by breakwa11** [comment]
目前不支持muapiV2

请用 python mujson_mgr.py -h
