### ISSUE TITLE
限速失效

### ISSUE THREAD

**Issue by kkkkke** [breakwa11/shadowsocks-rss#839]
version: 
3.1.2

system:
Debian 9

What did you do:
set user speed at **2048Kbps**

What did you expect to see:
Download speed limited at 2048Kbps

What did you see instead:
**FULL** speed at **70Mbps**

What is your config in detail (with all sensitive info masked):
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 443,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "password",
    "method": "aes-256-cfb",
    "protocol": "auth_chain_a",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "speed_limit_per_con": 2048,
    "speed_limit_per_user": 2048,
    "additional_ports" : {}, // only works under multi-user mode
    "additional_ports_only" : false, // only works under multi-user mode
    "timeout": 300,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": true
}

为了减少被发现的几率，设置限速可能是必须的。但是这个限速功能似乎不太管用。

**Comment by breakwa11** [comment]
你写了2048，那么限速是16384Kbps或16Mbps
