### ISSUE TITLE
建议负载均衡做成和旧版本一样在菜单里选择

### ISSUE THREAD

**Issue by wenliyang** [breakwa11/shadowsocks-rss#84]
3.52版本改到“选项设置”里了，感觉没有旧版本放在菜单里方便
旧版本在菜单里勾选或不勾选，很直观，而且设置方便
放到“选项设置”里，感觉操作便利性没有旧版本的好

**Comment by breakwa11** [comment]
便利性的问题，我的想法是比如shift加鼠标右键直接弹出选项框，这样操作速度和原来的差不多，同时一堆设置都可以快速修改

**Comment by redfrog999** [comment]
嗯嗯，更支持採用快捷鍵方式來快速操作，因為習慣於FF的強大快捷鍵，所以希望女俠盡可能地設置那些比較繁瑣的鼠標操作為快捷鍵。要是能預設一些可以自定義的快捷鍵就更好了。

**Comment by shuiyind** [comment]
负载均衡 不方便+1

**Comment by ARwMq9b6** [comment]
3.5.3 Beta 版的 `Shift + 左键单击托盘图标`，可否改成是双击托盘图标实现弹出“选项设置”窗口呢？

目前已知的快捷操作：

+ 左键单击托盘图标： 弹出“编辑服务器”窗口
+  <del>左键双击托盘图标： 弹出“编辑服务器”窗口<del>
+ 中键单击托盘图标： 弹出“服务器记录”窗口
+ Shifit + 左键单击托盘图标： 弹出“选项设置”窗口

**Comment by wenliyang** [comment]
我觉得 Shifit + 左键单击托盘图标 比 双击 好用，双击 很容易触发那个 单击

**Comment by ARwMq9b6** [comment]
@wenliyang 原来如此，谢谢！
