### ISSUE TITLE
单端口多用户安全问题

### ISSUE THREAD

**Issue by jackwangshanghai** [breakwa11/shadowsocks-rss#843]
一直以来有这样的一个疑问，就是单端口多用户的 端口配置参数是公布的，这样会不会导致 知道端口的人伪造服务器 从而导致一些安全隐患。端口内部的用户名密码 不知道客户端会不会去核实是否与服务器匹配，感觉只有服务器单方面认证 客户端，这是不是会有安全问题。 感觉单端口多用户是不是增加服务器认证功能，譬如协议中进行非对称密钥认证 以确保服务器是真实的。

**Comment by jackwangshanghai** [comment]
本来想干Preshared Key 但是想到端口会被公布，所以想到非对称加密。或者 每一个该端口内的用户的密码进行使用独立 Preshared Key认证

**Comment by breakwa11** [comment]
我认为不存在这个问题，请对照协议文档给出服务端攻击方法

**Comment by jackwangshanghai** [comment]
原来不会有问题 那么多虑了
