### ISSUE TITLE
付费咨询 window端部署遇到的问题

### ISSUE THREAD

**Issue by coco369z** [breakwa11/shadowsocks-rss#845]
安装了python 2.7.9,openSSL  ,下载源码到c盘  ，命名为 shadowsocksr
用笔记本打开 c盘  shadowsocksr.json   更改windows系统的ip  断口   密码  协议 等

开python 使用命令 运行  ：   python local.py -c /etc/shadowsocksr.json
报错  ：invalid syntax

qq 2486942765﻿

**Comment by yaoguaishou** [comment]
这是什么途径？什么系统？（笑

**Comment by yaoguaishou** [comment]
这个途径是不正确的
应该类似于C:\shadowsocks.....
windows环境变量设置请参考https://doub.io/ss-jc45
另外windows安装libsodium等于盲人摸象不能支持chacha20等算法
最后说一句：Linux大法好

**Comment by coco369z** [comment]
thanks
