### ISSUE TITLE
可否更新一下GoAgentX所需的文件？

### ISSUE THREAD

**Issue by imyellow** [breakwa11/shadowsocks-rss#85]
Mac下最好用的就是GoAgentX了，附带有chrome插件，非常方便的就可以自动增加规则，在使用 ShadowsocksR 之后，一直报错getpeername: Invalid argument，无法使用

**Comment by breakwa11** [comment]
其实我没听明白，这和goax有什么关系，然后又是怎么在mac下运行ssr的

**Comment by imyellow** [comment]
不好意思，我没说清楚，是这样的，Mac下有个非常好用的软件叫 GoAgentX，配合一些自动更新的规则和chrome插件，遇到需要代理的域名点一下就加到规则了，非常方便，并且除了SS同时也支持SSH之类别的代理服务的整合。

SS是他所支持的其中一个，我看目录是以一个扩展包的方式来载入的，并且有个更新，但因为原SS已经不见了，所以也没办法更新了。

![](http://ww4.sinaimg.cn/large/5f789f8fgw1ewlpexicicj20xc0qkn4a.jpg)
![](http://ww1.sinaimg.cn/large/5f789f8fgw1ewlpoahvnpj20i20823zw.jpg)

所以我来问问有什么办法，可以手动更新什么文件让GoAgentX可以像win一样支持shadowsocksR全功能。

按照 https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup 装好服务器之后，GoAgentX会报错，应该是某些参数不兼容之类

![](http://ww4.sinaimg.cn/large/5f789f8fgw1ewlphrtavqj20ui0x0wz4.jpg)

**Comment by breakwa11** [comment]
看起来好厉害的样子，但我现在没有mac环境是硬伤

**Comment by falseen** [comment]
@breakwa11  可以装个黑苹果嘛！

**Comment by breakwa11** [comment]
已经有人做出来了
