### ISSUE TITLE
请问SSR如何加速VIMEO的视频？

### ISSUE THREAD

**Issue by j0hnnie** [breakwa11/shadowsocks-rss#850]
pac模式下
打开vimeo很快
但是看视频就超级卡卡卡
又不能一直开着全局。。
怎么办呢

**Comment by Guochengjie** [comment]
这是你服务器的问题。如果是ovz就lkl加bbr或者netspeeder如果kvm就锐速或魔改版bbr，如果还不行，换机子。

**Comment by breakwa11** [comment]
自己修改PAC或修改代理规则
