### ISSUE TITLE
希望恢复ss-tunnel的使用

### ISSUE THREAD

**Issue by yu-xiong** [breakwa11/shadowsocks-rss#859]
目前ss-redir虽然支持udp模式，但对于dns解析还是要依赖tproxy模块，而很多现有电脑默认情况下并不带tproxy模块，而ss-tunnel就能很好的解决这个问题。所以最后强烈建议恢复ss-tunnel的编译。

**Comment by breakwa11** [comment]
根本就不存在恢复的问题

**Comment by thank243** [comment]
udp很多地方都封杀了。还是pdnsd套ssr最安全。
