### ISSUE TITLE
建议：加入屏蔽广告功能---不仅提速，还能清爽。同意的顶起！

### ISSUE THREAD

**Issue by ioudove** [breakwa11/shadowsocks-rss#86]
如题，记得GAE中就加入了屏蔽广告功能，若是Shadowsocks中能加入屏蔽广告功能岂不更加完美：）

**Comment by yfdyh000** [comment]
SOCKS包很难拆（大概），HTTPS和其他包没法拆（HTTPS中间人除外）。伪需求。

**Comment by falseen** [comment]
你肯定记错了，gae没有这个功能。而且ss做为一个穿墙工具，它只要完成它的本职工作就行了，去广告不是它应该做的（即使它能做）。

**Comment by yfdyh000** [comment]
goagent有这个功能，因为都是拆包（中间人）传输，并且都是HTTP(S)信息。

**Comment by cfcboy** [comment]
@falseen 顶你，不需要太花哨。实用第一。

**Comment by jang-u** [comment]
楼主是网警
鉴定完毕

**Comment by polong** [comment]
@jang-u 说说你的依据。

**Comment by sxdxyxy** [comment]
这个应用就是专门用于代理的，功能多了没意义，你看firefox,chrome都有拦截广告的插件，那不是挺好的吗？

余晓云
三峡大学水利与环境学院
TEL：+86-717-6392165
MOB：+86-13307208008
MSN：yuxiaoyun@ctgu.edu.cn
QQ:23937286
blog: http://yuxiaoyun.blogspot.com

**Comment by polong** [comment]
@sxdxyxy 晕，这个是楼主的个人信息？恕我愚钝，1、我咋没看出和楼主有什么必然的联系？2、我咋看不出是网警？

**Comment by nicedayever** [comment]
一点也没必要，代理工具做的越纯粹越好！

**Comment by aprikyblue** [comment]
去广告不是它该做的，不要试图加入一堆冗余功能。美其名曰“完美”“便利”，就像xx卫士xx管家。
越简洁纯粹越好，去广告的那么多你为什么不去用

**Comment by jang-u** [comment]
goagent没有去广告功能，去广告功能会增加特征，容易被封锁利用
楼主的建议翻译后的意思是：SS我们封不住，请SS作者提供特征帮助我们封锁

**Comment by yfdyh000** [comment]
@jang-u 有的，本地实现的规则过滤。但SS不可能拆包，所以不可能有这个特点。

@breakwa11 不来关掉这个吗。
