### ISSUE TITLE
单端口多用户的用户数上限问题

### ISSUE THREAD

**Issue by caiyiliyl** [breakwa11/shadowsocks-rss#862]
**想问一下单端口多用户的同时连接用户数上限应该在哪里设置？比如下面是我的mudbjson：**

{
        "d": 0,
        "enable": 1,
        "method": "none",
        "obfs": "tls1.2_ticket_auth",
        "passwd": "1234",
        "port": 80,
        "protocol": "auth_chain_a",
        **"protocol_param": "#",    //位置1**
        "transfer_enable": 1125899906842624,
        "u": 0,
        "user": "80"
    },
    {
        "d": 0,
        "enable": 1,
        "method": "none",
        "obfs": "tls1.2_ticket_auth",
        "passwd": "4321",
        "port": 100001,
        "protocol": "auth_chain_a",
        **"protocol_param": "2",    //位置2**
        "transfer_enable": 107374182400,
        "u": 0,
        "user": "100001"
    },
    {
        "d": 0,
        "enable": 1,
        "method": "none",
        "obfs": "tls1.2_ticket_auth",
        "passwd": "4321",
        "port": 100002,
        "protocol": "auth_chain_a",
        **"protocol_param": "2",    //位置3**
        "transfer_enable": 107374182400,
        "u": 0,
        "user": "100002"
    }

**在位置2、3设置参数，可以实现100002端口和100003端口各为两个用户数上限，加起来为四个用户数上限吗？**
**在blog的教程中，只有提到单端口多用户的设置，没有提到单端口多用户用户数上限的设置，谢谢解答！**

**Comment by breakwa11** [comment]
根本就没有设置连接数上限的

**Comment by caiyiliyl** [comment]
@breakwa11 抱歉，是我的表述问题，应该是同时连接用户数上限，100001和100002端口的同时连接用户数上限可以这么设置吗？或者说该如何设置？谢谢！

**Comment by breakwa11** [comment]
只能设置80端口的上限，100001目前不支持单独设置

**Comment by caiyiliyl** [comment]
@breakwa11 期待破娃酱能开发出该功能~本帖稍后关闭。
