### ISSUE TITLE
新版没有检测旧版的开机启动项键值

### ISSUE THREAD

**Issue by polong** [breakwa11/shadowsocks-rss#87]
导致旧版已设置开机启动，而新版不知道，并且当在新版设置开机启动后，开机会提示不能运行两个。

**Comment by shuiyind** [comment]
新版 在 选择服务器的下面 有个选项设置

**Comment by polong** [comment]
@shuiyind 你好像没明白我说的是啥意思，嘿嘿。

**Comment by wenliyang** [comment]
@polong 我明白你的意思，旧版本设置的手动删除就行了吧

**Comment by breakwa11** [comment]
启动一下原版，然后关掉开机启动就行了
