### ISSUE TITLE
V2EX有人或喝茶，或因SSR

### ISSUE THREAD

**Issue by dou4cc** [breakwa11/shadowsocks-rss#871]
[![](https://pbs.twimg.com/media/DFoffUdXUAAVnhH.jpg:large)](https://www.v2ex.com/t/377942)

**Comment by BenjaminGao** [comment]
不知道你发这个是什么意思？看发 issus 的要求了么？@breakwa11 无关 issus, 请求关闭

**Comment by WLZLCX** [comment]
网上的谣言 要自我判断

**Comment by wangxufire** [comment]
没人B你用，出事了还想找人负责吗
