### ISSUE TITLE
SSR-windows客户端经常强制关闭

### ISSUE THREAD

**Issue by nicedayever** [breakwa11/shadowsocks-rss#89]
系统WIN10 x64,

贴上log：
[2015-10-08 10:39:31] ShadowsocksR started
[2015-10-08 10:47:46] System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Listener.AcceptCallback(IAsyncResult ar)
[2015-10-08 10:47:52] System.IO.IOException: 文件“D:\Tools\Shadowsocks\temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()
[2015-10-08 10:47:52] ShadowsocksR started
[2015-10-08 10:48:02] System.Runtime.InteropServices.SEHException (0x80004005): 外部组件发生异常。
   在 System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   在 System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-08 11:10:45] System.ArgumentException: 源数组长度不足。请检查 srcIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 Shadowsocks.Obfs.VerifySimpleObfs.ClientEncode(Byte[] encryptdata, Int32 datalength, Byte[] outdata, Int32& outlength)
   在 Shadowsocks.Controller.Handler.RemoteSend(Byte[] bytes, Int32 length, Int32 tcp_protocol, Int32 obfs_max)
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)

**Comment by farrellyang** [comment]
我今天也遇到，3.5.3崩溃好几次，V6连接在较高上传速率时，win8.1 x64提示clr.dll错误，好像和.net4.0有关

2015-10-08 11:30 GMT+08:00 nicedayever <notifications@github.com>:

**Comment by breakwa11** [comment]
试试bt sync里的fix2版本，这个错误是已知的，试试那个版本修正了没有

**Comment by gamestart** [comment]
我好像一用12306就会出现这种情况，不知道是不是因为12306的原因

**Comment by nicedayever** [comment]
@gamestart 升级为3.6.6版本后，很少会出现崩溃的情况了。
