### ISSUE TITLE
您好...我想知道这个mysql的配置的目的是?

### ISSUE THREAD

**Issue by blankhang** [breakwa11/shadowsocks-rss#9]
服务端配置
shadowsocks目录内，文件Config.py：
MYSQL_HOST = 'mdss.mengsky.net' #前端mysql域名/IP
MYSQL_PORT = 3306 #mysql端口
MYSQL_USER = 'ss' #mysql用户名(建议不要用Root账户)
MYSQL_PASS = 'ss' #mysql密码
MYSQL_DB = 'shadowsocks' #数据库名

不知能否再详细一点配置说明...
目前的 配置会报错..无法连接mysql什么的..

**Comment by breakwa11** [comment]
多用户时的数据库，如果是单用户请运行子目录下的server.py
