### ISSUE TITLE
更新很快

### ISSUE THREAD

**Issue by jang-u** [breakwa11/shadowsocks-rss#90]
rc4-md5加密可能被破解，更换其他加密方式

我这旧协议还能用，还是先用旧协议顶着，新协议可能需要更多的测试

更新很快，大神辛苦了，感谢！

**Comment by jang-u** [comment]
又更新了，旧协议是否不安全了？要换成新协议吗？
看了新协议的介绍，什么强特征、未完成等，又不敢用了
个人用户具体怎么配置新协议，能不能有个详细的教程？

我是用下面命令行启用服务端的，要怎么用新协议？
python server.py -p 443 -k password -m aes-256-cfb -d start

最好把新协议的选择直接在客户端选，服务端不需要更改，方便我这种小白，谢谢！

**Comment by hulucc** [comment]
协议怎么可能只需要修改一端呢

**Comment by breakwa11** [comment]
服务端不需要更改这种梦不应该有

**Comment by jang-u** [comment]
有梦最美
