### ISSUE TITLE
ss链接格式考虑调整

### ISSUE THREAD

**Issue by breakwa11** [breakwa11/shadowsocks-rss#91]
原格式：
`ss://aes-256-cfb:password@abc.xyz:65535`
因不包含注释，在设备间复制的时候需要重新打一次注释
同时SSR存在协议插件，协议插件也需要加在字段里

新格式：
`ss://obfs-plugin:protocol-plugin:aes-256-cfb:password@abc.xyz:65535/obfs_param#remarks`
示例：
`ss://http_simple:auth_simple:aes-256-cfb:password@abc.xyz:65535/aHR0cF9z#aHR0cF9z`
其中obfs-plugin，protocol-plugin和obfs_param字段可选，如果为plain或origin则省略此字段以保持兼容性（如不为plain那兼容了也没意义），obfs_param为空时，它前面的'/'不应出现
remarks字段为了便于传递注释字段，但考虑到编码和注释冲突的问题，obfs_param和remarks需要使用urlsafe base64编码，原文必须为utf8编码

**Comment by breakwa11** [comment]
新版已支持，sspanel上配置加密方式的时候，例如使用http_simple插件，那么可以配置为：
`http_simple:aes-256-cfb`
其它插件和加密方式类似，以英文冒号分隔即可
但这样配置时产生的二维码或链接，目前只有本版本支持

**Comment by hxdyxd** [comment]
用ssr://吧，不然就和以前ss://的格式混淆了

**Comment by yyjdelete** [comment]
`ss://aes-256-cfb:password@abc.xyz:65535/obfs-plugin#remarks`
