### ISSUE TITLE
3.5.4 Beta 版将 remarks 转换成 Base64 编码好不习惯

### ISSUE THREAD

**Issue by ARwMq9b6** [breakwa11/shadowsocks-rss#92]
我属于这种情况：

注册了很多热心人提供的免费 Shadowsocks 服务，有时需要查找某一家的节点信息，就会用文本编辑器在 `gui-config.json` 里查找里面的 `remarks` 。3.5.4 Beta 版将 remarks 转换成 Base64 编码后就不好弄了，好不习惯。

可否实现个 ·使用 Base64 或不使用 Base64· 的选项呢？

**Comment by breakwa11** [comment]
如果原来的编码不是base64，那么直接按原来的编码读取，应该是兼容的

**Comment by breakwa11** [comment]
哦，理解错了，我有打算加一个字段用来显示用的

**Comment by breakwa11** [comment]
不过有一个问题，在统计列表上有完整列表，可以按remarks排序的，也可以较快地找到的吧？

**Comment by ARwMq9b6** [comment]
`remarks排序` 不够给力，有些想要查找的关键的字 ( jp1.xx.xx ) 并不是开头的字符……还是文本编辑器里查找方便……

**Comment by breakwa11** [comment]
@ARwMq9b6 下个版本那个字段会还原回去，base64用另一个字段保存

**Comment by ARwMq9b6** [comment]
谢谢你！

**Comment by redfrog999** [comment]
我这里更糟糕，出现好多乱码，完全看不清楚那个节点的信息了。等下个版本，现在暂时用3.3.6临时对付。

**Comment by breakwa11** [comment]
字段revert回去了

**Comment by ARwMq9b6** [comment]
红蛙兄姗姗来迟。 新的 3.5.5 版没有乱码了： https://github.com/breakwa11/shadowsocks-csharp/releases 。

**Comment by redfrog999** [comment]
Oh，Yeah。就是这个熟悉的味儿，又回来了。女侠妹子的效率直接应该投入离/在岸RMB的打BP里边去。☺

@ARwMq9b6 你最近在玩儿什么呢？

**Comment by ARwMq9b6** [comment]
@redfrog999 在学编程 ( PHP, Java ) , 混口饭吃。
