### ISSUE TITLE
查看链接日志提示这个，服务器配置没动过，放假回来就出现这问题

### ISSUE THREAD

**Issue by zd423** [breakwa11/shadowsocks-rss#94]
放假之前都正常，放假回来就3台都不正常，无法连接网站，SSH登录都正常，网站也打开正常。

我查看链接日志提示这个
2015-10-11 06:26:09 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 150, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 85, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '198.199.115.132' (113)")

**Comment by tardis2012** [comment]
MySQL 数据库有没有问题

**Comment by zd423** [comment]
数据库没问题的

**Comment by falseen** [comment]
有没有 too many openfile 的提示？

**Comment by tardis2012** [comment]
可能是你的表被锁住了，报错点是取用户的函数部分出错，并发读数据库太多可能会锁表

**Comment by zd423** [comment]
@tardis2012 怎么解决呢 重启了数据库还是一样

**Comment by zd423** [comment]
@falseen 没哟

**Comment by breakwa11** [comment]
我也很奇怪，我也遇到过类似的，数据库服务器不知道为啥会临时把节点的IP丢黑名单，然后就一直连不上了，需要在SQL那边解除黑名单

**Comment by falseen** [comment]
@breakwa11 你是说防火墙把节点ip拉黑了？

**Comment by zd423** [comment]
@breakwa11 sql怎么那边怎么解除

**Comment by breakwa11** [comment]
建议先用telnet测试SQL的端口能不能正常连接，换几个IP试试

**Comment by breakwa11** [comment]
如果telnet正常，试试更新一下python服务端的代码，然后重启运行
我之前说的错误是mysql Host 'host_name' is blocked because of many connection errors
和你这个应该无关

**Comment by zd423** [comment]
@breakwa11  运行什么更新python 我试试！

**Comment by breakwa11** [comment]
在空目录里git clone一个最新代码下来就行了
