### ISSUE TITLE
服务端总转发不了UDP

### ISSUE THREAD

**Issue by kenneth104** [breakwa11/shadowsocks-rss#95]
为了战舰世界，已经从配置EC2到搭建ss服务器&客户端。
ProxyCap能看到有UDP请求发出并转到了（sent）本地1080，但没有回应
TCP可正常使用

服务器是自己的AWS EC2
搭建从WIKI看的：https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup

ps；换成sockscap64就可以转发了
pss：sockscap64作者很眼熟？

**Comment by kenneth104** [comment]
服务器端配置

{
    "server":"0.0.0.0",
    "server_ipv6":"::",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "80":["password","verify_deflate"],
	"8080":["password","http_simple"],
        "443":["password","random_head"],
        "23333":["password","random_head"]
        
    },
    "timeout":300,
    "method":"chacha20",
    "fast_open": false,
    "workers": 1
}

**Comment by breakwa11** [comment]
其实我自己从来没有使用proxycap成功过，我也不清楚是什么原因

**Comment by kenneth104** [comment]
那我先试一下换个别的软件

**Comment by nicedayever** [comment]
@breakwa11 我尝试使用shadowsocksr代理迅雷下载BT资源也不成功。 好像shadowsocksr不支持udp relay吧.  server.py 也不支持 -u 的这个参数

**Comment by falseen** [comment]
用过Proxifier没 ？

**Comment by ZAPHIEV** [comment]
Proxifier可行

**Comment by wu360463231** [comment]
@falseen @ZAPHIEV Proxifier并不支持UDP协议
@kenneth104 看看是不是iptables没放行UDP端口
还不行的话代理软件换sockscap64或者Super Socks5Cap

**Comment by falseen** [comment]
刚测试了一下，ssr的c#客户端确实不能转发udp，而python版的客户端可以。我是用 [dnsproxy](https://github.com/breakwa11/dnsproxy)测试的。

**Comment by breakwa11** [comment]
我也好久没有测试过udp了，明天调试一下，可能是插件的问题

**Comment by breakwa11** [comment]
测试了一下，直接转发udp和udp over tcp是正常的

**Comment by falseen** [comment]
用哪个软件测的。

**Comment by breakwa11** [comment]
同样是dnsproxy，特别是udp over tcp的话成功率特别高

**Comment by falseen** [comment]
刚又测了一下，**发现3.5.9版可以转发udp。** 而之前是用的3.5.8版测的不可以转发udp。

3.5.8版不能转发upd的log如下：

```
[2015-10-20 23:42:25] System.NullReferenceException: 未将对象引用设置到对象的实
例。
   在 Shadowsocks.Controller.Handler.StartPipe()
```

至于3.5.8之前的版本能不能转发udp，那就不得而知了。

**Comment by nicedayever** [comment]
@falseen 我也测试了一下，3.5.9配上最新的服务端，确实可以转发UDP了，迅雷挂着SS下载BT十分之快！

**Comment by falseen** [comment]
@nicedayever 下载国外的资源？

**Comment by nicedayever** [comment]
下载美剧，走BANDWAGONHOST IPV6线路，速度达到2MB/s

**Comment by wu360463231** [comment]
@nicedayever 真勇士敢于作死。。小心被蜜罐。。

**Comment by kenneth104** [comment]
已经换成了sockscap64可以直接转UDP
但是出奇的是，用UDP over TCP反而更稳定

**Comment by agentmario** [comment]
@kenneth104 sockscap64 真的可以用？我用它的时候总是登陆不了 wows

**Comment by zydycjr** [comment]
@kenneth104 请问是怎么架设的SSR 端口映射的设置不太理解
