### ISSUE TITLE
ShadowsocksR 3.5.7 PAC

### ISSUE THREAD

**Issue by L-Meteor** [breakwa11/shadowsocks-rss#96]
最新版的 PAC 选项,新增了绕过局域网IP和绕过中国的IP,请问分别是什么意思?而原先的Chiplist 为何移除了呢?感觉Chiplist 比GFWlist 好用些!谢谢!

**Comment by Forty-nine** [comment]
Chiplist就是绕过中国的IP

**Comment by L-Meteor** [comment]
了解.谢谢您的解答!
