### ISSUE TITLE
请教下PAC模式和全局模式细节问题

### ISSUE THREAD

**Issue by selfiprvm** [breakwa11/shadowsocks-rss#97]
刚刚尝试了俩个模式，PAC和全局模式访问 youtube.com ，自我感觉全局模式的访问速度比PAC模式快一点点，从逻辑来看，PAC模式要执行代码，应该是比全局模式慢一点点才对，不知是不是这种情况，还有个问题就是全局模式能看到广告而PAC模式看不到广告，还有一点就是PAC模式和全局模式都访问youtube.com的时候，推荐的视频也是有区别的，烦请解答下。

**Comment by falseen** [comment]
唯一的可能是pac模式下访问youtube的时候有一部分流量没走代理，而youtube的广告和推荐是根据地区而进行变化的。

**Comment by seelea** [comment]
广告不同难道这个问题不是因为均衡负载更换了服务器节点吗

**Comment by selfiprvm** [comment]
2楼说得有道理
