### ISSUE TITLE
发现PAC模式更新chrome版本时无法更新

### ISSUE THREAD

**Issue by selfiprvm** [breakwa11/shadowsocks-rss#98]
烦请作者在下一次版本更新的时候考虑下我们这些chrome迷，在PAC模式下加上chrome更新访问

**Comment by breakwa11** [comment]
这和PAC无关吧

**Comment by breakwa11** [comment]
建议用离线包更新 https://support.google.com/installer/answer/126299?hl=en

**Comment by falseen** [comment]
也可以用便携版的Mychrome

**Comment by Aivier** [comment]
我要不要考虑写个第三方Updater....
