### ISSUE TITLE
合规需求，特别重要。

### ISSUE THREAD

**Issue by mentoryan** [breakwa11/shadowsocks-rss#99]
1、服务端需要URL屏蔽功能
2、限制用户端数量和服务端日志记录用户设备MAC
3、客户端直接一个登陆界面，登陆后，向服务端再读取配置文件
4、服务端分组功能（比如美国1组【多台】，美国2组，日本1组，欧洲1组）

**Comment by falseen** [comment]
1. 这个可以有
2. 貌似breakwa11正在做这个
3. 这个需要和前端配合，ss-panel的其中一个作者之前有打算做api，但是没找到懂c#的人。或许等以后ss-panel和这个项目合作开发的时候会实现这个功能。另外我见过一个网站，他们自己重新编译了c#客户端，实现了登录帐号后自动下载配置的功能。
4. 这个需求不是很大（客户端分组没什么意义，不如在前端分组），估计短期内不会有。

我不是开发人员，以上只是帮你分析一下。

**Comment by mentoryan** [comment]
嗯。我们有一部分JAVA和VC的开发人员，因为开源这个开发成熟度高，但是规范和注释较少，开发速度很慢。

WEB部分好处理，直接API读取和调用就可以了。

服务端分组，是因为保障用户稳定性和负载更可靠。客户端切换实际上来讲，有速度影响。

在 2015年10月13日 下午8:04，Falseen <notifications@github.com>写道：

**Comment by Siyuanm** [comment]
关于第三点，如果没记错的话，极速MM的客户端就是改版，可以下载配置，你可以看看

**Comment by falseen** [comment]
你们打算重写客户端？直接在原客户端的基础上修改不是更好么 ？

**Comment by mentoryan** [comment]
嗯。就是考虑在原客户端上修改，这样更有效率。

2015-10-13 20:30 GMT+08:00 Falseen <notifications@github.com>:

**Comment by mentoryan** [comment]
但是缺少.net <http://xn--gqqt52a8zhy6z.net>
开发人员，正在研究。我们是考虑做到一个整合的通信SDK终端上，现有终端配置是JAVA写的。

在 2015年10月13日 下午9:14，颜银华 <mentoryan@gmail.com>写道：

**Comment by x91270** [comment]
在 SSR 基础上增加用户登陆获取对应服务器列表不是什么难事 。 因为常用 C# 
但是手机端的开发就不行了。不懂 objective-c  , Java 也只是看的懂

**Comment by mentoryan** [comment]
我们的思路是：
我们的自己的推送，ERP平台。直接可以对接服务端和客户端，客户端每次登陆每个节点（或者多个节点）临时分配空闲端口和相应加密，混淆方式。分配完成后，将这个配置文件通过我们的平台，推送给每个终端用户。
这里就需要：客户端给我们一个SOCKET接口，来接入和生效这个配置文件。
客户端直接就能整合到其它的程序中。

在 2015年10月14日 上午2:25，x91270 <notifications@github.com>写道：

**Comment by falseen** [comment]
让breakwa11专门做一个商业用途的客户端有点不现实，其实你们可以在现有客户端的外面加一层壳，然后通过操作配置文件来实现你们的目的。至于生成配置文件，可以通过操作数据库来完成（用前端或自己编写程序操作）。

**Comment by mentoryan** [comment]
这个一是商业用途，二是开源的开放不会被喝茶，特别是服务端的URL详细日志记录功能。这样才能真正保护架VPN的。
我们就是考虑加个壳，但是缺少VS的人员，所以需要让breakwall协助写个SOCKET接口来控制就容易处理了。

在 2015年10月15日 上午12:38，Falseen <notifications@github.com>写道：

**Comment by mentoryan** [comment]
同时我们正在跟WJ沟通就是让开源的日志能够通过什么样的办法整合收集起来，这样大家都平衡了，这段时间打击的就是不合规定的服务端和开发人员，符合规定是放开的。比如我们正在参与测试和研究的广东试点。现在正在测试选型的平台就是breallwall
这个平台。这样报备起来也容易。

在 2015年10月15日 上午12:49，颜银华 <mentoryan@gmail.com>写道：

**Comment by falseen** [comment]
跟wj合作？那就是做阉割版的服务喽？有点意思。

**Comment by tardis2012** [comment]
如果真是和WJ合作建议用PPTP，告诉他们你服务器IP就可以不被封锁，而且PPTP有现成的开源维护软件，你说的需求有现成的PPTP版本

**Comment by falseen** [comment]
@tardis2012 同意。所以我不明白为什么非要用ss。

**Comment by v2ray** [comment]
WJ 是什么？

**Comment by falseen** [comment]
@v2ray  wangjing

**Comment by v2ray** [comment]
不明白这样的保护有什么意思，开放了日志的 ss 谁敢用

**Comment by aprikyblue** [comment]
@v2ray 代码都是开源的，谁真想记录，自己改代码照样记录。。
要么就是自己搭建server自己用咯。。
我觉得在这讨论 如果加了xxx就*不敢用* 没什么意义，应该讨论的是 *这个功能是否合理、对大多数人来说是否有用*

**Comment by bsfmig-a** [comment]
@v2ray 这样的需求其实算是合理的。比如一些学术用途，用户用起来方便，政府也放心。不喜欢这个政府的用户，也不妨碍自行架设服务器或者选择自己认为良心的服务商。另外即使是境外的机房，有时候也会有其他的一些合规性要求（版权、色情等），所以这不只是为了迎合中国政府。

**Comment by mikelei8291** [comment]
所以到头来还是自我阉割？用户隐私就没了？

**Comment by farrellyang** [comment]
翻墙都不会，搞毛学术啊；合理需求自己报备搞vpn就好了，还政府放心，奴才给主子考虑的还挺周全嘛；希望SS-rss独立发展，不要考虑太多外界指手画脚！

**Comment by farrellyang** [comment]
说的不好听点，提这需求的就是想用这个和体制合作发国难财的，@breakwa11关闭这个issue吧

**Comment by mikelei8291** [comment]
同意楼上观点，这个issue就不应该出现

**Comment by breakwa11** [comment]
顺便说明一下ssr的定位

服务端部分
不记录隐私（包括MAC地址），log只为了查错及记录异常连接
正常的连接不保留完整log，只保留来源IP和目标host及端口
不做实际协议分析（包括从http解析出具体URL，然后记录，或根据URL/关键字来拦截）
不做中间人（包括从http请求中获取、篡改内容，或拦截特定TLS请求等）

客户端部分
不会制作与具体平台绑定的功能（如自动登陆，自动获取节点信息）
不会留任何后门
不会记录设备相关信息（手机号，设备编号，通讯录等等，SSR android在制作中）

但由于服务端可能被站长修改，从而可能被记录下更多信息，对于这点我没有解决方案。
建议尽量只访问https站点，或自建VPS来使用，或使用你信得过的站的节点
客户端尽可能从github或客户端自动更新推送的页面下载，在其它地方下载的，记得验证SHA-1后再使用
如果任何人提出一个需求，需要用到以上所提及到的一定不会做的功能，那么这个需要只会无视

用另外一种简单的说法：专注代理，审查去死
